### ISSUE TITLE
Installing DatabaseTarget programmatically 

### ISSUE THREAD

**Issue by lalberto8085** [NLog/NLog#1094]
I've being using `NLog 4.2.2` with asp net 5 in my development environment for some time now and it works fine, but now when I deploy I need to make an `Install(...)` of the `DatabaseTarget` so that it creates the appropriate Table and StoredProcedure. However I'm getting this exception:

    System.ArgumentNullException 
    Value cannot be null.
    Parameter name: type

    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    at System.Activator.CreateInstance(Type type)
    at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString)
    at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString)
    at NLog.Targets.DatabaseTarget.RunInstallCommands(InstallationContext installationContext, IEnumerable<DatabaseCommandInfo> commands)
    at NLog.Targets.DatabaseTarget.Install(InstallationContext installationContext)

Am  initializing all properties for the `DatabaseCommandInfo`s I use so what could be going wrong?
This is my initialization code:

    dbTarget.InstallDdlCommands.Clear();
    dbTarget.InstallDdlCommands.Add(new DatabaseCommandInfo
    {
        ConnectionString = connectionString,
        CommandType = System.Data.CommandType.Text,
        Text = $@"IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'dbo' AND TABLE_NAME = '{TableName}')
                RETURN

             CREATE TABLE [dbo].[{TableName}] (
             [ID] [int] IDENTITY(1,1) NOT NULL,
             [MachineName] [nvarchar](200) NULL,
             [SiteName] [nvarchar](200) NOT NULL,
             [Logged] [datetime] NOT NULL,
             [Level] [varchar](5) NOT NULL,
             [UserName] [nvarchar](200) NULL,
             [Message] [nvarchar](max) NOT NULL,
             [Logger] [nvarchar](300) NULL,
             [Properties] [nvarchar](max) NULL,
             [ServerName] [nvarchar](200) NULL,
             [Port] [nvarchar](100) NULL,
             [Url] [nvarchar](2000) NULL,
             [Https] [bit] NULL,
             [ServerAddress] [nvarchar](100) NULL,
             [RemoteAddress] [nvarchar](100) NULL,
             [Callsite] [nvarchar](300) NULL,
             [Exception] [nvarchar](max) NULL,
           CONSTRAINT [PK_dbo.Log] PRIMARY KEY CLUSTERED ([ID] ASC) 
             WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY =  OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
          ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];"
    });

    dbTarget.InstallDdlCommands.Add(new DatabaseCommandInfo
    {
        ConnectionString = connectionString,
        CommandType = System.Data.CommandType.Text,
        IgnoreFailures = false,
        Text = $@"CREATE PROCEDURE [dbo].[{ProcName}] (
                @machineName nvarchar(200),
                @siteName nvarchar(200),
                @logged datetime,
                @level varchar(5),
                @userName nvarchar(200),
                @message nvarchar(max),
                @logger nvarchar(300),
                @properties nvarchar(max),
                @serverName nvarchar(200),
                @port nvarchar(100),
                @url nvarchar(2000),
                @https bit,
                @serverAddress nvarchar(100),
                @remoteAddress nvarchar(100),
                @callSite nvarchar(300),
                @exception nvarchar(max)
              ) AS
              BEGIN
                INSERT INTO [dbo].[{TableName}] (
                  [MachineName],
                  [SiteName],
                  [Logged],
                  [Level],
                  [UserName],
                  [Message],
                  [Logger],
                  [Properties],
                  [ServerName],
                  [Port],
                  [Url],
                  [Https],
                  [ServerAddress],
                  [RemoteAddress],
                  [CallSite],
                  [Exception]
                ) VALUES (
                  @machineName,
                  @siteName,
                  @logged,
                  @level,
                  @userName,
                  @message,
                  @logger,
                  @properties,
                  @serverName,
                  @port,
                  @url,
                  @https,
                  @serverAddress,
                  @remoteAddress,
                  @callSite,
                  @exception
                );
              END"
    });

    using (var context = new InstallationContext())
    {
        dbTarget.Install(context);
    }

**Comment by 304NotModified** [comment]
HI,

I see that has something to do with the SQL type used in the install. I think you use SQL server? You need the type `System.Data.SqlClient.SqlConnection` , is that installed with a package?

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Thanks a lot

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Would you like my Target configuration code?
Thanks a lot

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Would you like my Target configuration code?
Thanks a lot

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Would you like my Target configuration code?
Thanks a lot

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Would you like my Target configuration code?
Thanks a lot

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Would you like my Target configuration code?
Thanks a lot

**Comment by lalberto8085** [comment]
I don't know if as a package (*.nupkg) but I can use the `SqlConnection` and `SqlConnectionStringBuilder` after `using System.Data.SqlClient`. I can log everything on the DB if I create the table and procedure by hand. I do use SqlServer like this `DBProvider = "sqlserver"` when creating the target. 
Would you like my Target configuration code?
Thanks a lot

**Comment by UgurAldanmaz** [comment]
Hi @lalberto8085. It seems that null reference exception causes by `ConnectionType`. 
Could you send the internal logs? I want to be sure that dbTarget initialized.
Also configuration and full code would be helpful.

**Comment by lalberto8085** [comment]
This is the internal log:

    2015-12-16 15:48:10.1723 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
    2015-12-16 15:48:10.2125 Debug Start auto loading, location: C:\Users\lalbe\.dnx\packages\NLog\4.2.2\lib\net45
    2015-12-16 15:48:10.2125 Debug Auto loading done
    2015-12-16 15:48:10.2125 Debug ScanAssembly('NLog.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
    2015-12-16 15:48:10.2325 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2325 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
    2015-12-16 15:48:10.2325 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
    2015-12-16 15:48:10.2410 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
    2015-12-16 15:48:10.2410 Trace  Scanning SimpleLayout ''''
    2015-12-16 15:48:10.2410 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning ShortDateLayoutRenderer 'Layout Renderer: ${shortdate}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
    2015-12-16 15:48:10.2410 Debug Setting 'XmlEncodeLayoutRendererWrapper.xmlEncode' to 'true'
    2015-12-16 15:48:10.2410 Trace Wrapping AllEventPropertiesLayoutRenderer with XmlEncodeLayoutRendererWrapper
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning AllEventPropertiesLayoutRenderer 'Layout Renderer: ${all-event-properties}'
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2410 Trace Scanning XmlEncodeLayoutRendererWrapper 'Layout Renderer: ${xml-encode}'
    2015-12-16 15:48:10.2410 Trace  Scanning SimpleLayout ''''
    2015-12-16 15:48:10.2410 Trace   Scanning AllEventPropertiesLayoutRenderer 'Layout Renderer: ${all-event-properties}'
    2015-12-16 15:48:10.2410 Debug Registering target LogFile-buffered: NLog.Targets.Wrappers.BufferingTargetWrapper
    2015-12-16 15:48:10.2410 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning MachineNameLayoutRenderer 'Layout Renderer: ${machinename}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning IISInstanceNameLayoutRenderer 'Layout Renderer: ${iis-site-name}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning DateLayoutRenderer 'Layout Renderer: ${date}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning AspNetUserIdentityLayoutRenderer 'Layout Renderer: ${aspnet-user-identity}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
    2015-12-16 15:48:10.2562 Debug Setting 'XmlEncodeLayoutRendererWrapper.xmlEncode' to 'true'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning AllEventPropertiesLayoutRenderer 'Layout Renderer: ${all-event-properties}'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning XmlEncodeLayoutRendererWrapper 'Layout Renderer: ${xml-encode}'
    2015-12-16 15:48:10.2562 Trace  Scanning SimpleLayout ''${all-event-properties}''
    2015-12-16 15:48:10.2562 Trace   Scanning AllEventPropertiesLayoutRenderer 'Layout Renderer: ${all-event-properties}'
    2015-12-16 15:48:10.2562 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'SERVER_NAME'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2562 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'SERVER_PORT'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2562 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'HTTP_URL'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2562 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'HTTPS'
    2015-12-16 15:48:10.2562 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2562 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning WhenLayoutRendererWrapper 'Layout Renderer: ${when}'
    2015-12-16 15:48:10.2713 Trace  Scanning ConditionRelationalExpression '('${aspnet-request:serverVariable=HTTPS}' == 'on')'
    2015-12-16 15:48:10.2713 Trace   Scanning ConditionLayoutExpression ''${aspnet-request:serverVariable=HTTPS}''
    2015-12-16 15:48:10.2713 Trace    Scanning SimpleLayout ''${aspnet-request:serverVariable=HTTPS}''
    2015-12-16 15:48:10.2713 Trace     Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Trace   Scanning ConditionLayoutExpression ''on''
    2015-12-16 15:48:10.2713 Trace    Scanning SimpleLayout ''on''
    2015-12-16 15:48:10.2713 Trace     Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
    2015-12-16 15:48:10.2713 Trace  Scanning SimpleLayout ''1''
    2015-12-16 15:48:10.2713 Trace   Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
    2015-12-16 15:48:10.2713 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'HTTPS'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning WhenLayoutRendererWrapper 'Layout Renderer: ${when}'
    2015-12-16 15:48:10.2713 Trace  Scanning SimpleLayout ''0''
    2015-12-16 15:48:10.2713 Trace   Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
    2015-12-16 15:48:10.2713 Trace  Scanning ConditionRelationalExpression '('${aspnet-request:serverVariable=HTTPS}' != 'on')'
    2015-12-16 15:48:10.2713 Trace   Scanning ConditionLayoutExpression ''${aspnet-request:serverVariable=HTTPS}''
    2015-12-16 15:48:10.2713 Trace    Scanning SimpleLayout ''${aspnet-request:serverVariable=HTTPS}''
    2015-12-16 15:48:10.2713 Trace     Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Trace   Scanning ConditionLayoutExpression ''on''
    2015-12-16 15:48:10.2713 Trace    Scanning SimpleLayout ''on''
    2015-12-16 15:48:10.2713 Trace     Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
    2015-12-16 15:48:10.2713 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'LOCAL_ADDR'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'REMOTE_ADDR'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Debug Setting 'AspNetRequestValueLayoutRenderer.serverVariable' to 'REMOTE_PORT'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning AspNetRequestValueLayoutRenderer 'Layout Renderer: ${aspnet-request}'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning CallSiteLayoutRenderer 'Layout Renderer: ${callsite}'
    2015-12-16 15:48:10.2713 Debug Setting 'ExceptionLayoutRenderer.format' to 'type,message,method,stackTrace,data'
    2015-12-16 15:48:10.2713 Debug Setting 'ExceptionLayoutRenderer.separator' to '
    '
    2015-12-16 15:48:10.2713 Debug Setting 'ExceptionLayoutRenderer.innerFormat' to 'type,message,method,stackTrace'
    2015-12-16 15:48:10.2713 Debug Setting 'ExceptionLayoutRenderer.maxInnerExceptionLevel' to '10'
    2015-12-16 15:48:10.2713 Trace FindReachableObject<NLog.Internal.IRenderable>:
    2015-12-16 15:48:10.2713 Trace Scanning ExceptionLayoutRenderer 'Layout Renderer: ${exception}'

and this is the target configuration code:

    var dbTarget = new DatabaseTarget
    {
        Name = dbConfig.Name,
        CommandType = dbConfig.CommandType,
        KeepConnection = dbConfig.KeepConnection,
        ConnectionString = connectionString,
        CommandText = $"[dbo].[{ProcName}]",
        DBProvider = "sqlserver",
        InstallConnectionString = connectionString
    };

    foreach (var parameter in dbConfig.Parameters)
    {
        dbTarget.Parameters.Add(new DatabaseParameterInfo(parameter.Name, parameter.Layout));
    }

Could you please tell me what you mean by initialization and how can I check for/do it
Thank you, hope this helps

**Comment by UgurAldanmaz** [comment]
Initialization works [internally](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/DatabaseTarget.cs#L356). I need to be sure what happens. But I am too tired to concentrate.

I will examine the problem (probably tomorrow).

Thanks!

**Comment by lalberto8085** [comment]
I found a work around I downloaded the code for the `NLog 4.2.2` and reproduced my code on a Console application and ran into the same exception, from there I debugged your code and found it was what @UgurAldanmaz said, the `Target.Initialize()` method was not being called so called `config.Install()` in my code after I added the `DatabaseTarget` object and that did the trick. 

Thanks a lot for your help and pointing me me in the right direction.

**Comment by UgurAldanmaz** [comment]
Hi @lalberto8085.

I tested and found the problem. Yes, it causes by `ConnectionType`. `ConnectionType` is setting when configuration initialization.

A target installation should be managed by XmlLoggingConfiguration. I mean, you should call the `Install` method of the `XmlLoggingConfiguration`, not directly `DatabaseTarget`.

Take a look at [InstallNLogConfig console app](https://github.com/NLog/NLog/blob/master/src/InstallNLogConfig/Program.cs). You can figure out how installation code should be. 

This console app uses the config file. As I see your second code post, you want to configure it programmatically. So you can also take look at [Configuration-API](https://github.com/nlog/NLog/wiki/Configuration-API).

Final code should be like this:

```csharp
var config = new LoggingConfiguration();
config.AddTarget(dbTarget);
config.Rules.Add(...);
 using (var context = new InstallationContext())
{
     config.Install(context);
}
```

**Comment by UgurAldanmaz** [comment]
Oh @god. We was writing at the same time.

Ok. You are welcome.


BTW, really exist an account for @god. Fantastic! In future, I will mention this account in situations like this.

**Comment by 304NotModified** [comment]
Nice that it got fixed, but it's strange that `Install` won't call `Initialize`. At least, it should not crash!

**Comment by 304NotModified** [comment]
A new issue is more appropriate and better to handle. So will close this and a new issue has been created: https://github.com/NLog/NLog/issues/1098
