### ISSUE TITLE
.NET Core: fix autoload config

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1354]

**Comment by snakefoot** [comment]
@304NotModified Think this can be resolved with the release of NLog 5.0 BETA7

**Comment by 304NotModified** [comment]
Any change to get this tested?

**Comment by snakefoot** [comment]
@304NotModified Though it was included in the reload-config unit-tests?

**Comment by 304NotModified** [comment]
this problem is not really unit testable, as the basedir for asp.net core applications is different. We think ${basedir} is fixed and so this one, but it needs to be tested first before closing this one.

**Comment by pendenaor** [comment]
Hi,
Get some weird warnings about assemblies not been auto loaded with beta7:
```
2017-05-18 15:20:40.1439 Info Loading assembly: Notification.Template.Logging
2017-05-18 15:20:40.1978 Debug ScanAssembly('NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2017-05-18 15:20:40.1439 Info Loading assembly: Notification.Template.Logging
2017-05-18 15:20:40.1978 Debug ScanAssembly('NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2017-05-18 15:20:40.3452 Debug Start auto loading, location: /home/wsnotif/sci-instance
2017-05-18 15:20:40.3482 Info Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll
2017-05-18 15:20:40.3482 Info Loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll
2017-05-18 15:20:40.3482 Warn Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll failed! Skipping this file. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
2017-05-18 15:20:40.4597 Info Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll
2017-05-18 15:20:40.4597 Info Loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll
2017-05-18 15:20:40.4597 Warn Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll failed! Skipping this file. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
2017-05-18 15:20:40.4597 Debug Auto loading done
```

**NLog.config**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="/home/wsnotif/logs/sci-internal-nlog.log" internalLogLevel="Debug">

  <extensions>
    <!--<add assembly="NLog.Web.AspNetCore"/>-->
    <add assembly="Notification.Template.Logging"/>
  </extensions>
```

**Comment by 304NotModified** [comment]
@pendenaor please open a new issue and provide all the info in the template, thx!

**Comment by pendenaor** [comment]
New bug filled: https://github.com/NLog/NLog/issues/2120

**Comment by 304NotModified** [comment]
I assume this is already fixed
