### ISSUE TITLE
Logging doesn't work if mail target added to NLog configuration for web application

### ISSUE THREAD

**Issue by dimrun** [NLog/NLog#1407]
**Type**: Bug

**NLog version**: 4.3.2

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5

**Current NLog config** (xml or C#, if relevant):
nothing special, just mail target added to web.config

In case of a BUG:

- What is the current result?
Exception occurs:
```
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: exePath must be specified when not running inside a stand alone exe.
  at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
  at System.Configuration.ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel userLevel)
  at NLog.Targets.MailTarget.get_MailSettings()
```

- What is the expected result?
No errors

- Stack trace:
```
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: exePath must be specified when not running inside a stand alone exe.
  at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
  at System.Configuration.ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel userLevel)
  at NLog.Targets.MailTarget.get_MailSettings()
  --- End of inner exception stack trace ---
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
  at NLog.Internal.ObjectGraphScanner.ScanProperties[T](List`1 result, Object o, Int32 level, HashSet`1 visitedObjects)
  at NLog.Internal.ObjectGraphScanner.ScanProperties[T](List`1 result, Object o, Int32 level, HashSet`1 visitedObjects)
  at NLog.Internal.ObjectGraphScanner.ScanPropertiesList[T](List`1 result, IEnumerable`1 elements, Int32 level, HashSet`1 visitedObjects)
  at NLog.Internal.ObjectGraphScanner.ScanProperties[T](List`1 result, Object o, Int32 level, HashSet`1 visitedObjects)
  at NLog.Internal.ObjectGraphScanner.FindReachableObjects[T](Object[] rootObjects)
  at NLog.Config.LoggingConfiguration.ValidateConfig()
  at NLog.Config.LoggingConfiguration.InitializeAll()
  at NLog.LogFactory.get_Configuration()
  at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
  at NLog.LogFactory.GetLogger(String name)
  at NLog.LogManager.GetLogger(String name)
```

**Possible reason / fix**:

When we read SMTP configuration (`MailTarget.MailSettings` property) we don't take into account that it can be executed in scope of web application

Current code:
```C#
 _currentailSettings = System.Configuration.ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None).GetSection("system.net/mailSettings/smtp") as SmtpSection;
```

A special switch for this case should be added. Something like this:
http://stackoverflow.com/questions/5629209/how-to-replace-openexeconfiguration-in-a-web-context-asp-net-mvc-1

**Comment by ivanpointer** [comment]
I don't believe this problem doesn't exist in 4.3.1, and appears to have been introduced with 4.3.2.  Our organization is sticking with 4.3.1 until this is straightened out.

**Comment by ivanpointer** [comment]
This also includes WCF applications (I know, they're technically "web" applications).

**Comment by 304NotModified** [comment]
This bug is indeed introduced in 4.3.2. Will fix this in 4.3.3. Any idea how to unit test this?

**Comment by 304NotModified** [comment]
I think the code in http://stackoverflow.com/questions/5629209/how-to-replace-openexeconfiguration-in-a-web-context-asp-net-mvc-1 is problematic as it uses system.web, and we don't want a dependency to system.web from NLog. Any thoughts @ivanpointer ?

**Comment by krazyest** [comment]
note that if smtpDeliveryMethod="network" is used, it mitigates the issue and the exePath exception is not shown, but Nlog does not log anymore

**Comment by 304NotModified** [comment]
ATM I'm working on a fix

**Comment by 304NotModified** [comment]
This is fixed in NLog 4.3.3. Also the code is more robust - no crash or disabled logging when there are troubles reading the "from" from the SMTP config.

https://www.nuget.org/packages/NLog/4.3.3

**Comment by ivanpointer** [comment]
Thank you!  I just now saw the notes and will pull down 4.3.3 to verify.

Thanks again!

**Comment by 304NotModified** [comment]
:+1:
