### ISSUE TITLE
replaceFileContentsOnEachWrite does not work with createDirs properly

### ISSUE THREAD

**Issue by SoonDead** [NLog/NLog#1445]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type**: Bug

**NLog version**: 4.3.3

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Error" internalLogFile="c:\temp\nlog-internal.log" >

  <targets>
    <target xsi:type="File"
            name="StatusFile"
            replaceFileContentsOnEachWrite="true"
            createDirs="true"
            layout="${message}"
            fileName="${basedir}/log/status.txt"
            />
  </targets>

  <rules>
    <logger name="StateLogger" minlevel="Info" writeTo="StatusFile" final="true" />
  </rules>
</nlog>
```

In case of a BUG:

- What is the current result?

If the "log" directory does not exists, NLog throws a following exception:

```
Could not find a part of the path 'B:\\Libraries\\Documents\\Visual Studio 2015\\Projects\\TestSolution\\OmittedProjectName\\bin\\Debug\\log\\status.txt'.
```

If the "log" directory exists, it works fine.

- What is the expected result?

The "log" directory should be created automatically.

- Please post full exception details (message, stacktrace, inner exceptions)

```
System.TypeInitializationException: The type initializer for 'OmittedProjectName.ApplicationStateLogger.StateLogger' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'B:\Libraries\Documents\Visual Studio 2015\Projects\TestSolution\OmittedProjectName\bin\Debug\log\status.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at NLog.Targets.FileTarget.ReplaceFileContent(String fileName, Byte[] bytes)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message)
   at NLog.Logger.Info(String message)
   at MasterCommandLine.ApplicationStateLogger.StateLogger.Update() in B:\Libraries\Documents\Visual Studio 2015\Projects\TestSolution\OmittedProjectName\ApplicationStateLogger\StateLogger.cs:line 29
   at MasterCommandLine.ApplicationStateLogger.StateLogger..cctor() in B:\Libraries\Documents\Visual Studio 2015\Projects\TestSolution\OmittedProjectName\ApplicationStateLogger\StateLogger.cs:line 16
   --- End of inner exception stack trace ---
   at MasterCommandLine.ApplicationStateLogger.StateLogger.SetState(ApplicationState appState)
   at MasterCommandLine.AsyncProgram.<AsyncMainInternal>d__4.MoveNext() in B:\Libraries\Documents\Visual Studio 2015\Projects\TestSolution\OmittedProjectName\AsyncProgram.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MasterCommandLine.AsyncProgram.<AsyncMain>d__3.MoveNext() in B:\Libraries\Documents\Visual Studio 2015\Projects\TestSolution\OmittedProjectName\AsyncProgram.cs:line 36
```

- Are there any workarounds? yes

I can create the log directory beforehand.

- Is there a version in which it did worked?

Not sure/Unable to find one.
 
- Can you help us by writing an unit test?

        [TestMethod]
        public void ShouldCreateDirectory()
        {
            var config = new LoggingConfiguration();

            LogManager.ThrowExceptions = true;
            

            var target =
                new FileTarget
                {
                    FileName = "${basedir}/log/info.log",
                    ReplaceFileContentsOnEachWrite = true,
                    CreateDirs = true
                };

            config.AddTarget("logfile", target);

            var rule = new LoggingRule("*", LogLevel.Debug, target);

            config.LoggingRules.Add(rule);

            LogManager.Configuration = config;

            ILogger logger = LogManager.GetLogger("A");
            logger.Info("a");
        }

**Comment by 304NotModified** [comment]
Thanks for the report & unit test!
