### ISSUE TITLE
Fix unit tests running in .NET Core 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1476]
Broken since upgrade to RC2. Related #1458 
- [x] building local
- [x] enabled basedir tests
- [ ] succeeding 
- [ ] working on appveyor

**Comment by 304NotModified** [comment]
```
Project NLog (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project SampleExtensions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project NLog.UnitTests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
xUnit.net .NET CLI test runner (64-bit win10-x64)
  Discovering: NLog.UnitTests
  Discovered:  NLog.UnitTests
  Starting:    NLog.UnitTests
    NLog.UnitTests.Targets.PlainFileTargetTests.ArchiveAboveSizeWithArchiveNumberingModeDate_maxfiles_o [SKIP]
      this is not supported, because we cannot create multiple archive files with  ArchiveNumberingMode.Date (for one day)
    NLog.UnitTests.Targets.PlainFileTargetTests.ArchiveFileOnStartTests(enableCompression: True, customFileCompressor: False) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\NLogTestBase.cs(220,0): at NLog.UnitTests.NLogTestBase.AssertZipFileContents(String fileName, String contents, Encoding encoding)
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\Targets\FileTargetTests.cs(370,0): at NLog.UnitTests.Targets.FileTargetTests.ArchiveFileOnStartTests(Boolean enableCompression, Boolean customFileCompressor)
    NLog.UnitTests.Targets.PlainFileTargetTests.SimpleFileTestInRoot [FAIL]
      File 'c:\nlog-test.log' doesn't exist.
      Expected: True
      Actual:   False
      Stack Trace:
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\NLogTestBase.cs(228,0): at NLog.UnitTests.NLogTestBase.AssertFileContents(String fileName, String contents, Encoding encoding)
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\Targets\FileTargetTests.cs(136,0): at NLog.UnitTests.Targets.FileTargetTests.SimpleFileTestInRoot()
    NLog.UnitTests.Targets.WrappedFileTargetTests.ArchiveFileOnStartTests(enableCompression: True, customFileCompressor: False) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\NLogTestBase.cs(220,0): at NLog.UnitTests.NLogTestBase.AssertZipFileContents(String fileName, String contents, Encoding encoding)
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\Targets\FileTargetTests.cs(370,0): at NLog.UnitTests.Targets.FileTargetTests.ArchiveFileOnStartTests(Boolean enableCompression, Boolean customFileCompressor)
    NLog.UnitTests.Targets.WrappedFileTargetTests.SimpleFileTestInRoot [FAIL]
      File 'c:\nlog-test.log' doesn't exist.
      Expected: True
      Actual:   False
      Stack Trace:
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\NLogTestBase.cs(228,0): at NLog.UnitTests.NLogTestBase.AssertFileContents(String fileName, String contents, Encoding encoding)
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\Targets\FileTargetTests.cs(136,0): at NLog.UnitTests.Targets.FileTargetTests.SimpleFileTestInRoot()
    NLog.UnitTests.Targets.WrappedFileTargetTests.ArchiveAboveSizeWithArchiveNumberingModeDate_maxfiles_o [SKIP]
      this is not supported, because we cannot create multiple archive files with  ArchiveNumberingMode.Date (for one day)
    NLog.UnitTests.Common.InternalLoggerTests_Trace.ShouldNotLogInternalWhenLogToTraceIsDisabled(internalLogToTrace: null, logToTrace: null) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
        X:\Github-nlog-production\NLog\tests\NLog.UnitTests\Common\InternalLoggerTests_Trace.cs(63,0): at NLog.UnitTests.Common.InternalLoggerTests_Trace.ShouldNotLogInternalWhenLogToTraceIsDisabled(Nullable`1 internalLogToTrace, Nullable`1 logToTrace)
  Finished:    NLog.UnitTests
=== TEST EXECUTION SUMMARY ===
   NLog.UnitTests  Total: 1119, Errors: 0, Failed: 5, Skipped: 2, Time: 258,035s
```

**Comment by snakefoot** [comment]
@304NotModified Think this has become obsolete.

**Comment by 304NotModified** [comment]
yes done!
