### ISSUE TITLE
NLog crash in production

### ISSUE THREAD

**Issue by FrancoisBeaune** [NLog/NLog#1497]
**Type**: Bug

**NLog version**: 4.2.2

**Platform**: .Net 4.5

**Current NLog config**:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" throwExceptions="true" internalLogLevel="Info" internalLogFile="logs/InMagCrawlerNLog.log">
    <variable name="messageLayout" value="${longdate:universalTime=True}Z | ${pad:padding=4:inner=${threadid}} | ${pad:padding=5:inner=${level:uppercase=true}} | ${message}${onexception:${newline}${exception:format=tostring}}"/>

    <targets>
        <target name="console" xsi:type="ColoredConsole" layout="${messageLayout}">
            <highlight-row condition="level == LogLevel.Debug" foregroundColor="DarkGray" />
            <highlight-row condition="level == LogLevel.Info" foregroundColor="Gray" />
            <highlight-row condition="level == LogLevel.Warn" foregroundColor="Magenta" />
            <highlight-row condition="level == LogLevel.Error" foregroundColor="Red" />
            <highlight-row condition="level == LogLevel.Fatal" foregroundColor="White" backgroundColor="Red" />
        </target>

        <target name="messagesLogFile"
                xsi:type="File"
                layout="${messageLayout}"
                encoding="UTF-8"
                fileName="${basedir}/logs/InMagCrawler.log"
                archiveFileName="${basedir}/logs/InMagCrawler.{#}.log"
                archiveNumbering="Rolling"
                archiveEvery="Day"
                maxArchiveFiles="7"
                concurrentWrites="False"/>

        <target name="statisticsLogFile"
                xsi:type="File"
                layout="${longdate:universalTime=True}Z ${message}"
                fileName="${basedir}/logs/InMagCrawlerStats.log"
                archiveFileName="${basedir}/logs/InMagCrawlerStats.{#}.log"
                archiveNumbering="Rolling"
                archiveEvery="Day"
                maxArchiveFiles="7"
                concurrentWrites="False"/>
    </targets>

    <rules>
        <logger name="InMagCrawler.Statistics" minlevel="Info" writeTo="statisticsLogFile" final="True"/>
        <logger name="*" minlevel="Debug" writeTo="messagesLogFile"/>
        <logger name="*" minlevel="Debug" writeTo="console"/>
    </rules>
</nlog>
```

NLog crashed at 12:00am during log files rotation:

```
Application: InMagCrawler.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.File.InternalMove(System.String, System.String, Boolean)
   at NLog.Targets.FileTarget.ArchiveFile(System.String, System.String, Boolean)
   at NLog.Targets.FileTarget.RollArchiveForward(System.String, System.String, Boolean)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.RecursiveRollingRename(System.String, System.String, Int32)
   at NLog.Targets.FileTarget.Write(NLog.LogEventInfo)
   at NLog.Targets.Target.Write(NLog.Common.AsyncLogEventInfo)

Exception Info: NLog.NLogRuntimeException
   at NLog.LoggerImpl+<>c__DisplayClass1.<Write>b__0(System.Exception)
   at NLog.Internal.SingleCallContinuation.Function(System.Exception)
   at NLog.Targets.Target.Write(NLog.Common.AsyncLogEventInfo)
   at NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Internal.TargetWithFilterChain, NLog.LogEventInfo, NLog.Common.AsyncContinuation)
   at NLog.LoggerImpl.Write(System.Type, NLog.Internal.TargetWithFilterChain, NLog.LogEventInfo, NLog.LogFactory)
   at NLog.Logger.Info(System.String)
   at InMagCrawler.Statistics.WriteReport(Metrics, Metrics, Double)
   at InMagCrawler.Statistics.Print()
   at InMagCrawler.Program.StatisticsTask(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by 304NotModified** [comment]
Hi, 

There were aot of fixes in archiving in NLog 4.3. Please upgrade to the lastest version.  (please note the throwExceptions option, see news post)

**Comment by FrancoisBeaune** [comment]
Thanks @304NotModified, I'll move to NLog 4.3 and investigate the throwsException settings.

**Comment by FrancoisBeaune** [comment]
@304NotModified Could you point me to the relevant news post regarding `throwExceptions` please?

Also, would setting `throwExceptions` to false prevent NLog from crashing the application in case of an I/O error like the one we observed?

**Comment by 304NotModified** [comment]
latest news post on http://nlog-project.org/

http://nlog-project.org/2016/04/16/nlog-4-3-has-been-released.html

if `throwExceptions` = `false` no exception should be ever thrown when running NLog. (note setting invalid values in C#, could lead to exceptions, like changing the timeout to -1 etc. This is not the case when configuration with the XML file, invalid values will only lead to errors in the internal log)

**Comment by FrancoisBeaune** [comment]
Excellent, thank you. We're about to deploy a new version of our service running NLog 4.3.4 and we set `throwException` to false.

I'll close this issue for now and reopen it if we find that the problem persists.

Thanks again for the quick support.

**Comment by 304NotModified** [comment]
OK! Thanks for the feedback!
