### ISSUE TITLE
.NET Core Layouts seem to be missing

### ISSUE THREAD

**Issue by niemyjski** [NLog/NLog#1499]
It doesn't seem like any (and I tried about 10) layout renders work but the data is accessible in .net standard.

Please take a look at our app as we collect all of this info today on .net standard:
https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
<img width="1021" alt="screen shot 2016-06-07 at 12 05 28 pm" src="https://cloud.githubusercontent.com/assets/1020579/15867332/738add26-2ca8-11e6-8eea-fa788fd0d50b.png">

**Comment by 304NotModified** [comment]
Almost all the unit tests are succeeding, so there should be some else wrong. Please check the internal log (trace level) when rendering.

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by niemyjski** [comment]
Yes, I haven't had time to look into it.. Getting married tomorrow

**Comment by 304NotModified** [comment]
Congrats!

**Comment by 304NotModified** [comment]
Do you still need some help on this?

**Comment by niemyjski** [comment]
I'll try and reproduce my previous issue in a few minutes, sorry got side tracked and forgot about this.

**Comment by niemyjski** [comment]
There is still an issue here: You can reproduce by pulling down http://github.com/exceptionless/Exceptionless.Net setting the startup project to `Exceptionless.SampleConsole` and update the `nlog.config` target to:

```xml
    <target name="exceptionless" xsi:type="Exceptionless">
      <field name="host" layout="${machinename}" />
      <field name="identity" layout="${identity}" />
      <field name="windows-identity" layout="${windows-identity:userName=True:domain=False}" />
      <field name="process" layout="${processname}" />
    </target>
```
NLog.NLogConfigurationException was unhandled
  HResult=-2146233088
  Message=Exception occurred when loading configuration from NLog.config
  Source=NLog
  StackTrace:
       at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
       at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
       at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
       at NLog.LogFactory.get_Configuration()
       at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
       at NLog.Fluent.Log.Create(LogLevel logLevel, String callerFilePath)
       at Exceptionless.SampleConsole.Program.Main(String[] args) in C:\Code\Exceptionless.Net\src\Samples\Exceptionless.SampleConsole\Program.cs:line 62
  InnerException: 
       HResult=-2146233088
       Message=Error when setting property 'Layout' on Exceptionless.NLog.ExceptionlessField
       Source=NLog
       StackTrace:
            at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
            at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
            at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
            at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
            at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
            at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
            at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
            at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
       InnerException: 
            HResult=-2147024809
            Message=LayoutRenderer cannot be found: 'identity'
            Source=NLog
            StackTrace:
                 at NLog.Config.Factory`2.CreateInstance(String name)
                 at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
                 at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
                 at NLog.Layouts.SimpleLayout.set_Text(String value)
                 at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
                 at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
            InnerException: 

```

**Comment by 304NotModified** [comment]
That's correct a there is a limited set implemented. Microsoft did also dropped a lot of functionality in .net core. See https://github.com/nlog/nlog/wiki/platform-support

**Comment by niemyjski** [comment]
Everyone of those I tried and they don't work and yet I can get all that info in net core.....

**Comment by 304NotModified** [comment]
Do you have a case of a layout renderer which isn't working, but is listed the table as supported?

**Comment by niemyjski** [comment]
I'd like to know why any of those are not working specifically and I'll tell you the api that needs to be called. I've done all the work and linked you to it in my first post. Do you need a pr for this?

**Comment by niemyjski** [comment]
Machine name is a bit harder but is coming in v1.1

**Comment by 304NotModified** [comment]
Yeah PR would be great! To the coreCLR branch. 

Most of the cases as we didn't found the replacement, at least not at beta8-rc1 phase. Also most of us won't work with .net core daily.

**Comment by 304NotModified** [comment]
Closing this as we close all known issues.
