### ISSUE TITLE
404 Conflict error after running fine for a period of time

### ISSUE THREAD

**Issue by andrewrutter** [NLog/NLog#1506]
Bug

**NLog version**: 3.1.0.0

**Platform**: Azure, .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    throwExceptions="true" internalLogFile="c:\nlog.txt" internalLogLevel="Debug" >

  <extensions>
    <add assembly="NLog.AzureAppendBlob" />
  </extensions>

  <targets>
    <!--to Store log data on the Azure storage -->
    <target xsi:type="AzureAppendBlob"
         name="Azure"
         layout="${newline} ${longdate} ${level} ${aspnet-user-identity} ${message}"
         connectionString="DefaultEndpointsProtocol=http;..."
         container="logs"
         blobName="${date:format=yyyy-MM-dd}${machinename}.log" />
  </targets>
  <rules>
    <logger name="*" appendTo="Azure"/>
  </rules>
</nlog>
```

We are seeing 409 Conflict errors being returned from logging calls after it is running for several hours with no issues. 

```
NLog.NLogRuntimeException: Exception occurred in NLog ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (409) Conflict. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex)
   at Microsoft.WindowsAzure.Storage.Blob.CloudAppendBlob.<AppendBlockImpl>b__76(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Flush()
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Commit()
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Microsoft.WindowsAzure.Storage.Blob.CloudAppendBlob.UploadFromStreamHelper(Stream source, Nullable`1 length, Boolean createNew, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudAppendBlob.AppendFromByteArray(Byte[] buffer, Int32 index, Int32 count, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudAppendBlob.AppendText(String content, Encoding encoding, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
   at NLog.AzureAppendBlob.AzureAppendBlobTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1.<Write>b__0(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(LogLevel level, String message, Object[] args)
```

**Comment by 304NotModified** [comment]
Hi, 

As you can see the error is thrown by azure / the NLog extension. It seems a bug in those components.  Please contact the maintainer of the extension.  

To prevent the throw Exception, you can set throwExceptions to false.

**Comment by 304NotModified** [comment]
Do you need some help on this or can we close it?
