### ISSUE TITLE
Rule with level="Off" prevents any rules below it to be loaded.

### ISSUE THREAD

**Issue by gulerin** [NLog/NLog#1509]
**Bug**
**NLog version**: 4.2.3
**Platform**: .Net 4.5

**Current NLog config**

```xml
<?xml version="1.0"?>
<nlog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
    <variable name="logDirectory" value="D:\Logs\app"/>
    <targets>
        <target name="ErrorAppender" xsi:type="File"
          fileName="${logDirectory}\Error.log"
          layout="[${longdate:universalTime=true}] ${level:uppercase=true} ${message}${newline}${onexception:${exception:format=ToString:innerFormat=ToString:maxInnerExceptionLevel=10}${newline}}"
          encoding="utf-8"
          lineEnding="None"
          archiveAboveSize="262144000"
          maxArchiveFiles="9999"
          archiveFileName="${logDirectory}\archive\Error.{#}.log"
          archiveNumbering="DateAndSequence"
          archiveEvery="Day"
          archiveDateFormat="yyyy-MM-dd"
          keepFileOpen="true"
          concurrentWrites="false"/>
        <target name="WarningAppender" xsi:type="File"
          fileName="${logDirectory}\Warning.log"
          layout="[${longdate:universalTime=true}] ${level:uppercase=true} ${message}${newline}${onexception:${exception:format=ToString:innerFormat=ToString:maxInnerExceptionLevel=10}${newline}}"
          encoding="utf-8"
          lineEnding="None"
          archiveAboveSize="262144000"
          maxArchiveFiles="9999"
          archiveFileName="${logDirectory}\archive\Warning.{#}.log"
          archiveNumbering="DateAndSequence"
          archiveEvery="Day"
          archiveDateFormat="yyyy-MM-dd"
          keepFileOpen="true"
          concurrentWrites="false"/>
        <target name="InfoAppender" xsi:type="File"
          fileName="${logDirectory}\Info.log"
          layout="[${longdate:universalTime=true}] ${level:uppercase=true} ${message}${newline}${onexception:${exception:format=ToString:innerFormat=ToString:maxInnerExceptionLevel=10}${newline}}"
          encoding="utf-8"
          lineEnding="None"
          archiveAboveSize="262144000"
          maxArchiveFiles="9999"
          archiveFileName="${logDirectory}\archive\Info.{#}.log"
          archiveNumbering="DateAndSequence"
          archiveEvery="Day"
          archiveDateFormat="yyyy-MM-dd"
          keepFileOpen="true"
          concurrentWrites="false"/>
        <target name="DebugAppender" xsi:type="File"
          fileName="${logDirectory}\Debug.log"
          layout="[${longdate:universalTime=true}] ${level:uppercase=true} ${message}${newline}${onexception:${exception:format=ToString:innerFormat=ToString:maxInnerExceptionLevel=10}${newline}}"
          encoding="utf-8"
          lineEnding="None"
          archiveAboveSize="262144000"
          maxArchiveFiles="9999"
          archiveFileName="${logDirectory}\archive\Debug.{#}.log"
          archiveNumbering="DateAndSequence"
          archiveEvery="Day"
          archiveDateFormat="yyyy-MM-dd"
          keepFileOpen="true"
          concurrentWrites="false"/>
        <target name="WebServiceAppender" xsi:type="File"
          fileName="${logDirectory}\WebService.log"
          layout="[${longdate:universalTime=true}] ${message}${newline}"
          encoding="utf-8"
          lineEnding="None"
          archiveAboveSize="262144000"
          maxArchiveFiles="9999"
          archiveFileName="${logDirectory}\archive\WebService.{#}.log"
          archiveNumbering="DateAndSequence"
          archiveEvery="Day"
          archiveDateFormat="yyyy-MM-dd"
          keepFileOpen="true"
          concurrentWrites="false"/>
    </targets>
    <rules>
        <logger name="general" minlevel="Error" writeTo="ErrorAppender" />
        <logger name="general" minlevel="Warn" writeTo="WarningAppender" />
        <logger name="general" minlevel="Info" writeTo="InfoAppender" />
        <logger name="general" level="Off" writeTo="DebugAppender" />
        <logger name="webservice" minlevel="Info" writeTo="WebServiceAppender" />
    </rules>
</nlog>
```

With the configuration above I'd expect logging to appear in the error, warning, info and webservice appenders. The debug appender is defined, but the rule for sending log entries to that appender is set to _Off_.

What actually happens is that logging appears in the error, warning and info appenders and the webservice appender is disabled.
If I look at the properties on the NLog class at runtime, I see there is simply no rule to send log entries to the webservice appender and that's probably why the logger is disabled.

When I change the _level="Off"_ from the debug appender rule to _minlevel="Debug"_ and change the rule from the info appender from _minlevel="Info"_ to _level="Off"_ then both debug and webservice appender are disabled unexpectedly.
Effectively setting a _level="Off"_ on a rule prevents any rules below that to be loaded.

If I look at the internal log Is see the following:
```
2016-06-16 17:07:38.6627 Info Adding target File Target[WebServiceAppender]
2016-06-16 17:07:38.6627 Debug Registering target WebServiceAppender: NLog.Targets.FileTarget
2016-06-16 17:07:38.6627 Trace ParseRulesElement
2016-06-16 17:07:38.6777 Error Error in Parsing Configuration File. Exception : NLog.NLogConfigurationException: Exception occurred when loading configuration from D:\Projects\Coga\src\CogaServer\web.config ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NLog.Config.XmlLoggingConfiguration.ParseLoggerElement(NLogXmlElement loggerElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseRulesElement(NLogXmlElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2016-06-16 17:07:38.6777 Debug --- NLog configuration dump ---
```

Interestingly enough, using _minlevel="Off"_ works just fine, but I found this intuitive to use.

**Comment by 304NotModified** [comment]
Thsys strange. Another work around is to use the enabled attribute (on logger)

**Comment by 304NotModified** [comment]
Anyway, Thanks for reporting!

**Comment by gulerin** [comment]
Since this is an open source project and I'm a developer, I figured I'd give fixing it a shot.
My first ever PR :-)

#1511

**Comment by 304NotModified** [comment]
Thanks!
