### ISSUE TITLE
Exception during startup. Asp.Net Core RC2

### ISSUE THREAD

**Issue by EltonInAtlanta** [NLog/NLog#1515]
Question: (how the heck do you add a tag for this?)
Hi!
I'm working on a test project with asp.net core rc2 and the full .net framework (net4.6.1, not the cross platform stuff).  My nlog package is "NLog.Extensions.Logging": "1.0.0-rc2-final-2016-05-21",

I can run this under the local IISExpress server and it's happy.  When I publish (dotnet publish), an error is thrown when I call a test page and I get a 500 response.

Here is my startup.cs code:
```
Console.WriteLine("Current Path: " + Environment.CurrentDirectory);
loggerFactory.AddNLog();
env.ConfigureNLog(@".\nlog.config");


```
Here is the output from the console:

```
Current Path: P:\MyTestApp\nxt\wallet\wallet\src\wallet\bin\Debug\net461\win7-x64\publish
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.GetParent(String path)
   at NLog.Extensions.Logging.AspNetExtensions.ConfigureNLog(IHostingEnvironment env, String configFileRelativePath)
   at wallet.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in P:\MyTestApp\nxt\wallet\wallet\src\wallet\Startup.cs:line 99
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: P:\MyTestApp\nxt\wallet\wallet\src\wallet\bin\Debug\net461\win7-x64\publish
Now listening on: http://localhost:31844/WALLETAPI
Application started. Press Ctrl+C to shut down.

```
The nlog.config file is 
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd nlog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Error" 
      internalLogFile="c:\temp\nlog-internal.log" >
  <targets>
    <target xsi:type="ColoredConsole" name="console"/>
    <!--Writing events to the a file with the date in the filename.--> 
    <target xsi:type="File" name="debugFile" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    <target xsi:type="File" name="infolog" fileName="${basedir}/logs/info-${shortdate}.log"
layout="${longdate}|${level}|${callsite:className=true:methodName=true}|${machinename}|${message}" />
    <target xsi:type="File" name="bonzi" fileName="${basedir}/logs/bonzi-${shortdate}.log"
        layout="${longdate} ${uppercase:${level}} ${message} ${newline} ${stacktrace} ${newline} ${exception:format=ToString}" />
  </targets>
  <rules>
    <!-- add your logging rules here -->
    <!--<logger name="*" levels="Info,Warn,Debug" writeTo="console" />-->
    <logger name="*" levels="Debug,Warn" writeTo="debugFile" />
    <logger name="*" levels="Trace,Info,Debug" writeTo="infolog" />
    <logger name="*" levels="Error,Fatal" writeTo="bonzi" />
    <!--<logger name="*" minlevel="Off" writeTo="bonzi" />
    <logger name="*" level="Off" writeTo="exceptiondb" />-->
  </rules>
</nlog>

```
The most odd thing is even though it's throwing this exception, and I'm getting a 500 response from the server, it is creating log files.  If I comment out the two configuration lines in the startup file, I get the expected result from the GET, not a 500 response (and of course no nlog files).

Very strange. 

the nlog.config file is published where it's expected. It's in the same directory as the web.config, executable.

Putting a Try/Catch wrapper around the two nlog lines in startup.cs results in a 200 response with the expected content, nlog files written, and the following console output:
```
Current Path: P:\MyTestApp\nxt\wallet\wallet\src\wallet\bin\Debug\net461\win7-x64\publish
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.GetParent(String path)
   at NLog.Extensions.Logging.AspNetExtensions.ConfigureNLog(IHostingEnvironment env, String configFileRelativePath)
   at wallet.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in P:\MyPaymentsPlus\nxt\wallet\wallet\src\wallet\Startup.cs:line 101
Hosting environment: Production
Content root path: P:\MyTestApp\nxt\wallet\wallet\src\wallet\bin\Debug\net461\win7-x64\publish
Now listening on: http://localhost:4598/WALLETAPI
Application started. Press Ctrl+C to shut down.

```

**Comment by 304NotModified** [comment]
> Question: (how the heck do you add a tag for this?)

Do you mean 'label'? Only users with write rights could do this (too bad)

This is a known bug, the environment value used in the code is unexpected `null`.

Work around:  

instead of `env.ConfigureNLog(@".\nlog.config");`

use ` LogManager.Configuration = new XmlLoggingConfiguration(fileName, true);`

**Comment by EltonInAtlanta** [comment]
>> Do you mean 'label'? Only users with write rights could do this (too bad)
Ah, something to aspire to!

Thanks for the tip.  If only all my problems were so easily solved.  Any thought on my other mystery?

**Comment by 304NotModified** [comment]
The error? See the work around. It's a bug :(

**Comment by 304NotModified** [comment]
dupl of https://github.com/NLog/NLog.Extensions.Logging/issues/43

**Comment by EltonInAtlanta** [comment]
Sorry.  I meant issue 1512

**Comment by 304NotModified** [comment]
This should be fixed: https://www.nuget.org/packages/NLog.Extensions.Logging/1.0.0-rtm-alpha2

if not, please let us know!

thanks @ORuban !
