### ISSUE TITLE
Nlog SQL Database Target

### ISSUE THREAD

**Issue by mahikkp** [NLog/NLog#1516]
Hi..
I am working  on log's store in  SQL database using NLog. after run my console application the application it's working fine but the log's are not stored in the table. Can you please check what iam missing.

**the below are console application.**

```c#
programe.cs file
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NLog;

namespace NLog
{
    class Program
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        static void Main(string[] args)
        {
            
            try
            {

                int zero = 0;
                int result = 5 / zero;
            }
            catch (DivideByZeroException ex)
            {
                var logger = LogManager.GetLogger("db");
                logger.Debug("What is going on here");
              

            }
            Console.WriteLine("we are now passed the expetion handler logic");
            Console.ReadLine();

        }
    }
}
```

**the NLog.config file ;**

```xml
<?xml version="1.0" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <!--<targets>
    <target name="file" xsi:type="File"
        layout="${date:format=yyyy-MM-dd} ${message}"
        fileName="${basedir}/logs/logfile.txt"
        keepFileOpen="true"
        encoding="iso-8859-2" />
  </targets>-->
  <targets>
    <target name="db"
          xsi:type="Database"
          connectionStringName="NLogConn"
          commandType="StoredProcedure"
          commandText="[dbo].[NLog_AddEntry_p]"
        >
      <parameter name="@machineName"    layout="${machinename}" />
      <parameter name="@siteName"       layout="${iis-site-name}" />
      <parameter name="@logged"         layout="${date}" />
      <parameter name="@level"          layout="${level}" />
      <parameter name="@username"       layout="${aspnet-user-identity}" />
      <parameter name="@message"        layout="${message}" />
      <parameter name="@logger"         layout="${logger}" />
      <parameter name="@properties"     layout="${all-event-properties:separator=|}" />
      <parameter name="@serverName"     layout="${aspnet-request:serverVariable=SERVER_NAME}" />
      <parameter name="@port"           layout="${aspnet-request:serverVariable=SERVER_PORT}" />
      <parameter name="@url"            layout="${aspnet-request:serverVariable=HTTP_URL}" />
      <parameter name="@https"          layout="${when:inner=1:when='${aspnet-request:serverVariable=HTTPS}' == 'on'}${when:inner=0:when='${aspnet-request:serverVariable=HTTPS}' != 'on'}" />
      <parameter name="@serverAddress"  layout="${aspnet-request:serverVariable=LOCAL_ADDR}" />
      <parameter name="@remoteAddress"  layout="${aspnet-request:serverVariable=REMOTE_ADDR}:${aspnet-request:serverVariable=REMOTE_PORT}" />
      <parameter name="@callSite"       layout="${callsite}" />
      <parameter name="@exception"      layout="${exception:tostring}" />
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="db" />
  </rules>
</nlog>
```

App.config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
  <connectionStrings>
    <add name="NLogConn" providerName="System.Data.SqlClient" connectionString="Server=Servername ;Database=Databasename;User ID=username;Password=password;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;" />
</connectionStrings>
</configuration>
```

**Comment by 304NotModified** [comment]
Hi,  please check the internal log and do use the issue template if you still need help.

**Comment by mahikkp** [comment]
this is the internal log's

2016-06-22 13:17:58.7848 Debug Loading config from C:\Views\NLog\NLog\NLog\bin\Debug\NLog.config
2016-06-22 13:17:58.7978 Trace ParseNLogElement
2016-06-22 13:17:58.8148 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2016-06-22 13:17:58.8728 Debug Start auto loading, location: C:\Views\NLog\NLog\NLog\bin\Debug
2016-06-22 13:17:58.8788 Debug Auto loading done
2016-06-22 13:17:58.8928 Debug Setting 'DatabaseTarget.name' to 'database'
2016-06-22 13:17:58.8928 Debug Setting 'DatabaseTarget.connectionStringName' to 'NLogConn'
2016-06-22 13:17:58.8928 Debug Setting 'DatabaseTarget.commandText' to 'exec NLog_AddEntry_p           @machineName,           @siteName,           @logged,           @level,           @username,           @message,           @message,           @logger,           @properties,           @properties,           @serverName,           @port,           @url,           @https,           @serverAddress,           @remoteAddress,           @callSite,           @exception                      '
2016-06-22 13:17:58.9128 Debug Setting 'DatabaseParameterInfo.name' to '@machineName'
2016-06-22 13:17:58.9128 Debug Setting 'DatabaseParameterInfo.layout' to '${machinename}'
2016-06-22 13:17:58.9268 Trace FindReachableObject<NLog.Internal.IRenderable>:
2016-06-22 13:17:58.9268 Trace Scanning MachineNameLayoutRenderer 'Layout Renderer: ${machinename}'
2016-06-22 13:17:58.9418 Debug Setting 'DatabaseParameterInfo.name' to '@siteName'
2016-06-22 13:17:58.9418 Debug Setting 'DatabaseParameterInfo.layout' to '${iis-site-name}'
2016-06-22 13:17:58.9958 Warn Error when setting property 'Layout' on 'NLog.Targets.DatabaseParameterInfo' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'iis-site-name'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
2016-06-22 13:17:59.0208 Error Error in Parsing Configuration File. Exception: NLog.NLogConfigurationException: Exception occurred when loading configuration from C:\Views\NLog\NLog\NLog\bin\Debug\NLog.config ---> NLog.NLogConfigurationException: Error when setting property 'Layout' on NLog.Targets.DatabaseParameterInfo ---> System.ArgumentException: LayoutRenderer cannot be found: 'iis-site-name'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2016-06-22 13:17:59.0208 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Error when setting property 'Layout' on NLog.Targets.DatabaseParameterInfo ---> System.ArgumentException: LayoutRenderer cannot be found: 'iis-site-name'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
2016-06-22 13:17:59.0399 Debug --- NLog configuration dump ---
2016-06-22 13:17:59.0399 Debug Targets:
2016-06-22 13:17:59.0549 Debug Rules:
2016-06-22 13:17:59.0549 Debug --- End of NLog configuration dump ---
2016-06-22 13:17:59.0769 Trace FindReachableObject<System.Object>:
2016-06-22 13:17:59.0849 Info Found 0 configuration items
2016-06-22 13:17:59.0849 Info Configuration initialized.
2016-06-22 13:17:59.1009 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.3.2698. Product version: 4.3.5.
2016-06-22 13:17:59.1009 Debug Targets for NLog.Program by level:
2016-06-22 13:17:59.1159 Debug Trace =>
2016-06-22 13:17:59.1159 Debug Debug =>
2016-06-22 13:17:59.1289 Debug Info =>
2016-06-22 13:17:59.1289 Debug Warn =>
2016-06-22 13:17:59.1429 Debug Error =>
2016-06-22 13:17:59.1429 Debug Fatal =>

**Comment by 304NotModified** [comment]
> LayoutRenderer cannot be found: 'iis-site-name'

Registration of the NLog.Web  extension failed.  Did you installed that nuget package? Which platform is this?

**Comment by mahikkp** [comment]
after register  NLog.Web.dll now it's  stored the logs in database.
and one more question 1) how to assign value in layout in C#.
Ex: layout="${username}"
how to assign  username value in .cs file.

Thanks

**Comment by 304NotModified** [comment]
Ok nice! 

See https://github.com/NLog/NLog/wiki/Var-Layout-Renderer
