### ISSUE TITLE
Error on Nlog 4.3.5 when target type is DataBase

### ISSUE THREAD

**Issue by Mostafasaffari** [NLog/NLog#1535]
Hi

**Type** (choose one):

- Bug

**NLog version**: (4.3.5)

**Platform**: .Net 4.6.1

i use target database but when i use nlog 4.3.5 Nlog fired this error on C:\temp

```
2016-07-10 11:58:04.1627 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2016-07-10 11:58:04.1927 Debug Start auto loading, location: C:\Users\Mostafa\Documents\Visual Studio 2013\Projects\testnlog\testnlog\bin
2016-07-10 11:58:04.1927 Debug Auto loading done
2016-07-10 11:58:04.2097 Debug Setting 'DatabaseTarget.name' to 'database'
2016-07-10 11:58:04.2097 Debug Setting 'DatabaseTarget.connectionStringName' to 'SGPVOCConnectionString'
2016-07-10 11:58:04.2097 Debug Setting 'DatabaseTarget.commandText' to '
        INSERT INTO [dbo].[Logs] (
        [MachineName],
        [SiteName],
        [Logged],
        [Level],
        [UserName],
        [Message],
        [Logger],
        [Properties],
        [ServerName],
        [Port],
        [Url],
        [ServerAddress],
        [RemoteAddress],
        [CallSite],
        [Exception],
        [Browser],
        [HeaderSent],
        [RegisterDate],
        [IsActive]
        ) VALUES (
        @machineName,
        @siteName,
        @logged,
        @level,
        @userName,
        @message,
        @logger,
        @properties,
        @serverName,
        @port,
        @url,
        @serverAddress,
        @remoteAddress,
        @callSite,
        @exception,
        @browser,
        @headersent,
        GetDate(),
        1
        );
      '
2016-07-10 11:58:04.2147 Debug Setting 'DatabaseParameterInfo.name' to '@machineName'
2016-07-10 11:58:04.2147 Debug Setting 'DatabaseParameterInfo.layout' to '${machinename}'
2016-07-10 11:58:04.2147 Trace FindReachableObject<NLog.Internal.IRenderable>:
2016-07-10 11:58:04.2147 Trace Scanning MachineNameLayoutRenderer 'Layout Renderer: ${machinename}'
2016-07-10 11:58:04.2147 Debug Setting 'DatabaseParameterInfo.name' to '@siteName'
2016-07-10 11:58:04.2147 Debug Setting 'DatabaseParameterInfo.layout' to '${iis-site-name}'
2016-07-10 11:58:04.2718 Warn Error when setting property 'Layout' on 'NLog.Targets.DatabaseParameterInfo' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'iis-site-name'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
2016-07-10 11:58:04.3058 Error Error in Parsing Configuration File. Exception: NLog.NLogConfigurationException: Exception occurred when loading configuration from C:\Users\Mostafa\Documents\Visual Studio 2013\Projects\testnlog\testnlog\NLog.config ---> NLog.NLogConfigurationException: Error when setting property 'Layout' on NLog.Targets.DatabaseParameterInfo ---> System.ArgumentException: LayoutRenderer cannot be found: 'iis-site-name'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2016-07-10 11:58:04.3058 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Error when setting property 'Layout' on NLog.Targets.DatabaseParameterInfo ---> System.ArgumentException: LayoutRenderer cannot be found: 'iis-site-name'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
2016-07-10 11:58:04.3087 Debug --- NLog configuration dump ---
2016-07-10 11:58:04.3087 Debug Targets:
2016-07-10 11:58:04.3087 Debug Rules:
2016-07-10 11:58:04.3087 Debug --- End of NLog configuration dump ---
2016-07-10 11:58:04.3087 Info Watching path 'C:\Users\Mostafa\Documents\Visual Studio 2013\Projects\testnlog\testnlog' filter 'NLog.config' for changes.
2016-07-10 11:58:04.3087 Trace FindReachableObject<System.Object>:
2016-07-10 11:58:04.3087 Info Found 0 configuration items
2016-07-10 11:58:04.3087 Info Configuration initialized.
2016-07-10 11:58:04.3087 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.3.2698. Product version: 4.3.5.
2016-07-10 11:58:04.3248 Debug Targets for testnlog.Controllers.HomeController by level:
2016-07-10 11:58:04.3248 Debug Trace =>
2016-07-10 11:58:04.3248 Debug Debug =>
2016-07-10 11:58:04.3248 Debug Info =>
2016-07-10 11:58:04.3248 Debug Warn =>
2016-07-10 11:58:04.3248 Debug Error =>
2016-07-10 11:58:04.3248 Debug Fatal =>
```

**Comment by 304NotModified** [comment]
This is the error :

> LayoutRenderer cannot be found: 'iis-site-name

Did you included NLog.Web?

**Comment by Mostafasaffari** [comment]
yes i used nlog 4.2.3 and it worked. but now update 4.3.5 and nlog fire this error.
and  NLog.Logger can't recognize target database.

this is my nlog config

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >


  
  <variable name="myvar" value="myvalue"/>
  <extensions>
    <add assembly="NLog.Extended"/>
    <add assembly="NLog.Web"/>
  </extensions>
  
  <targets>

    

    

    <target name="database" xsi:type="Database">
      <connectionStringName>BgGoldConnectionString</connectionStringName>
      <commandText>
        INSERT INTO [dbo].[Logs] (
        [MachineName],
        [SiteName],
        [Logged],
        [Level],
        [UserName],
        [Message],
        [Logger],
        [Properties],
        [ServerName],
        [Port],
        [Url],
        [ServerAddress],
        [RemoteAddress],
        [CallSite],
        [Exception],
        [Browser],
        [HeaderSent],
        [RegisterDate],
        [IsActive],
        [IsDelete]
        ) VALUES (
        @machineName,
        @siteName,
        @logged,
        @level,
        @userName,
        @message,
        @logger,
        @properties,
        @serverName,
        @port,
        @url,
        @serverAddress,
        @remoteAddress,
        @callSite,
        @exception,
        @browser,
        @headersent,
        GetDate(),
        1,
        0
        );
      </commandText>

      <parameter name="@machineName"    layout="${machinename}" />
      <parameter name="@siteName"       layout="${iis-site-name}" />
      <parameter name="@logged"         layout="${date}" />
      <parameter name="@level"          layout="${level}" />
      <parameter name="@username"       layout="${aspnet-user-identity}" />
      <parameter name="@message"        layout="${message}" />
      <parameter name="@logger"         layout="${logger}" />
      <parameter name="@properties"     layout="${all-event-properties:separator=|}" />
      <parameter name="@serverName"     layout="${aspnet-request:serverVariable=SERVER_NAME}" />
      <parameter name="@port"           layout="${aspnet-request:serverVariable=SERVER_PORT}" />
      <parameter name="@url"            layout="${aspnet-request:serverVariable=HTTP_URL}" />
      <parameter name="@serverAddress"  layout="${aspnet-request:serverVariable=LOCAL_ADDR}" />
      <parameter name="@remoteAddress"  layout="${aspnet-request:serverVariable=REMOTE_ADDR}:${aspnet-request:serverVariable=REMOTE_PORT}" />
      <parameter name="@callSite"       layout="${callsite}" />
      <parameter name="@exception"      layout="${exception:tostring}" />
      <parameter name="@browser"        layout="${aspnet-request:item=HTTP_USER_AGENT}" />
      <parameter name="@headersent"     layout="${aspnet-request:item=ALL_HTTP}" />
    </target>

  </targets>

  <rules>
    

    
    <logger name="*" minlevel="Trace" writeTo="database">
      <filters>
        <when condition="equals('${logger}','BgGold.Domain.Core.Language')" action="Ignore" />
        <when condition="equals('${logger}','BgGold.Domain.Core.LanguageDictionary')" action="Ignore" />
      </filters>
    </logger>
  </rules>
</nlog>

**Comment by 304NotModified** [comment]
Is nlog.web.dll in  C:\Users\Mostafa\Documents\Visual Studio 2013\Projects\testnlog\testnlog\bin?

**Comment by Mostafasaffari** [comment]
no, is not on there!
just exists nlog.dll
i get nlog config on nuget

**Comment by 304NotModified** [comment]
Please try to (re) install nlog.web from nuget.

**Comment by Mostafasaffari** [comment]
yes it's work
thank you

**Comment by 304NotModified** [comment]
Glad to hear!
