### ISSUE TITLE
Without Nlog.config  file how to set target using C#

### ISSUE THREAD

**Issue by mahikkp** [NLog/NLog#1538]
Hi team,
I am trying to find the solution for Without Nlog.config  file how to set target using C#.  we need to store the logs in Database. 

the below example for logs stored  in to file but now i want to store the logs in SQL  Database.
             string fileName = "test.txt";

                #region Setup Logger settings

                string nameID = "Test";
                FileTarget fileTarget = new FileTarget();
                fileTarget.Name = nameID;
                fileTarget.NetworkWrites = true;
                fileTarget.KeepFileOpen = false;
                fileTarget.FileName = string.Concat(System.IO.Path.Combine(path, fileName), ".${date:format=yyyyMMdd}.active");

                fileTarget.ArchiveFileName = string.Concat(System.IO.Path.Combine(path, fileName), ".${date:format=yyyyMMdd}.{#}");
                fileTarget.ArchiveAboveSize = 5242880; // Updated to 5 MB to allow HACC Light to read fewer files.

                fileTarget.ArchiveNumbering = ArchiveNumberingMode.Sequence;
                fileTarget.MaxArchiveFiles = 9999;
                fileTarget.ConcurrentWrites = true;

                fileTarget.Layout = "${message}";
                config.AddTarget(nameID, fileTarget);
                config.LoggingRules.Add(new LoggingRule(nameID, LogLevel.Info, fileTarget));

Thanks.

**Comment by 304NotModified** [comment]
Well  something like that, but using databaseTarget. See http://nlog-project.org/documentation/v4.3.0/html/T_NLog_Targets_DatabaseTarget.htm

**Comment by mahikkp** [comment]
Thanks for the reply..
i implemented Database target but after debugging the application. logs are not stored  to the databse.see the below are internal logs and and my code.

internal logs :
2016-07-13 10:10:26.1376 Info Found 48 configuration items
2016-07-13 10:10:26.2216 Info Found 48 configuration items
2016-07-13 10:11:30.5056 Error Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString)
   at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString)
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
ClientConnectionId:00000000-0000-0000-0000-000000000000


my code:

DatabaseTarget target = new DatabaseTarget();
            DatabaseParameterInfo param;

            target.DBProvider = "sqlserver";
            target.DBHost = ".";

            target.Name = "database";
           target.DBUserName = "DBusername";
            target.DBPassword = "Dbpassword";
            target.DBDatabase = "Dbname";
            target.CommandText = "exec NLog_Webservice @site_id,@request_xml,@response_xml,@servername, @datetimestamp,@session_id,@method, @username,@data1,@data2,@data3,@data4";

            param = new DatabaseParameterInfo();
            param.Name = "@site_id";
            param.Layout = "${gdc:item=site_id}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@request_xml";
            param.Layout = "${gdc:item=requestxml}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@response_xml";
            param.Layout = "${gdc:item=responsexml}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@servername";
            param.Layout = "${machinename}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@datetimestamp";
            param.Layout = "${date}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@session_id";
            param.Layout = "${gdc:item=sessionid}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@method";
            param.Layout = "${gdc:item=method}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@username";
            param.Layout = "${windows-identity}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@data1";
            param.Layout = "${gdc:item=data1}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@data2";
            param.Layout = "${gdc:item=data2}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@data3";
            param.Layout = "${gdc:item=data3}";
            target.Parameters.Add(param);

            param = new DatabaseParameterInfo();
            param.Name = "@data4";
            param.Layout = "${gdc:item=data4}";
            target.Parameters.Add(param);
            InternalLogger.LogFile = "c:\\log1.txt";
           

            config.AddTarget(target.Name, target);
            config.LoggingRules.Add(new LoggingRule("tableLogegr", LogLevel.Debug, target));
            NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(target, LogLevel.Debug);

            Logger logger = LogManager.GetLogger("tableLogegr");
            logger.Debug("log message");

**Comment by 304NotModified** [comment]
Isn't the errori n the log clear? The credentials are wrong

**Comment by 304NotModified** [comment]
http://stackoverflow.com/questions/6134359/read-connection-string-from-web-config

**Comment by mahikkp** [comment]
after implemented your solution we are getting connection string is  null. please see the below Code.

target.DBProvider = "sqlserver";
            target.DBHost = ".";
            target.Name = "database";
            target.ConnectionString = ConfigurationManager.ConnectionStrings["NLogConn"].ConnectionString;
            target.CommandText = "exec NLog_Webservice @site_id,@request_xml,@response_xml,@servername, @datetimestamp,@session_id,@method, @username,@data1,@data2,@data3,@data4";

**Comment by 304NotModified** [comment]
please debug your own code.  I `ConfigurationManager.ConnectionStrings["NLogConn"].ConnectionString;` really returning a value?

**Comment by mahikkp** [comment]
this statement  throwing null reference exception.
target.ConnectionString=System.Configuration.ConfigurationManager.ConnectionStrings["NLogConn"].ConnectionString;

**Comment by 304NotModified** [comment]
maybe you need ConfigurationManager.AppSettings, see https://msdn.microsoft.com/en-us/library/system.configuration.configurationmanager(v=vs.110).aspx

that's dependent of your .config.

Or maybe your .config is just wrong.

**Comment by 304NotModified** [comment]
We assume this question has been answered. If not, just let us know!
