### ISSUE TITLE
NLog 3 to 4 exception

### ISSUE THREAD

**Issue by chrisdrobison** [NLog/NLog#1552]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      throwExceptions="true"
      autoReload="true">

  <variable name="logPath" value="C:\Logs"/>
  <variable name="fileName" value="XactPrmMigration"/>

  <variable name="timeJson" value='"Time":"${longdate:jsonEncode=true}"'/>
  <variable name="levelJson" value='"Level":"${level}"'/>
  <variable name="machineJson" value='"Machine":"${machinename:jsonEncode=true}"'/>
  <variable name="loggerJson" value='"Logger":"${logger:jsonEncode=true}"'/>
  <variable name="callSiteJson" value='"CallSite":"${callsite:jsonEncode=true}"'/>
  <variable name="messageJson" value='"Message":"${message:jsonEncode=true}"'/>
  <variable name="generalInfoJson" value ='${timeJson},${newline}${levelJson},${newline}${machineJson},${newline}${loggerJson},${newline}${callSiteJson},${newline}${messageJson}'/>

  <variable name="exceptionType" value = '"ExceptionType"\:"${exception:format=type:jsonEncode=true}"'/>
  <variable name="exceptionMessage" value = '"ExceptionMessage"\:"${exception:format=message:jsonEncode=true}"'/>
  <variable name="exceptionMethod" value = '"ExceptionSourceMethod"\:"${exception:format=method:jsonEncode=true}"'/>
  <variable name="exceptionStackTrace" value = '"ExceptionStackTrace"\:"${exception:format=stacktrace:maxInnerExceptionLevel=15:innerFormat=type,message,method,stacktrace:jsonEncode=true}"'/>
  <variable name="excJsonBlock" value = '${exceptionType},${newline}${exceptionMessage},${newline}${exceptionMethod},${newline}${exceptionStackTrace}'/>

  <!-- 
  See http://nlog-project.org/wiki/Configuration_file 
  for information on customizing logging rules and outputs.
   -->
  <targets>
    <target xsi:Type="AsyncWrapper" name="log-file" queueLimit="5000" overflowAction="Discard">
      <target xsi:type="File" fileName="${logPath}\${fileName}.log" createDirs="true"
              autoFlush="true"
              layout="{${generalInfoJson}${onexception:,${newline}${excJsonBlock}}}${newline}"
              maxArchiveFiles="5"
              archiveNumbering="Date"
              archiveEvery="Day"
              archiveDateFormat="yyyy-MM-dd"
              archiveFileName="${logPath}\${fileName}.{#}.log"/>
    </target>

    <target xsi:type="Console"
            name="console"
            layout="${longdate} | ${level:uppercase=true} | ${message} ${exception:format=tostring:maxInnerExceptionLevel=10}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="log-file"></logger>
    <logger name="*" minlevel="Debug" writeTo="console"></logger>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?

We just barely upgraded from NLog 3 to NLog 4 and are getting an exception we can't explain. Deleting all the log files seems to fix the issue. We've been unable to reproduce in dev.

- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, here is the relevant output.

2016-07-22 11:58:26.0537 Trace Calculating archive date. Last write time: 07/20/2016 12:11:01; Previous log event time: 
2016-07-22 11:58:26.0537 Trace Using last write time
2016-07-22 11:58:26.0537 Info Archiving C:\Logs\XactPrmMigration.log to C:\Logs\XactPrmMigration.2016-07-20.log
2016-07-22 11:58:26.0537 Error Error has been raised. Exception: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
2016-07-22 11:58:26.0537 Error AsyncWrapper 'log-file': Error in lazy writer timer procedure. Exception: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
   at NLog.Targets.FileTarget.Write(AsyncLogEventInfo[] logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEventInfos, AsyncContinuation continuation)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)

- Please post full exception details (message, stacktrace, inner exceptions)

[11:50:31][Step 1/4] Unhandled Exception:
[11:50:31][Step 1/4] NotSpecified: (:) [], RemoteException
[11:50:31][Step 1/4] System.IO.IOException: Cannot create a file when that file already exists.
[11:50:31][Step 1/4]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
[11:50:31][Step 1/4]    at System.IO.File.InternalMove(String sourceFileName, String destFileName, 
[11:50:31][Step 1/4] Boolean checkHost)
[11:50:31][Step 1/4]    at NLog.Targets.FileTarget.ArchiveFile(String fileName, String 
[11:50:31][Step 1/4] archiveFileName)
[11:50:31][Step 1/4]    at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, 
[11:50:31][Step 1/4] LogEventInfo logEvent)
[11:50:31][Step 1/4]    at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo 
[11:50:31][Step 1/4] eventInfo)
[11:50:31][Step 1/4]    at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String 
[11:50:31][Step 1/4] fileName, Byte[] bytesToWrite)
[11:50:31][Step 1/4]    at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, 
[11:50:31][Step 1/4] LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
[11:50:31][Step 1/4]    at NLog.Targets.FileTarget.Write(AsyncLogEventInfo[] logEvents)
[11:50:31][Step 1/4]    at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEvents)
[11:50:31][Step 1/4]    at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object 
[11:50:31][Step 1/4] state)
[11:50:31][Step 1/4]    at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
[11:50:31][Step 1/4]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext 
[11:50:31][Step 1/4] executionContext, ContextCallback callback, Object state, Boolean 
[11:50:31][Step 1/4] preserveSyncCtx)
[11:50:31][Step 1/4]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, 
[11:50:31][Step 1/4] ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:50:31][Step 1/4]    at System.Threading.TimerQueueTimer.CallCallback()
[11:50:31][Step 1/4]    at System.Threading.TimerQueueTimer.Fire()
[11:50:31][Step 1/4]    at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
[11:50:31][Step 1/4]    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWo
[11:50:31][Step 1/4] rkItem.ExecuteWorkItem()
[11:50:31][Step 1/4]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[11:50:31][Step 1/4]    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

- Are there any work arrounds? yes/no

Yes, delete all logs

- Is there a version in which it did worked? 

NLog 3

- Can you help us by writing an unit test?

No able to reliably reproduce this.

**Comment by 304NotModified** [comment]
This exception was probably also in NLog 3, but masked. See http://nlog-project.org/2016/04/16/nlog-4-3-has-been-released.html "Consistent handling of exceptions (BEHAVIOUR CHANGE)"

**Comment by chrisdrobison** [comment]
Ok, I totally thought I had this stuff set correctly, apparently I didn't. Thanks.
