### ISSUE TITLE
How to update connection string from code in DatabaseTarget?

### ISSUE THREAD

**Issue by QuAzI** [NLog/NLog#1570]
Hi!

How can I update ConnectionString from C# code ?
Now I have this code

```
Target targetWrapper = LogManager.Configuration.FindTargetByName("database");
if (targetWrapper is AsyncTargetWrapper)
{
    databaseTarget = (targetWrapper as AsyncTargetWrapper).WrappedTarget as DatabaseTarget;
}
else if (targetWrapper is DatabaseTarget)
{
    databaseTarget = targetWrapper as DatabaseTarget;
}

if (databaseTarget != null)
{
    databaseTarget.ConnectionString = connectionString;
    LogManager.ReconfigExistingLoggers();
}
```

After ReconfigExistingLoggers() no logs writed to DB anymore. If ConnectionString configured in app.config - only before ReconfigExistingLoggers() log writed even if ConnectionString not changed;

My app.config
```
<target name="database" type="Database" keepConnection="true" useTransactions="true"
        dbProvider="System.Data.SqlClient"
        connectionString="data source=localhost;initial catalog=Logs;user id=sa;password=local_pass"
        dbDatabase="Logs"
        commandText="INSERT INTO Logger ([Time],[Severity],[Thread],[Logger],[Message],[Error],[StackTrace]) VALUES (@Time,@Severity,@Thread,@Logger,@Message,@Error,@StackTrace);">
    <parameter name="Time" layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff}" />
    <parameter name="Severity" layout="${level:uppercase=true}" />
    <parameter name="Thread" layout="${threadname}" />
    <parameter name="Logger" layout="${logger}" />
    <parameter name="Message" layout="${message}" />
    <parameter name="Error" layout="${exception}" />
    <parameter name="StackTrace" layout="${stacktrace}, ${callsite-linenumber}" />
</target>
```
in internal NLog log I see next
```
2016-07-28 15:00:56.6910 Error Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Logger'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(AsyncLogEventInfo[] logEvents)
```

**NLog version**: (e.g. 4.3.5)
**Platform**: .Net 4.0
**Database**: MS SQL Server 2014

**Comment by 304NotModified** [comment]
It seems from the error that the logger table isn't found. Can you enable the internal log on trace level and post it?

**Comment by 304NotModified** [comment]
> databaseTarget.ConnectionString = connectionString;

This is OK and should be enough

**Comment by QuAzI** [comment]
Log table renamed for compliance with project name, it is ok

Internal log
[nlog-internal.txt](https://github.com/NLog/NLog/files/390079/nlog-internal.txt)

Schema
![cl_yarsql2014 logs_-_dbo zugls_-_microsoft_sql_se_ssms_2016-07-29_10-57-13_ojwbyaae](https://cloud.githubusercontent.com/assets/1897605/17241597/43277c42-557b-11e6-91e2-7a9e7310cde0.png)

**Comment by UgurAldanmaz** [comment]
In your internal log file, I see that inserting log record is succeed.

Your problem is solved?

**Comment by QuAzI** [comment]
Sorry.
Old log was made with removed ConnectionString updating.
Log updated.

**Comment by 304NotModified** [comment]
I see in the log it reopens the new connection correctly:

> 2016-07-29 17:39:41.5106 Trace DatabaseTarget: close connection because of opening new.
2016-07-29 17:39:41.5106 Trace DatabaseTarget: open connection.
2016-07-29 17:39:41.5106 Trace Executing Text: INSERT INTO ZugLS ([Time],[Severity],[Thread],[Logger],[Message],[Error],[StackTrace]) VALUES (@Time,@Severity,@Thread,@Logger,@Message,@Error,@StackTrace);
2016-07-29 17:39:41.5106 Trace   Parameter: 'Time' = '2016-07-29 17:39:41.478' (String)
2016-07-29 17:39:41.5106 Trace   Parameter: 'Severity' = 'TRACE' (String)
2016-07-29 17:39:41.5106 Trace   Parameter: 'Thread' = '' (String)
2016-07-29 17:39:41.5106 Trace   Parameter: 'Logger' = 'ZugLSCommon.Logger' (String)
2016-07-29 17:39:41.5106 Trace   Parameter: 'Message' = '' (String)
2016-07-29 17:39:41.5106 Trace   Parameter: 'Error' = '' (String)
2016-07-29 17:39:41.5106 Trace   Parameter: 'StackTrace' = 'TISDBEventLogger.AddDBLog => Logger.AddDBLog => Logger.AddDBLog, 189' (String)
2016-07-29 17:39:41.5106 Error Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'ZugLS'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(AsyncLogEventInfo[] logEvents)
ClientConnectionId:cc69e9be-9f16-4bb0-a0b7-b84da8abc139


The open connection succeeds, but writing not.

> Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'ZugLS'.

Are you sure your new connectionstring is OK? I think the login and server is OK, but it points to the wrong database? It can't find the table 'ZugLS' in the database.

**Comment by QuAzI** [comment]
Oops. This is my mistake. Sorry.
Encoded connection string connect to existing copy of database on this server but this copy has no table for log.
Thanks!
