### ISSUE TITLE
Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by viseu** [NLog/NLog#1608]
Type: Bug

NLog version: 4.3.7

Platform: .NET 4.6.1

Current NLog config

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">
    <targets>
        <target name="BackgroundUploaderLog" xsi:type="File" maxArchiveFiles="5" archiveNumbering="Rolling" archiveAboveSize="20" concurrentWrites="true" filename="App.log" />
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="BackgroundUploaderLog" />
    </rules>
  </nlog>

```

In case of a BUG:

- What is the current result?
An exception is likely to occur if the attached project is run through visual studio . Try to run few times, should be reproducible at least one time for each 5 executions.  Note that the exception is less likely to be thrown whilst running in command line.

- What is the expected result?
Write the logs without exception.

- Please post full exception details (message, stacktrace, inner exceptions)

```
Unhandled Exception: System.IO.IOException: Cannot create a file when that file
already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Bo
olean checkHost)
   at NLog.Targets.FileTarget.RollArchiveForward(String existingFileName, String
 newFileName)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventI
nfo)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String file
Name, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetL
istHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogE
ventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object mes
sage, Exception exception) in c:\_oss\common-logging\src\Common.Logging.NLog10\L
ogging\NLog\NLogLogger.cs:line 951
   at Common.Logging.NLog.NLogLogger.Debug(Object message) in c:\_oss\common-log
ging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 272
   at ConsoleApplication1.LongRunningProcess.Run() in c:\users\fernando\document
s\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\LongRunnin
gProcess.cs:line 24
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

- Are there any work arrounds? 
No. I tried to use keepFileOpen = true and an AsyncWrapper.
I also tried to use the version 4.4.0 Beta V15, but with the same results.

[ConsoleApplication1.zip](https://github.com/NLog/NLog/files/449208/ConsoleApplication1.zip)

**Comment by 304NotModified** [comment]
I will try to look at this when I have returned from my holiday. (10 sept)

**Comment by viseu** [comment]
No worries. Enjoy your holidays!

**Comment by 304NotModified** [comment]
Thx!

**Comment by 304NotModified** [comment]
After 20 runs I cannot reproduce this. 

I think this is a race condition. I think I can fix the race condition by retrying. If I create a beta package, could you test this within a few days?

**Comment by viseu** [comment]
Hi,
Sure I can.
Tks

**Comment by 304NotModified** [comment]
Please test with the following (hidden) package

 https://www.nuget.org/packages/NLog/4.3.9-test-retry-archive

**Comment by viseu** [comment]
I still get an exception. Tks

Access to the path 'C:\Users\fernando\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\bin\Debug\App.4.log' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String pattern, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String pattern, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String pattern, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String pattern, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String pattern, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String pattern, Int32 archiveNumber)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 951
   at Common.Logging.NLog.NLogLogger.Debug(Object message) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 272
   at ConsoleApplication1.AnotherLongRunningProcess.Run() in C:\Users\fernando\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\AnotherLongRunningProcess.cs:line 23
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by 304NotModified** [comment]
are the rights set right? as "Access to the path ... denied"  is a NTFS error?

**Comment by viseu** [comment]
Yes. It only happens once after 30 executions (roughly). 

Would you kindly run the following on your command line against the sample I provided:

for /l %x in (0,1,30) do (ConsoleApplication1.exe)

If you don't get any exception, then this may be on my environment and this issue can be closed. The other exception seems gone!

**Comment by 304NotModified** [comment]
> Would you kindly run the following on your command line against the sample I provided:

Will try to do this this week. A bit more difficult that responding on questions (on mobile) ;)

**Comment by 304NotModified** [comment]
like this?

![image](https://cloud.githubusercontent.com/assets/5808377/18489273/2e3d22f4-79fd-11e6-8b6c-51d926e71233.png)


No exceptions seen. Ran it 3 times

**Comment by 304NotModified** [comment]
also tried `(0,1,300)` , no exceptions

**Comment by viseu** [comment]
Sorry, I meant a command prompt!  If you could please open a command prompt and run that command on the folder where the executable is would be great.

**Comment by 304NotModified** [comment]
Well isnt the same?

**Comment by viseu** [comment]
Your way would only pass the whole statement as parameters for the test program, but the test program would ignore parameters.
With a command prompt (cmd.exe) I would instruct the operating system to call the test program 30 times in sequence. 

I know it is a non methodic approach, but the issue is a bit hard to reproduce hence the brute force approach.

**Comment by 304NotModified** [comment]
OK I will test again soon!

**Comment by 304NotModified** [comment]
Running now

> I still get an exception. I ensured that no old logn was left in the debug/release folder by deleting all files before the rebuild.
> Tks
> 
> Access to the path 'C:\Users\fernando\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\bin\Debug\App.4.log' is denied.

What kind of exception is this?  UnauthorizedAccessException? IOException? Please post the full details including innerExceptions and data.

**Comment by 304NotModified** [comment]
I have ran it twice. One normal and one with trace logs. No exceptions have been thrown.

Could you test while writing to the internal log? 

please use this config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <common>
    <logging>
      <factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog41">
        <arg key="configDeferType" value="INLINE" />
      </factoryAdapter>
    </logging>
  </common>
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  internalLogFile="internallog.log" internalLogLevel="Trace"
  throwExceptions="true">
    <targets>
        <target name="BackgroundUploaderLog" xsi:type="File" maxArchiveFiles="5" archiveNumbering="Rolling" archiveAboveSize="20" concurrentWrites="true" filename="App.log" />
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="BackgroundUploaderLog" />
    </rules>
  </nlog>
</configuration>
```

**Comment by 304NotModified** [comment]
I think it's a race condition, but dunno how to fix yet. I depends on the full exception details

**Comment by 304NotModified** [comment]
@bhaeussermann any idea on this? See also #1617

**Comment by 304NotModified** [comment]
Keeping this openend, as it isn't fully fixed

**Comment by 304NotModified** [comment]
@bhaeussermann that's indeed a better idea :)

**Comment by 304NotModified** [comment]
@bhaeussermann any idea if this is the same issue? https://github.com/NLog/NLog/issues/1645

**Comment by bhaeussermann** [comment]
> @bhaeussermann any idea if this is the same issue? #1645

Not sure. The config uses `concurrentWrites="false"`

**Comment by viseu** [comment]
Thank you guys. Will double check on next release ;)
