### ISSUE TITLE
${processid} not recognized in .NET Core platform NLog 4.4.0-betaV15 - LayoutRenderer cannot be found

### ISSUE THREAD

**Issue by dejfcz** [NLog/NLog#1609]
Hi! 

**Type** (choose one):
- Bug

**NLog version**: (e.g. 4.4.0-betaV15)

**Platform**: .Net Core 1.0.0 (no problems on other platforms)

**Current NLog config** (xml or C#, if relevant)
Any config with target layout that contains ${processid}. If ${processid} omitted, it works. No problems with ${threadid}.

**Internal Nlog error message**

2016-09-01 15:44:47.6224 Warn Error when setting property 'Layout' on 'File Target[logfile]' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'processid'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)

In case of a BUG:
- What is the current result?
  Internal logger reports error and logging does not work.
- What is the expected result?
  ${processid} to work as with other .NET platforms.
- Are there any work arrounds? yes/no
  Avoid ${processid}

**Comment by 304NotModified** [comment]
Hi,

This is expected. Please check https://github.com/nlog/nlog/wiki/platform-support

If you know how to get the process Id in c#, we would be happy to implement it

**Comment by dejfcz** [comment]
Ah, I see I was just comparing https://github.com/nlog/nlog/wiki/ProcessId-Layout-Renderer to https://github.com/nlog/nlog/wiki/ThreadId-Layout-Renderer and it seemed to me that if ${threadid} worked, ${processid} should also ...

As for how to get process ID, is there any reason why you can't use System.Diagnostics.Process.GetCurrentProcess().Id?

**Comment by 304NotModified** [comment]
No there isn't :). 

Could you make a PR to the coreclr branch? (Of course create also from the coreclr branch)

I

**Comment by dejfcz** [comment]
Will try, give me couple of days pls.

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
No that's strange. I guess there aren't unit tests for it?

**Comment by dejfcz** [comment]
I'm sorry I really don't know. I see the code of NLog for the first time, ...

**Comment by 304NotModified** [comment]
OK, I'll check it these days   

Ps the tests file has the class name postfixed with tests. (Most of the time).

**Comment by 304NotModified** [comment]
In tests/NLog.unittests

**Comment by 304NotModified** [comment]
Checked it, both renderer and helper are disabled for .netcore (we use UWP10 for netcore, have to fix that)

**Comment by 304NotModified** [comment]
There are no unit tests for processid.

**Comment by dejfcz** [comment]
Ah, that was what I missed - I did not realized that UWP10 means netcore ...

Obviously I can see this condition ...

`#if !SILVERLIGHT && !__IOS__ && !UWP10`

**Comment by 304NotModified** [comment]
I think we need to create a new subclass of the abstract helper, and then we could implement the process layout renderer on netcore.  

Sorry for the missing details, on mobile now

**Comment by UgurAldanmaz** [comment]
If there is not any work on this, I want to take a look.

**Comment by 304NotModified** [comment]
That would be great!

**Comment by 304NotModified** [comment]
> I did not realized that UWP10 means netcore ...

PS: it does not, but the .NET Core code is created from the UWP branch. Its on the todo list

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.

**Comment by snakefoot** [comment]
Will be resolved with  #2039
