### ISSUE TITLE
LinkAssemblies task failed

### ISSUE THREAD

**Issue by Mikycrazy** [NLog/NLog#1612]
Hi! 

**Type** (choose one):

- Bug / Question

**NLog version**: 4.3.7

**Platform**: Xamarin Android 

**Current NLog config**:  without config

**Full error**:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'System.String System.String::Format(System.IFormatProvider,System.String,System.Object,System.Object,System.Object)' (defined in 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null') from 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.String System.String::Format(System.IFormatProvider,System.String,System.Object,System.Object,System.Object)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	App1	 

In case of a BUG:

- What is the current result?

      Build solution in Debug mode works fine, but if i tried to build in release always get: "The Link Assemblies task failed unexpectedly" viz error above. 

I Tried different kind of target-frameworks and always same error. In case its bug on my side I'am sorry for spam.

**Comment by 304NotModified** [comment]
Maybe there is something useful stuff over here: http://stackoverflow.com/questions/37177430/link-assemblies-task-failed-unexpectedly-issue-while-app-build-in-xamarin

**Comment by Mikycrazy** [comment]
Thanks, it worked!! I changed linking assemblies and now its works fine.
Again thanks for help.

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
Please share your experience with NLog on Xamarin, as I never used Xamarin much :) Thanks!
