### ISSUE TITLE
ConsoleTarget: I/O race condition exception when Console is "null"

### ISSUE THREAD

**Issue by chrisdrobison** [NLog/NLog#1631]
**Type** (choose one): Bug

**NLog version**: 4.3.5

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      internalLogFile="C:\Logs\nlog-svc-errors.log" 
      internalLogLevel="Error"
      throwExceptions="false"
      autoReload="true">

  <variable name="logPath" value="C:\Logs"/>
  <variable name="fileName" value="XactPrmSvc"/>

  <variable name="timeJson" value='"Time":"${longdate:jsonEncode=true}"'/>
  <variable name="levelJson" value='"Level":"${level}"'/>
  <variable name="machineJson" value='"Machine":"${machinename:jsonEncode=true}"'/>
  <variable name="loggerJson" value='"Logger":"${logger:jsonEncode=true}"'/>
  <variable name="callSiteJson" value='"CallSite":"${callsite:jsonEncode=true}"'/>
  <variable name="messageJson" value='"Message":"${message:jsonEncode=true}"'/>
  <variable name="generalInfoJson" value ='${var:timeJson},${newline}${var:levelJson},${newline}${var:machineJson},${newline}${var:loggerJson},${newline}${var:callSiteJson},${newline}${var:messageJson}'/>

  <variable name="exceptionType" value = '"ExceptionType"\:"${exception:format=type:jsonEncode=true}"'/>
  <variable name="exceptionMessage" value = '"ExceptionMessage"\:"${exception:format=message:jsonEncode=true}"'/>
  <variable name="exceptionMethod" value = '"ExceptionSourceMethod"\:"${exception:format=method:jsonEncode=true}"'/>
  <variable name="exceptionStackTrace" value = '"ExceptionStackTrace"\:"${exception:format=stacktrace:maxInnerExceptionLevel=15:innerFormat=type,message,method,stacktrace:jsonEncode=true}"'/>
  <variable name="excJsonBlock" value = '${var:exceptionType},${newline}${var:exceptionMessage},${newline}${var:exceptionMethod},${newline}${var:exceptionStackTrace}'/>

  <!-- 
  See http://nlog-project.org/wiki/Configuration_file 
  for information on customizing logging rules and outputs.
   -->
  <targets>
    <target xsi:Type="AsyncWrapper" name="log-file" queueLimit="5000" overflowAction="Discard">
      <target xsi:type="File" fileName="${var:logPath}\${var:fileName}.log" createDirs="true"
              autoFlush="true"
              layout="{${var:generalInfoJson}${onexception:,${newline}${var:excJsonBlock}}}${newline}"
              maxArchiveFiles="5"
              archiveNumbering="Date"
              archiveEvery="Day"
              archiveDateFormat="yyyy-MM-dd"
              archiveFileName="${var:logPath}\${var:fileName}.{#}.log"/>
    </target>

    <target xsi:type="Console"
            name="console"
            layout="${longdate} | ${level:uppercase=true} | ${message} ${exception:format=tostring:maxInnerExceptionLevel=10}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="log-file"></logger>
    <logger name="*" minlevel="Debug" writeTo="console">
      <filters>
        <when condition="level == LogLevel.Debug and starts-with('${message}', 'InactivityMonitor')" action="Ignore" />
        <when condition="level == LogLevel.Debug and starts-with('${message}', 'Got ping response for sessionid')" action="Ignore" />
        <when condition="level == LogLevel.Debug and starts-with('${message}', 'Shutdown of Consumer')" action="Ignore" />
        <when condition="level == LogLevel.Debug and starts-with('${message}', 'Remove of Consumer')" action="Ignore" />
        <when condition="level == LogLevel.Debug and ends-with('${message}', 'No Active TX closing normally.')" action="Ignore" />
        <when condition="starts-with('${message}', 'Closing The Session with Id')" action="Ignore" />
        <when condition="starts-with('${message}', 'Closed The Session with Id')" action="Ignore" />
        <when condition="starts-with('${message}', 'Executing Shutdown on Session with Id')" action="Ignore" />
      </filters>
    </logger>
  </rules>
</nlog>
```

In case of a BUG:

- What is the current result?

Every so often we are seeing the following error:

```Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.```

- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, and nothing

- Please post full exception details (message, stacktrace, inner exceptions)

Here are a couple of them:

```
Void InternalBlockCopy(System.Array, Int32, System.Array, Int32, Int32) 
    ExceptionStackTrace:     at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
```

```
Error during session close: System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
```

- Are there any work arrounds? yes/no

No

- Is there a version in which it did worked? 

We never saw this error in NLog 3.x

- Can you help us by writing an unit test?

Not sure how to reproduce consistently. But, I'd certainly love to help out anyway I can.

**Comment by 304NotModified** [comment]
Thanks for the info!

Do you know in which target the problem is? It's not fully clear to me. I never have seen this error before, it's a BCL error? Also an idea where/how to fix this?

**Comment by chrisdrobison** [comment]
Googling the I/O race condition brings up quite a few things, mostly people suggesting to not share StreamWriters or TextWriters amongst threads. My guess has been the file target because of this call: "NLog.Targets.Target.WriteAsyncLogEvent" in the stack trace since the file target is the only one wrapped in an async wrapper.

**Comment by 304NotModified** [comment]
yes the "async" name is here a bit misleading, we always do `WriteAsyncLogEvent` for each target. (as we only know at target level if it's async or not).

I pretty sure the issue is in the console target, as we don't use text of streamwriters directly AFAIK.

```
        private void Output(string textLine)
        {
            if (this.Error)
            {
                Console.Error.WriteLine(textLine);
            }
            else
            {
                Console.Out.WriteLine(textLine);
            }
        }

```

`Console.Error` and `Console.Out` are `TextWriters`

Can you confirm this is in the console target? Otherwise it would be difficult to fix this one if we dunno where the problem is.

**Comment by chrisdrobison** [comment]
Sure. I will mess with the targets this week to see what I can find.

**Comment by 304NotModified** [comment]
Thanks!

**Comment by chrisdrobison** [comment]
Looks like this confirms your theory a little bit:

http://stackoverflow.com/questions/33915790/console-out-and-console-error-race-condition-error-in-a-windows-service-written

**Comment by 304NotModified** [comment]
Thanks for the info. I think we could detect that's writing to StreamWriter.Null and then disabling logging?

You be sure, this won't break you application when thrown exceptions is false, right?

**Comment by chrisdrobison** [comment]
So, I already have thrownExceptions set to false and this is making it past that.

**Comment by 304NotModified** [comment]
yes, but are those written to the internal log only or is the exception thrown in to your own program (the latter should be impossible...)

**Comment by chrisdrobison** [comment]
It's being thrown in my program as that is where those stack traces came from above.

**Comment by 304NotModified** [comment]
that's bad!

**Comment by chrisdrobison** [comment]
I thought so as well :)

**Comment by 304NotModified** [comment]
```c#
        /// <summary>
        /// Writes the log to the target.
        /// </summary>
        /// <param name="logEvent">Log event to write.</param>
        public void WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
        {
            lock (this.SyncRoot)
            {
                if (!this.IsInitialized)
                {
                    logEvent.Continuation(null);
                    return;
                }

                if (this.initializeException != null)
                {
                    logEvent.Continuation(this.CreateInitException());
                    return;
                }

                var wrappedContinuation = AsyncHelpers.PreventMultipleCalls(logEvent.Continuation);

                try
                {
                    this.Write(logEvent.LogEvent.WithContinuation(wrappedContinuation));
                }
                catch (Exception exception)
                {
                    if (exception.MustBeRethrown())
                    {
                        throw;
                    }

                    wrappedContinuation(exception);
                }
            }
        }
```

Dunno why this would thrown the exception

**Comment by chrisdrobison** [comment]
I'll see if I can come up with a simple project to consistently reproduce this consistently based off the bug mentioned in the Stackoverflow article.

**Comment by 304NotModified** [comment]
What is the type of the outer most exception? `IndexOutOfRangeException`?

**Comment by chrisdrobison** [comment]
Yes

**Comment by 304NotModified** [comment]
yes will write an unit test. But I don't see the flawn. I exception should be catched and not rethrown.

**Comment by chrisdrobison** [comment]
Here is a link to the filed Microsoft bug:

https://connect.microsoft.com/VisualStudio/feedback/details/2057284/console-out-probable-i-o-race-condition-issue-in-multi-threaded-windows-service

**Comment by 304NotModified** [comment]
I can reproduce the exception while debugging, but the error isn't rethrown when `throwExceptions=false`.

Are you sure you have posted the correct config?

**Comment by 304NotModified** [comment]
full exeption:

```
System.IndexOutOfRangeException occurred
  HResult=-2146233080
  Message=Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
  Source=mscorlib
  StackTrace:
       at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
       at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
       at System.IO.TextWriter.WriteLine(String value)
       at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
       at NLog.Targets.ConsoleTarget.Output(String textLine) in X:\nlog\NLog\src\NLog\Targets\ConsoleTarget.cs:line 153
  InnerException: 

```

**Comment by 304NotModified** [comment]
BTW, The outer exception should be of type nlogruntimeexception.

**Comment by chrisdrobison** [comment]
I'm pretty sure I did, but I will double check.

**Comment by chrisdrobison** [comment]
I'm not seeing that ConsoleTarget line in my stack traces

**Comment by chrisdrobison** [comment]
I kind of trimmed it before, but here is an example complete stack trace:

```
at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.Diagnostics.TextWriterTraceListener.WriteLine(String message)
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at Telerik.Reporting.Processing.TraceTimer.WriteLine(String message)
   at Telerik.Reporting.Processing.Timer.Dispose()
   at Telerik.Reporting.Processing.ReportProcessor.ProcessReport(ReportSource reportSource, Hashtable deviceInfo, IRenderingContext context)
   at Telerik.Reporting.Processing.ReportProcessor.ProcessAndRender(String format, ReportSource reportSource, Hashtable deviceInfo, IRenderingContext renderingContext, CreateStream createStreamCallback)
   at Telerik.Reporting.Processing.ReportProcessor.ProcessAndRenderStateless(String format, ReportSource reportSource, Hashtable deviceInfo, IRenderingContext renderingContext, CreateStream createStreamCallback)
   at Telerik.Reporting.Processing.ReportProcessor.RenderReport(String format, ReportSource reportSource, Hashtable deviceInfo)
   at XactPrm.Services.ReportGenerator.GeneratePdf(ReportProcessor reportProcessor, ReportSource instanceReportSource) in D:\BuildAgent2\work\b2c0b1bf5309070d\Services\XactPrm.Services\ReportGenerator.cs:line 552
   at XactPrm.Services.ReportGenerator.RenderReport(BaseGenerateReport arg, ReportProcessor reportProcessor, InstanceReportSource instanceReportSource) in D:\BuildAgent2\work\b2c0b1bf5309070d\Services\XactPrm.Services\ReportGenerator.cs:line 417
   at XactPrm.Services.ReportGenerator.GenerateReport(GenerateReport arg) in D:\BuildAgent2\work\b2c0b1bf5309070d\Services\XactPrm.Services\ReportGenerator.cs:line 202 
```

Here is different one.

```
at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at XactPrm.Services.XactNet.XactNetInstanceState.<GetSmartObjectFileRecords>d__68.MoveNext() in D:\BuildAgent2\work\b2c0b1bf5309070d\Services\XactPrm.Services\XactNet\XactNetInstanceState.cs:line 350
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at XactPrm.Services.XactNet.XactNetInstanceState.PreLoadSmartObjectFileRecords() in D:\BuildAgent2\work\b2c0b1bf5309070d\Services\XactPrm.Services\XactNet\XactNetInstanceState.cs:line 298
   at XactPrm.Services.XactNet.XactNetUploadService.OnMessageReceived(UploadAssignment obj) in D:\BuildAgent2\work\b2c0b1bf5309070d\Services\XactPrm.Services\XactNet\XactNetUploadService.cs:line 61 
```

Looks like the same thing happens with the Debug target as well.

**Comment by chrisdrobison** [comment]
My operations team just sent me, the NLog.config. What I sent you was not correct. Apparently the configuration they have is with throw exceptions set to true.

**Comment by 304NotModified** [comment]
Thanks for the confirm!

**Comment by 304NotModified** [comment]
I could reproduce this in an unit test :)

Too bad I cannot recognize the `.Null` writers (would expect that as it should be a singleton)

```
 var output = GetOutput();
            var isNull = (output == TextWriter.Null || output == StreamWriter.Null);
```

**Comment by 304NotModified** [comment]
I think I will pause logging to the console when the error arises (IndexOutOfRangeException). Do you think that's OK?

**Comment by chrisdrobison** [comment]
I think that will be okay.

**Comment by 304NotModified** [comment]
OK will be 4.3.9! This week release!

**Comment by 304NotModified** [comment]
NLog 4.3.9 is live! https://www.nuget.org/packages/NLog/4.3.9
