### ISSUE TITLE
${callsite} in cross domain application sometime not working (Akka.net)

### ISSUE THREAD

**Issue by verysimplenick** [NLog/NLog#1671]
Hi.

**Type**: Bug

**NLog version**: (> 4.3.7)  [builded from commit cdb1fcf14f6e505317ab9cdd00322fe60ba4b4ca](https://github.com/NLog/NLog/commit/cdb1fcf14f6e505317ab9cdd00322fe60ba4b4ca)

**Platform**: .Net 4.6.1

**Current NLog config** 

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- go to http://nlog-project.org/wiki/Configuration_file for more information -->

    <variable name="ConsoleLayout" value="${date:format=HH\:mm\:ss.fff} ${pad:padding=5:inner=${level:uppercase=true}} ${message} ${onexception:EXCEPTION OCCURRED\:${exception:format=tostring}}" />
    <variable name="NormalLayout"  value="${longdate} ${level:uppercase=true} ${callsite} ${message} ${onexception:EXCEPTION OCCURRED\:${exception:format=tostring}}" />
    <variable name="VerboseLayout" value="${longdate} ${level:upperCase=true} ${callsite:includSourcePath=true} ${message} ${exception:format=tostring}" />
    <variable name="ExceptionVerboseLayout" value="${VerboseLayout} (${stacktrace:topFrames=10})  
                     ${exception:format=ToString}"                  />


    <targets async="true">

        <target xsi:type="File" name="appLog"
            layout="${VerboseLayout}"
            fileName="${basedir}/logs/current_log.txt"
            archiveFileName="${basedir}/archives/log.{#}.zip"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="7"
          enableArchiveFileCompression="true" />


        <target name="errorsLog"
        xsi:type="FilteringWrapper"
        condition="length('${exception}')>0">
            <target xsi:type="File" name="warnLog"
                layout="${ExceptionVerboseLayout}"
                fileName="${basedir}/logs/errors.txt"
                archiveFileName="${basedir}/archives/errors.{#}.zip"
                archiveEvery="Day"
                archiveNumbering="Rolling"
                maxArchiveFiles="15"
              enableArchiveFileCompression="true" />
        </target>



        <target xsi:type="ColoredConsole" name="console" layout="${ConsoleLayout}">
            <highlight-row condition="level == LogLevel.Warn" foregroundColor="Yellow" />
            <highlight-row condition="level == LogLevel.Error" foregroundColor="Red" />
            <highlight-row condition="level == LogLevel.Fatal" foregroundColor="White" backgroundColor="Red" />

            <highlight-word text="DEBUG" foregroundColor="DarkBlue" />
            <highlight-word text="INFO" foregroundColor="DarkGreen" />
            <highlight-word text="WARN" foregroundColor="Black" backgroundColor="Yellow" />

        </target>
    </targets>
    <rules>
        <logger name="*" minlevel="Trace" writeTo="appLog,console" />
        <logger name="*" minlevel="Warn" writeTo="errorsLog,warnLog" />
    </rules>
</nlog>
```

In case of a BUG:
- What is the current result?
  Incorrect ${callsite} in Log
- What is the expected result?
  ${callsite} in my class
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  Nope
- Please post full exception details (message, stacktrace, inner exceptions)

${callsite} in cross domain application sometime not working (using with Akka.net).
I use NLog in my Adapter class. Log object shared across 2 AppDomains. It's fine works, but if I use this object in Akka.net actor I get incorrect ${callsite}. Maybe Akka.net issue.

``` cs
public class NLogAdapter : MarshalByRefObject, ILog {
// cropped. ^^^ this object used by 2 AppDomains + used by Akka.net Logging
        public NLogAdapter()
        {
            LogManager.AddHiddenAssembly(Assembly.GetExecutingAssembly());
            LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(NLog.Logger)));

            _nlog = LogManager.GetCurrentClassLogger();
        }
}
```

What get in log (error log with stacktrace):

```
2016-10-04 11:00:11.2872 ERROR NLog.LoggerImpl.Write [akka://RuleProcessor/user/AggregateRuleGroupActor#388440039] Test!  (CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Error => Logger.Error => LoggerImpl.Write)
```
- Are there any work arrounds? yes/no
  no
- Is there a version in which it did worked? 
  I don't know
- Can you help us by writing an unit test?
  maybe if can reproduce without Akka.net

**Comment by 304NotModified** [comment]
Could you try when you adding something like this?

    LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(AkkaNet.SomeTypeThere)))

**Comment by verysimplenick** [comment]
Yep, same result:
```
2016-10-05 02:06:21.2262 WARN NLog.LoggerImpl.Write ActorSystem(RuleProcessor) NewtonSoftJsonSerializer has been detected as a default serializer. It will be obsoleted in Akka.NET starting from version 1.5 in the favor of Wire (for more info visit: http://getakka.net/docs/Serialization#how-to-setup-wire-as-default-serializer ). If you want to suppress this message set HOCON `akka.suppress-json-serializer-warning` config flag to on.  (CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Warn => Logger.Warn => LoggerImpl.Write)                        
2016-10-05 02:06:21.2722 ERROR Onyx.RuleProcessor.RuleProcessor.RunLoop Start wait  (ThreadPoolWorkQueue.Dispatch => Task.ExecuteEntry => Task.ExecuteWithThreadLocal => ExecutionContext.Run => ExecutionContext.RunInternal => Task.Execute => RuleProcessorController.<Start>b__21_0 => RuleProcessor.RunLoop)                        
2016-10-05 02:06:21.2892 ERROR NLog.LoggerImpl.Write [akka://RuleProcessor/user/aggregateRuleGroupPool/$a#1683342400]  Handle is: 2148  (CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Error => Logger.Error => LoggerImpl.Write)                        
```
Looks like it's issue with [Akka logging] (http://getakka.net/docs/Logging).
I use my logging actor in child AppDomain like this:
```cs
public class LoggingActor : ReceiveActor, ILogReceive, IRequiresMessageQueue<ILoggerMessageQueueSemantics>
    {

        public static ILog Log = null; // <<-- this NLogAdapter, this works correctly if I run Log.Info() for example
        
        private static void LogEvent(LogEvent logEvent)
        {
            if (Log != null)
            {
                if (logEvent is Error)
                {
                    var logObj = (Error) logEvent;
                    if (logObj.Cause != null)
                        Log.Error(logObj.Cause, string.Concat(logObj.LogSource, " ", logObj.Message));
                    else
                        Log.Error(string.Concat(logObj.LogSource, " ", logObj.Message));
                }
                else if (logEvent is Debug)
                {
                    var logObj = (Debug) logEvent;
                    Log.Debug(string.Concat(logObj.LogClass, " ", logObj.LogSource, " ", logObj.Message));
                }
                else if (logEvent is Info)
                {
                    Log.Info(string.Concat(logEvent.LogSource, " ", logEvent.Message));
                }
                else if (logEvent is Warning)
                {
                    Log.Warn(string.Concat(logEvent.LogSource, " ", logEvent.Message));
                }

            }
        }

        /// <summary>
        /// Initializes a new instance of the class.
        /// </summary>
        public OnyxLoggingActor()
        {
            Receive<Error>  (m  => LogEvent(m));
            Receive<Warning>(m  => LogEvent(m));
            Receive<Info>   (m  => LogEvent(m));
            Receive<Debug>  (m  => LogEvent(m));
            Receive<ILog>   (m  => Log = m ?? Log);

            Receive<InitializeLogger>(m => Sender.Tell(new LoggerInitialized()));
            
        }
    }
```
In actor:

```cs
private readonly ILoggingAdapter Log = Logging.GetLogger(Context);
```
If I use this in Actor or by ActorModel.Log it's print wrong ${callsite}
```cs
var actorSystem = ActorSystem.Create("someName", Akka.Configuration.ConfigurationFactory.ParseString(@"akka.loggers = [""MyNamespace.Actors.LoggingActor,MyAssembly""]"));
actorSystem.Log.Error("Test without actors, by ActorSystem.Log");
```

**Comment by 304NotModified** [comment]
Could you log `${stacktrace:topFrames=20}`? Then we could check is the expected frame is located (and where) in the stacktrace. 

Thanks in advance!

**Comment by verysimplenick** [comment]
Yep change to 30 frames:
wrong ${callsite} from `actorSystem.Log.Error("Test without actors, by ActorSystem.Log");`
```
2016-10-05 13:29:34.3091 ERROR NLog.LoggerImpl.Write ActorSystem(RuleProcessor) Test without actors, by ActorSystem.Log  (CrossAppDomainSink.DoTransitionDispatchCallback => CrossAppDomainSink.DoDispatch => ChannelServices.SyncDispatchMessage => CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Error => Logger.Error => LoggerImpl.Write)                        
```
and for example right error logging without akka adapter: `Log.Fatal("Now we done. Exit");` in same function

```
2016-10-05 13:29:34.6920 FATAL Onyx.RuleProcessor.RuleProcessor.RunLoop Now we done. Exit  (ThreadPoolWorkQueue.Dispatch => Task.ExecuteEntry => Task.ExecuteWithThreadLocal => ExecutionContext.Run => ExecutionContext.RunInternal => Task.Execute => RuleProcessorController.<Start>b__21_0 => RuleProcessor.RunLoop)
```

**Comment by 304NotModified** [comment]
Maybe it was a better idea to log `${stacktrace:topFrames:20:format:raw}` as the namespaces are now missing ;)



> actorSystem.Log.Error("Test without actors, by ActorSystem.Log"); // <-- this adapter use same object my ILog implentation as in next line


> Log.Error("Test without actors, by ActorSystem.Log");
What is Log here? A property? Of what type?

Your stacktrace, bit more readable:

```
2016-10-05 13:34:38.5249 ERROR Onyx.RuleProcessor.RuleProcessor.RunLoop Test without actors, by ActorSystem.Log  (ThreadPoolWorkQueue.Dispatch
 Task.ExecuteEntry
 Task.ExecuteWithThreadLocal
 ExecutionContext.Run
 ExecutionContext.RunInternal
 Task.Execute
 RuleProcessorController.<Start>b__21_0
 RuleProcessor.RunLoop) 
 
2016-10-05 13:34:38.5249 ERROR NLog.LoggerImpl.Write ActorSystem(RuleProcessor) Test without actors, by ActorSystem.Log  (CrossAppDomainSink.DoTransitionDispatchCallback
 CrossAppDomainSink.DoDispatch
 ChannelServices.SyncDispatchMessage
 CrossContextChannel.SyncProcessMessage
 Thread.InternalCrossContextCallback
 CrossContextChannel.SyncProcessMessageCallback
 ServerContextTerminatorSink.SyncProcessMessage
 ServerObjectTerminatorSink.SyncProcessMessage
 StackBuilderSink.SyncProcessMessage
 StackBuilderSink._PrivateProcessMessage
 NLogAdapter.Error
 Logger.Error
 LoggerImpl.Write)
```

**Comment by 304NotModified** [comment]
It seems that the frames are not in the tracetrace? (due to inlining), so therefor it falls back to the last.

**Comment by verysimplenick** [comment]
Same code, but edit to `${stacktrace:topFrames:20:format:raw}`
Get in log :
```
2016-10-06 21:10:00.0029 ERROR NLog.LoggerImpl.Write ActorSystem(RuleProcessor) Test without actors, by ActorSystem.Log  (
NLogAdapter.Error 
Logger.Error 
LoggerImpl.Write) 
2016-10-06 21:10:00.0029 ERROR Onyx.RuleProcessor.RuleProcessor.RunLoop Test without actors, by ActorSystem.Log  (
Task.Execute
RuleProcessorController.<Start>b__22_0
RuleProcessor.RunLoop) 
```
Yep, `Log` is my interface ILog implementation (not same as NLog), code of NLogAdapter easy, something like this:
```cs
 public class NLogAdapter : MarshalByRefObject, ILog
 protected Logger _nlog;

        public NLogAdapter()
        {
            LogManager.AddHiddenAssembly(Assembly.GetExecutingAssembly());
            LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(NLog.Logger)));
            LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(Akka.Actor.ActorBase))); // this line isn't here (in Main()), but for simplify I put it here)
            _nlog = LogManager.GetCurrentClassLogger();
...
}
... 
        public void Error(string text)
        {
            if (ReportingLevel.HasFlag(LogLevel.Error))
                _nlog.Error(text);
        }
...
```
LogAdapter for Akka use same object -> NLogAdapter (as u can see in stacktrace).

**Comment by 304NotModified** [comment]
But what strackframe you think should be the one for `${callsite}`? `NLogAdapter.Error ` ?

**Comment by verysimplenick** [comment]
I should see same `${callsite}`, I has `OnyxLoggingActor` in different library, has NLogAdapter in another, try run this in two AppDomains
```cs
NLog.LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(Logging.Akka.OnyxLoggingActor)));
NLog.LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(Akka.Actor.ActorBase)));
NLog.LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(NLogAdapter)));
```
If I use original NLogAdapter object has right `${callsite}` : `Task.Execute => RuleProcessorController.Start>b__22_0 => RuleProcessor.RunLoop` in same place( in `RunLoop` function in next line) use class from Hidden assembly (`Logging.Akka.OnyxLoggingActor`) and get different `${callsite}`, but I use `AddHiddenAssembly` on my `OnyxLoggingActor`.

**Comment by verysimplenick** [comment]
I try reproduce without Akka, but for now without success.
If I create solution with same behaviour with Akka it's helps you?

**Comment by 304NotModified** [comment]
> If I create solution with same behaviour with Akka it's helps you?

Yes, that would be great.

But I have to admit I'm a bit lost. So from my viewpoint: the `${stacktrace}` and `$callsite}` are really related, 

a) if the stracktrace contains the correct line (strackframe), then that should be the callsite (nb: we searching it with custom code in NLog).
b) if the stacktrace doesn't have the strackframe, then the callsite will never be correct. We cannot fix it. This is mostly caused by inlining.

I'm not sure if we at a) or b). If a), which are the correct lines in the stacktrace (and which one is now found?)

**Comment by verysimplenick** [comment]
@304NotModified I create solution for you, I think my english is so bad, maybe I can't clearly explain problem :)
See code is best for us :)
(Solution) [https://drive.google.com/file/d/0B3VPbtBFBjYgbURXN3lBQlJxZk0/view?usp=sharing]

**Comment by verysimplenick** [comment]
@304NotModified 
Any progress? see issue with callsite now?

**Comment by 304NotModified** [comment]
Not yet. Debugging another program takes some time. Therefor we prefer a more scoped issue (what's is wrong with which input)

**Comment by verysimplenick** [comment]
Ok, thanks, wait your review 👍

**Comment by verysimplenick** [comment]
Any help needed for reproduce bug?

**Comment by 304NotModified** [comment]
Yes, an unit test would be the best.

**Comment by 304NotModified** [comment]
Hi!

I debugged your program. Changed some stuff to make it more clear:

program.cs

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Akka.Actor;
using NLog;
using NLogAdapter;
using NLogAdapterWrapper;


namespace NLogCallSiteTest
{

    public sealed class Isolated<T> : IDisposable where T : MarshalByRefObject
    {
        /// <summary>
        /// Созданный AppDomain
        /// </summary>
        public AppDomain Domain { get; private set; }

        /// <summary>
        /// Создает изолированный объект типа T, внутри нового AppDomain
        /// </summary>
        public Isolated()
        {
            Domain = AppDomain.CreateDomain(string.Concat("IsolatedDomain_", Guid.NewGuid()), null, AppDomain.CurrentDomain.SetupInformation);
            Value = (T)Domain.CreateInstanceAndUnwrap(typeof(T).Assembly.FullName, typeof(T).FullName);
        }
        /// <summary>
        /// Объект runner используемый для загрузки домена
        /// </summary>
        public T Value { get; }

        /// <summary>
        /// Указывает был ли освобожден объект или нет.
        /// </summary>
        public bool IsDisposed;
        /// <summary>
        /// Выгружает домен
        /// </summary>
        public void Dispose()
        {
            if (IsDisposed || Domain == null)
                return;
            IsDisposed = true;
            AppDomain.Unload(Domain);
            Domain = null;
        }
    }

    public class ChildAppDomainRunner : MarshalByRefObject
    {
        public void RunTest(ILog adapter)
        {
            
            NLogAdapterWrapper.NLogAdapterWrapper wrapper = new NLogAdapterWrapper.NLogAdapterWrapper(adapter);
            
            adapter.Error("test2 (RunTest)");
            wrapper.Error("test2 (RunTest)");

            ActorSystem sys = ActorSystem.Create("test", @"akka.loggers = [""NLogAdapterWrapper.LoggingActor,NLogAdapterWrapper""]");
            LoggingActor.Log = adapter;
            sys.Log.Error("test3 (RunTest)");

        }
    }

    class Program
    {
        static void Main(string[] args)
        {


            NLog.LogManager.AddHiddenAssembly(Assembly.GetAssembly(typeof(Akka.Actor.ActorBase)));


            NLogAdapter.NLogAdapter adapter = new NLogAdapter.NLogAdapter();
            NLogAdapterWrapper.NLogAdapterWrapper wrapper = new NLogAdapterWrapper.NLogAdapterWrapper(adapter);
            adapter.Error("test1 (MAIN)");
            wrapper.Error("test1 (MAIN)");
            using (var childAppDomain = new Isolated<ChildAppDomainRunner>())
            {
                childAppDomain.Value.RunTest(adapter);

            }

            LogManager.Flush();


        }
    }
}

```

nlog.config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true">

    <!-- go to http://nlog-project.org/wiki/Configuration_file for more information -->

    <variable name="ConsoleLayout" value="${date:format=HH\:mm\:ss.fff} ${pad:padding=5:inner=${level:uppercase=true}} ${message} ${onexception:EXCEPTION OCCURRED\:${exception:format=tostring}}" />
    <variable name="NormalLayout"  value="${longdate} ${level:uppercase=true} ${callsite} ${message} ${onexception:EXCEPTION OCCURRED\:${exception:format=tostring}}" />
    <variable name="VerboseLayout" value="${longdate} ${level:upperCase=true} ${callsite:includSourcePath=true} ${message} ${exception:format=tostring}" />
    <variable name="ExceptionVerboseLayout" value="${longdate} ${level:upperCase=true} ${message} | ${callsite}  | (${stacktrace:topFrames=20:format=Flat}) ${exception:format=ToString}" />
    <!--<variable name="ExceptionVerboseLayout" value="${VerboseLayout} (${stacktrace:topFrames=30}) ${exception:format=ToString}" />-->


    <targets async="true">

        <target xsi:type="File" name="appLog"
            layout="${ExceptionVerboseLayout}"
            fileName="${basedir}/logs/nlog_test.txt"
        
     />


        <!--<target name="errorsLog"
        xsi:type="FilteringWrapper"
        condition="length('${exception}')>0">
            <target xsi:type="File" name="warnLog"
                layout="${ExceptionVerboseLayout}"
                fileName="${basedir}/logs/errors.txt"
                archiveFileName="${basedir}/archives/errors.{#}.zip"
                archiveEvery="Day"
                archiveNumbering="Rolling"
                maxArchiveFiles="15"
              enableArchiveFileCompression="true" />
        </target>-->
        
        

    </targets>
    <rules>
        <logger name="*" minlevel="Trace" writeTo="appLog" />
       
    </rules>
</nlog>




```

----


I have now the following output:

```

2016-11-20 14:43:51.7313 ERROR test1 (MAIN) | NLogCallSiteTest.Program.Main  | (ThreadHelper.ThreadStart => ExecutionContext.Run => ExecutionContext.Run => ExecutionContext.RunInternal => ThreadHelper.ThreadStart_Context => HostProc.RunUsersAssembly => AppDomain.ExecuteAssembly => AppDomain._nExecuteAssembly => Program.Main) 
2016-11-20 14:43:51.7313 ERROR test1 (MAIN) | NLogCallSiteTest.Program.Main  | (ThreadHelper.ThreadStart => ExecutionContext.Run => ExecutionContext.Run => ExecutionContext.RunInternal => ThreadHelper.ThreadStart_Context => HostProc.RunUsersAssembly => AppDomain.ExecuteAssembly => AppDomain._nExecuteAssembly => Program.Main) 
2016-11-20 14:43:51.8343 ERROR test2 (RunTest) | NLogCallSiteTest.ChildAppDomainRunner.RunTest  | (ThreadHelper.ThreadStart => ExecutionContext.Run => ExecutionContext.Run => ExecutionContext.RunInternal => ThreadHelper.ThreadStart_Context => HostProc.RunUsersAssembly => AppDomain.ExecuteAssembly => AppDomain._nExecuteAssembly => Program.Main => ChildAppDomainRunner.RunTest) 
2016-11-20 14:43:51.8343 ERROR test2 (RunTest) | NLogCallSiteTest.ChildAppDomainRunner.RunTest  | (ThreadHelper.ThreadStart => ExecutionContext.Run => ExecutionContext.Run => ExecutionContext.RunInternal => ThreadHelper.ThreadStart_Context => HostProc.RunUsersAssembly => AppDomain.ExecuteAssembly => AppDomain._nExecuteAssembly => Program.Main => ChildAppDomainRunner.RunTest) 
2016-11-20 14:43:52.4403 ERROR NewtonSoftJsonSerializer has been detected as a default serializer. It will be obsoleted in Akka.NET starting from version 1.5 in the favor of Wire (for more info visit: http://getakka.net/docs/Serialization#how-to-setup-wire-as-default-serializer ). If you want to suppress this message set HOCON `akka.suppress-json-serializer-warning` config flag to on. | NLog.LoggerImpl.Write  | (Thread.CompleteCrossContextCallback => CrossAppDomainSink.DoTransitionDispatchCallback => CrossAppDomainSink.DoDispatch => ChannelServices.SyncDispatchMessage => CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => Thread.CompleteCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => LeaseSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Error => Logger.Error => Logger.WriteToTargets => LoggerImpl.Write) 
2016-11-20 14:43:52.4403 ERROR test3 (RunTest) | NLog.LoggerImpl.Write  | (Thread.CompleteCrossContextCallback => CrossAppDomainSink.DoTransitionDispatchCallback => CrossAppDomainSink.DoDispatch => ChannelServices.SyncDispatchMessage => CrossContextChannel.SyncProcessMessage => Thread.InternalCrossContextCallback => Thread.CompleteCrossContextCallback => CrossContextChannel.SyncProcessMessageCallback => ServerContextTerminatorSink.SyncProcessMessage => LeaseSink.SyncProcessMessage => ServerObjectTerminatorSink.SyncProcessMessage => StackBuilderSink.SyncProcessMessage => StackBuilderSink._PrivateProcessMessage => NLogAdapter.Error => Logger.Error => Logger.WriteToTargets => LoggerImpl.Write) 

````

I guess the problem is in the last line, "test3"

**Comment by 304NotModified** [comment]
If we check the stacktrace, then it's clear why NLog can't find the callsite - it's not in the stacktrace!

![image](https://cloud.githubusercontent.com/assets/5808377/20463385/95723342-af31-11e6-813b-bd92c65a4c29.png)



```
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at NLogAdapter.NLogAdapter.Error(String text) in C:\Users\j.verdurmen\Desktop\NLogCallSiteTest\NLogAdapter\NLogAdapter.cs:line 29
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Lifetime.LeaseSink.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(Object[] args)
   at System.Threading.Thread.CompleteCrossContextCallback(InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)
   at System.Threading.Thread.CompleteCrossContextCallback(InternalCrossContextDelegate ftnToCall, Object[] args)
```

**Comment by verysimplenick** [comment]
Ok, thanks for your work.
Result: in MS Remoting + Akka.net has some code that break stacktrace?

**Comment by 304NotModified** [comment]
Yes,

I tried you find a fix, but I failed.

There is an option to set the stacktrace to NLog ([`LogEventInfo.SetStackTrace`](http://nlog-project.org/documentation/v4.3.0/html/M_NLog_LogEventInfo_SetStackTrace.htm))

But could not find the stacktrace captured by Akka.net
