### ISSUE TITLE
Handle single quotes inside the when condition

### ISSUE THREAD

**Issue by janrhansen** [NLog/NLog#1677]
**Type** (choose one):Bug
**NLog version**: 4.3.9
**Platform**: .Net 4.5 

```xml
<logger name="*" minlevel="Warn" writeTo="f-warnings-test">
  <filters>
      <!-- look for exceptions with the error message containing
      Cannot insert the value NULL into column 'Testcolumn'
      -->
    <when condition="contains('${exception}', 'Cannot insert the value NULL into column 'Tes')" action="LogFinal"></when>
    <!-- all others are ignored-->
    <when condition="equals('1', '1')" action="Ignore"></when>
  </filters>
</logger>
```

- What is the current result?
Unable to filter on texts where the condition contains one or more single quotes

- What is the expected result?
It should be possible

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes

- Please post full exception details (message, stacktrace, inner exceptions)

```
2016-10-05 15:00:40.1519 Error Error in Parsing Configuration File. Exception: NLog.NLogConfigurationException: Exception occurred when loading configuration from D:\projects\temp\ConsoleApplication1\bin\Debug\NLog.config ---> NLog.NLogConfigurationException: Error when setting property 'Condition' on NLog.Filters.ConditionBasedFilter ---> NLog.Conditions.ConditionParseException: Expected token of type: RightParen, got Keyword (Tes).
   at NLog.Conditions.ConditionTokenizer.Expect(ConditionTokenType tokenType)
   at NLog.Conditions.ConditionParser.ParsePredicate(String functionName)
   at NLog.Conditions.ConditionParser.ParseLiteralExpression()
   at NLog.Conditions.ConditionParser.ParseBooleanRelation()
   at NLog.Conditions.ConditionParser.ParseBooleanPredicate()
   at NLog.Conditions.ConditionParser.ParseBooleanAnd()
   at NLog.Conditions.ConditionParser.ParseBooleanOr()
   at NLog.Conditions.ConditionParser.ParseExpression(String expressionText, ConfigurationItemFactory configurationItemFactories)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseFilters(LoggingRule rule, NLogXmlElement filtersElement)
   at NLog.Config.XmlLoggingConfiguration.ParseLoggerElement(NLogXmlElement loggerElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseRulesElement(NLogXmlElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```

- Are there any work arrounds? yes/no
No. Tried using `&amp;apos;` as a way to escape the quote, but no luck

- Is there a version in which it did worked? Dont know

- Can you help us by writing an unit test?
I'd like to, but Im not familiar with github, so it would probably take too long

**Comment by 304NotModified** [comment]
you need to escape the `'` as the quotes are now unbalanced.

    condition="contains('${exception}', 'Cannot insert the value NULL into column 'Tes')"

should be

    condition="contains('${exception}', 'Cannot insert the value NULL into column \'Tes')"

**Comment by 304NotModified** [comment]
tested, 

it should be escaped with `'`, so:

`contains('${message}', 'Cannot insert the value NULL into column ''Tes')`

**Comment by 304NotModified** [comment]
I have updated the wiki: https://github.com/NLog/NLog/wiki/Conditions

**Comment by 304NotModified** [comment]
See also test cases; https://github.com/NLog/NLog/pull/1679

**Comment by janrhansen** [comment]
Thanks a lot for your quick reply. I actually thought I had tried that way of escaping, but apparently not so.. Anyway, it works now :) Thanks!

**Comment by 304NotModified** [comment]
Well it wasn't also well documented, so I needed also some tries. 

But that's now done :)
