### ISSUE TITLE
DB Target does not work after config file reload

### ISSUE THREAD

**Issue by daniefer** [NLog/NLog#1705]
**Type**: Bug

**NLog version**: 4.3.9

**Platform**:  .Net 4.5

**Current NLog config**
The configuration is a combinations of code and XML

``` csharp
           // The below is run in the LogManager_ConfigurationReloaded event handler and its intent is to 
           // set the connection sting info using internal tools
           var dbConfig = configuration.FindTargetByName<DatabaseTarget>("TpsDatabaseTarget");
            if (dbConfig == null)
            {
                // Unable to configure db logging, missing a configuration file entry
                return;
            }

            try
            {
                dbConfig.ConnectionString = SpecialFunctionThatGetsConnectionString();
            }
            catch (Exception e)
            {
                // Unable to get connection string, so writing to a database will not be an option.
                dbConfig.ConnectionString = string.Empty;
            }

           LogManager.ReconfigExistingLoggers();

            return;
```

``` xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Warn" internalLogFile="c:\temp\nlog-internal.log">

    <!-- Set in the NLogTpsConfigure class. Do not set these variables -->
    <variable name="mhsKey" value=""/>

    <!-- Static variables. These should not change unless we need to update all logging. -->
    <variable name="TpsDetailedExceptionLayout" value="${exception:innerFormat=Message,Type,ToString,StackTrace:maxInnerExceptionLevel=3:innerExceptionSeparator=\r\nInnerExceptions:\r\n:separator=\r\n:format=ToString}"/>
    <variable name="localAppDataDirectoryLogLocation" value="${specialfolder:folder=LocalApplicationData}/TPS/Logs${when:inner=.${var:mhsKey}:when='${var:mhsKey}' != ''}"/>

    <targets>

      <target xsi:type="Database"
              name="TpsDatabaseTarget"
              commandText="[dbo].[InsertLog]"
              keepConnection="true" 
              commandType="StoredProcedure">
        <parameter name="@dateTime" layout="${longdate}"/>
        <parameter name="@message" layout="${message}"/>
        <parameter name="@mhsKey" layout="${when:when='${asp-session:variable=mhsKey}' != '':inner=${asp-session:variable=mhsKey}}${when:when='${asp-session:variable=mhsKey}' == '':inner=${var:mhsKey}}"/>
        <parameter name="@level" layout="${level:uppercase=true}"/>
        <parameter name="@logger" layout="${logger}"/>
        <parameter name="@machineName" layout="${machinename}"/>
        <parameter name="@processId" layout="${processid}"/>
        <parameter name="@windowsIdentity" layout="${windows-identity}"/>
        <parameter name="@identity" layout="${identity}"/>
        <parameter name="@appDomain" layout="${appdomain:format={1\}}"/>
        <parameter name="@assemblyVersion" layout="${assembly-version}"/>
        <parameter name="@callSite" layout="${callsite:fileName=true}"/>
        <parameter name="@detailedException" layout="${var:TpsDetailedExceptionLayout}"/>
        <parameter name="@stackTrace" layout="${stacktrace:format=DetailedFlat}"/>
        <parameter name="@threadId" layout="${threadid}"/>
        <parameter name="@threadName" layout="${threadname}"/>
        <parameter name="@logicalContextKey" layout="${event-properties:item=ContextKey}"/>
      </target>

      <target xsi:type="File"
              name="TpsFileTarget"
              encoding="utf-8"
              lineEnding="CRLF"
              archiveEvery="None"
              replaceFileContentsOnEachWrite="false"
              fileAttributes="Normal"
              fileName="${var:localAppDataDirectoryLogLocation}/${processname:fullName=false}.detailed.log"
              archiveFileName="$${var:localAppDataDirectoryLogLocation}/Archives/log.{#####}.detailed.txt"
              archiveAboveSize="1000240"
              archiveNumbering="Rolling"
              maxArchiveFiles="7"
              forceManaged="false"
              cleanupFileName="true"
              archiveOldFileOnStartup="false"
              maxLogFilenames="3">
        <layout xsi:type="JsonLayout">
          <attribute name="DateTime" layout="${longdate}"/>
          <attribute name="Message" layout="${message}"/>
          <attribute name="MhsKey" layout="${when:when='${asp-session:variable=mhsKey}' != '':inner=${asp-session:variable=mhsKey}}${when:when='${asp-session:variable=mhsKey}' == '':inner=${var:mhsKey}}"/>
          <attribute name="Level" layout="${level:uppercase=true}"/>
          <attribute name="Logger" layout="${logger}"/>
          <attribute name="MachineName" layout="${machinename}"/>
          <attribute name="ProcessId" layout="${processid}"/>
          <attribute name="WindowsIdentity" layout="${windows-identity}"/>
          <attribute name="Identity" layout="${identity}"/>
          <attribute name="AppDomain" layout="${appdomain:format={1\}}"/>
          <attribute name="AssemblyVersion" layout="${assembly-version}"/>
          <attribute name="CallSite" layout="${callsite:fileName=true}"/>
          <attribute name="DetailedException" layout="${var:TpsDetailedExceptionLayout}"/>
          <attribute name="StackTrace" layout="${stacktrace:format=DetailedFlat}"/>
          <attribute name="ThreadId" layout="${threadid}"/>
          <attribute name="ThreadName" layout="${threadname}"/>
          <attribute name="LogicalContextKey" layout="${event-properties:item=ContextKey}"/>
        </layout>
      </target>

      <target xsi:type="RetryingWrapper" name="TpsDatabaseRetryWrapper" retryCount="5" retryDelayMilliseconds="100">
        <target-ref name="TpsDatabaseTarget"/>
      </target>

      <target xsi:type="AsyncWrapper" name="TpsDBAsyncWrapper" batchSize="1" overflowAction="Grow" queueLimit="10000" timeToSleepBetweenBatches="500">
        <target-ref name="TpsDatabaseRetryWrapper"/>
      </target>

      <target xsi:type="AsyncWrapper" name="TpsFileAsyncWrapper" batchSize="20" overflowAction="Grow" queueLimit="10000" timeToSleepBetweenBatches="500">
        <target-ref name="TpsFileTarget"/>
      </target>


    </targets>

    <rules>
      <logger name="*" minlevel="Debug" enabled="true" writeTo="TpsDBAsyncWrapper"/>
      <logger name="*" minlevel="Debug" enabled="true" writeTo="TpsFileAsyncWrapper"/>
    </rules>
</nlog>

```

In case of a BUG:
- What is the current result?

The DB configuration works the first time but when the reload is fired by the file updating, the DB target throws the below exception and nothing is sent to the DB log. I am logging the connection string right after the call to `LogManager.ReconfigExistingLoggers()` and it is getting written to the file target but not the database target. The connection string is the same before and after the reload.
The nlog-internal.log Exception details:

```
 2016-10-12 12:14:31.8001 Error Error when writing to database. Exception: 

System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.InsertLog'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
ClientConnectionId:db2ae9ab-ff79-4cd2-9f93-6bec2f729962
Error Number:2812,State:62,Class:16
2016-10-12 12:14:31.8166 Warn Error while writing to 'Database Target[TpsDatabaseTarget]': System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.InsertLog'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
ClientConnectionId:db2ae9ab-ff79-4cd2-9f93-6bec2f729962
```
- What is the expected result?
  No error in the nlog-internal.log file and the database target works like it does when the app initially loads
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  Yes. 
- Please post full exception details (message, stacktrace, inner exceptions)
  See the quote above
- Are there any work arrounds? 
  Not that I know of, other than turning off auto reload
- Is there a version in which it did worked? 
  Don't know
- Can you help us by writing an unit test?
  Yes, just let me know when.

**Comment by daniefer** [comment]
I also just noticed that sometimes I get one of the exceptions mentioned above on the initial load, but after the first failed attempt the second one works. If I can narrow it down some more I will post an update.

**Comment by 304NotModified** [comment]
> The configuration is a combinations of code and XML

Are you updating the config after the config reload? E.g. with the `LogManager.ConfigurationReloaded` event?

**Comment by daniefer** [comment]
@304NotModified - Yes, I am using the `LogManager.ConfigurationReloaded` event to trigger the C# config changes.

**Comment by 304NotModified** [comment]
I mean, is this code called 

```
  // The below is run in the LogManager_ConfigurationReloaded event handler and its intent is to 
           // set the connection sting info using internal tools
           var dbConfig = configuration.FindTargetByName<DatabaseTarget>("TpsDatabaseTarget");
            if (dbConfig == null)
            {
                // Unable to configure db logging, missing a configuration file entry
                return;
            }

            try
            {
                dbConfig.ConnectionString = SpecialFunctionThatGetsConnectionString();
            }
            catch (Exception e)
            {
                // Unable to get connection string, so writing to a database will not be an option.
                dbConfig.ConnectionString = string.Empty;
            }

           LogManager.ReconfigExistingLoggers();

            return;

```

on `LogManager.ConfigurationReloaded`? 

e.g. `LogManager.ConfigurationReloaded += updateConfig`

**Comment by daniefer** [comment]
Yes. Exactly like that.

**Comment by 304NotModified** [comment]
> 2016-10-12 12:14:31.8001 Error Error when writing to database. Exception:

Does this happen between the reloads? Please post the full internal log (trace level)

**Comment by daniefer** [comment]
I had to rename the file to upload it (.log -> .txt), but here you go.
[nlog-internal.txt](https://github.com/NLog/NLog/files/525454/nlog-internal.txt)

**Comment by 304NotModified** [comment]
Do you know if the exceptions are still there when the config is finished reloading?

**Comment by daniefer** [comment]
@304NotModified - Here is the trace output. 
[nlog-internal.trace.txt](https://github.com/NLog/NLog/files/525599/nlog-internal.trace.txt)

I am not sure what you are talking about when you say:
>...when the config has finished reloading?

Are you asking "Do those exceptions still occur when I attempt to log to the database target after the `LogManager.ConfigurationReloaded` handler has finished executing?"

If so, yes.

**Comment by daniefer** [comment]
@304NotModified - I have traced it though a debug sessions of NLog I am able to locate the exception. It was happening because of an ill formatted connection string. I'm still tracing down the exact issue but it looks like my ConfigurationReloaded event is not firing for some reason (the EventHandler is null). I'll post some more when I figure out what is going on, but I just wanted to give you an update.

**Comment by 304NotModified** [comment]
:+1:

**Comment by daniefer** [comment]
@304NotModified 
It looks like I misspoke earlier when I said the C# code was executing on the `LogManager.ConfigurationReloaded` event. It is actually executing on the `LogManager.ConfigurationChanged` event (my function was named wrong and I guess I was blinded by staring at it for too long).

What is the difference between the `ConfigurationReloaded` and `ConfigurationChanged` event handlers? I was manipulating the config returned from the `LoggingConfigurationChangedEventArgs.NewConfiguration` variable but it seems like that is what was causing the issue. I switched to the `LogManager.ConfigurationReloaded` event and read the config from `LogManager.Configuration` and now the database target is working after reloads. However, since there is no config object attached to the `LoggingConfigurationReloadedEventArgs` parameter, how do I know I am getting the new config or the old one. Is that the correct way to modify the config after a file change is detected? Or to say another way, should I be reading the config from `LogManager.Configuration` when I need to make changes after a config file reload?

**Comment by 304NotModified** [comment]
> What is the difference between the ConfigurationReloaded and ConfigurationChanged event handlers?

Reload when it's read the config and change if it was changed. So always reload and most of the time changed. 

I will close this as this has been fixed, but we could improve the docs on this.
