### ISSUE TITLE
Append to archive sometimes fails

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1707]
probably and result of  #1680 since NLog 4.3.10

https://ci.appveyor.com/project/nlog/nlog/build/4.0.3358

> Strange that this build error has started to come "randomly": 

(see https://github.com/NLog/NLog/pull/1706#issuecomment-253301042)

> ...NLog.UnitTests.Targets.WrappedFileTargetTests.DeleteArchiveFilesByDateWithDateName [FAIL]
>    System.IO.IOException : The process cannot access the file 'C:\Users\appveyor\AppData\Local\Temp\1\38d53f98-4243-431f-921b-13c219a6989c\20161012182959914.txt' because it is being used by another process.
>    Stack Trace:
>       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>       at System.IO.File.Open(String path, FileMode mode)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1307,0): at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1579,0): at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1764,0): at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1848,0): at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1043,0): at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1136,0): at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
>       C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1031,0): at NLog.Targets.FileTarget.Write(AsyncLogEventInfo[] logEvents)
>       C:\projects\nlog\src\NLog\Targets\Target.cs(287,0): at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEvents)
>       C:\projects\nlog\tests\NLog.UnitTests\Targets\Mocks\MockTargetWrapper.cs(67,0): at NLog.UnitTests.Targets.Mocks.MockTargetWrapper.Write(AsyncLogEventInfo logEvent)
>       C:\projects\nlog\src\NLog\Targets\Target.cs(231,0): at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
>       C:\projects\nlog\src\NLog\LoggerImpl.cs(252,0): at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
>       C:\projects\nlog\src\NLog\LoggerImpl.cs(99,0): at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
>       C:\projects\nlog\src\NLog\Logger.cs(559,0): at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message)
>       C:\projects\nlog\src\NLog\Logger1.cs(454,0): at NLog.Logger.Debug(String message)
>       C:\projects\nlog\tests\NLog.UnitTests\Targets\FileTargetTests.cs(890,0): at NLog.UnitTests.Targets.FileTargetTests.DeleteArchiveFilesByDateWithDateName()

**Comment by 304NotModified** [comment]
Fixed by #1886
