### ISSUE TITLE
Unable to install package on UWP

### ISSUE THREAD

**Issue by chamamo** [NLog/NLog#1879]
Hi!

**Type**: Bug
**NLog version**: 5.0.0-beta04 (Also for previous versions)
**Platform**: .UWP (Win10)

I can't install the package on my project, I have this errors: Package restore failed. Rolling back package changes for 'App2'.

**Error detail**:

```
System.Threading.AccessControl 4.0.0 provides a compile-time reference assembly for System.Threading.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
System.Security.AccessControl 4.0.0 provides a compile-time reference assembly for System.Security.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
System.Threading.ThreadPool 4.0.10 provides a compile-time reference assembly for System.Threading.ThreadPool on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
System.IO.FileSystem.AccessControl 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
System.Threading.AccessControl 4.0.0 provides a compile-time reference assembly for System.Threading.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.Security.AccessControl 4.0.0 provides a compile-time reference assembly for System.Security.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.Threading.ThreadPool 4.0.10 provides a compile-time reference assembly for System.Threading.ThreadPool on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.IO.FileSystem.AccessControl 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Threading.AccessControl 4.0.0 provides a compile-time reference assembly for System.Threading.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
System.Security.AccessControl 4.0.0 provides a compile-time reference assembly for System.Security.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
System.Threading.ThreadPool 4.0.10 provides a compile-time reference assembly for System.Threading.ThreadPool on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
System.IO.FileSystem.AccessControl 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
System.Threading.AccessControl 4.0.0 provides a compile-time reference assembly for System.Threading.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.Security.AccessControl 4.0.0 provides a compile-time reference assembly for System.Security.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.Threading.ThreadPool 4.0.10 provides a compile-time reference assembly for System.Threading.ThreadPool on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.IO.FileSystem.AccessControl 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Threading.AccessControl 4.0.0 provides a compile-time reference assembly for System.Threading.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
System.Security.AccessControl 4.0.0 provides a compile-time reference assembly for System.Security.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
System.Threading.ThreadPool 4.0.10 provides a compile-time reference assembly for System.Threading.ThreadPool on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
System.IO.FileSystem.AccessControl 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
System.Threading.AccessControl 4.0.0 provides a compile-time reference assembly for System.Threading.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.Security.AccessControl 4.0.0 provides a compile-time reference assembly for System.Security.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.Threading.ThreadPool 4.0.10 provides a compile-time reference assembly for System.Threading.ThreadPool on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.IO.FileSystem.AccessControl 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.AccessControl on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
```

Thank you in advance.

**Comment by 304NotModified** [comment]
Is this a netstandard project? Or just UWP? 

We only support UWP by netstandard

**Comment by 304NotModified** [comment]
Related 
http://stackoverflow.com/questions/38315273/cannot-reference-net-core-library-from-uwp

**Comment by gtbuchanan** [comment]
Same issues for me with a UWP (uap10.0) project. The build succeeds even with the above errors, but I receive a runtime error relating to `System.IO.FileSystem.Watcher` (likely because UWP doesn't support this assembly).

```
System.TypeInitializationException: The type initializer for 'NLog.LogManager' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem.Watcher, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at NLog.LogFactory..ctor()
   at NLog.LogManager..cctor()
   --- End of inner exception stack trace ---
   at NLog.LogManager.GetLogger(String name)
```

I'm having a hard time following all the discussions about NLog and UWP. I noticed there is a UWP branch, albeit outdated, that attempts to fix some of these issues using UWP10 compiler flags. However, I saw #1483 exists to remove the UWP10 flags. I don't see anything obviously relating to UWP in the master or coreCLR branches.

> We only support UWP by netstandard

I don't really follow this statement either. There's a way we can use NLog with UWP without having a UWP project?

**Comment by 304NotModified** [comment]
> Same issues for me with a UWP (uap10.0) project.

Most of the issues are with installing. Also the TS?

> I'm having a hard time following all the discussions about NLog and UWP. I noticed there is a UWP branch, albeit outdated, that attempts to fix some of these issues using UWP10 compiler flags. However, I saw #1483 exists to remove the UWP10 flags. I don't see anything obviously relating to UWP in the master or coreCLR branches.

The UWP build has been evolved to the NETSTANDARD version (NLog 5), as UWP should run with NETSTANDARD. CoreCLR is the name before the NETSTANDARD. 

> I don't really follow this statement either. There's a way we can use NLog with UWP without having a UWP project?

See 

![image](https://cloud.githubusercontent.com/assets/5808377/22076352/06d4bae4-ddb0-11e6-9122-3b5edb4cabde.png)

https://docs.microsoft.com/en-us/dotnet/articles/standard/library



> System.IO.FileSystem.Watcher (likely because UWP doesn't support this assembly).

If it's in NETSTANDARD, it should be supported. That's the whole idea with NETSTANDARD

Also there is no standalone UWP build anymore, as we couldn't run unit tests automated for UWP :(

**Comment by gtbuchanan** [comment]
@304NotModified Thank you for the additional info. However, [this StackOverflow answer](http://stackoverflow.com/a/40046806/1409101) from a .NET team member states `System.IO.FileSystem.Watcher` is not supported in UWP (even though NuGet allows you to reference the library from a .NET Standard 1.4 project without complaint).

[project.json](https://github.com/NLog/NLog/blob/coreCLR/src/NLog/project.json) in the coreCLR branch looks like it references `System.IO.FileSystem.Watcher` in all supported .NET Standard versions, which leads me to believe NLog 5 won't work at all with UWP. This sort of explains why we are receiving these errors, right?

Seems to me like instances such as [this](https://github.com/NLog/NLog/blob/coreCLR/src/NLog/LogFactory.cs#L68) will need to check some sort of compiler flag like they were previously (WINDOWS_UWP) to actually have support for UWP. It's a bummer about the unit tests, though.

**Comment by 304NotModified** [comment]
> Thank you for the additional info. However, this StackOverflow answer from a .NET team member states System.IO.FileSystem.Watcher is not supported in UWP (even though NuGet allows you to reference the library from a .NET Standard 1.4 project without complaint).

yeah could not understand that. What should be read all those information? So we can't include any package with the risk of runtime errors? We can't support that as unit tests also won't work on the build server.



> project.json in the coreCLR branch looks like it references System.IO.FileSystem.Watcher in all supported .NET Standard versions, which leads me to believe NLog 5 won't work at all with UWP. This sort of explains why we are receiving these errors, right?

correct. Won't work. We could remove it, but not sure what will be the next issue.

I hope NETSTANDARD 2 fixes these issues.

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.

**Comment by gtbuchanan** [comment]
It's still an issue, but I've forked the coreCLR branch and made fixes so I can actually use NLog on UWP.

I can submit a pull request if you're interested, but you didn't seem like you wanted to put workarounds in place for the incompatibilities with UWP and some of the NET Standard 1.4 supported libraries.

https://github.com/energyworldnet/NLog/commit/bf377d08a97447ff5f94a6961a535570dffa554d

**Comment by 304NotModified** [comment]
I'm interested but also curious how many changes it need.

**Comment by 304NotModified** [comment]
this should be fixed in NLog 5 beta07. Thanks to @gtbuchanan  and @snakefoot !
