### ISSUE TITLE
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. on OSX

### ISSUE THREAD

**Issue by ritasker** [NLog/NLog#1882]
**Type** : Bug

**NLog version**: 5.0.0-beta04

**Platform**: .NET Core (osx.10.11-x64)

**Current NLog config** (xml or C#, if relevant)

```C#
using System;
using System.IO;
using NLog;
using NLog.Config;
using NLog.Targets;

namespace NLogConsoleApp
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var logger = GetLogger();

            var files = Directory.GetFiles("/Users/richard/Documents");

            foreach (string file in files)
            {
                Console.WriteLine(file);
                logger.Info(file);
            }
        }

        private static Logger GetLogger()
        {
            var config = new LoggingConfiguration();
            var fileTarget = new FileTarget();
            config.AddTarget("file", fileTarget);

            fileTarget.FileName = Path.Combine("/Users/richard/Documents", "logs.log");
            fileTarget.Layout = "${message}";
            var rule = new LoggingRule("*", LogLevel.Trace, fileTarget);
            config.LoggingRules.Add(rule);
            LogManager.Configuration = config;
            LogManager.ThrowExceptions = true;

            return LogManager.GetCurrentClassLogger();
        }
    }
}
```

Hi!

On OSX I am unable to use a `FileTarget` as a `System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.` exception is thrown.

```
Unhandled Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLogConsoleApp.Program.Main(String[] args)
```

The above code sample recreates the issue. On Windows, this works as expected once I have updated the path to point to my Documents folder. I am also printing the contests of the directory to the console to make sure it wasn't related to .net having problems reading the unix folder path.

Please let me know if you require anything else.

-- Rich

**Comment by 304NotModified** [comment]
Could you post full the internal log? (trace level). Thanks !

**Comment by snakefoot** [comment]
Probably the same bug again, that has sneaked in again after the merge: #1737 (See the new BaseMutexFileAppender.cs):

-            canonicalName = canonicalName.Replace('\\', '/');
+            canonicalName = canonicalName.Replace('\\', '_');
+            canonicalName = canonicalName.Replace('/', '_');

**Comment by ritasker** [comment]
I have tried to get the internal log, its not very informative.
```
dotnet run
Project NLogConsoleApp (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
2016-12-30 19:18:16.3156 Debug Targets for Program by level:
2016-12-30 19:18:16.3200 Debug Trace =>
2016-12-30 19:18:16.3200 Debug Debug =>
2016-12-30 19:18:16.3200 Debug Info =>
2016-12-30 19:18:16.3200 Debug Warn =>
2016-12-30 19:18:16.3200 Debug Error =>
2016-12-30 19:18:16.3200 Debug Fatal =>
/Users/richard/Documents/.DS_Store
2016-12-30 19:18:16.3427 Error Error has been raised. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

Unhandled Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLogConsoleApp.Program.Main(String[] args)
```
This is the whole console output.

-- Rich

**Comment by 304NotModified** [comment]
> Probably the same bug, that has sneaked in again after the 4.4 merge: #1737 (See the new BaseMutexFileAppender.cs that doesn't remove all slashes):

Oops. Sounds like the problem. Didn't checked yet. Will have more time next year ;)

**Comment by ritasker** [comment]
I was hoping to fix and PR this today. It looks like I would want to branch and PR on the `CoreCLR` branch, is that correct?

**Comment by 304NotModified** [comment]
that's correct!  (well `coreCLR` with lower `c`, as git is case sensitive) 

See https://github.com/NLog/NLog/pull/1160

Thanks in advance!

**Comment by 304NotModified** [comment]
Should be fixed in https://www.nuget.org/packages/NLog/5.0.0-beta05-test

Could you please test it? Thanks!

**Comment by maslakov** [comment]
We have the same issue with AWS linux instances. Our application cannot write logs to the file.
Waiting for the fixed version.

**Comment by maslakov** [comment]
I checked https://www.nuget.org/packages/NLog/5.0.0-beta05-test
Don't know what else has to be checked, but at least the logs are in the file now. Thanks!
Will use this package until there is something more official in place.

**Comment by 304NotModified** [comment]
The non test is the replacement ;) (same code)

**Comment by ritasker** [comment]
Tested this earlier it works, I just didn't get around to commenting before the issue was closed. Thanks

**Comment by 304NotModified** [comment]
Thanks for the feedback. Also thanks to @snakefoot for the code for the fix ! :)))
