### ISSUE TITLE
NLog with NLog.Targets.Syslog - Object reference error

### ISSUE THREAD

**Issue by Kalyanr** [NLog/NLog#1894]
Iam trying to log to the papertrail systems using Nlog and NLog.Targets.Syslog and somehow Nlog fails to load the target from the Nlog.config when i call

```
Logger logger = LogManager.GetCurrentClassLogger();
```

and throws the exception Object reference not set to an instance of an object.

```
at NLog.Targets.Syslog.Settings.Rfc3164Config..ctor()
   at NLog.Targets.Syslog.Settings.MessageBuilderConfig..ctor()
   at NLog.Targets.Syslog.SyslogTarget..ctor()
Stacktrace
at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at NLogPaperTrail.Controllers.HomeController.Index() in I:\Temp\Proj\tempsolution\NLogPaperTrail\NLogPaperTrail\Controllers
```

This is the Nlog.config

  
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true"     ThrowExceptions = "true"  >

 <extensions>

       <add assembly="NLog.Targets.Syslog" />
    </extensions>

    <targets>
        <target name="syslog" xsi:type="Syslog" syslogserver="host.papertrailapp.com" port="5677" facility="Local7"/>

   </targets>

    <rules>

     <logger name="*" minLevel="Trace" appendTo="syslog"/>
    </rules>
</nlog>

```

Can anyone help or provide your suggestions?

**Comment by 304NotModified** [comment]
hi!

I think this is a bug in the syslog target. We don't manage that target, but luckily it's open source.

It seems that the bug is here:

```
        public Rfc3164Config()
        {
            Hostname = Dns.GetHostName();
            Tag = Assembly.GetEntryAssembly().GetName().Name;
        }
```
See https://github.com/graffen/NLog.Targets.Syslog/blob/master/src/NLog.Targets.Syslog/Settings/Rfc3164Config.cs

Probably `Assembly.GetEntryAssembly()` returns `null` 

I would recommend to open an issue at https://github.com/graffen/NLog.Targets.Syslog

**Comment by luigiberrettini** [comment]
Closed by [graffen/NLog.Targets.Syslog#53](https://github.com/graffen/NLog.Targets.Syslog/pull/53)

**Comment by 304NotModified** [comment]
thanks @luigiberrettini !!
