### ISSUE TITLE
"Invalid Punctuation: $" error when trying to use `When` layout renderer

### ISSUE THREAD

**Issue by dougthor42** [NLog/NLog#1901]
## Summary
When trying to use the `when` layout renderer, the "Invalid punctuation: $" error is thrown. I can't tell if it's user error or actually a bug. I'm working off of [this StackOverflow answer](http://stackoverflow.com/a/31192985/1354930).

## The problem I'm trying to solve
My C# code runs on both Windows and on Linux. Currently I log everything to a folder in `${basedir}`, but I now need to log to `/var/log/project` when on linux.

*However*, for purposes of this bug report, I'm attempting to simplify things a bit by only checking `${environment:Is64BitOperatingSystem}`, as per the SO link above.

## Info
**Type**: Bug
**NLog version**: 4.4.1
**Platform**: Windows .Net 4.6, Linux Mono 4.6
**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug" internalLogFile="nlog-internal.log">

  <variable name="UTC" value="${date:universalTime=true:format=yyyy-MM-ddTHH\:mm\:ss.ffffZ}"/>
  <variable name="defaultLayout" value="${UTC} [${level:uppercase=true:padding=-5}] [${callsite}]::  ${message}"/>

  <targets>
    <target xsi:type="Console" name="console" layout="${defaultLayout}"/>
    <target xsi:type="file"
            name="file"
            layout="${defaultLayout}"
            filename="c:\temp\${when:when=${environment:Is64BitOperatingSystem}=true:inner=64:else=32}\file.log"
            archiveFileName="${basedir}/log/nsutil_{#}.log"
            archiveEvery="Day"
            archiveNumbering="Date"
            archiveDateFormat="yyyyMMdd"
            maxArchiveFiles="14"
      />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="console" />
    <logger name="*" minlevel="Info" writeTo="file"/>
  </rules>
</nlog>
```

## Internal Log (Debug level)
```
2017-01-12 15:07:00.6610 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2017-01-12 15:07:00.6911 Debug Start auto loading, location: C:\gitlab\dthor\ns-util\NSUtil\bin\Debug
2017-01-12 15:07:00.6911 Info Auto loading assembly file: C:\gitlab\dthor\ns-util\NSUtil\bin\Debug\NLog.CrossPlatformFileTarget.dll
2017-01-12 15:07:00.7286 Info NLog.CrossPlatformFileTarget, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. File version: 1.0.0.0. Product version: 1.0.0.0.
2017-01-12 15:07:00.7286 Debug ScanAssembly('NLog.CrossPlatformFileTarget, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
2017-01-12 15:07:00.7286 Info Auto loading assembly file: C:\gitlab\dthor\ns-util\NSUtil\bin\Debug\NLog.CrossPlatformFileTarget.dll succeeded!
2017-01-12 15:07:00.7286 Debug Auto loading done
2017-01-12 15:07:00.7286 Debug Setting 'DateLayoutRenderer.universalTime' to 'true'
2017-01-12 15:07:00.7416 Debug Setting 'DateLayoutRenderer.format' to 'yyyy-MM-ddTHH:mm:ss.ffffZ'
2017-01-12 15:07:00.7416 Debug Setting 'DateLayoutRenderer.universalTime' to 'true'
2017-01-12 15:07:00.7416 Debug Setting 'DateLayoutRenderer.format' to 'yyyy-MM-ddTHH:mm:ss.ffffZ'
2017-01-12 15:07:00.7416 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-01-12 15:07:00.7556 Debug Setting 'PaddingLayoutRendererWrapper.padding' to '-5'
2017-01-12 15:07:00.7556 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-01-12 15:07:00.7556 Debug Setting 'ConsoleTarget.name' to 'console'
2017-01-12 15:07:00.7556 Debug Setting 'ConsoleTarget.layout' to '${date:universalTime=true:format=yyyy-MM-ddTHH\:mm\:ss.ffffZ} [${level:uppercase=true:padding=-5}] [${callsite}]::  ${message}'
2017-01-12 15:07:00.7556 Debug Setting 'DateLayoutRenderer.universalTime' to 'true'
2017-01-12 15:07:00.7556 Debug Setting 'DateLayoutRenderer.format' to 'yyyy-MM-ddTHH:mm:ss.ffffZ'
2017-01-12 15:07:00.7556 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-01-12 15:07:00.7556 Debug Setting 'PaddingLayoutRendererWrapper.padding' to '-5'
2017-01-12 15:07:00.7556 Info Adding target Console Target[console]
2017-01-12 15:07:00.7556 Debug Registering target console: NLog.Targets.ConsoleTarget
2017-01-12 15:07:00.7556 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-01-12 15:07:00.7711 Debug Setting 'FileTarget.name' to 'file'
2017-01-12 15:07:00.7711 Debug Setting 'FileTarget.layout' to '${date:universalTime=true:format=yyyy-MM-ddTHH\:mm\:ss.ffffZ} [${level:uppercase=true:padding=-5}] [${callsite}]::  ${message}'
2017-01-12 15:07:00.7711 Debug Setting 'DateLayoutRenderer.universalTime' to 'true'
2017-01-12 15:07:00.7711 Debug Setting 'DateLayoutRenderer.format' to 'yyyy-MM-ddTHH:mm:ss.ffffZ'
2017-01-12 15:07:00.7711 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-01-12 15:07:00.7711 Debug Setting 'PaddingLayoutRendererWrapper.padding' to '-5'
2017-01-12 15:07:00.7711 Debug Setting 'FileTarget.filename' to 'c:\temp\${when:when=${environment:Is64BitOperatingSystem}=true:inner=64:else=32}\file.log'
2017-01-12 15:07:00.7711 Warn Error when setting property 'FileName' on 'File Target[file]' Exception: NLog.Conditions.ConditionParseException: Invalid punctuation: $
   at NLog.Conditions.ConditionTokenizer.GetNextToken()
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
2017-01-12 15:07:00.7711 Warn Error when setting 'c:\temp\${when:when=${environment:Is64BitOperatingSystem}=true:inner=64:else=32}\file.log' on attibute 'filename'
2017-01-12 15:07:00.7711 Error Parsing configuration from C:\gitlab\dthor\ns-util\NSUtil\bin\Debug\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\gitlab\dthor\ns-util\NSUtil\bin\Debug\NLog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'FileName' on File Target[file] ---> NLog.Conditions.ConditionParseException: Invalid punctuation: $
   at NLog.Conditions.ConditionTokenizer.GetNextToken()
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```

## Expected Result
+ No error is thrown
+ On a 64 bit system, the file is logged to `C:\temp\64\file.log`
+ On a 32 bit system, the file is logged to `C:\temp\32\file.log`

## Answers to the other questions
- Are there any work arrounds?
  - Not that I have been able to figure out.
- Is there a version in which it did worked?
  - Not that I'm aware
- Can you help us by writing an unit test?
  - I could try, but my experience with C# is pretty limited.

**Comment by dougthor42** [comment]
Sigh... yeah, it was PEBKAC.

My `filename` line should have single-quotes `'` surrounding the inner `${}`:

```xml
<target xsi:type="file"
         name="file"
         layout="${defaultLayout}"
         filename="c:\temp\${when:when='${environment:Is64BitOperatingSystem}'=true:inner=64:else=32}\file.log"
/>
```

Sorry for adding to the noise!

**Comment by 304NotModified** [comment]
Well, it was lazy and didn't tested it.

The forgot the quotes indeed.

And now tested it, and it won't work :(

The dos of `${environment}` where wrong!  https://github.com/NLog/NLog/wiki/Environment-Layout-Renderer It's reading the env variables, and NOT the properties of the Environment class!  (but was stated like this).

Have update the docs. But there is no "Is64BitOperatingSystem" variable. (at least not on my bit64 system)

**Comment by 304NotModified** [comment]
created a bug report. #1902 for this
