### ISSUE TITLE
Error saving log file in Linux

### ISSUE THREAD

**Issue by xordi** [NLog/NLog#1920]
Hi!

I'm writing with regard to a bug I'm experiencing when using the FileTarget in Ubuntu Linux 16.04. The log file is not being created in Linux in the same folder where I'm executing the application (the user who executes the application has write permissions in the folder), but it works perfectly in Windows. The ConsoleTarget works perfectly in both systems.

The NLog version I'm using is 5.0.0-beta4

The application type is a .NET Core Console application (self-contained application) targeting:

- ubuntu.16.04-x64
- win10-x64

When configuring Internal Logger to log into console , I see the following error:

```
2017-01-16 09:59:02.2330 Error Error has been raised. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFilePar                                                                                                   ameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
```
The application code is the following:

```
    public class Program
    {
        public static void Main(string[] args)
        {
            var consoleTarget = new ColoredConsoleTarget { Layout = @"${date:format=HH\:mm\:ss} ${logger} ${message}" };
            var fileTarget = new FileTarget
            {
                FileName = "corenlogtest.log",
                ArchiveFileKind = FilePathKind.Relative,

            };

            var config = new LoggingConfiguration();
            config.AddTarget("file", fileTarget);
            config.AddTarget("console", consoleTarget);

            config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, consoleTarget));
            config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, fileTarget));            

            LogManager.Configuration = config;

            InternalLogger.LogToConsole = true;
            InternalLogger.LogLevel = LogLevel.Trace;

            var logger = LogManager.GetCurrentClassLogger();

            logger.Trace("trace log message");
            logger.Debug("debug log message");
            logger.Info("info log message");
            logger.Warn("warn log message");
            logger.Error("error log message");
            logger.Fatal("fatal log message");
        }
    }
```

**Comment by 304NotModified** [comment]
this is https://github.com/NLog/NLog/issues/1882 is guess.

I was under the impression this is only when archiving is enabled. 

Waiting for a PR, but will fix it otherwise this week

**Comment by 304NotModified** [comment]
Should be fixed in https://www.nuget.org/packages/NLog/5.0.0-beta05-test

Could you please test it? Thanks!

**Comment by deppe** [comment]
I was seeing a very similar issue using Microsoft.Extensions.NLog. Is this patch only for the "NLog" package, or will it fix that as well?

**Comment by 304NotModified** [comment]
Its in NLog but NLog.Extensions.Logging is using it. 

You have to manually update/define your NLog package when using NLog.Extensions.Logging

**Comment by xordi** [comment]
Hi @304NotModified ,

The writing in FileTarget problem seems to be solved, although another one arised. In my FileTarget configuration, I specified the ArchiveEvery property to every hour

```
var fileTarget = new FileTarget
{
	FileName = "corenlogtest.log",
	ArchiveFileKind = FilePathKind.Relative,
	ConcurrentWrites = false,
	ArchiveEvery = FileArchivePeriod.Hour,
	ArchiveNumbering = ArchiveNumberingMode.DateAndSequence,
	ArchiveDateFormat = "yyyyMMddHHmm"
};
```

the archivation period is set to every hour. But as you can see in the following extract from the internal logger, in every log writing the log file is archived and a new one is created:

```
08:55:31 C:\Users\jordi.oliver\Source\Repos\CoreNLogTest\src\CoreNLogTest\Program debug log message
2017-01-24 08:55:31.4234 Trace Opening /home/jordi/core-log-test/corenlogtest.log with allowFileSharedWriting=False
08:55:31 C:\Users\jordi.oliver\Source\Repos\CoreNLogTest\src\CoreNLogTest\Program info log message
2017-01-24 08:55:31.5172 Trace Calculating archive date. Last write time: 01/24/2017 08:55:31; Previous log event time: 01/24/2017 08:55:31
2017-01-24 08:55:31.5172 Trace Using previous log event time (is more recent)
2017-01-24 08:55:31.5670 Info Archiving /home/jordi/core-log-test/corenlogtest.log to /home/jordi/core-log-test/corenlogtest.201701240855.0.log
2017-01-24 08:55:31.5712 Trace Opening /home/jordi/core-log-test/corenlogtest.log with allowFileSharedWriting=False
08:55:31 C:\Users\jordi.oliver\Source\Repos\CoreNLogTest\src\CoreNLogTest\Program warn log message
2017-01-24 08:55:31.5712 Trace Calculating archive date. Last write time: 01/24/2017 08:55:31; Previous log event time: 01/24/2017 08:55:31
2017-01-24 08:55:31.5712 Trace Using previous log event time (is more recent)
2017-01-24 08:55:31.5804 Info Archiving /home/jordi/core-log-test/corenlogtest.log to /home/jordi/core-log-test/corenlogtest.201701240855.1.log
2017-01-24 08:55:31.5804 Trace Opening /home/jordi/core-log-test/corenlogtest.log with allowFileSharedWriting=False
08:55:31 C:\Users\jordi.oliver\Source\Repos\CoreNLogTest\src\CoreNLogTest\Program error log message
2017-01-24 08:55:31.5804 Trace Calculating archive date. Last write time: 01/24/2017 08:55:31; Previous log event time: 01/24/2017 08:55:31
2017-01-24 08:55:31.5804 Trace Using previous log event time (is more recent)
2017-01-24 08:55:31.5827 Info Archiving /home/jordi/core-log-test/corenlogtest.log to /home/jordi/core-log-test/corenlogtest.201701240855.2.log
2017-01-24 08:55:31.5827 Trace Opening /home/jordi/core-log-test/corenlogtest.log with allowFileSharedWriting=False
08:55:31 C:\Users\jordi.oliver\Source\Repos\CoreNLogTest\src\CoreNLogTest\Program fatal log message
2017-01-24 08:55:31.5827 Trace Calculating archive date. Last write time: 01/24/2017 08:55:31; Previous log event time: 01/24/2017 08:55:31
2017-01-24 08:55:31.5827 Trace Using previous log event time (is more recent)
2017-01-24 08:55:31.5827 Info Archiving /home/jordi/core-log-test/corenlogtest.log to /home/jordi/core-log-test/corenlogtest.201701240855.3.log
2017-01-24 08:55:31.5827 Trace Opening /home/jordi/core-log-test/corenlogtest.log with allowFileSharedWriting=False
```

Thanks for your help!

**Comment by 304NotModified** [comment]
OK thanks for the feedback! 

> But as you can see in the following extract from the internal logger, in every log writing the log file is archived and a new one is created:

This is https://github.com/NLog/NLog/issues/1633
