### ISSUE TITLE
Database target isn't writing logs - timeout (async)

### ISSUE THREAD

**Issue by soninsunil** [NLog/NLog#1970]
- Question

**NLog version**: ~(e.g. 2.0.0.0)~ (4.4.3 - Julian)

**Platform**: .Net 4.0 

**Current NLog config** (xml)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets async="true">
      <target name="file" xsi:type="File" 
              fileName="D:/Test/log/AppService_${shortdate}.txt" 
              archiveFileName="D:/Test/log/AppService_${shortdate}.txt" 
              archiveAboveSize="50000000" archiveEvery="Day" 
              archiveNumbering="Rolling" maxArchiveFiles="30" 
              concurrentWrites="true" keepFileOpen="false" 
              encoding="iso-8859-2" 
              layout="${longdate}|${level:uppercase=true}|${logger}|${event-context:item=Group}
              |${message}}|${exception:format=tostring:maxInnerExceptionLevel=3}" />
      <target name="database" xsi:type="Database" connectionStringName="EntityConnection">
        <commandText>
          EXEC [dbo].[insertLogMessages] @Group, @moduleName, @severity, @detail, @isFlag
        </commandText>
        <parameter name="@Group" layout="${event-context:item=Group}" />
        <parameter name="@moduleName" layout="${logger}" />
        <parameter name="@severity" layout="${level:uppercase=true}" />
        <parameter name="@detail" layout="${message}" />
        <parameter name="@isFlag" layout="${event-context:item=IsFlag}" />
      </target>
    </targets>
    <rules>
      <logger name="log" minlevel="Debug" writeTo="file" />
      <logger name="log.db" minlevel="Info" writeTo="database" />
    </rules>
  </nlog>
```

Logger class is static initialized from code and based on severity log is inserted into DB for WARN/ERROR. But sometime logger does not insert record in db target and have to restart service.

Now enabled internal logging as well but not sure if we missed anything, please suggest.

**Comment by 304NotModified** [comment]
could you post the content of the internal log, on debug level? Als please tell us which NLog version this is.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by soninsunil** [comment]
NLog version:4.4.3

Internal Log:

Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning()
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(DbAsyncResult result, String methodName, Boolean sendToPipe)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(IList`1 logEvents)

**Comment by 304NotModified** [comment]
Do you get that error once or continuously?

**Comment by soninsunil** [comment]
Hi, Thanks for checking on this. Yes we are getting this error every day and database logging is stopped after this, but file logging is working file.

**Comment by 304NotModified** [comment]
isn't your database to busy? 

related: https://github.com/NLog/NLog/issues/1997

**Comment by snakefoot** [comment]
@soninsunil Do you also have log-messages like these, for your database-target:

>2017-03-01 21:34:43.0285 Trace DatabaseTarget: close connection because of exception
2017-03-01 21:34:43.0285 Trace DatabaseTarget: close connection because of KeepConnection=false
2017-03-01 21:34:43.0285 Error AsyncWrapper 'database': Error in lazy writer timer procedure. Exception: System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
>
> 2017-03-01 21:34:12.9049 Trace DatabaseTarget: close connection because of exception
> 2017-03-01 21:34:12.9049 Trace DatabaseTarget: close connection because of KeepConnection=false
> 
> 2017-03-01 21:34:43.0909 Trace AsyncWrapper 'database': writing 96 events (Timer)
> 2017-03-01 21:34:43.0909 Trace DatabaseTarget: open connection.

**Comment by soninsunil** [comment]
#1997 is the exact issue, i was not aware this was created. please close this as duplicate of #1997

**Comment by mshibani7** [comment]
How to check/Confirm that AsyncWrapper being too fast?
