### ISSUE TITLE
Dot.net Core Error NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c

### ISSUE THREAD

**Issue by nicollaas94** [NLog/NLog#2018]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

- Bug
- Question

**NLog version**: (e.g. 4.3.1)

**Platform**
NET Core 

**Current NLog config**
Followed 
https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json)

In case of a BUG:

- What is the current result?
throws 
`Could not load file or assembly 'NLog, Version = 5.0.0.0, Culture = neutral, PublicKeyToken = 5120e14c03d0593c' or one of its dependencies. The localized assembly manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

on 
` env.ConfigureNLog("nlog.config");`
Or 
`app.AddNLogWeb();`

- What is the expected result?
Run

- Please post full exception details (message, stacktrace, inner exceptions)

```
System.IO.FileLoadException: Could not load file or assembly 'NLog, Version = 5.0.0.0, Culture = neutral, PublicKeyToken = 5120e14c03d0593c' or one of its dependencies. The localized assembly manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File Name: 'NLog, Version = 5.0.0.0, Culture = neutral, PublicKeyToken = 5120e14c03d0593c'
   In MarketingReports.Ng2.Startup..ctor (IHostingEnvironment env)
--- End of stack trace from the previous location where the exception was raised ---
   At System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
   At the Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance (IServiceProvider provider)
   At Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance (IServiceProvider provider, Type type)
   In Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods (IServiceProvider services, Type startupType, String environmentName)
   In Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions. <> C__DisplayClass1_0.b__1 (IServiceProvider sp)
   At Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke (ServiceProvider provider)
   At Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService (IServiceProvider provider, Type serviceType)
   At the Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService [T] (IServiceProvider provider)
   At Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup ()
   In Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices ()
   In Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication ()

=== Information about pre-association state ===
LOG: DisplayName = NLog, Version = 5.0.0.0, Culture = neutral, PublicKeyToken = 5120e14c03d0593c
 (Fully-specified)
LOG: Appbase = file: /// C: /***/bin/Debug/net452/win7-x64/
LOG: Initial PrivatePath = NULL
Calling assembly: MarketingReports.Ng2, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = null.
===
LOG: This association starts in the default load context.
LOG: Using Application Configuration File: C: \ ***
LOG: Using Host Configuration File:
LOG: Using machine configuration file from C: \ Windows \ Microsoft.NET \ Framework64 \ v4.0.30319 \ config \ machine.config.
LOG: Post-Policy Reference: NLog, Version = 5.0.0.0, Culture = neutral, PublicKeyToken = 5120e14c03d0593c
LOG: attempting to download new URL file: c:\***
AVI: Assembly name comparison resulted in incompatibility: Major Version
ERR: Failed to complete assembly configuration (hr = 0x80131040). Probing locked up.
```

**Comment by 304NotModified** [comment]
Could you check if the example (https://github.com/NLog/NLog.Extensions.Logging/tree/master/examples/aspnet-core-example)

is working for you?

**Comment by 304NotModified** [comment]
Which CLI / .NET Core version is this?

**Comment by nicollaas94** [comment]
The problem was in my visual Studio ... update to vs15 to 17 and migrate the project solve the bug

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍

**Comment by bmallen1** [comment]
I have this issue on a production windows server running .NET 4.6. This configuration works on my local machine only.

```Packages.config:
  <package id="NLog" version="4.4.11" targetFramework="net46" />
  <package id="NLog.Schema" version="4.4.11" targetFramework="net46" />
  <package id="NLog.Targets.Stackify" version="1.25.3" targetFramework="net46" />
  <package id="StackifyLib" version="1.25.4" targetFramework="net46" />  <--Also tried version 1.25.3

Debug log:
2017-06-30 18:39:49.0184 Info Shutting down logging...
2017-06-30 18:39:49.0184 Trace Flushing all targets...
2017-06-30 18:39:49.0184 Trace ForEachItemInParallel() 0 items
2017-06-30 18:39:49.0184 Debug Closing logging configuration...
2017-06-30 18:39:49.0184 Debug Finished closing logging configuration.
2017-06-30 18:39:49.0184 Info Logger has been shut down.
2017-06-30 18:40:23.6404 Info Loading assembly name: NLog.Targets.Stackify
2017-06-30 18:40:23.6404 Debug ScanAssembly('NLog.Targets.Stackify, Version=1.18.6200.39247, Culture=neutral, PublicKeyToken=null')
2017-06-30 18:40:23.6404 Warn Type load exception. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2017-06-30 18:40:23.6560 Error Parsing configuration from C:\inetpub\wwwroot\mycompany\myapp\api.mysite.com\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\inetpub\wwwroot\mycompany\myapp\api.mysite.com\NLog.config.  ---> System.ArgumentException: Target cannot be found: 'StackifyTarget'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2017-06-30 18:40:23.6560 Debug --- NLog configuration dump ---
2017-06-30 18:40:23.6560 Debug Targets:
2017-06-30 18:40:23.6560 Debug Rules:
2017-06-30 18:40:23.6560 Debug --- End of NLog configuration dump ---
2017-06-30 18:40:23.6560 Trace FindReachableObject<System.Object>:
2017-06-30 18:40:23.6560 Info Found 0 configuration items
2017-06-30 18:40:23.6560 Info Configuration initialized.
2017-06-30 18:40:23.6560 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.4.5422. Product version: 4.4.11.
2017-06-30 18:40:23.6560 Debug Targets for service by level:
2017-06-30 18:40:23.6560 Debug Trace =>
2017-06-30 18:40:23.6560 Debug Debug =>
2017-06-30 18:40:23.6560 Debug Info =>
2017-06-30 18:40:23.6560 Debug Warn =>
2017-06-30 18:40:23.6560 Debug Error =>
2017-06-30 18:40:23.6560 Debug Fatal =>

Assembly binding in Web.config:
      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>

NLog.config:
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" internalLogFile="C:\inetpub\wwwroot\mycompany\myapp\api.mysite.com\App_Data\log.txt" internalLogLevel="Trace">
	<extensions>
		<add assembly="NLog.Targets.Stackify" />
	</extensions>
	<targets>
		<target name="stackify" type="StackifyTarget" logMethodNames="true" logAllParams="true" mappedContextKeys="VisitorID,AffiliateId,AffiliateCampaignId,AffiliateCampaignName"/>
	</targets>
	<rules>
		<logger name="service" writeTo="stackify" minlevel="Debug" />
	</rules>
</nlog>```

**Comment by 304NotModified** [comment]
Please create a new issue, thanks.
