### ISSUE TITLE
date in a PostgreSQL target

### ISSUE THREAD

**Issue by damienbod** [NLog/NLog#2024]
- Bug or Question

**NLog version**: 5.0.0 beta 5

 .NET Core 

**Current NLog config** (xml or C#, if relevant)

https://github.com/damienbod/AspNetCoreNlog/blob/postgresqlLogging/src/ConsoleNLogPostgreSQL/nlog.config

I'm setting up NLog with a PostgreSQL target. I have a problem if I set the logged, or timestamp field in the database to date. If I set this to text everything is fine.

Is they anyway I can log this field as a date type?

Error:

Error Error when writing to database. Exception: Npgsql.PostgresException: 42804: column "logged" is of type date but expression is of type text
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__146.MoveNext()

Greetings Damien

**Comment by 304NotModified** [comment]
Currently all the parameters are text only. Probable if you format the date to ISO 8601, it will be accepted.

See  https://github.com/NLog/NLog/issues/522
