### ISSUE TITLE
Target WebService - fails when app cannot communicate via target url 

### ISSUE THREAD

**Issue by minime1233** [NLog/NLog#2035]
Hi! 

We're using nlog WebService target to log various events to REST endpoint.
Our application is classic WPF app (.NET Framework 4.5.2) and we're using NLog 4.4.4.

However, we keep getting an error:
```
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>Adora.Assistant.vshost.exe</AppDomain><Exception><ExceptionType>System.Net.WebException, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Unable to connect to the remote server</Message><StackTrace>   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp;amp; context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at NLog.Targets.WebServiceTarget.&amp;lt;&amp;gt;c__DisplayClass7.&amp;lt;DoInvoke&amp;gt;b__5(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.HttpWebRequest.SetResponse(Exception E)
   at System.Net.HttpWebRequest.SetAndOrProcessResponse(Object responseOrException)
   at System.Net.ConnectionReturnResult.SetResponses(ConnectionReturnResult returnResult)
   at System.Net.Connection.CompleteConnectionWrapper(Object request, Object state)
   at System.Net.PooledStream.ConnectionCallback(Object owningObject, Exception e, Socket socket, IPAddress address)
   at System.Net.ServicePoint.ConnectSocketCallback(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)</StackTrace><ExceptionString>System.Net.WebException: Unable to connect to the remote server ---&amp;gt; System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.0.101:80
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp;amp; socket, IPAddress&amp;amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp;amp; exception)
   --- End of inner exception stack trace ---
```

The nlog target we're using:
```xml
<target xsi:type="WebService"
            name="wslog"
            url="http://IPADDRESS/api/v1/RESTMETHOD"
            protocol="JsonPost"
            encoding="UTF-8">
      <parameter name="Level" type="System.String" layout="${level}"/>
      <parameter name="TimeStamp" type="System.DateTime" layout="${date}"/>
      <parameter name="CallSite" type="System.String" layout="${callsite}"/>
      <parameter name="CallSiteLineNumber" type="System.String" layout="${callsite-linenumber}"/>
      
      <parameter name="CustomParameter1" type="System.String" layout="${event-properties:item=CustomParameter1}"/>
      <parameter name="CustomParameter2" type="System.String" layout="${event-properties:item=CustomParameter2}"/>
      <parameter name="CustomParameter3" type="System.String" layout="${event-properties:item=CustomParameter3}"/>
    </target>
```

This is how we create nlog event with custom app parameters:
```c#
public static LogEventInfo WSLogEvent(
            LogLevel level,
            string CustomParameter1,
            string CustomParameter2,
            string CustomParameter3,
            Exception exception = null)
        {
            var eventInfo = new LogEventInfo();

            eventInfo.Level = level;
            eventInfo.TimeStamp = DateTime.Now;

            eventInfo.Properties["CustomParameter1"] = CustomParameter1;
            eventInfo.Properties["CustomParameter2"] = CustomParameter2;
            eventInfo.Properties["CustomParameter3"] = CustomParameter3;
})
```

And later we call it like this:
```c#
private static readonly nlogger1 Logger = LogManager.GetCurrentClassLogger();
nlogger1 .Log(LoggingHelper.WSLogEvent(
                    level: NLog.LogLevel.Debug,
                    CustomParameter1: "Something",
                    CustomParameter2: "More of something",
                    CustomParameter3: "Still more"));
```

Has anyone else encountered this issue?
And if yes, is there a workaround?

Thank you for all the help

**Comment by 304NotModified** [comment]
Could you test with NLog 4.4.5? Thanks in advance!

**Comment by minime1233** [comment]
Thanks for an answer

I've tried it and so far there's no difference.
I still get the same exception. :(

**Comment by minime1233** [comment]
Hi. 

Maybe I should mention one more thing. Logger is calling Api Method located on test server. If Log is able to get response from server (if the machines are on the same network or I am connected via VPN) then everything is working fine.

If the remote server is unreachable then I get this error and the whole app crashes.

Personally I would be ok, if I could at least catch this exception and handle it on my side.

Do you have any other suggestion or workaround this issue.

Thanks a million.

**Comment by 304NotModified** [comment]
could you post the full config? NLog should never throw exceptions, all of them should be catched. (but it depends on the config)

**Comment by snakefoot** [comment]
@minime1233 You should configure `<nlog throwExceptions="false" />` as it should only be used for debugging purposes.

I have created  #2040, so this parameter is not checked in the async completion method.

**Comment by minime1233** [comment]
Hi

@304NotModified, this is my nlog.config:
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      throwExceptions="false"
      internalLogFile="~/log/nlog.txt"
      internalLogLevel="Debug">

      <!-- WEBSERVICE TARGET FROM PREVIOUS POST -->
</nlog>
```

@snakefoot, thanks for a suggestion.
You're right, I had this parameter set as `true`, but I've changed it to `<nlog throwExceptions="false" />` and it kind of works. I still get **many** exceptions (in the output console), but at least the app doesn't crash. :)
Is there a setting to limit max number of attempts for nlog to log the loginfo?

**Comment by 304NotModified** [comment]
OK, this isn't a bug but by-design. If you set throwExceptions=true, you will get exceptions as requested ;)



> I still get many exceptions

If this is also expected, disable the internal log should be fine
