### ISSUE TITLE
In the config file, order of targets and rules blocks may cause errors

### ISSUE THREAD

**Issue by ryancole** [NLog/NLog#2045]
I'm new to NLog and just went through a process of setting up NLog within a project of mine. I couldn't get NLog to properly load for awhile. I eventually got NLog to generate the internal log file and got an error saying that NLog could not locate a target of mine. I looked at my config and noticed that my `targets` block was below my `rules` block. So, I swapped it so that `targets` was now above `rules` and everything started working as intended. This remained the case regardless of whether or not I used a stand alone `NLog.config` file or the `app.config` file.

I'm unsure of how NLog loads the config file, but order of these blocks interfering with things seems odds to me. I think that this is either a bug or needs to be mentioned in the config file documentation, if it's not already.

**Comment by 304NotModified** [comment]
The order shouldn't matter. We read the XML with a custom parser, but its order independent. 

Do you have some errors/diagnostics from the internal log?

**Comment by ryancole** [comment]
@304NotModified Yup. Here's an example of the log output. The first chunk of log lines is from a successful run, where I have the `targets` block defined above the `rules` block. The second chunk of log lines is from after switching `targets` to be below the `rules` block. I put the new lines in manually.

```
2017-03-31 16:53:52.4658 Info Adding target File Target[logfile]
2017-03-31 16:53:52.4798 Info Configured from an XML element in C:\Users\Ryan\Desktop\NativeRDP\source code\relativity-session-manager\RelativitySessionManager\bin\Debug\RelativitySessionManager.vshost.exe.Config...
2017-03-31 16:53:52.5028 Info Found 16 configuration items
2017-03-31 16:53:52.5218 Info Configuration initialized.
2017-03-31 16:53:52.5218 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.4.4755. Product version: 4.4.5.
2017-03-31 16:53:55.8770 Info Shutting down logging...
2017-03-31 16:53:55.8970 Info Logger has been shut down.



2017-03-31 16:54:13.1350 Error Parsing configuration from C:\Users\Ryan\Desktop\NativeRDP\source code\relativity-session-manager\RelativitySessionManager\bin\Debug\RelativitySessionManager.vshost.exe.Config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\Users\Ryan\Desktop\NativeRDP\source code\relativity-session-manager\RelativitySessionManager\bin\Debug\RelativitySessionManager.vshost.exe.Config.  ---> NLog.NLogConfigurationException: Target logfile not found.
   at NLog.Config.XmlLoggingConfiguration.ParseLoggerElement(NLogXmlElement loggerElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseRulesElement(NLogXmlElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2017-03-31 16:54:13.1650 Info Found 0 configuration items
2017-03-31 16:54:13.1730 Info Configuration initialized.
2017-03-31 16:54:13.1730 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.4.4755. Product version: 4.4.5.
2017-03-31 16:54:17.6423 Info Shutting down logging...
2017-03-31 16:54:17.6573 Info Logger has been shut down.
```

**Comment by ryancole** [comment]
👍
