### ISSUE TITLE
Question: I'm getting the following exception at application start.  "The type initializer for 'NLog.Common.InternalLogger' threw an exception"

### ISSUE THREAD

**Issue by JohnRMarshallSr** [NLog/NLog#2080]
- Question
After adding the <entityFramework> section in my App.config file my derived Target class (MemoryTarget) is throwing the above exception in the call to NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(this, LogLevel.Trace);
Prior to adding this to the App.Config everything was logging just fine.  
How to I get past this exception?

**NLog version**: v4.0.30319

**Platform**: WinForms .NET 4.5.2

**Current NLog config** (xml or C#, if relevant)
My App.config file:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <connectionStrings>
    <add name="CPAEntities" connectionString="metadata=res://*/CpaContext.csdl|res://*/CpaContext.ssdl|res://*/CpaContext.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=LQ-12711\SQLEXPRESS;initial catalog=CPA;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
</configuration>

I have not modified the generated NLog.xml file

In case of a BUG:

- Please post full exception details (message, stacktrace, inner exceptions)
System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'NLog.Common.InternalLogger' threw an exception.
  Source=NLog
  TypeName=NLog.Common.InternalLogger
  StackTrace:
       at NLog.Common.InternalLogger.get_IsDebugEnabled()
       at NLog.Config.LoggingConfiguration.Dump()
       at NLog.LogFactory.set_Configuration(LoggingConfiguration value)
       at NLog.Config.SimpleConfigurator.ConfigureForTargetLogging(Target target, LogLevel minLevel)
       at CPA.Log.MemoryTarget..ctor() in F:\Projects\CPA\CPA\Log\MemoryTarget.cs:line 12
       at lambda_method(Closure , IBuilderContext )
       at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
       at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
       at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
       at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
  InnerException: 
       BareMessage=Configuration system failed to initialize
       HResult=-2146232062
       Line=0
       Message=Configuration system failed to initialize
       Source=System.Configuration
       StackTrace:
            at System.Configuration.ConfigurationManager.PrepareConfigSystem()
            at System.Configuration.ConfigurationManager.GetSection(String sectionName)
            at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
            at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
            at System.Diagnostics.DiagnosticsConfiguration.Initialize()
            at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
            at System.Diagnostics.TraceInternal.InitializeSettings()
            at System.Diagnostics.TraceInternal.get_Listeners()
       InnerException: 
            BareMessage=Unrecognized configuration section entityFramework.
            Filename=F:\Projects\CPA\CPA\bin\Debug\CPA.vshost.exe.Config
            HResult=-2146232062
            Line=6
            Message=Unrecognized configuration section entityFramework. (F:\Projects\CPA\CPA\bin\Debug\CPA.vshost.exe.Config line 6)
            Source=System.Configuration
            StackTrace:
                 at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
                 at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
                 at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
                 at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
            InnerException: 

- Are there any work arrounds? no
- Is there a version in which it did worked? 
Yes it worked before adding the <entityFramework> section to my App.config file

- Can you help us by writing an unit test? No

**Comment by JohnRMarshallSr** [comment]
I had to add a reference to entity framework to the applicaiton
