### ISSUE TITLE
.NET Core: auto load fails

### ISSUE THREAD

**Issue by pendenaor** [NLog/NLog#2120]
Problem seems to be tied to linux (Debian 8), Windows (2012R2) does not exhibit this behavior.

**Type** :

- Bug

**NLog version**:

- NLog 5.0.0-beta07
- NLog.Web.AspNetCore 4.4.0

**Platform**: 

- .NET Core 1.1

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="/home/wsnotif/logs/sci-internal-nlog.log" internalLogLevel="Debug">

  <extensions>
    <!--<add assembly="NLog.Web.AspNetCore"/>-->
    <add assembly="Notification.Template.Logging"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
	<target xsi:type="File" name="infofile" fileName="/home/wsnotif/logs/notif_template_sci.log"
            layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff} ${uppercase:${level}} : ${message} ${exception:format=tostring}"
            archiveFileName="/home/wsnotif/logs/archive/WSNotif_Main-${shortdate}.{####}.log"
            archiveAboveSize="209715200"
            archiveEvery="Day"
            archiveNumbering = "Sequence"
            maxArchiveFiles="2"
            concurrentWrites="false"
                    />
    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Info" writeTo="blackhole" final="true" />

    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Debug" writeTo="infofile" />
  </rules>
</nlog>
```

**What is the current result?**

internal logging :
```
2017-05-18 15:20:40.1439 Info Loading assembly: Notification.Template.Logging
2017-05-18 15:20:40.1978 Debug ScanAssembly('NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2017-05-18 15:20:40.3452 Debug Start auto loading, location: /home/wsnotif/sci-instance
2017-05-18 15:20:40.3482 Info Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll
2017-05-18 15:20:40.3482 Info Loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll
2017-05-18 15:20:40.3482 Warn Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll failed! Skipping this file. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
2017-05-18 15:20:40.4597 Info Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll
2017-05-18 15:20:40.4597 Info Loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll
2017-05-18 15:20:40.4597 Warn Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll failed! Skipping this file. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
2017-05-18 15:20:40.4597 Debug Auto loading done
```

- What is the expected result?

No warning and `NLog.Extensions.Logging.dll` should be excluded from auto loading.

- Is there a version in which it did worked? 

Beta5 didn't display these warnings, but i didn't test thoroughly if it really worked.

**Comment by 304NotModified** [comment]
Thanks for the report!  I think only an error is logged, but it does work. Am I correct?

**Comment by snakefoot** [comment]
Could it be that file permission are not setup correctly to execute code ?

**Comment by pendenaor** [comment]
Sorry for the delay.
@304NotModified yes, file logging seems to work.
@snakefoot the SO link does not seem to apply to my pb: i'm deploying on linux and all assemblies are in path.

**Comment by pendenaor** [comment]
@304NotModified is it safe to ignore the warning ?

**Comment by 304NotModified** [comment]
yes it is.

**Comment by pendenaor** [comment]
Ok, i can live with it 😃 !
Do you plan to correct this behavior before the final release ?

**Comment by 304NotModified** [comment]
yes, it's a bug :)

**Comment by 304NotModified** [comment]
@snakefoot would be nice if we could fix this for beta8, isn't it?

**Comment by 304NotModified** [comment]
https://github.com/NLog/NLog/issues/2143

has it also on Windows

**Comment by 304NotModified** [comment]
related: https://stackoverflow.com/questions/40908568/assembly-loading-in-net-core

**Comment by 304NotModified** [comment]
fixed by #2174

**Comment by 304NotModified** [comment]
thanks again @snakefoot !

**Comment by 304NotModified** [comment]
NLog beta 8 is on it's way! Online in a couple of hours!

**Comment by pendenaor** [comment]
Sorry for the delay!
Good to hear, thanks.
