### ISSUE TITLE
Email not sent while using AppDomain.CurrentDomain.UnhandledException handler

### ISSUE THREAD

**Issue by Ashish225** [NLog/NLog#2134]
Hello,

I want to configure NLog to log all exception in application, for this I found this way to do - https://stackoverflow.com/a/13896150

check out my code below

```
lass Program
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(AppDomain_CurrentDomain_UnhandledException);

            try
            {
                logger.Info("This is the first line of Main method.");
                logger.Fatal("No Exception.");
                // NLog Mail function needs time?
                Thread.Sleep(10000);
                throw new Exception("Test Exception.");
            }
            catch (Exception e)
            {
                // Mail not working.
                logger.Fatal(e.Message);
                Thread.Sleep(10000);
            }

            throw new Exception("unhandled   Exception.");

        }

        private static void AppDomain_CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            var ex = e.ExceptionObject as Exception;
            logger.Fatal(ex.Message);
        }
    }
```

**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
Mail is not sending in AppDomain_CurrentDomain_UnhandledException method
- What is the expected result?
Mail should be sent in AppDomain_CurrentDomain_UnhandledException method
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
No
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment]
Please check the internal log (trace level). Please post it here as text. Thx

**Comment by Ashish225** [comment]
Hello,

There isn't anything update in internal log, no error nothing happened to internal log.

**Comment by 304NotModified** [comment]
Then probably your config can't be found. On trace level there should be tens of lines there.

**Comment by Ashish225** [comment]
Config is found, as I am getting email for exception handled outside AppDomain_CurrentDomain_UnhandledException method, I am getting emails from AppDomain_CurrentDomain_UnhandledException method also but not always. and regarding internal log I can see every time different log in internal-log file and sometimes no log. 

Internal log content
2017-05-31 14:55:47.7769 Error Error sending mail. Exception: System.Net.Mail.SmtpException: The operation has timed out.
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NLog.Internal.MySmtpClient.NLog.Internal.ISmtpClient.Send(MailMessage )
   at NLog.Targets.MailTarget.ProcessSingleMailMessage(IList`1 events)
2017-05-31 15:00:10.3032 Error Error sending mail. Exception: System.Net.Mail.SmtpException: Failure sending mail. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Mail.SmtpConnection.Flush()
   at System.Net.Mail.ReadLinesCommand.Send(SmtpConnection conn)
   at System.Net.Mail.EHelloCommand.Send(SmtpConnection conn, String domain)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NLog.Internal.MySmtpClient.NLog.Internal.ISmtpClient.Send(MailMessage )
   at NLog.Targets.MailTarget.ProcessSingleMailMessage(IList`1 events)
2017-05-31 15:02:44.1727 Error Error sending mail. Exception: System.Net.Mail.SmtpException: The operation has timed out.
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at NLog.Internal.MySmtpClient.NLog.Internal.ISmtpClient.Send(MailMessage )
   at NLog.Targets.MailTarget.ProcessSingleMailMessage(IList`1 events)

**Comment by 304NotModified** [comment]
> Authentication failed because the remote party has closed the transport stream.

sounds like a config error!

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.
