### ISSUE TITLE
Nlog System.ArgumentException: LayoutRenderer cannot be found

### ISSUE THREAD

**Issue by StevenLiSiwei** [NLog/NLog#2215]
**Type** (choose one):
- Question

**NLog version**: (e.g. 4.2.3)

**Platform**: Net 4.5

**Current NLog config** C#

I encountered issue using NLog when I want to render asp.net related info into my database. Here is the internal logging for NLog. 

```
2017-07-16 03:08:06.5485 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=')
    2017-07-16 03:08:06.5796 Debug Start auto loading, location: 
    2017-07-16 03:08:06.5796 Debug Auto loading done
    2017-07-16 03:08:06.6036 Error Error parsing layout aspnet-request-method will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-request-method'. Is NLog.Web not included?
       at NLog.Config.Factory`2.CreateInstance(String name)
       at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
    2017-07-16 03:08:06.6115 Error Error parsing layout aspnet-request-method will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-request-method'. Is NLog.Web not included?
       at NLog.Config.Factory`2.CreateInstance(String name)
       at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
    2017-07-16 03:08:06.6115 Debug --- NLog configuration dump ---
    2017-07-16 03:08:06.6115 Debug Targets:
    2017-07-16 03:08:06.6276 Debug Rules:
    2017-07-16 03:08:06.6276 Debug logNamePattern: (:All) levels: [ Debug Info Warn Error Fatal ] appendTo: [  ]
    2017-07-16 03:08:06.6276 Debug logNamePattern: (:All) levels: [ Debug Info Warn Error Fatal ] appendTo: [  ]
    2017-07-16 03:08:06.6276 Debug --- End of NLog configuration dump ---
    2017-07-16 03:08:06.6456 Info Found 24 configuration items
    2017-07-16 03:08:06.6966 Info Found 24 configuration items
    2017-07-16 03:08:06.7085 Debug Targets for LicenseServer.Utility.Log by level:
    2017-07-16 03:08:06.7085 Debug Trace =>
    2017-07-16 03:08:06.7085 Debug Debug =>  
    2017-07-16 03:08:06.7225 Debug Info =>  
    2017-07-16 03:08:06.7225 Debug Warn =>  
    2017-07-16 03:08:06.7225 Debug Error =>  
    2017-07-16 03:08:06.7225 Debug Fatal =>  
```
I am avoiding doing configuration on xml file. so I took programmatic configuration approach. which is working fine totally except it is giving issue when I put 'aspnet-request-method' and any other aspnet related layouts. I installed NLog.Web and NLog.Extend but it is still not working. below is my code on setting up configuration :

```
public static class Log { public static Logger _logger { get; set; }

public static void Init()
{

    InternalLogger.LogFile = @"D:\Nlog.txt";
    InternalLogger.LogLevel = LogLevel.Debug;
    var config = new LoggingConfiguration();
    var db_target = new DatabaseTarget();
    db_target.DBProvider = @"MySql.Data.MySqlClient.MySqlConnection, MySql.Data";
    db_target.ConnectionString =
        $@"server={DBConfig._server};database={DBConfig._dbname};userid={DBConfig._username};password={DBConfig
            ._password};";
    db_target.DBHost = DBConfig._server;
    db_target.DBDatabase = DBConfig._dbname;
    db_target.DBUserName = DBConfig._username;
    db_target.DBDatabase = DBConfig._password;
    db_target.Co
```mmandText = @"INSERT INTO error_log(system, module, action, content) VALUES(@activityid, @request, @logger, @ip)";
    db_target.Parameters.Add(new DatabaseParameterInfo("@activityid", new NLog.Layouts.SimpleLayout("${activityid}")));
    db_target.Parameters.Add(new DatabaseParameterInfo("@request", new NLog.Layouts.SimpleLayout(@"${aspnet-request-method}")));
    db_target.Parameters.Add(new DatabaseParameterInfo("@logger", new NLog.Layouts.SimpleLayout("${logger}")));
    db_target.Parameters.Add(new DatabaseParameterInfo("@ip", new NLog.Layouts.SimpleLayout("${aspnet-request-method}")));
    db_target.KeepConnection = true;
    var rule = new LoggingRule("*", LogLevel.Debug, db_target);
    config.LoggingRules.Add(rule);
    config.LoggingRules.Add(rule);
    LogManager.Configuration = config;
    _logger = LogManager.GetCurrentClassLogger();
}
}

Please help. thanks in advanced !!.

**Comment by 304NotModified** [comment]
I think you have to register the DLLs in code, have to check that

**Comment by StevenLiSiwei** [comment]
Could you please give a detailed code on how to register NLog.Web in programmatic way. I couldn't find it on [wiki](https://github.com/NLog/NLog/wiki/Configuration-API). thanks !

**Comment by 304NotModified** [comment]
any idea why the location is empty?
https://github.com/NLog/NLog/blob/7399c9356a97c333a9aabb05600ff4bc696b50dc/src/NLog/Config/ConfigurationItemFactory.cs#L385

**Comment by 304NotModified** [comment]
what's the NLog version?

**Comment by StevenLiSiwei** [comment]
I manually removed the location for privacy purpose.

NLog version => 4.4.11
NLog.Extended version => 4.0.0.1
NLog.Web version => 4.5.0

Thanks

**Comment by 304NotModified** [comment]
is nlog.web.dll in that location?

**Comment by StevenLiSiwei** [comment]
Thanks Julian, I got NLog working. The root cause is due to my folder naming issue, so my previous directory is 'D:/Repo/C#/project_folder/project_name/bin', but Nlog can only find up to here D:\Repo. everything works like a charm when I renamed my C# folder to csharp. all issue is gone. thank you again for your patience and time.

**Comment by 304NotModified** [comment]
👍 great to hear :)
