### ISSUE TITLE
Email subject is blank when using a layout of ${event-properties}

### ISSUE THREAD

**Issue by MorganVergara** [NLog/NLog#2254]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)
4.4.12

**Platform**: 
.Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
	  autoReload="true"
	  throwExceptions="false"
	  internalLogLevel="Trace" internalLogFile="c:\NLog\NLog\nlog-internal.log">
	<targets>
		<target xsi:type="Mail" name="EmailTarget" subject="${event-properties:item=Subject}" smtpServer="server" smtpPort="25" smtpUserName="xxxxxx" smtpPassword="xxxxx" smtpAuthentication="Basic" layout="Date: ${longdate}${newline}${message}" to="xxx@yyy.com" from="zzz@foo.com"></target>
	</targets>
	<rules>
		<logger enabled="true" minlevel="Info" name="EmailLogger" writeTo="EmailTarget"/>
	</rules>
</nlog>

```
Here's the calling code:
```C#
private static readonly Logger emailLog = LogManager.GetLogger("EmailLogger");

public static void Main(string[] args)
{
	LogEventInfo emailInfo = new LogEventInfo(
		LogLevel.Info,
		"EmailLogger",
		$"The message goes here.");
	emailInfo.Properties["Subject"] = "LaunchDarkly Relay Configuration File Dropper - Run Complete";
	emailLog.Info(emailInfo);
}
```
In case of a BUG:

- What is the current result?
Email subject is empty string when using an event property value.
- What is the expected result?
Email subject should be set to value passed in as event property.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, the internal log shows the subject set to an empty string.
- Please post full exception details (message, stacktrace, inner exceptions)
There's no exception being thrown, simply not working as it should.
- Are there any work arrounds? yes/no
No workarounds.
- Is there a version in which it did worked? 
Don't know.
- Can you help us by writing an unit test?
Unfortunately, no.

**Comment by 304NotModified** [comment]
Please also post the logging call (eg c#)

**Comment by MorganVergara** [comment]
Done.  Apologies for leaving it out.

Morgan

**Comment by 304NotModified** [comment]
If you use `${event-properties:item=Subject}` in the `layout `  property, does that work?

**Comment by MorganVergara** [comment]
No, that doesn't render either.

I changed the target to:

```Xml
<target xsi:type="Mail" name="EmailTarget" subject="${event-properties:item=Subject}" smtpServer="server" smtpPort="25" smtpUserName="xxxxxx" smtpPassword="xxxxx" smtpAuthentication="Basic" layout="Date: ${longdate}${newline}${message}${newline}${event-properties:item=Subject}" to="xxx@yyy.com" from="zzz@foo.com"></target>
```

The email message contains the message text, but not the value of the Subject property.

Thanks,

Morgan

**Comment by MorganVergara** [comment]
As additional information, I tried making the To address configurable via the event properties, and it is likewise blank.  Here's the last few lines of the internal log file:

2017-08-18 16:02:56.7398 Error Error sending mail. Exception: NLog.NLogRuntimeException: After the processing of the MailTarget's 'To/Cc/Bcc' property it appears to be empty. The email message will not be sent.
   at NLog.Targets.MailTarget.CreateMailMessage(LogEventInfo lastEvent, String body)
   at NLog.Targets.MailTarget.ProcessSingleMailMessage(IList`1 events)

It appears the entire contents of the event properties collection are lost somehow.

**Comment by 304NotModified** [comment]
Could you try to log this to a file? (`${event-properties:item=Subject}`) (easier to test).

Your code looks good. I have never experienced problems with `${event-properties` and use it whole the time.

Please not that the key of the event-properties is case sensitive. But that isn't the issue here I guess

**Comment by snakefoot** [comment]
@MorganVergara Could you attach a small example project that displays the issue?

**Comment by MorganVergara** [comment]
I'll get this done as soon as I can. Apologies but work just picked up
quite a bit.

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.
