### ISSUE TITLE
Nlog 5.0.9, Mail Target doesn't replace variables. Database target, without problems, same config

### ISSUE THREAD

**Issue by frontegi** [NLog/NLog#2286]
**Type** (choose one):

- Bug

**NLog version**: 5.0.9

**Platform**:  .NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="c:\temp\internal-nlog.txt">

  <!-- Load the ASP.NET Core plugin -->
  
  
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
    <add assembly="NLog.MailKit"/>
  </extensions>

  <variable name="smtp-Server" value="localhost"/>
  <variable name="smtp-Port" value="25"/>
  <variable name="smtp-UserName" value="Nope"/>
  <variable name="smtp-Password" value="Nope"/>
  <variable name="smtp-Authentication" value="None"/>
  
  <!-- the targets to write to -->
  <targets>   

  <!-- NOT WORKING MAIL TARGET -->
    <target name="errormail"
          xsi:type="Mail"
          smtpServer="${var:smtp-Host}"
          smtpUserName="${var:smtp-UserName}"
          smtpPassword="${var:smtp-Password}"
          smtpPort="${var:smtp-Port}"
          smtpAuthentication="None"
          html="true"
          subject="${machinename} -  Alert (${shortdate:format=dd. MM. yyyy})"
          from="alert@test.com"
          to="test@test.com"
          layout="${longdate}   LEVEL=${uppercase:${level}},   LOCATION=${callsite:className=true:includeSourcePath=true:methodName=true},               
                  MESSAGE=${message}${newline} EXCEPTION=${exception:format=tostring,StackTrace}${newline}" >    
    </target>

	<!-- WORKING MAIL TARGET -->
    <!--target name="errormail"
         xsi:type="Mail"
         smtpServer="localhost"
         smtpPort="25"
         smtpUserName=""
         smtpPassword=""
         smtpAuthentication="None"
         subject="${machinename} - Alert (${shortdate:format=dd. MM. yyyy})"
         from="alert@test.com"
         to="test@test.com"
         layout="${longdate}   LEVEL=${uppercase:${level}},   LOCATION=${callsite:className=true:includeSourcePath=true:methodName=true},               
                  MESSAGE=${message}${newline} EXCEPTION=${exception:format=tostring,StackTrace}${newline}" /-->
    
      
      <target name="database" xsi:type="Database" >
        

    <connectionString>${var:connectionString}</connectionString>

          <commandText>
              insert into dbo.Log (
              UserEmail,
              Application, 
              Logged, 
              Level, 
              Message,
              Logger, 
              CallSite, 
              Exception,
              ThreadId
              ) values (
              @useremail,
              @Application, 
              @Logged, 
              @Level, 
              @Message,
              @Logger, 
              @Callsite, 
              @Exception,
              @ThreadId
              );
          </commandText>

          <parameter name="@application" layout="AspNetCoreNlog" />
          <parameter name="@useremail" layout="${aspnet-user-identity}" />
          <parameter name="@logged" layout="${date}" />
          <parameter name="@level" layout="${level}" />
          <parameter name="@message" layout="url: ${aspnet-request-url} | action: ${aspnet-mvc-action} | ${message}" />
          
          <parameter name="@logger" layout="${logger}" />
          <parameter name="@callSite" layout="${callsite:filename=true}" />
          <parameter name="@exception" layout="${exception:tostring}" />
        <parameter name="@threadid" layout="${threadid}" />
      </target>
  
  
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>

    <logger name="*" minlevel="Error" writeTo="errormail" />

    <logger name="*" minlevel="Trace" writeTo="allfile" />   

    <logger name="*" minlevel="Debug" writeTo="database" >    
    </logger>
  
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
I'd like to receive a mail alert when an Error occur.
I have a working Database Target with Connection String that is set from the Asp.Net Core Startup.cs.
My Startup.cs Section is 

```
  LogManager.Configuration.Variables["connectionString"] = Configuration.GetConnectionString("DefaultConnection");
            LogManager.Configuration.Variables["configDir"] = "nlog";
            LogManager.Configuration.Variables["smtp-Server"] = Configuration["MailMan:SMTPLogger:Host"];
            LogManager.Configuration.Variables["smtp-Port"] = Configuration["MailMan:SMTPLogger:Port"];
            LogManager.Configuration.Variables["smtp-UserName"] = Configuration["MailMan:SMTPLogger:Username"];
            LogManager.Configuration.Variables["smtp-Password"] = Configuration["MailMan:SMTPLogger:Password"];
            LogManager.Configuration.Variables["smtp-Authentication"] = Configuration["MailMan:SMTPLogger:Authentication"];
LogManager.ReconfigExistingLoggers();
```

In the config I placed the two version of mail Target.
The one, working, with hardcoded values, and the second with variables.
Mail are not sent, found errors in Internal Log

- What is the expected result?
Mail Sent
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
YES,
- Please post full exception details (message, stacktrace, inner exceptions)
The one, with variables, fail:

```
2017-09-20 00:37:25.6514 Warn Error when setting '${var:smtp-Port}' on attibute 'smtpPort'
2017-09-20 00:37:25.6514 Error Parsing configuration from C:\TFS\ChiaraMente\ChiaraMente\nlog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\TFS\ChiaraMente\ChiaraMente\nlog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'SmtpPort' on Mail Target[errormail] ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```
It seems to me that variables are not replaced.
I tried to set the smtpPort as a tag inside the Target `<smtpPort>${var:smtp-Port}</smtpPort> `with the same result.

- Are there any work arounds? 
Tried, not found
- Is there a version in which it did worked? 
Don't know
- Can you help us by writing an unit test?
No,Sorry

**Comment by snakefoot** [comment]
Have you checked that platform support for NLog 5.0, and whether it includes mail-target for Net Core?

https://github.com/NLog/NLog/wiki/Platform-Support

Maybe you want to checkout:

https://www.nuget.org/packages/NLog.MailKit/

**Comment by frontegi** [comment]
Hi Rolf, if you take a look at the config, I included MailKit Assembly, and I'm able to send email when the settings are hard-coded.
So my Nlog 5 send mail, but not If I try to set variables from Startup.cs . 
However, another variable related to another Target, work seamlessly.

**Comment by 304NotModified** [comment]
This is unfortunate how it works. Only the parameters that are of type `Layout` are layoutable. See https://github.com/NLog/NLog/wiki/Mail-Target.

See #1234 

As work around:

- use variables, like `${smtp-Port}` (but you can't change them in code), or
- use the .NET API, e.g. get the mailTarget and change the config

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by frontegi** [comment]
Hi Julian, I managed to do it programmatically into Startup.cs, Configure Method.
It's not optimal, but it works.

posting the code in case someone else need a similar solution:
```
MailTarget mailTarget = new MailTarget("errormail");
            mailTarget.SmtpServer = Configuration["MailMan:SMTPLogger:Host"];
            mailTarget.SmtpPort = Convert.ToInt32(Configuration["MailMan:SMTPLogger:Port"]);
            mailTarget.SmtpUserName = Configuration["MailMan:SMTPLogger:Username"];
            mailTarget.SmtpPassword = Configuration["MailMan:SMTPLogger:Password"];
            mailTarget.Html = true;
            mailTarget.Subject = "${machinename} - Chiarissimo Alert (${shortdate:format=dd. MM. yyyy})";
            mailTarget.From = "alert@mydomain.com";
            mailTarget.To = "destination@gmail.com";
            mailTarget.Layout = "${longdate}<br>USER=${aspnet-User-Identity}" +
                "<br>LEVEL=${uppercase:${level}}" +
                "<br>URL=${aspnet-Request-Url}" +
                "<br>LOCATION=${callsite:className=true:includeSourcePath=true:methodName=true}" +
                "<br>HOST=${aspnet-Request-Host}" +
                "<br>MESSAGE=${message}${newline}" +
                "<br>EXCEPTION=${exception:format=tostring,StackTrace}${newline}";
                        switch (Configuration["MailMan:SMTPLogger:Authentication"].ToUpper())
            {
                
                case "BASIC":
                    mailTarget.SmtpAuthentication = NLog.Targets.SmtpAuthenticationMode.Basic;
                    break;
                case "NTLM":
                    mailTarget.SmtpAuthentication = NLog.Targets.SmtpAuthenticationMode.Ntlm;
                    break;
                case "NONE":
                default:
                    mailTarget.SmtpAuthentication = NLog.Targets.SmtpAuthenticationMode.None;
                    break;
            }
                        
            LogManager.Configuration.AddTarget("errormail",mailTarget);
            var rule = new LoggingRule("*", NLog.LogLevel.Error, mailTarget);
            LogManager.Configuration.LoggingRules.Add(rule);

            LogManager.ReconfigExistingLoggers();
```

**Comment by 304NotModified** [comment]
Thanks for the feedback!

**Comment by pr0gg3r** [comment]
> 
> 
> This is unfortunate how it works. Only the parameters that are of type `Layout` are layoutable. See https://github.com/NLog/NLog/wiki/Mail-Target.
> 
> See #1234
> 
> As work around:
> 
>     * use variables, like `${smtp-Port}` (but you can't change them in code), or
> 
>     * use the .NET API, e.g. get the mailTarget and change the config

There is a third option, a workaround I used for database targets connection strings. Setting connectionString for target also does not work with LogManager.Configuration.Variables. So I used a workaround with temporary environment variables:
```
<target xsi:type="Database" name="tDatabase"
            dbProvider="Microsoft.Data.Sqlite.SqliteConnection, Microsoft.Data.Sqlite"
            connectionString="Data Source =.\${environment:DATABASE_FILE_NAME};"
            commandText="INSERT INTO ...">
      <parameter name="@MachineName" layout="${machinename}" />
      ...
</target>
```
So you just use ${environment:DATABASE_FILE_NAME} and
`Environment.SetEnvironmentVariable("DATABASE_FILE_NAME", "foo.log");`
instead of ${var:DATABASE_FILE_NAME} and
`NLog.LogManager.Configuration.Variables["DATABASE_FILE_NAME"] =  "foo.log";`

**Comment by snakefoot** [comment]
Created #4435 to resolve this for NLog 5.0
