### ISSUE TITLE
Compressed archives contain incomplete log files when used in multiprocess environment

### ISSUE THREAD

**Issue by robfr** [NLog/NLog#2296]
**Type** (choose one):

- Bug

**NLog version**: (e.g. 5.0.0-beta11)

**Platform**: ASP.NET using .Net 4.5 and a worker pool with a maximum of 3 processes. 

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
    <variable name="EventLogsFolder" value="D:\" />

  <targets>
        <target name="FileTarget"
                xsi:type="AsyncWrapper"
                overflowAction="Grow" >
            <target xsi:type="File"
                    fileName="${var:EventLogsFolder}\Events.log"
                    layout="${message}"
                    encoding="UTF-8"
                    keepFileOpen="true"
                    openFileCacheTimeout="10"
                    concurrentWrites="true"
                    autoFlush="true"
                    createDirs="true"
                    archiveEvery="Minute"
                    archiveFileName="${var:EventLogsFolder}\archives\Events-{#}.zip"
                    archiveNumbering="Date"
                    archiveDateFormat="yyyy.MM.ddTHH.mm"
                    enableArchiveFileCompression="true"
                    maxArchiveFiles="60" />
  </targets>
  <rules>
        <logger name="*" minlevel="Info" writeTo="FileTarget" />
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
Running an ASP.NET site that is serving between 50 and 100 requests per second, using 2/3 worker pool processes we are encountering errors on nightly file rotation and archivage. Some times the archive file is much smaller (containing 5 or 10 logs for an entire day) than expected and the rest of the data logged for the day is missing.

The problem can be reproduced easily using a benchmark tool to hit the site with higher traffic and switching to a "minute-ly" file rotation+archivage.

- What is the expected result?
Previous similar bugs have been closed/fixed which would leave me to believe that multiple processes /can/ write to the same file and have rotation+archiage function properly.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? yes

- Please post full exception details (message, stacktrace, inner exceptions)
[NLog.log](https://github.com/NLog/NLog/files/1339068/NLog.log)

```
2017-09-28 02:16:59.5190 Info Archiving D:\EventLogs\Events.log to compressed D:\EventLogs\archives\Events-2017.09.28T02.09.zip
2017-09-28 02:16:59.5500 Info Archiving D:\EventLogs\Events.log to compressed D:\EventLogs\archives\Events-2017.09.28T02.09.zip
2017-09-28 02:16:59.5500 Warn Failed to archive file 'D:\EventLogs\Events.log'. Exception: System.IO.IOException: The process cannot acc
ess the file 'D:\EventLogs\archives\Events-2017.09.28T02.09.zip' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 b
ufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost
)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options,
String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at NLog.Targets.ZipArchiveFileCompressor.CompressFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
2017-09-28 02:16:59.5500 Error AsyncWrapper 'FileTarget': Error in lazy writer timer procedure. Exception: System.IO.IOException: The pr
ocess cannot access the file 'D:\EventLogs\archives\Events-2017.09.28T02.09.zip' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 b
ufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost
)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options,
String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at NLog.Targets.ZipArchiveFileCompressor.CompressFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, ArraySegment`1 bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, Exception& las
tException)
   at NLog.Targets.FileTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.WriteEventsInQueue(Int32 batchSize, String reason)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)
```

- Are there any work arounds?
No
- Is there a version in which it did worked?
No
- Can you help us by writing an unit test?
Not sure a unit test applies here.

**Comment by snakefoot** [comment]
Its is going to be difficult to solve this one. Multi-Process/AppDomain file logging and archive logic doesn't work well with `keepFileOpen="true"`. With or without compression, because moving/deleting files while other having open file handles is difficult.

**Comment by 304NotModified** [comment]
Or just `keepFileOpen="false"`

**Comment by snakefoot** [comment]
> Or just keepFileOpen="false"

Super bad performance that will generate a huge overhead. Instead much better to have an external scheduled task to performance the compression.

**Comment by snakefoot** [comment]
Closing as not top priority. Pull requests are ofcourse welcome. See also: https://github.com/NLog/NLog/issues/3711#issuecomment-559604944
