### ISSUE TITLE
Issue with archiving when archiveFileName contains variable

### ISSUE THREAD

**Issue by plaes** [NLog/NLog#2330]
**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.4.12)

**Platform**: ..Net 4.0

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="debug"
      internalLogToConsole="true"
  >
  <variable name="basedir" value="${basedir}" />
  <targets async="true">
    <target name="test_log_file" xsi:type="File"
            fileName="${var:basedir}\test.txt"
            layout="${longdate}|${message} ${exception:format=tostring}"
            archiveFileName="{var:basedir}\archives\test.{#}.txt"
            archiveNumbering="Date"
            archiveEvery="Day"
            archiveDateFormat="yyyyMMdd"
    />
  </targets>
  <rules>
    <logger name="test_logger" minLevel="Info" writeTo="test_log_file"/>
  </rules>
</nlog>
```

In case of a BUG:

- What is the current result? Archive files are not created
- What is the expected result? Archive files are created
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes :)
- Please post full exception details (message, stacktrace, inner exceptions)
```
2017-10-10 11:52:46.5894 Warn Failed to archive file 'C:\full-path-to\test.txt'. Exception: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
2017-10-10 11:52:46.6094 Debug Creating file appender: C:\full-path-to\test.txt
```

- Are there any work arrounds? not that I know
- Is there a version in which it did worked?  no
- Can you help us by writing an unit test?
Powershell example:
```powershell
function main {
    ## Create existing file...
    $file = "{0}\test.txt" -f $pwd
    "Hello World" | Set-Content $file
    ## ...and modify its change and creation times
    $f = Get-Item $file
    $f.CreationTime = (get-date).AddDays(-2)
    $f.LastWriteTime = (get-date).AddDays(-2)

    # Set up logging
    [Reflection.Assembly]::LoadFile("$pwd\NLog.dll") | Out-Null
    # Load configuration XML
    $cfg = New-Object NLog.Config.XmlLoggingConfiguration("$pwd\NLogTest.config")

    # XXX: Override the $basedir variable value
    # https://github.com/NLog/NLog/issues/2231
    $cfg.Variables.basedir.Text = $pwd

    # Initialize configuration
    ([NLog.LogManager]::Configuration) = $cfg
    $global:logger = [NLog.LogManager]::GetLogger("test_logger")

    $logger.Info('Script started...')

    $logger.Info('Script finished...')
}
```

**Comment by 304NotModified** [comment]
it should be `${var:basedir}` and not `{var:basedir}`

in (` archiveFileName="{var:basedir}\archives\test.{#}.txt"`)

**Comment by plaes** [comment]
Thanks for spotting the typo :1st_place_medal:
