### ISSUE TITLE
Appsetting layout renderer not found with NLog.Extended

### ISSUE THREAD

**Issue by Kelvin0395** [NLog/NLog#2367]
**Type :** Question
**NLog version:** 5.0-beta11
**Nlog.Extended:** 4.5.0-beta07
**Platform:** .Net 4.6

I am trying to get the file path for the targets from the App.Config file with the appsetting-layout from the NLog.Extended package. No matter what I have tried, nothing seems to work and I am stuck now. Any help or more documentations with this problem?

**Current NLog config**
`<variable name="exceptionLogFilePath" value="${appsetting:name=ExceptionLogfilePath:default=d:\Logs\logger-exception.log}"/>
`
Have used several variations on the nlog config line.

**App.Config**
`
    <add key="ExceptionLogfilePath" value="d:\logs\Logger_Exception.log" />
`

**Internal Log error **
```Error Error parsing layout appsetting will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'appsetting'   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)```

**Comment by 304NotModified** [comment]
Please try with NLog 4.5 beta. That should work!

**Comment by Kelvin0395** [comment]
Will try it right now!

What is the mayor difference between Nlog 5.0 and 4.5? Will I notice a difference? (Except for the Extended to work)

**Comment by Kelvin0395** [comment]
I have used NLog 4.5 beta and the resp. Nlog.Extended. But it is still giving me the same error. Which is the layout renderer appsetting is not found.

**Log message**
```Warn Error when setting property 'FileName' on 'File Target[allFile]' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'appsetting'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)```

What am I doing wrong?
I have got both of the packages and the config file. Both are also referenced.

**Comment by 304NotModified** [comment]
Could you please try it without `<variable `?

NLog 4.5 is the version that support .net standard, without breaking changes.

**Comment by Kelvin0395** [comment]
I have completely simplified the config file so it only has one target which uses the appsetting and no use of variable, but still the same error.

**Full config file**
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace" internalLogFile="d:\logs\nlog-internal.log">

  <targets>

    <!--To Do: Change temp path to variable-->
    <target xsi:type="File" name="allFile" fileName="${appsetting:name=StandardLogFilePath}"/>
   </targets>

  <rules>
    <logger name="*" writeTo="allFile"/>
   </rules>
</nlog>



```
**Full Internal log**
```
2017-10-25 08:49:46.1603 Info Message Template Auto Format enabled
2017-10-25 08:49:46.1759 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-10-25 08:49:46.1759 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-10-25 08:49:46.1759 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-10-25 08:49:46.1857 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2017-10-25 08:49:46.1857 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-10-25 08:49:46.1857 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-10-25 08:49:46.1857 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-10-25 08:49:46.1857 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-10-25 08:49:46.1857 Trace  Scanning Property Culture '' System.Globalization
2017-10-25 08:49:46.1857 Trace  Scanning Property Inner '''' NLog.Layouts
2017-10-25 08:49:46.1857 Trace  Scanning SimpleLayout ''''
2017-10-25 08:49:46.1857 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-10-25 08:49:46.1857 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-10-25 08:49:46.1857 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-10-25 08:49:46.1857 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-10-25 08:49:46.1857 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-10-25 08:49:46.1857 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-10-25 08:49:46.1857 Debug Setting 'FileTarget.name' to 'allFile'
2017-10-25 08:49:46.1857 Debug Setting 'FileTarget.fileName' to '${appsetting:name=StandardLogFilePath}'
2017-10-25 08:49:46.2032 Warn Error when setting property 'FileName' on 'File Target[allFile]' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'appsetting'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
2017-10-25 08:49:46.2032 Warn Error when setting '${appsetting:name=StandardLogFilePath}' on attibute 'fileName'
2017-10-25 08:49:46.2032 Error Parsing configuration from D:\Git\Bas.Diagnostics.StructuredLogger\Dev\Impl\Diagnostics.StructuredLogger\StructuredLogger.Tests\bin\Debug\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing D:\Git\Bas.Diagnostics.StructuredLogger\Dev\Impl\Diagnostics.StructuredLogger\StructuredLogger.Tests\bin\Debug\NLog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'FileName' on File Target[allFile] ---> System.ArgumentException: LayoutRenderer cannot be found: 'appsetting'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```

**Comment by Kelvin0395** [comment]
I have gotten a way to get it to work.
The problem was that I use an wrapper project for NLog which contains the project and the references. The other project which references the wrapper and uses it does not automatically copy/get the Nlog.Extended package since the package does not explicitly get used in the wrapper project. Manually placing the Nlog.extended.dll in the debug folder resolved the issue.

Now I will probably have to set a dependency manually somewhere in order to get it to work automatically. but at least we can go on.

**Comment by 304NotModified** [comment]
Ah that's makes things more clear. 

Another option is to load manually nlog.extended with the `<extension ` in the config.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by idreeshaddad** [comment]
I have NLog 4.5.9, and adding:

```
<extensions>
    <add assembly="NLog.Extended"/>
</extensions>

```
to app config did not copy the DLL to bin folder.

**Comment by 304NotModified** [comment]
no that's is for loading the dll. The dll should be in your bin folder for that. The latter is dependent of you Visual Studio project settings  and how you installed NLog.Extended

**Comment by idreeshaddad** [comment]
> no that's is for loading the dll. The dll should be in your bin folder for that. The latter is dependent of you Visual Studio project settings and how you installed NLog.Extended

I installed it through NuGet just like I installed NLog.

I have NLog in an infrastructure project that is referenced in the Web project.
I can see in the web bin the NLog.dll, but not the NLog.Extended!

Any Ideas?

**Comment by 304NotModified** [comment]
You need "CopyToOutputDirectory" option, it depends of your csproj format

**Comment by idreeshaddad** [comment]
> CopyToOutputDirectory

Isn't CopyToOutputDirectory for project files, and not references?
In VS dlls I have "Copy Local" property, and setting it to True didn't copy the file.

I believe the problem is that, although, NLog.Extended is referenced in Logger project, it is not used in the code, so it will not copy to target project bin folder.

So either I:
1- Put dummy code in Logger project.
2- Reference NLog.Extended in Web project.
3- Copy the DLL with a post build event -> I think I will go with this option for now.

**Comment by 304NotModified** [comment]
I would recommend to install the NLog.Extended in your webproject.  I think that's option 2
