### ISSUE TITLE
System.OutOfMemoryException on NLog(v4.4.12) which causes our application crash

### ISSUE THREAD

**Issue by younsol** [NLog/NLog#2379]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug

**NLog version**: 4.4.12

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="http://builder2:20202/schemas/NLog.xsd"
      throwExceptions="true"
      autoReload="true">
    <variable name="logDirectory" value="${basedir}/logs/" />

    <!-- Console -->
    <targets async="true">
        <target name="console" xsi:type="ColoredConsole" useDefaultRowHighlightingRules="true">
            <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false" quoting="Nothing">
                <column name="datetime" layout="${longdate}" />
                <column name="level" layout="${level:uppercase=true}" />
                <column name="logger" layout="${logger}" />
                <column name="message" layout="${message}" />
            </layout>
        </target>
    </targets>

    <!-- Async File -->
    <targets>
        <default-wrapper xsi:type="AsyncWrapper" overflowAction="Block" batchSize="10000" />
        <default-target-parameters xsi:type="File" encoding="utf-8">
            <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false" quoting="Nothing">
                <column name="datetime" layout="${longdate}" />
                <column name="level" layout="${level:uppercase=true}" />
                <column name="logger" layout="${logger}" />
                <column name="message" layout="${message}" />
            </layout>
        </default-target-parameters>

        <target name="gameLogFile" xsi:type="File" fileName="${logDirectory}GameLog${date:format=yyyyMMddHH}.tlg" />
        <target name="serverLogFile" xsi:type="File" fileName="${logDirectory}ServerLog${date:format=yyyyMMddHH}.tlg" />

        <target name="chatTraceFile" xsi:type="File" fileName="${logDirectory}ChatTrace${date:format=yyyyMMddHH}.tlg" />

        <target name="debugFile" xsi:type="File" fileName="${logDirectory}TozDebug${date:format=yyyyMMddHH}.tlg" />
        <target name="errorFile" xsi:type="File" fileName="${logDirectory}TozError${date:format=yyyyMMddHH}.tlg" />
        <target name="unhandledFile" xsi:type="File" fileName="${logDirectory}Unhandled${date:format=yyyyMMddHH}.tlg" />
    </targets>

    <!-- Non-async File -->
    <targets>
        <target name="fatalFile" xsi:type="File" encoding="utf-8" fileName="${logDirectory}TozFatal${date:format=yyyyMMddHH}.tlg">
            <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false" quoting="Nothing">
                <column name="datetime" layout="${longdate}" />
                <column name="level" layout="${level:uppercase=true}" />
                <column name="logger" layout="${logger}" />
                <column name="message" layout="${message}" />
            </layout>
        </target>
    </targets>

    <!-- Buffering Mail -->
    <targets>
        <default-wrapper xsi:type="BufferingWrapper" slidingTimeout="false" bufferSize="10000" flushTimeout="900000" />
        <default-target-parameters xsi:type="Mail" encoding="utf-8" smtpServer="127.0.0.1" smtpPort="25" enableSsl="false"
                subject="[TozErrors] ${level} Log Occurred - ${machinename}" from="pbstoz@nexon-red.com" to="PBS-Server-Workgroup@nexon-red.com" addNewLines="true">
            <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false" quoting="Nothing">
                <column name="datetime" layout="${longdate}" />
                <column name="level" layout="${level:uppercase=true}" />
                <column name="logger" layout="${logger}" />
                <column name="message" layout="${message}" />
            </layout>
        </default-target-parameters>
        <target name="errorMail" xsi:type="Mail" />
        <target name="fatalMail" xsi:type="Mail" />
    </targets>

    <!-- Non-buffering Mail -->
    <targets>
        <target name="crashMail" xsi:type="Mail" encoding="utf-8" smtpServer="127.0.0.1" smtpPort="25" enableSsl="false"
                subject="[TozCrash] Server Crash - ${machinename}" from="pbstoz@nexon-red.com" to="PBS-Server-Workgroup@nexon-red.com" addNewLines="true">
            <layout xsi:type="CsvLayout" delimiter="Tab" withHeader="false" quoting="Nothing">
                <column name="datetime" layout="${longdate}" />
                <column name="level" layout="${level:uppercase=true}" />
                <column name="logger" layout="${logger}" />
                <column name="message" layout="${message}" />
            </layout>
        </target>
    </targets>

    <rules>
        <logger name="*" writeTo="console" />

        <logger name="*" level="Error" writeTo="errorMail" />
        <logger name="*" level="Fatal" writeTo="fatalMail" />

        <logger name="HackChecker_*" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="Stage_Join" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="Stage_Start" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="Stage_End" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="User_Login" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="User_Logout" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="MatchMake_Normal" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="MatchMake_ClanParty" level="Info" writeTo="gameLogFile" final="true" />
        <logger name="EventOnTime_Missed" level="Info" writeTo="gameLogFile" final="true" />

        <logger name="Statistics_*" level="Info" writeTo="serverLogFile" final="true" />
        <logger name="UserNum_Lobby" level="Info" writeTo="serverLogFile" final="true" />
        <logger name="UserNum_Battle" level="Info" writeTo="serverLogFile" final="true" />

        <logger name="ChatLogger" writeTo="chatTraceFile" final="true" />

        <logger name="*" minlevel="Trace" maxlevel="Debug" writeTo="debugFile" />
        <logger name="*" minlevel="Warn" maxlevel="Error" writeTo="errorFile" />
        <logger name="*" level="Fatal" writeTo="fatalFile" />
        <logger name="*" level="Info" writeTo="unhandledFile" />

        <logger name="Crash" level="Fatal" writeTo="crashMail" />
    </rules>
    <extensions />
</nlog>

```

In case of a BUG:

**What is the current result?**
- out of memory exception occured

**What is the expected result?**
- No out of memory issue from Logger and application must smoothly work with logger.

**Did you checked the Internal log?**
- Not yet..

**Please post full exception details (message, stacktrace, inner exceptions)**
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
    at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
    at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes, Int32 offset, Int32 count)
    at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, ArraySegment`1 bytes, Boolean justData)
    at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, ArraySegment`1 bytesToWrite)
    at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, Exception& lastException)
    at NLog.Targets.FileTarget.Write(IList`1 logEvents)
    at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
    at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
    at NLog.Targets.Wrappers.AsyncTargetWrapper.WriteEventsInQueue(Int32 batchSize, String reason)
    at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)
    at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.TimerQueueTimer.CallCallback()
    at System.Threading.TimerQueueTimer.Fire()
    at System.Threading.TimerQueue.FireNextTimers()
    at System.Threading.TimerQueue.AppDomainTimerCallback()
```
**Are there any work arrounds?** yes
- We change the value of overflowAction to "Grow" and stare on..

Each GameLog~.tlg file size is about to 150MB,
also each TozDebug~.tlg file size is about to 150MB,
and other log files have very small size compare with those 2 files.

The log files are concurrently read on another process.

**Comment by younsol** [comment]
Wrong report....
the issue is on our application's build setting...
we miss the setting "<Prefer32Bit>false</Prefer32Bit>"

**Comment by snakefoot** [comment]
@younsol You should add timeToSleepBetweenBatches="0" to the default async-wrapper:

`<default-wrapper xsi:type="AsyncWrapper" overflowAction="Block" batchSize="10000" timeToSleepBetweenBatches="0" />`

@younsol You should add keepFileOpen to the default file-target-parameters:

`<default-target-parameters xsi:type="File" encoding="utf-8" keepFileOpen="true">`

See also https://github.com/NLog/NLog/wiki/Performance#file-logging-performance
