### ISSUE TITLE
Archiving Logs in Multi-IIS-W3WP scenario does not work

### ISSUE THREAD

**Issue by occcy** [NLog/NLog#2383]
Type: Bug
NLog version: 4.4.12
Platform: .Net 4.5.2

Current config (snippet):
```
        <target xsi:type="File"
                name="FileTarget"
                fileName="c:\data\mylog.log"
                concurrentWrites="true"
                keepFileOpen="true"
                autoFlush="true"
                archiveEvery="Day"
                maxArchiveFiles="25"
                archiveFileName="c:\data\mylog-${date:format=yyyy-MM-dd-HH-mm}.log" />
```
Application Setting:
* Microsoft IIS Version 10.0
* Web Application spawns multiple worker processes
* All worker processes share single log-file
* User permissions are sufficient (sucessfully testet with one worker process)

Result:
* Archive file was not created
* NLOG Internal Log-File reports:
2017-11-07 01:46:03.1440 Info Archiving c:\data\mylog.log to c:\data\mylog-2017-11-07-01-46.51.log
2017-11-07 01:46:04.2379 Error Cannot archive file 'c:\data\mylog.log'. Exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.DynamicFileArchive.AddToArchive(String archiveFileName, String fileName, Boolean createDirectory)
2017-11-07 01:46:04.2533 Warn Failed to archive file 'c:\data\mylog.log'. Exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.DynamicFileArchive.AddToArchive(String archiveFileName, String fileName, Boolean createDirectory)
   at NLog.Targets.FileTarget.DynamicFileArchive.Archive(String archiveFileName, String fileName, Boolean createDirectory)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
* This behavior shows every time an existing log must be archived.

Remarks:
* Archiving works as expected in single worker process configuration
* Logging into log-file from multiple processes works as expected

**Comment by 304NotModified** [comment]
I think `  keepFileOpen="true"` won't working with archiving and multi threading.

**Comment by occcy** [comment]
It seems so that this solves my problem.
Thanks for the fast feedback!

**Comment by snakefoot** [comment]
@occcy Could you try this setup, and see if you also get UnauthorizedAccessException ?

```
    fileName="c:\data\mylog.log"
    archiveFileName="c:\data\mylog-{#}.log"
    archiveDateFormat="yyyy-MM-dd"
    archiveNumbering="Date"
    archiveEvery="Day"
    maxArchiveFiles="25"
    concurrentWrites="true"
    keepFileOpen="true"
    autoFlush="true"
```

It is a really bad idea to use `keepFileOpen="true"`, if you are logging more than 50 messages/sec. So if the above fails, then I recommend the following config:

```
    fileName="c:\data\mylog-${date:format=yyyy-MM-dd}.log"
    archiveFileName="c:\data\mylog-{#}.log"
    archiveDateFormat="yyyy-MM-dd"
    archiveNumbering="Date"
    archiveEvery="Year"
    maxArchiveFiles="25"
    concurrentWrites="true"
    keepFileOpen="true"
    autoFlush="true"
```

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
