### ISSUE TITLE
GetTargetsByLevelForLogger - LoggingConfiguration.LoggingRules is not thread safe

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2393]
```
[xUnit.net 00:00:27.8269283]       System.AggregateException : One or more errors occurred. (Destination array was not long enough. Check the destination index, length, and the array's lower bounds.
[xUnit.net 00:00:27.8270756]       Parameter name: destinationArray)
[xUnit.net 00:00:27.8312139]         ----- Inner Stack Trace -----
[xUnit.net 00:00:27.8312708]            at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
[xUnit.net 00:00:27.8313274]            at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[xUnit.net 00:00:27.8313899]         /home/travis/build/NLog/NLog/src/NLog/LogFactory.cs(855,0): at NLog.LogFactory.GetTargetsByLevelForLogger(String name, IEnumerable`1 rules, TargetWithFilterChain[] targetsByLevel, TargetWithFilterChain[] lastTargetsByLevel, Boolean[] suppressedLevels)
[xUnit.net 00:00:27.8314531]         /home/travis/build/NLog/NLog/src/NLog/LogFactory.cs(914,0): at NLog.LogFactory.GetConfigurationForLogger(String name, LoggingConfiguration configuration)
[xUnit.net 00:00:27.8315153]         /home/travis/build/NLog/NLog/src/NLog/LogFactory.cs(1218,0): at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
[xUnit.net 00:00:27.8315640]         /home/travis/build/NLog/NLog/tests/NLog.UnitTests/LogManagerTests.cs(572,0): at NLog.UnitTests.LogManagerTests.<>c__DisplayClass25_0.<ThreadSafe_getCurrentClassLogger_test>b__2(Int32 e)
[xUnit.net 00:00:27.8316180]            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
[xUnit.net 00:00:27.8316537]         --- End of stack trace from previous location where exception was thrown ---
```

https://travis-ci.org/NLog/NLog/builds/303097933?utm_source=github_status&utm_medium=notification

**Comment by 304NotModified** [comment]
guess we need a `lock`, ins't?
