### ISSUE TITLE
Concurrent write exception

### ISSUE THREAD

**Issue by OlinCamber** [NLog/NLog#2494]
Hi,

I'm currently sometimes gettings the following error:

```
process cannot access the file because it is being used by another process. (Exception de HRESULT : 0x80070020)":null

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NLog.Internal.FileAppenders.BaseFileAppender.WindowsCreateFile(String fileName, Boolean allowFileSharedWriting)
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting)
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.Log(LogEventInfo logEvent)
   at Echosens.Fibroscan.Log.Log.CallLogger(Logger log, LogEventInfo logEvent, FbCategory category, FibroscanLogFile 
```

My program is working with **Nlog 4.3.11**.  Theorically the log is not supposed to be opened by several processes.
My software is the only one to write to this file.

I've attached my nlog config file.
[NLog.zip](https://github.com/NLog/NLog/files/1614431/NLog.zip)

After some investigation, could it be related to fast stop and start of my software which uses this log ?
Is there a way to avoid this error ?

Thanks in advance for the help

**Comment by snakefoot** [comment]
@OlinCamber Any reason why you have configured `ConcurrentWrites="false"` for the first two file-targets?

When having `ConcurrentWrites="true"` and then it will actually retry the open-file call 10 times (ConcurrentWriteAttempts), each time doubling the sleep time (ConcurrentWriteAttemptDelay)

If you want to ensure only one instance of your application is running, then you could create your own global mutex during program initialization, and use it for waiting for any zombie instances to disappear before allowing application to continue startup.

Can see that you have correctly configured `ThrowExceptions="false"` (Default - Setting to "true" should never be done in production, but only for unit testing), so I guess you have caught this exception in the debugger, and the application just goes on without stopping? (Because WriteAsyncThreadSafe has a catch all that should swallow the exception)

**Comment by OlinCamber** [comment]
Hi @snakefoot 

I've configured the ConcurrentWrites="false"  for the Two first file-targets because they are supposed to be used by my software only. The software already have a check for unique instance management and it do not detect several instances of my software.(I've checked with an external software too)

Indeed I've this exception when I'm working in debug (with ThrowExceptions="true")
but I do not understand why I'm stroke by this issue.

Have you any leads ? Could it be related to Visual Studio Debugger? (vshost, ... )?
I'm still investigating but I haven't any new clue.

**Comment by snakefoot** [comment]
> @OlinCamber Have you any leads ? Could it be related to Visual Studio Debugger?

No idea. I guess it could be possible that Visual Studio has a dangling debugging-host-engine.

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by OlinCamber** [comment]
Hi sorry for the lack of news.
I've found the issue. A archiving mechanism has been added at the startup of the software. The file was locked by a zipping action but the zip was not handled correctly...
So no bug here.
Sorry  and thanks for the help!

**Comment by 304NotModified** [comment]
OK thanks for the feedback!
