### ISSUE TITLE
Issues with aspnetbuffer and autofac

### ISSUE THREAD

**Issue by dyardyGIT** [NLog/NLog#2556]
Problem: does this wrapper work?

https://github.com/NLog/NLog/wiki/AspNetBufferingWrapper-target

- Question
Using this target (below) on iis7+, and mvc I am trying to have 1 email sent instead of multiple.

Do I need to add any additional nuget packages for this target?
Do I need to put anything in the web.config?
At the current time, I get 1 email for every logger.info('message') i send.

thx

    <target xsi:type="AspNetBufferingWrapper"
         name="bufferedmailbyrequest"      
         growBufferAsNeeded="true"
            bufferSize="100">

      <target name="mail" xsi:type="Mail"
          smtpServer="test.test.COM"
          smtpPort="25"
          skipCertificateValidation="true"
          enableSsl="false"
          from="noreply@test.com"
          to="test@test.com"
          cc=""
          layout="${longdate}   LEVEL=${uppercase:${level}},   LOCATION=${callsite:className=true:includeSourcePath=true:methodName=true}, MESSAGE=${message}${newline} EXCEPTION=${exception:format=tostring,StackTrace}${newline}" 
          html="true"
          subject="test Log"                
        />
    </target>

**Comment by snakefoot** [comment]
It should only send one email for each web-request (As you can read from documentation).

It should be included in this nuget-package: https://www.nuget.org/packages/NLog.Web 

You can try and enable the [InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) to investigate any unexpected behavior.

If you want buffering of messages across web-requests, then you might want to use this instead: https://github.com/nlog/NLog/wiki/BufferingWrapper-target

**Comment by snakefoot** [comment]
AspNetBufferingWrapper will only work if it can find a `HttpContext.Current`, so if using `async=true` or other wrappers, then it will not work.

**Comment by dyardyGIT** [comment]
I am not using any other wrappers as shown above.

Yes, with internal logging turned on i see this "ASP.NET request buffer does not exist" and looking in the code.
This is an mvc 4 application on iis7+.  

[https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/Targets/Wrappers/AspNetBufferingTargetWrapper.cs](url)

```         InternalLogger.Trace("ASP.NET request buffer does not exist. Passing to wrapped target.");
.....
            HttpContext context = HttpContext.Current;
            if (context == null)
            {
                return null;
            }
```


The question then becomes why?  Is this wrapper not applicable in mvc 4?  SO says [https://stackoverflow.com/questions/15117379/httpcontext-current-not-resolving-in-mvc-4-project](url)

"This means that when you attempt to use it without any qualification in the controller it resolves to the local property and not System.Web.HttpContext. The type of the property is HttpContextBase which does have a Request property that would do what you want (though note that it isn't the same class as you would get from System.Web.HttpContext"

I am also having issues reading appsettings AppName as well.
I have nlog, nlog.config, nlog.web, nlog.extended nuget packages loaded as well.

Perplexted.

**Comment by dyardyGIT** [comment]
Note: I am using AutoFac to create the instance with the following...
builder.RegisterType<LoggingService>().As<ILoggingService>().InstancePerLifetimeScope();

Could this be effecting the fact that httpcontext is null for me??

**Comment by dyardyGIT** [comment]
Not sure if I should be posting my issues here or SO.  Even without autofac I am having an hard time with httpcontext and getting access to aspnet variables.  Odd thing is that it was working for 1 or 2 hours locally.

[](https://stackoverflow.com/questions/48591203/httpcontext-with-nlog)

**Comment by snakefoot** [comment]
Have you tried to google the exception "Request is not available in this context" ? Maybe you are expecting to HttpContext be ready at Application_Start ?

Don't have much experience with IIS and ASP.NET but the availability of the HttpContext is not an NLog-issue, but an application-issue.

**Comment by dyardyGIT** [comment]
I have googled around and no luck.



2018-02-02 17:20:17.4212 Error Error parsing layout aspnet-request-summary will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-request-summary'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)



Internal log file look like


```
2018-02-02 17:20:17.3084 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2018-02-02 17:20:17.3345 Debug Start auto loading, location: C:\inetpub\wwwroot\IT\CH2Mobile\ODOT\Main\ODOT\ODOT.Web\bin
2018-02-02 17:20:17.3355 Info Auto loading assembly file: C:\inetpub\wwwroot\IT\CH2Mobile\ODOT\Main\ODOT\ODOT.Web\bin\NLog.MailKit.dll
2018-02-02 17:20:17.3355 Info NLog.MailKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.0.140. Product version: 2.1.1.
2018-02-02 17:20:17.3355 Debug ScanAssembly('NLog.MailKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2018-02-02 17:20:17.3355 Info Auto loading assembly file: C:\inetpub\wwwroot\IT\CH2Mobile\ODOT\Main\ODOT\ODOT.Web\bin\NLog.MailKit.dll succeeded!
2018-02-02 17:20:17.3355 Info Auto loading assembly file: C:\inetpub\wwwroot\IT\CH2Mobile\ODOT\Main\ODOT\ODOT.Web\bin\NLog.Web.dll
2018-02-02 17:20:17.3536 Info NLog.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.0.0.0. Product version: 4.0.0.0.
2018-02-02 17:20:17.3536 Debug ScanAssembly('NLog.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2018-02-02 17:20:17.3536 Info Auto loading assembly file: C:\inetpub\wwwroot\IT\CH2Mobile\ODOT\Main\ODOT\ODOT.Web\bin\NLog.Web.dll succeeded!
2018-02-02 17:20:17.3536 Debug Auto loading done
2018-02-02 17:20:17.3536 Debug ScanAssembly('NLog.Extended, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2018-02-02 17:20:17.3536 Info Loading assembly name: NLog.Web
2018-02-02 17:20:17.3536 Debug ScanAssembly('NLog.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2018-02-02 17:20:17.3811 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3851 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2018-02-02 17:20:17.3851 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2018-02-02 17:20:17.3851 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2018-02-02 17:20:17.3851 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3851 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2018-02-02 17:20:17.3851 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3851 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2018-02-02 17:20:17.3851 Trace  Scanning SimpleLayout ''''
2018-02-02 17:20:17.3851 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2018-02-02 17:20:17.3851 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3851 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2018-02-02 17:20:17.3851 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3851 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2018-02-02 17:20:17.3851 Debug Setting 'FileTarget.name' to 'logfile'
2018-02-02 17:20:17.3982 Debug Setting 'FileTarget.fileName' to 'file.txt'
2018-02-02 17:20:17.3982 Debug Setting 'FileTarget.layout' to '${longdate}                  LEVEL=${level:upperCase=true}: ${message}${newline} (${stacktrace}) ${exception:format=tostring}               ${newline}SUMMARY=${aspnet-request-summary}                 '
2018-02-02 17:20:17.3982 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3982 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2018-02-02 17:20:17.3982 Debug Setting 'UppercaseLayoutRendererWrapper.upperCase' to 'true'
2018-02-02 17:20:17.3982 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2018-02-02 17:20:17.3982 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3982 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2018-02-02 17:20:17.3982 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3982 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2018-02-02 17:20:17.3982 Trace  Scanning SimpleLayout ''''
2018-02-02 17:20:17.3982 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2018-02-02 17:20:17.3982 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3982 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2018-02-02 17:20:17.3982 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3982 Trace Scanning NewLineLayoutRenderer 'Layout Renderer: ${newline}'
2018-02-02 17:20:17.3982 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.3982 Trace Scanning StackTraceLayoutRenderer 'Layout Renderer: ${stacktrace}'
2018-02-02 17:20:17.4212 Debug Setting 'ExceptionLayoutRenderer.format' to 'tostring'
2018-02-02 17:20:17.4212 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.4212 Trace Scanning ExceptionLayoutRenderer 'Layout Renderer: ${exception}'
2018-02-02 17:20:17.4212 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.4212 Trace Scanning NewLineLayoutRenderer 'Layout Renderer: ${newline}'
2018-02-02 17:20:17.4212 Error Error parsing layout aspnet-request-summary will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-request-summary'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
2018-02-02 17:20:17.4212 Trace FindReachableObject<NLog.Internal.IRenderable>:
2018-02-02 17:20:17.4293 Trace Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2018-02-02 17:20:17.4293 Info Adding target File Target[logfile]
2018-02-02 17:20:17.4293 Debug Registering target logfile: NLog.Targets.FileTarget
2018-02-02 17:20:17.4293 Debug Setting 'BufferingTargetWrapper.name' to 'mailBuffer'
2018-02-02 17:20:17.4293 Debug Setting 'BufferingTargetWrapper.slidingTimeout' to 'true'
2018-02-02 17:20:17.4293 Debug Setting 'BufferingTargetWrapper.bufferSize' to '100'
2018-02-02 17:20:17.4293 Debug Setting 'BufferingTargetWrapper.flushTimeout' to '30'
2018-02-02 17:20:17.4293 Trace FindReachableObject<NLog.Internal.IRenderable>:

```

**Comment by snakefoot** [comment]
What are you now trying to solve? "Request is not available in this context" or  'aspnet-request-summary' cannot be found ?

`aspnet-request-summary` doesn't exist in NLog.Web. Have you just grapped some random code from the internet and then using stackoverflow to make it work ?

Have now also googled `aspnet-request-summary` for you and found https://www.nuget.org/packages/NLog.Extensions/

**Comment by 304NotModified** [comment]
Is this still an issue?

**Comment by dyardyGIT** [comment]
You can close this issue.  Thank you!
