### ISSUE TITLE
Method not found: 'Void NLog.MessageTemplates.MessageTemplateParameter

### ISSUE THREAD

**Issue by BenDonnelly** [NLog/NLog#2578]
- Bug

**NLog version**: 4.5.0-beta05
NLog.Web.AspNetCore Version: 4.5.0-rc2

**Platform**: NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\temp\internal-nlog.txt">


  <!-- the targets to write to -->
  <targets>
    <target name="db"
            xsi:type="Database"
            connectionString="Server=localhost;Database=MIS_Logs;Trusted_Connection=True;MultipleActiveResultSets=True;"
            commandType="StoredProcedure"
            commandText="[dbo].[NLog_AddEntry]"
        >
      <parameter name="@machineName"    layout="${machinename}" />
      <parameter name="@siteName"       layout="${iis-site-name}" />
      <parameter name="@logged"         layout="${date}" />
      <parameter name="@level"          layout="${level}" />
      <parameter name="@username"       layout="${aspnet-user-identity}" />
      <parameter name="@message"        layout="${message}" />
      <parameter name="@logger"         layout="${logger}" />
      <parameter name="@properties"     layout="${all-event-properties:separator=|}" />
      <parameter name="@serverName"     layout="${aspnet-request:serverVariable=SERVER_NAME}" />
      <parameter name="@port"           layout="${aspnet-request:serverVariable=SERVER_PORT}" />
      <parameter name="@url"            layout="${aspnet-request:serverVariable=HTTP_URL}" />
      <parameter name="@https"          layout="${when:inner=1:when='${aspnet-request:serverVariable=HTTPS}' == 'on'}${when:inner=0:when='${aspnet-request:serverVariable=HTTPS}' != 'on'}" />
      <parameter name="@serverAddress"  layout="${aspnet-request:serverVariable=LOCAL_ADDR}" />
      <parameter name="@remoteAddress"  layout="${aspnet-request:serverVariable=REMOTE_ADDR}:${aspnet-request:serverVariable=REMOTE_PORT}" />
      <parameter name="@callSite"       layout="${callsite}" />
      <parameter name="@exception"      layout="${exception:tostring}" />
    </target>

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
    
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>


    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="db" />
  </rules>
</nlog>

```

When creating a new logger inside the controller, I get this below error method in the output console.
```
System.AggregateException: An error occurred while writing to logger(s). (Method not found: 'Void NLog.MessageTemplates.MessageTemplateParameter..ctor(System.String, System.Object, System.String, NLog.MessageTemplates.CaptureType)'.) ---> System.MissingMethodException: Method not found: 'Void NLog.MessageTemplates.MessageTemplateParameter..ctor(System.String, System.Object, System.String, NLog.MessageTemplates.CaptureType)'.
   at NLog.Extensions.Logging.NLogMessageParameterList.get_Item(Int32 index)
   at NLog.Internal.PropertiesDictionary..ctor(IList`1 parameterList)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfoWithMultipleParameters(LogLevel nLogLogLevel, String message, IReadOnlyList`1 parameterList)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfo(LogLevel nLogLogLevel, String message, IReadOnlyList`1 parameterList)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.LogRequestStarting(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.CreateContext(IFeatureCollection contextFeatures)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'Void NLog.MessageTemplates.MessageTemplateParameter..ctor(System.String, System.Object, System.String, NLog.MessageTemplates.CaptureType)'.
   at NLog.Extensions.Logging.NLogMessageParameterList.get_Item(Int32 index)
   at NLog.Internal.PropertiesDictionary..ctor(IList`1 parameterList)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfoWithMultipleParameters(LogLevel nLogLogLevel, String message, IReadOnlyList`1 parameterList)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfo(LogLevel nLogLogLevel, String message, IReadOnlyList`1 parameterList)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
```

Here is my list of references..
```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Owin" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" />
    <PackageReference Include="NLog" Version="4.5.0-beta05" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.5.0-rc2" />
    <PackageReference Include="System.AppContext" Version="4.3.0" />
```

Here is the BuildWebHost of the program.cs
```
 public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseNLog()
                .Build();

```

Its good to note that in my Main method, I do this and this actaully works and logs against the DB.
```
     public static void Main(string[] args)
        {
            var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            logger.Debug("init main");
            BuildWebHost(args).Run();
        }
```

But when its inside the controller however like this, I get the above error message.
```
    public class AccountController : NXController {
        private readonly string AuthenticationType = "ApplicationCookie";
        //      private readonly IAuthenticationProvider AuthenticationProvider;
        //        private readonly IOwinContext OwinContext;
        private readonly ILogger<AccountController> Logger;

        private static IConfiguration Configuration { get; set; }

        public AccountController(NXContext context, IConfiguration configuration, ILogger<AccountController> logger) : base(context) {
            //OwinContext = owinContext;
            //AuthenticationProvider = authenticationProvider;
            Configuration = configuration;
            Logger = logger;
            Logger.LogCritical("asdasd");
        }

```

**Comment by 304NotModified** [comment]
NLog.Web.AspNetCore 4.5.0-rc2 depends on NLog.Extensions.Logging >=1.0.0-rtm-rc4
NLog.Extensions.Logging 1.0.0-rtm-rc4 depends on NLog >= 4.5.0-rc02

so you have installed (manually) non-matching versions. Recommend to delete the `PackageReference Include="NLog" Version="4.5.0-beta05" />` OR update it

**Comment by BenDonnelly** [comment]
Thanks that fixed. Opted to update.

How can I make the connection string for the DB target come from my enviroment settings? As the DB Conn string will be different dependent on whether its dev or prod

**Comment by 304NotModified** [comment]
got it working?

**Comment by BenDonnelly** [comment]
Yes thank you 👍

**Comment by BenDonnelly** [comment]
How did you work that out by the way? Which line did I miss

**Comment by 304NotModified** [comment]
I checked the dependency list of the packages on nuget.org

This is a common error and I dunno how people install the incompatible versions, it should be enforced by the nuget client.
