### ISSUE TITLE
IndexOutOfRangeException in NestedDiagnosticsLogicalContext

### ISSUE THREAD

**Issue by xamele0n** [NLog/NLog#2635]
**Type** : Bug

**NLog version**: 4.5.0

**Platform**: .Net 4.5

**Current NLog config** 
```xml
<nlog throwExceptions="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<variable name="app" value="pc"/>
	<variable name="env" value="PC"/>
	<variable name="dbpFullLayout" value="${longdate} | ${level} | ${logger} | ${identity} | ${ndlc:separator=#} | ${message} ${exception:format=message}" />
	<targets>
		<target xsi:type="File" name="full" fileName="C:\LOGS\${env}\${machinename}-${var:app}-${shortdate}.log" layout="${dbpFullLayout}" />		
	</targets>

	<rules>
		<logger name="*" minlevel="Trace" writeTo="full" />		
	</rules>
</nlog>

```
I have a case in wich i start a long running task (over Task.Factory.StartNew) inside of Microsoft.Extension.Logging.Logger.BeginScope. When this scope will disposed i have got  IndexOutOfRangeException in NestedDiagnosticsLogicalContext

```
   at NLog.NestedDiagnosticsLogicalContext.GetAllObjects()
   at NLog.LayoutRenderers.NdlcLayoutRenderer.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
   at NLog.Layouts.SimpleLayout.RenderAllRenderers(LogEventInfo logEvent, StringBuilder target)
   at NLog.Layouts.Layout.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder target, Boolean cacheLayoutResult)
   at NLog.Targets.FileTarget.RenderFormattedMessageToStream(LogEventInfo logEvent, StringBuilder formatBuilder, Char[] transformBuffer, MemoryStream streamTarget)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```
The problem in this part of code. 
```c#
            object[] messages = new object[currentContext.FrameLevel];
            while (currentContext != null)
            {
                messages[index++] = currentContext.Value;
                currentContext = currentContext.Parent;
            }
```
in this case currentContext was disposed and has FrameLevel = 0

P.s: Sorry for my english

**Comment by 304NotModified** [comment]
hi! Thanks for reporting this.

**Comment by xamele0n** [comment]
Thanks!
