### ISSUE TITLE
System.OutOfMemoryException Nlog v4.03

### ISSUE THREAD

**Issue by SurendraChhaliwal** [NLog/NLog#2728]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3)

v4.3.1

**Platform**:  .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog autoReload="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets async="true">
      <target xsi:type="File" name="flatfile" layout="${longdate} ${uppercase:${level}} ${message} ${exception:format=tostring,StackTrace}" 
              archiveAboveSize="2000000" archiveFileName="${basedir}/logs/archive/${shortdate}-{#####}.engine.log" archiveNumbering="Sequence" archiveEvery="None" 
              maxArchiveFiles="100" fileName="${basedir}/logs/engine.current.log" keepFileOpen="true" concurrentWrites="true" />
     
      <target xsi:type="EventLog" name="eventlog" layout="${longdate} ${uppercase:${level}} ${message} ${exception:format=tostring} ${StackTrace}" log="Application" source="Nuance Interface Engine Service" eventId="${event-properties:EventID}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="flatfile">
     
        <filters>
          <when condition="(equals('${logger}','Castle.Facilities.AutoTx.AutoTxFacility') and level &lt;= LogLevel.Error)" action="Ignore" />
          <when condition="(equals('${logger}','Castle.Facilities.AutoTx.Lifestyles.PerTopTransactionLifestyleManager') and level &lt;= LogLevel.Error)" action="Ignore" />
          <when condition="(equals('${logger}','Castle.Transactions.TransactionManager.Transaction') and level &lt;= LogLevel.Error)" action="Ignore" />
          <when condition="(equals('${logger}','Castle.Facilities.AutoTx.TransactionInterceptor') and level &lt;= LogLevel.Error)" action="Ignore" />
        </filters>
      </logger>
      <logger name="*" minlevel="Trace" writeTo="eventlog" />
    </rules>
  </nlog>
```

In case of a BUG:

- What is the current result?

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Text.StringBuilder..ctor(System.String, Int32, Int32, Int32)
   at NLog.Layouts.SimpleLayout.GetFormattedMessage(NLog.LogEventInfo)
   at NLog.Targets.FileTarget.GetFormattedMessage(NLog.LogEventInfo)
   at NLog.Targets.FileTarget.GetBytesToWrite(NLog.LogEventInfo)
   at NLog.Targets.FileTarget.Write(NLog.Common.AsyncLogEventInfo[])
   at NLog.Targets.Target.WriteAsyncLogEvents(NLog.Common.AsyncLogEventInfo[])
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

- What is the expected result?

Running application in multithreaded environment, this exception should not be thrown as and when this exception occurs windows service stopped. 

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

No

- Please post full exception details (message, stacktrace, inner exceptions)

Already done above

- Are there any workarounds? yes/no
no

**Comment by 304NotModified** [comment]
Please check the proper NLog version, there is no 4.03, that's the internal .NET version

https://www.nuget.org/packages/NLog/

**Comment by SurendraChhaliwal** [comment]
Nlog v4.3.1

**Comment by snakefoot** [comment]
See also the StackOverflow Question:

https://stackoverflow.com/questions/50388331/the-process-was-terminated-due-to-an-unhandled-exception-wcf-service

**Comment by 304NotModified** [comment]
thanks!
