### ISSUE TITLE
NLog stops logging when the config file is broken, and then config is repaired (autoreload)

### ISSUE THREAD

**Issue by PetrMachek** [NLog/NLog#273]
Reproducting the issue
1. Use autoreload="True" parameter in config file.
2. Start application - NLog working fine.
3. Invalidate XML structure in NLog.config file (i.e. delete some closing tag), save the file, then NLog will stop logging.
4. Change NLog.config to the previous valid state, save it - NLog still not logging until the application is restarted.

**Comment by 304NotModified** [comment]
I will try to reproduce and fix this. (Next week)

**Comment by ilya-g** [comment]
Isn't it the same issue as #403?

**Comment by 304NotModified** [comment]
I think you're right! @ilya-g

**Comment by 304NotModified** [comment]
Really need to double check this

**Comment by kwaak** [comment]
Can confirm.
After corrupting the XML in the .config file, and making it valid again it won't auto reload
Also no error about the invalid XML in the .config file is logged to the internal log file

Version: 2.1.0.0

**Comment by 304NotModified** [comment]
developers hint: add unit test, test in 2.1 and fix in master

**Comment by 304NotModified** [comment]
Confirm, this is still a bug in 3.2.0


Log file:

```
2015-04-17 00:02:41.8000 Info Adding target File Target[fileRobot]
2015-04-17 00:02:41.8000 Info Configured from an XML element in x:\folder\bin\NLog.config...
2015-04-17 00:02:41.8120 Info Closing old configuration.
2015-04-17 00:02:41.8120 Info Found 21 configuration items
2015-04-17 00:02:41.8270 Info Found 21 configuration items
2015-04-17 00:02:41.8460 Info Watching path 'x:\folder\bin' filter 'NLog.config' for changes.
2015-04-17 00:02:52.5107 Info Configuration file change detected! Reloading in 1000ms...
2015-04-17 00:02:53.5257 Info Reloading configuration...
2015-04-17 00:02:53.5257 Info Stopping file watching for path 'x:\folder\bin' filter 'NLog.config'
2015-04-17 00:02:53.5597 Error Error in Parsing Configuration File. Exception : NLog.NLogConfigurationException: Exception occurred when loading configuration from x:\folder\bin\NLog.config ---> System.Xml.XmlException: Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 23, position 5.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at NLog.Config.NLogXmlElement.Parse(XmlReader reader)
   at NLog.Config.NLogXmlElement..ctor(XmlReader reader)
   at NLog.Config.NLogXmlElement.Parse(XmlReader reader)
   at NLog.Config.NLogXmlElement..ctor(XmlReader reader)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2015-04-17 00:02:53.5597 Info Closing old configuration.
2015-04-17 00:02:53.5867 Info Found 0 configuration items
2015-04-17 00:02:53.6037 Info Found 0 configuration items

```

**Comment by 304NotModified** [comment]
Probably it the bug in `LogFactory`

```C#
 internal void ReloadConfigOnTimer(object state)
        {
            LoggingConfiguration configurationToReload = (LoggingConfiguration)state;

            InternalLogger.Info("Reloading configuration...");
            lock (this.syncRoot)
            {
                if (this.reloadTimer != null)
                {
                    this.reloadTimer.Dispose();
                    this.reloadTimer = null;
                }

                this.watcher.StopWatching();
                try
                {
                    if (this.Configuration != configurationToReload)
                    {
                        throw new NLogConfigurationException("Config changed in between. Not reloading.");
                    }

                    LoggingConfiguration newConfig = configurationToReload.Reload();
                    if (newConfig != null)
                    {
                        this.Configuration = newConfig;
                        if (this.ConfigurationReloaded != null)
                        {
                            this.ConfigurationReloaded(this, new LoggingConfigurationReloadedEventArgs(true, null));
                        }
                    }
                    else
                    {
                        throw new NLogConfigurationException("Configuration.Reload() returned null. Not reloading.");
                    }
                }
                catch (Exception exception)
                {
                    if (exception is NLogConfigurationException)
                    {
                        InternalLogger.Warn(exception.Message);
                    }
                    else if (exception.MustBeRethrown())
                    {
                        throw;
                    }

                    this.watcher.Watch(configurationToReload.FileNamesToWatch);

                    var configurationReloadedDelegate = this.ConfigurationReloaded;
                    if (configurationReloadedDelegate != null)
                    {
                        configurationReloadedDelegate(this, new LoggingConfigurationReloadedEventArgs(false, exception));
                    }
                }
            }
```
