### ISSUE TITLE
Unexpected error "Could not load file or assembly Mono.Android, Version = 0.0.0.0 or one of its dependencies. The system cannot find the file specified" on Windows server

### ISSUE THREAD

**Issue by TalismanicCoder** [NLog/NLog#2753]
**NLog version**: 4.5.3

**Platform**: .Net 4.5 on Windows 2008 server

**Current NLog config** (xml or C#, if relevant)

c# Code:
NLog.LogFactory.GetCurrentClassLogger();

- What is the current result? When the code tries to get Configuration i.e. NLog.LogFactory.Configuration, the type initializer throws an exception
"Could not load file or assembly Mono.Android, Version = 0.0.0.0 or one of its dependencies. The system cannot find the file specified".

- What is the expected result? The exception is not expected. The code trying to load Mono.Android is suspicious as the build/assembly is targeted for windows only.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No. Could try this.
- Please post full exception details (message, stacktrace, inner exceptions)
System.TypeInitializationException: The type initializer throws an exception
"Could not load file or assembly Mono.Android, Version = 0.0.0.0 or one of its dependencies. The system cannot find the file specified".
at NLog.LogFactory.TryLoadFromAndroidAssets()
at NLog.LogFactory.get_Configuration()
at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
at NLog.LogFactory.GetLogger(String Name)
at NLog.LogFactory.GetCurrentClassLogger()

- Are there any workarounds? no
- Is there a version in which it did work? 2.1.0

**Comment by snakefoot** [comment]
Are you using some kind of custom build? As `TryLoadFromAndroidAssets` requires one to use the `monoandroid44`-platform:

https://github.com/NLog/NLog/blob/4b46dd971a11e7f7897fa27cd65d75ba5827d887/src/NLog/LogFactory.cs#L321-L330

Have you installed something weird in the GAC ? What is the Assembly Title when you show File Properties for the NLog.dll in your application?

Think something is broken in your build/deployment process.

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info -
 thanks!
