### ISSUE TITLE
Unable to load from AppConfig should not crash application

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#2754]
Just like NLog is able to load configuration from many potential file-locations (without crashing if file doesn't exist), then NLog should treat app.config just like that (Even when ThrowException=true).

```
System.TypeInitializationException: The type initializer threw an exception. ---> System.IO.FileNotFoundException: 
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at System.Configuration.ClientConfigPaths.SetNamesAndVersion(String applicationFilename, Assembly exeAssembly, Boolean isHttp)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at NLog.Config.XmlLoggingConfiguration.get_AppConfig()
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
```

Would prefer that NLog-Configuration-Loading was separate nuget-packages. Ex. loading from simple xml-nlog.config. Ex. loading from the application app.config, Ex. loading from appsettings.json. So all this auto-loading logic with unexpected surprises becomes a thing of the past (OptIn by choosing nuget-package). See also [#2376](https://github.com/NLog/NLog/issues/2376#issuecomment-341716532) and #1776

**Comment by 304NotModified** [comment]
> Would prefer that NLog-Configuration-Loading was separate nuget-packages.

Me too

**Comment by snakefoot** [comment]
There is already exception protection (The stack trace from an old NLog version), and since NetFramework is in legacy maintenance-mode. Then just created #3053
