### ISSUE TITLE
NLog +asp.net core + net 472 + rdlc: error generating a report

### ISSUE THREAD

**Issue by luisabreu** [NLog/NLog#2812]
Hello guys.

While migrating an existing .net 4.7.1 web app which uses local reports (rdlc)  to asp.net core I've started getting an exception at runtime when I try to generate the rdlc frmo the server side. 

Currently, I'm getting this error:

```cs
Microsoft.Reporting.WebForms.LocalProcessingException: An error occurred during local report processing. ---> Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: Failed to load expression host assembly. Details: Type 'Microsoft.AspNetCore.Mvc.Internal.MvcCoreLoggerExtensions+ActionLogScope' in assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable.
   at Microsoft.ReportingServices.RdlExpressions.ReportRuntime.ProcessLoadingExprHostException(ObjectType assemblyHolderObjectType, Exception e, ProcessingErrorCode errorCode)
   at Microsoft.ReportingServices.RdlExpressions.ReportRuntime.LoadCompiledCode(IExpressionHostAssemblyHolder expressionHostAssemblyHolder, Boolean includeParameters, Boolean parametersOnly, ObjectModelImpl reportObjectModel, ReportRuntimeSetup runtimeSetup)
   at Microsoft.ReportingServices.OnDemandProcessing.Merge.Init(Boolean includeParameters, Boolean parametersOnly)
   at Microsoft.ReportingServices.OnDemandProcessing.Merge.Init(ParameterInfoCollection parameters)
   at Microsoft.ReportingServices.ReportProcessing.Execution.ProcessReportOdp.CreateReportInstance(OnDemandProcessingContext odpContext, OnDemandMetadata odpMetadata, ReportSnapshot reportSnapshot, Merge& odpMerge)
   at Microsoft.ReportingServices.ReportProcessing.Execution.ProcessReportOdp.Execute(OnDemandProcessingContext& odpContext)
   at Microsoft.ReportingServices.ReportProcessing.Execution.RenderReportOdpInitial.ProcessReport(ProcessingErrorContext errorContext, ExecutionLogContext executionLogContext, UserProfileState& userProfileState)
   at Microsoft.ReportingServices.ReportProcessing.Execution.RenderReport.Execute(IRenderingExtension newRenderer)
   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.RenderReport(IRenderingExtension newRenderer, DateTime executionTimeStamp, ProcessingContext pc, RenderingContext rc, IChunkFactory yukonCompiledDefinition)
   at Microsoft.Reporting.LocalService.CreateSnapshotAndRender(ReportProcessing repProc, IRenderingExtension renderer, ProcessingContext pc, RenderingContext rc, SubreportCallbackHandler subreportHandler, ParameterInfoCollection parameters, DatasourceCredentialsCollection credentials)
   at Microsoft.Reporting.LocalService.Render(String format, String deviceInfo, String paginationMode, Boolean allowInternalRenderers, IEnumerable dataSources, CreateAndRegisterStream createStreamCallback)
   at Microsoft.Reporting.WebForms.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
   --- End of inner exception stack trace ---
   at Microsoft.Reporting.WebForms.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
   at Microsoft.Reporting.WebForms.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.WebForms.LocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.WebForms.Report.Render(String format, String deviceInfo, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Grm.GestaoFrotas.NetCore.Frotas.Results.PdfReportActionResult.ExecuteResultAsync(ActionContext context) in D:\code\work\tfsonline\GestaoFrotas\code\GestaoFrotas\Grm.GestaoFrotas.NetCore.Frotas\ActionViews\PdfReportActionResult.cs:line 39
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
```

This will only happen when I activate NLog during startup:
```cs
public class Program {
        public static void Main(string[] args) {
            var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try {
                CreateWebHostBuilder(args).Build().Run();
            }
            catch (Exception ex) {
                logger.Error(ex);
                throw;
            }
            finally {
                LogManager.Shutdown();
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureServices(s =>s.AddAutofac())
                .UseStartup<Startup>()
                .UseNLog(); // <---------- Commenting this line does generate the report, but no logging :(
    }
```

Here's the server side code used for generating the report:

```cs
      public override Task ExecuteResultAsync(ActionContext context) {
            var report = new LocalReport();// {ReportPath = _reportDefinition};
            report.LoadReportDefinition(_reportDefinition);
            //report.DataSources.Add( new ReportDataSource( "DataSet1", new [] {_fillReportWithInfo}  ) );

            _fillReportWithInfo(report);
            report.Refresh();

           // ERROR happens during rendering...
            var renderedBytes = report.Render(
                _reportType,
                _deviceInfo,
                out var mimeType,
                out _, //encoding
                out var fileNameExtension,
                out _, //encoding
                out _); //warnings


            var response = context.HttpContext.Response;

            var disposition = $"attachment; filename = \"{_reportName}.{fileNameExtension}\"";
            response.Headers.Add("Content-Disposition", disposition);
            return  response.Body.WriteAsync(renderedBytes, 0, renderedBytes.Length);
        }
```

As I said, I had to change the target of the asp.net core app (net472 instead o netcore2.1) so that I can reuse the existing rdlc files and the reporting services dlls.

Btw, this issue has alread been presented in MS MVP github here: https://github.com/aspnet/Mvc/issues/4910

Since this happens when NLog is activated, I thought it would be better to raise the issue here.

Thanks again.

Luis

**Comment by luisabreu** [comment]
Any idea on when it will be available?

**Comment by 304NotModified** [comment]
Think next week

**Comment by luisabreu** [comment]
Nice...I'll give it a run in 2 weeks time...
