### ISSUE TITLE
Archive in UWP app throws exceptions

### ISSUE THREAD

**Issue by StrangerUA** [NLog/NLog#2824]
**NLog version**: (e.g. 4.5.7)
**Platform**: UWP
**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info">
  <targets>
    <target name="file"
            xsi:type="File"
            fileName="${var:LogPath}\*****-${shortdate}.log"
            layout="${date}|${logger}|${uppercase:${level}}|${message} ${exception}"
            archiveAboveSize="104857600"
            maxArchiveFiles="4"           
            />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="File" />
  </rules>
</nlog>

```

- What is the current result?
On first log to file app throws an 
System.UnauthorizedAccessException:

```
Access to the path 'Global\NLog-FileFileArchiveLock-c:_users_pavlo.holubovych_appdata_local_packages_*******_4sdaedqydyjdm_localstate_******-2018-07-31.log' is denied.'

   at System.IO.__Error.WinIOError(Int32 errorCode, String str)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at NLog.Internal.FileAppenders.BaseMutexFileAppender.CreateSharableMutex(String mutexNamePrefix)
   at NLog.Internal.FileAppenders.BaseMutexFileAppender.CreateArchiveMutex()

```

Log is working after I continue though. It throws an exception only once per file, SO the next one will be after first files reaches archiveAboveSize.

Problem is not reproduced without archive option, so the issue is somewhere there

Internal log file was not created

**Comment by snakefoot** [comment]
Problems comes from UWP on NetCore2 doesn't support all features:

https://github.com/NLog/NLog/issues/2742#issuecomment-392099407

Maybe change the logic so if running `KeepFileOpen=true` AND `concurrentWrites=false`, then there should be no need to create archive-mutex (When NetStandard)

**Comment by snakefoot** [comment]
Problems comes from UWP on NetCore2 doesn't support all features. See also:

https://github.com/NLog/NLog/issues/2742#issuecomment-392099407

The solution is to configure  `KeepFileOpen=true` AND `concurrentWrites=false`, then there should be no need to create archive-mutex. See also #2758

**Comment by StrangerUA** [comment]
It works well with KeepFileOpen=true AND concurrentWrites=false
Thanks!

**Comment by 304NotModified** [comment]
Thanks for the feedback!
