### ISSUE TITLE
Cannot set int value from variable for file layout for archiveAboveSize

### ISSUE THREAD

**Issue by daviatorstorm** [NLog/NLog#2888]
**NLog version**: 4.5.9 

**Platform**:  .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```c#
  LogManager.Configuration.Variables["destination"] = loggingConfigurations.Destination;
  LogManager.Configuration.Variables["fileName"] = loggingConfigurations.Filename;
  LogManager.Configuration.Variables["maxFileSize"] = loggingConfigurations.MaxFileSize.ToString();
```

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="debug"
      internalLogFile="internal-nlog.txt">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <targets>
    <target xsi:type="File" name="allfile" fileName="${var:destination}/${var:fileName}-${shortdate}.log"
            archiveNumbering="Sequence" archiveAboveSize="${var:maxFileSize}"
            layout=" ${level}: ${date} ${message} ${exception:format=tostring}" />
  </targets>
  <rules>
    <logger name="FCBT.*" writeTo="allfile" />
  </rules>

</nlog>
```

Result from internal.log

```
2018-08-31 13:47:31.5763 Warn Error when setting property 'ArchiveAboveSize' on 'File Target[allfile]' Exception: System.Exception: ${var:maxFileSize} is not a valid value for Int64. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.Int64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at NLog.Internal.PropertyHelper.TryTypeConverterConversion(Type type, String value, Object& newValue)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
```

Expected Result
The value will be setted

- Are there any workarounds? no
- Is there a version in which it did work? didn't try
- Can you help us by writing an unit test? Yes

**Comment by snakefoot** [comment]
Sounds like this issue: #1234

**Comment by 304NotModified** [comment]
yes indeed, this is #1234

as, for example, `ArchiveAboveSize` is of type `long` and not `Layout`, isn't not layoutable.

The only thing you could use are "const" variables, like ${myvar}, those are set when reading the config - you can't set them runtime!

You could set it runtime, with the following code:

```c#
var config = LogManager.Configuration;
var myFileTarget =  config.FindTargetByName<FileTarget>("myFileTarget"); // get target
myFileTarget.ArchiveAboveSize = 1000; // change setting
LogManager.Configuration = config; //apply new config
```

**Comment by 304NotModified** [comment]
closing as it's a duplicate -  #1234
