### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'System, Version=4.0.0.0,  with Unity

### ISSUE THREAD

**Issue by benzben** [NLog/NLog#2889]
**NLog version**: 4.5.9

**Platform**: .Net 4.5

Hi there,

I'm trying to integrate Nlog in a HoloLens project using .Net 4.x . It does not matter that it's a UWP App, because I integrate the Nlog.dll into Unity via 'don't process' and deactivate any specific code by using #if !UNITY_EDITOR - by that, Nlog will only be accessible after building the solution with Unity and then working solely in VisualStudio.
If I try to follow the config tutorial on 'https://github.com/NLog/NLog/wiki/Configuration-API', I can't even get beyond

```C#
// Step 1. Create configuration object 
var config = new LoggingConfiguration();
```
as it's giving me a strange exception:

```
Exception thrown: 'System.TypeInitializationException' in NLog.dll
System.TypeInitializationException: The type initializer for 'NLog.LogManager' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at NLog.LogFactory..ctor()
   at NLog.LogManager..cctor()
   --- End of inner exception stack trace ---
   at NLog.LogManager.get_LogFactory()
   at NLog.Config.LoggingConfiguration..ctor()
   at GlobalTracingManager.ConfigureFileLogging()
```

I couldn't find any solution for this in the existing issues (or did I miss anything important?).

The only thing I could think about is that Unity can't include additional files into the built VisualStudio Solution, and therefore Nlog is missing the Nlog.xml file that comes with installing Nlog regularly via Nuget, but if I add this file retroactively manually it still does not work, so I don't have any clue on how to fix that...

I would be glad for any help!

**Comment by snakefoot** [comment]
Looks similar to this:

http://www.networkcomms.net/forums/topic/nlog-error-with-unity3d/

Where they have made it work with NLog ver. 2.0

Not an expert on Unity. Think older versions of Unity will probably not work with latest NLog. See also #268

Think the latest version of Unity has some support for NetStandard. There should be a good chance that using the NetStandard1.3 NLog.dll will have good success.

Somebody called "AiUnity products" is also selling a special NLog-build for Unity3D (I guess it is a special where all the stuff mentioned in #268 has been removed)

https://assetstore.unity.com/packages/tools/utilities/nlog-logger-powerful-logging-framework-78220

**Comment by 304NotModified** [comment]
I think this is a strong name issue, could you add this to your .config:


```
      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.9.9.9" newVersion="4.0.0.0" />
      </dependentAssembly>
```

it needs to be in   `<configuration>` -  `<runtime>`  -   `<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">`

**Comment by snakefoot** [comment]
Try upgrade Microsoft.NETCore.UniversalWindows platform to ver 5.2.2



Sent from my Samsung device


-------- Original message --------

**Comment by benzben** [comment]
@snakefoot I've already installed version 6.1.7

**Comment by snakefoot** [comment]
Then you should investigate why you get a warning about using ver. 5.0.0



Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Also strange that you say that you are using Net45. And then suddenly loading NetCore nuget-packages. Make sure to use a Net46 (or newer) with NetCore


Sent from my Samsung device


-------- Original message --------

**Comment by benzben** [comment]
Do I need to include any of this nlog.config or nlog.schema stuff in my project as well?
![grafik](https://user-images.githubusercontent.com/39216624/45012434-5dd86800-b017-11e8-96f6-e4312ec92c19.png)

**Comment by snakefoot** [comment]
You should use the NLog Nuget-package. Instead of direct reference to NLog.dll.


Sent from my Samsung device


-------- Original message --------

**Comment by benzben** [comment]
Allright, I looked in the wrong place for the version of Microsoft.NETCore.UniversalWindows, and updated it to 5.2.2. After that, I was able to install Nlog properly using Nuget.
However, this is not what I finally want to achieve - namely to include Nlog in Unity so that Unity will include Nlog automatically into the VS solution that is built.
There's even no need for Nlog to be compatible with Unity as one can choose to 'disable' Plugins for Unity while a project is opened:
![grafik](https://user-images.githubusercontent.com/39216624/45023567-0e099900-b037-11e8-827b-9d86e5e143a9.png)
I thought about including everything into my Unity project Nlog needs, but that's just too many libraries.

**Comment by 304NotModified** [comment]
> There's even no need for Nlog to be compatible with Unity as one can choose to 'disable' Plugins for Unity while a project is opened ('don't process'):

So this issue could be closed? Or not?

**Comment by 304NotModified** [comment]
Do you know how to solve this in NLog so it should work out of the box for Unity? That's unclear to me now,

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info -
 thanks!
