### ISSUE TITLE
unhandled exceptions not logged on server

### ISSUE THREAD

**Issue by hercul1017** [NLog/NLog#2924]
I am experiencing following behavior:

1. In development (local) there is no problem logging exceptions, all kind works.

2. When I logged in remote server ( by remote desktop connection ) and open a chrome inside the server and create the exception,  there is also no problem, all kind of logging works.

3. If I use my laptop and Chrome Browser to  open the same website that is hosted on the server:

Controller/Action
```c#
{
       // log record gets created for the following line
       logger.Log(LogLevel.Fatal, "Sample informational message"); 

       // log record not created. However this record get created in item 1 and 2 case above
       int a = int.Parse("A");  
}
```

Global.asax
```c#
 protected void Application_Error(object sender, EventArgs e)
 {
            Logger logger = LogManager.GetCurrentClassLogger();
            logger.Fatal(Server.GetLastError());
            Server.ClearError();
 }
```

NLog.config
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off"
      internalLogFile="D:\...\logs\nlog-internal.log">
 
  <!--Define Various Log Targets like files, database or asp.net trace files-->
  <targets>
    <target name="console" xsi:type="ColoredConsole" layout="${message}" />
    <!--Write logs to File  where we want to write error logs-->
    <target name="file"              
            archiveFileName="logs/archives/app-log.{#}.txt" 
            archiveEvery="Day" 
            archiveNumbering="Rolling" 
            maxArchiveFiles="7" 
            xsi:type="File" 
            fileName="D:\...\logs\ErrorLogFile.log" 
            layout="--------------------- ${level} (${longdate}) ${machinename} --------------------
            ${newline}      
            ${newline}
            Additional Info  : ${message}${newline}
            Exception Type   : ${exception:format=Type}${newline}
            Exception Message: ${exception:format=Message}${newline}
            Stack Trace      : ${exception:format=Stack Trace}${newline}
                 
            ">
    </target>

  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="file" />

  </rules>
</nlog>
```

MVC 5 project. .Net 4.5.2. NLog version 4.5.7

I also use SignalR in the project.  The log folder has modify rights for IIS_IUSRS.

Any help appreciated.

**Comment by snakefoot** [comment]
Have you tried to enable the InternalLogger and looked at that:

https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by snakefoot** [comment]
Yes it looks like everything is working as it should. What are you logging? and what is the contents of the log file:

> C:\temp\logs\ErrorLogFile.log

**Comment by hercul1017** [comment]
I tried to explain above.  When users browse the website and an exception happens, the exception does not get logged. However, strangely If I remote desktop the server and exception happens it does appear in the log file. It also works for the development environment.

I created the case as follow:
    
    // log record gets created for the following line in all cases
       logger.Log(LogLevel.Fatal, "Sample informational message"); 

    // log record not created. However this record get created in item 1 and 2 case above
       int a = int.Parse("A"); 

Parsing creates Exception but it does not appear in the log file of the production server, when users are browsing. But the parsing exception entry appears both in local dev environment, and when remote desktop and use the browser in the server.

Content of the log file when above code runs.

            --------------------- Fatal (2018-09-20 22:53:44.6817) VME015D0C --------------------             
                   
             Additional Info  : Sample informational message
             Exception Type   : 
             Exception Message: 
             Stack Trace      :

**Comment by hercul1017** [comment]
I remote desktop the prod server. Deleted log file. Opened a browser and went the page that creates the exception. It created following expected log file.

--------------------- Fatal (2018-09-20 22:58:12.0420) VME015D0C --------------------             
                   
             Additional Info  : Sample informational message
             Exception Type   : 
             Exception Message: 
             Stack Trace      : 
                               
--------------------- Fatal (2018-09-20 22:58:12.0490) VME015D0C --------------------             
                   
             Additional Info  : System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at TAAExam.UI.Controllers.HomeController.About() in D:\XX\Controllers\HomeController.cs:line 206
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
             Exception Type   : System.FormatException
             Exception Message: Input string was not in a correct format.
             Stack Trace      :    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at TAAExam.UI.Controllers.HomeController.About() in D:\XX\Controllers\HomeController.cs:line 206
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by snakefoot** [comment]
NLog is a logging library. It doesn't inject random code that catches all exceptions and performs logging of these. 

Guess you have something in your ASP MVC application that triggers a call to NLog on Exception for certain cases. I'm not a ASP MVC developer, so cannot help you. Can only see that NLog is logging just fine.

**Comment by hercul1017** [comment]
I am not expecting NLOG to trigger anything.  MVC does that. I want NLog to log and the described case above, it doesn't.

I understand that since you are not ASP MVC developer you didn't understand the case.  Hopefully someone who knows ASP.NET MVC and maybe IIS could help.

**Comment by 304NotModified** [comment]
I'm a ASP.NET MVC developer and I also don't understand the case.

> When I logged in remote server ( by remote desktop connection ) and open a chrome inside the server and create the exception, there is also no problem, all kind of logging works.

> If I use my laptop and Chrome Browser to open the same website that is hosted on the server:

I don't see how that could be different. Sounds like your IIS error settings. 

This could be related: https://stackoverflow.com/questions/6508415/application-error-not-firing-when-customerrors-on

**Comment by 304NotModified** [comment]
Also I think this is off topic for here. It's an ASP.NET MVC / IIS question, not NLog.

**Comment by hercul1017** [comment]
Most of the examples about using NLog for ASP.NET MVC applications suggest using Application_Error method in Global.asax for unhandled exceptions. It works in dev but not in server environment. So when unhandled exceptions not get logged in server (prod) then first thing comes to mind is that it is Nlog fault and NLog not good choice. At this point it could become NLog's problem because logging unhandled exceptions is one of the most important reason using logging library.

Anyway, in my case it turned out it wasn't NLog's fault. #304NotModified pointed me to the right direction. Application_Error was't getting called and that's why NLog wasn't be able to log the unhandled exceptions.

I am not sure if it is the best solution but following what I've done and working for me.

Create following class. OnException gets called when unhandled exception occur even in server (prod) evironment.

        public class ExecuteCustomErrorHandler : ActionFilterAttribute, IExceptionFilter
        {

            public void OnException(ExceptionContext filterContext)
            {
                Logger logger = LogManager.GetCurrentClassLogger();
                // Fatal error is relevant here.            
                logger.Fatal(filterContext.Exception);
            }
        }

Add filter in  Global.asax Application_Start method (it is the last line).

      protected void Application_Start()
      {
            AreaRegistration.RegisterAllAreas();
            UnityConfig.RegisterComponents();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            GlobalConfiguration.Configure(WebApiConfig.Register);
            System.Globalization.CultureInfo.DefaultThreadCurrentCulture = new System.Globalization.CultureInfo("en-GB");
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
            **GlobalFilters.Filters.Add(new ExecuteCustomErrorHandler());**

        }

NLog people should check if this is the best or acceptable solution and should provide the information for ASP.NET MVC  developers.
Thanks,

**Comment by 304NotModified** [comment]
> ost of the examples about using NLog for ASP.NET MVC applications suggest using Application_Error

not sure about this, IMO and error filter is better (the     GlobalFilters.Filters.)

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
