### ISSUE TITLE
using appsettings in nlog.config not working

### ISSUE THREAD

**Issue by andres-carrilloAdapt2** [NLog/NLog#3007]
NLog version 4.5.11

Platform: .Net 4.7.2 

<nlog autoReload="true"
      throwExceptions="true">

  <extensions>
    <add assembly="NLog.Gelf" />
    <add assembly="NLog.Extended" />
  </extensions>
  <targets>

    <target name="GelfHttp" type="GelfHttp" serverUrl="${appsetting:GraylogEndpoint}" facility="myfacility"/>
    
  </targets>

  <rules>
    <logger name="*" minLevel="Trace" appendTo="GelfHttp"/>
  </rules>
</nlog>

- What is the current result?
the serverUrl is not being updated 
- What is the expected result?
the serverUrl should point to my endpoint and log files
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
2018-11-08 13:01:53.8171 Error Unable to send logging event to remote host ${appsetting:GraylogEndpoint} Exception: System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
- Please post full exception details (message, stacktrace, inner exceptions)
System.NullReferenceException: Object reference not set to an instance of an object.
   at NLog.Config.LoggingConfiguration.ExpandSimpleVariables(String input)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner ExceptionDetail stack trace ---
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.LogFactory.LoadXmlLoggingConfiguration(String configFile)
   at NLog.LogFactory.TryLoadLoggingConfiguration(String configFile, LoggingConfiguration& config)
   at NLog.LogFactory.TryLoadFromFilePaths()
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at Adapt2.ISO.ISOService.CommonService..cctor()
   --- End of inner ExceptionDetail stack trace ---
   at Adapt2.ISO.ISOService.CommonService.GetEnvironment()
   at SyncInvokeGetEnvironment(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)}
- Are there any workarounds? no
- Is there a version in which it did work? 
no

**Comment by andres-carrilloAdapt2** [comment]
"Right now ${appsetting} requires you to use NLog.Extended. Sadly enough it depends on System.Messaging (MSMQ and friends)." By this, do you mean that if i reference system.messaging in my project i can reference $appsettings?

**Comment by snakefoot** [comment]
> By this, do you mean that if i reference system.messaging in my project i can reference $appsettings?

No I'm saying that you should add a dependency to https://www.nuget.org/packages/NLog.Extended/, and everything should happen automatically.

**Comment by andres-carrilloAdapt2** [comment]
Added assembly but still not working
<nlog autoReload="true"
      throwExceptions="true" >

  <extensions>
    <add assembly="NLog.Gelf" />
    <add assembly="NLog.Extended" />
  </extensions>
  <targets>

    <target name="GelfHttp" type="GelfHttp"
serverUrl="${appsetting:GraylogEndpoint}" facility="myfacility"/>

  </targets>

  <rules>
    <logger name="*" minLevel="Trace" appendTo="GelfHttp"/>
  </rules>
</nlog>

Andres Carrilloc

**Comment by andres-carrilloAdapt2** [comment]
Web.Config:

<nlog autoReload="true"
      throwExceptions="true" internalLogFile="c:\log.txt" internalLogLevel="Trace">

  <extensions>
    <add assembly="NLog.Gelf" />
    <add assembly="NLog.Extended" />
  </extensions>
  <targets>

    <target name="GelfHttp" type="GelfHttp" serverUrl="${appsetting:GraylogEndpoint}" facility="myfacility"/>
    
  </targets>

  <rules>
    <logger name="*" minLevel="Trace" appendTo="GelfHttp"/>
  </rules>
</nlog>

how should i add dependency? it is already a project reference, but to no avail

**Comment by snakefoot** [comment]
> Added assembly but still not working

And what is the error? I'm not sitting next to your. Is it loading NLog.Extended correctly?

**Comment by andres-carrilloAdapt2** [comment]
2018-11-08 14:47:08.6919 Error Unable to send logging event to remote host
${appsetting:GraylogEndpoint} Exception: System.UriFormatException: Invalid
URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NLog.Gelf.Senders.GelfHttpSender.Send(String message)
   at NLog.Gelf.Senders.GelfBaseSender.Send(GelfMessage message)
   at NLog.Gelf.GelfBaseTarget.Write(LogEventInfo logEvent)

Andres Carrillo

**Comment by snakefoot** [comment]
Please lower `internalLogLevel` to `Trace` so you can see if NLog.Extended is loading properly

**Comment by snakefoot** [comment]
Are you assigning any NLog-variables at runtime?  It is weird you get a NullReferenceException in ExpandSimpleVariables without having any NLog-variables.

**Comment by andres-carrilloAdapt2** [comment]
I can replace serverUrl with the endpoint and it logs correctly. 


[log.txt](https://github.com/NLog/NLog/files/2563575/log.txt)
 


 web.config : (snippet)
[Web.txt](https://github.com/NLog/NLog/files/2563594/Web.txt)


NLog.config:
[NLog.txt](https://github.com/NLog/NLog/files/2563587/NLog.txt)

**Comment by andres-carrilloAdapt2** [comment]
I am assigning the appsettings variable at compile time

Andres Carrillo

**Comment by snakefoot** [comment]
Ahhh sorry. Now I understand. It is the NLog.Gelf that doesn't support Layout for `serverUrl`

https://github.com/mantasaudickas/NLog.Gelf/blob/c4bd706ff1745bba0369408c335619205d5e10b9/src/NLog.Gelf/Targets/GelfBaseTarget.cs#L18

Either fix the Gelf Target to use NLog Layout (instead of string), or configure the `serverUrl` using NLog variables.

```c#
NLog.LogManager.KeepVariablesOnReload = true;
NLog.LogManager.Configuration.Variables["var_GraylogEndpoint"] = ConfigurationManager.AppSettings["GraylogEndpoint"];
```

And then use this in your nlog.config:

`<target name="GelfHttp" type="GelfHttp" serverUrl="${var_GraylogEndpoint}" facility="myfacility"/>`

Above alternative must be prepared in Adapt2.ISO.ISOService.CommonService.GetEnvironment or Adapt2.ISO.ISOService.CommonService (before calling GetCurrentClassLogger).

**Comment by andres-carrilloAdapt2** [comment]
"Either fix the Gelf Target to use NLog Layout" how do i do this?

**Comment by andres-carrilloAdapt2** [comment]
If possible i would like to not have  to modify every class that calls GetCurrentClassLogger.

**Comment by snakefoot** [comment]
> "Either fix the Gelf Target to use NLog Layout" how do i do this?

Means modifying the code.

> If possible i would like to not have to modify every class that calls GetCurrentClassLogger.

You just have to configure the NLog-variable during startup/initialization of your application.

**Comment by andres-carrilloAdapt2** [comment]
okay, that sounds easy

**Comment by snakefoot** [comment]
You can also try a combination of NetworkTarget and NLog.GelfLayout:

`<target xsi:type="Network" name="GelfHttp" address="${appsetting:GraylogEndpoint}" layout="${gelf:facility=MyFacility}"`

Nuget-package for NLog.GelfLayout; https://www.nuget.org/packages/NLog.GelfLayout/

But I'm not that skilled with Gelf.

**Comment by snakefoot** [comment]
Yet another alternative could be WebService-Target and NLog.GelfLayout:

```
<target xsi:type="WebService" name="GelfHttp" protocol="JsonPost" Url="${appsetting:GraylogEndpoint}">
   <parameter type='System.String' layout='${gelf:facility=MyFacility}'/>
</target>
```

**Comment by andres-carrilloAdapt2** [comment]
thank you

**Comment by snakefoot** [comment]
@andres-carrilloAdapt2 If you are able to get WebService-target or Network-target working with NLog.GelfLayout then please tell. Might help others running around in the dark.

**Comment by andres-carrilloAdapt2** [comment]
> 
You can also try a combination of NetworkTarget and NLog.GelfLayout:

<target xsi:type="Network" name="GelfHttp" address="${appsetting:GraylogEndpoint}" layout="${gelf:facility=MyFacility}" />
> 
This worked great
