### ISSUE TITLE
NLog fails silently with malformed config file

### ISSUE THREAD

**Issue by binaryunary** [NLog/NLog#3025]
**NLog version**: 4.5.11

**Platform**: .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwConfigExceptions="true"
      autoReload="true"
      internalLogLevel="Error"
      internalLogIncludeTimestamp="true" >>>>> THIS SHOULD NOT BE HERE <<<<<
      internalLogToConsole = "true"
      internalLogToConsoleError = "true"
      internalLogFile="log/internal-nlog.txt">

  <variable name="AppName" value="test"/>
  <!-- Note! Relative LogRoot for local runs -->
  <variable name="LogRoot" value="log"/>
  <variable name="DatePrefix" value="${date:format=yyyy-MM-dd:universalTime=true}"/>
  <variable name="CompleteLogFile" value="${LogRoot}/${DatePrefix}.${AppName}.complete.log"/>
  <variable name="ErrorLogFile" value="${LogRoot}/${DatePrefix}.${AppName}.error.log"/>
  <variable name="DefaultLayout" value="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${replace-newlines:${exception:format=ToString}}"/>

  <targets>
    <target xsi:type="File" name="completefile" fileName="${CompleteLogFile}" layout="${DefaultLayout}" />
    <target xsi:type="Console" name="logconsole" layout="${DefaultLayout}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="completefile" />
    <logger name="*" minlevel="Trace" writeTo="logconsole" />
  </rules>
</nlog>
```

This initially came up when I noticed that I had accidentally added the `internalLogLevel` attribute twice:
```xml
internalLogLevel="Error"
internalLogLevel="Debug"
```

- What is the current result?
Nothing gets logged, no errors are shown neither in console nor in the internal (NLog) log file; no stack trace anywhere.

- What is the expected result?
By setting `throwConfigExceptions="true"` I'd expect to see an exception somewhere if parsing the config file fails.

- Can you help us by writing an unit test?
Minimal example highlighting the issue: https://github.com/binaryunary/nlog-failure

**Comment by 304NotModified** [comment]
Hi!

Could you please capture the internal log (trace level) - https://github.com/NLog/NLog/wiki/Internal-logging (maybe set it up from code before loading the config)

it will help us fixing the issue

**Comment by binaryunary** [comment]
@304NotModified , here it is:
```
2018-11-22 13:16:50.3131 Debug Hide assemblies for callsite
2018-11-22 13:16:50.3288 Trace Assembly 'NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' will be hidden in callsite stacktrace
2018-11-22 13:16:50.3288 Trace Assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' will be hidden in callsite stacktrace
2018-11-22 13:16:50.3288 Trace Assembly 'Microsoft.Extensions.Logging, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' will be hidden in callsite stacktrace
2018-11-22 13:16:50.3340 Debug Loading config from /home/magi/fiddles/nlog-failure/bin/Debug/netcoreapp2.1/nlog.config
2018-11-22 13:16:50.3688 Error Parsing configuration from /home/magi/fiddles/nlog-failure/bin/Debug/netcoreapp2.1/nlog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing /home/magi/fiddles/nlog-failure/bin/Debug/netcoreapp2.1/nlog.config.  ---> System.Xml.XmlException: Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 7, position 73.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at NLog.Config.NLogXmlElement.Parse(XmlReader reader)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2018-11-22 13:16:50.3688 Warn Failed loading config from /home/magi/fiddles/nlog-failure/bin/Debug/netcoreapp2.1/nlog.config. Invalid XML?
2018-11-22 13:16:50.3688 Debug --- NLog configuration dump ---
2018-11-22 13:16:50.3688 Debug Targets:
2018-11-22 13:16:50.3725 Debug Rules:
2018-11-22 13:16:50.3725 Debug --- End of NLog configuration dump ---
2018-11-22 13:16:50.3725 Trace FindReachableObject<System.Object>:
2018-11-22 13:16:50.3767 Info Found 0 configuration items
2018-11-22 13:16:50.3964 Debug Targets for Program.Runner by level:
2018-11-22 13:16:50.3969 Debug Trace =>
2018-11-22 13:16:50.3969 Debug Debug =>
2018-11-22 13:16:50.3969 Debug Info =>
2018-11-22 13:16:50.3969 Debug Warn =>
2018-11-22 13:16:50.3969 Debug Error =>
2018-11-22 13:16:50.3969 Debug Fatal =>
```

**Comment by 304NotModified** [comment]
and what happend if `      throwConfigExceptions="false"`?

**Comment by binaryunary** [comment]
Nothing, no trace of this exception anywhere.

**Comment by snakefoot** [comment]
When the xml-parser fails to parse the input stream, then NLog should scan the configuration-blob for these strings:

- `throwConfigExceptions="true"`
- `throwExceptions="true"`

And if finding match then it should throw exception. PullRequests are welcome

**Comment by ericnewton76** [comment]
Also, it should try to report the line number where the parser failed.  I'm running into that... I had to turn on throwConfigExceptions to find out the parser isnt parsing correctly, but no line number makes me sad.

Indeed a PR might fix this, if I can find some time I might start one independent of that "other" one...

**Comment by ericnewton76** [comment]
Oh another interesting thing.  The file is still in use as the exception is raised.  Which means probably a dangling file handle perhaps.

I'm paused on the debugger, with the NLogConfigurationException displayed, but the NLog.config is still opened.  I couldnt save and It was bizarre initially then I realized what was going on.

**Comment by 304NotModified** [comment]
close this in favor of https://github.com/NLog/NLog/issues/3178
