### ISSUE TITLE
Error parsing layout shor will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'shor'

### ISSUE THREAD

**Issue by ngohungphuc** [NLog/NLog#3030]
**NLog version**:
NLog.Web.AspNetCore" Version="4.7.0"
NLog Version="4.5.11"

**Platform**: .NET Core 2

**Config file**

![devenv_2018-11-26_22-20-45](https://user-images.githubusercontent.com/13591213/49023302-8791cd00-f1c9-11e8-9ed4-08b7dc3438ff.png)

- What is the current result?

It generate ${currentdir}\Log folder like this and not put into Log folder like I want like 
nlog-all & nlog-own file

![devenv_2018-11-26_22-21-16](https://user-images.githubusercontent.com/13591213/49023333-97111600-f1c9-11e8-9cd6-d5326162f30c.png)

- Please post full exception details (message, stacktrace, inner exceptions)

2018-11-26 22:19:28.2981 Info Message Template Auto Format enabled
2018-11-26 22:19:28.2981 Info Loading assembly: NLog.Web.AspNetCore
2018-11-26 22:19:28.3701 Error Error parsing layout shor will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'shor'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
2018-11-26 22:19:28.3895 Info Adding target File Target[allfile]
2018-11-26 22:19:28.3922 Info Adding target File Target[ownFile-web]
2018-11-26 22:19:28.3922 Info Configured from an XML element in D:\SourceCode\Awesome-CMS-Core\src\AwesomeCMSCore\AwesomeCMSCore\bin\Debug\netcoreapp2.1\nlog.config...
2018-11-26 22:19:28.4205 Info Found 45 configuration items
2018-11-26 22:19:28.6107 Info Message Template Auto Format enabled
2018-11-26 22:19:28.6107 Info Found 45 configuration items
2018-11-26 22:19:28.6107 Info Loading assembly: NLog.Web.AspNetCore
2018-11-26 22:19:28.6107 Error Error parsing layout shor will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'shor'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
2018-11-26 22:19:28.6107 Info Adding target File Target[allfile]
2018-11-26 22:19:28.6107 Info Adding target File Target[ownFile-web]
2018-11-26 22:19:28.6107 Info Configured from an XML element in D:\SourceCode\Awesome-CMS-Core\src\AwesomeCMSCore\AwesomeCMSCore\nlog.config...
2018-11-26 22:19:28.6107 Info Closing old configuration.
2018-11-26 22:19:28.6413 Info Found 45 configuration items

**Comment by snakefoot** [comment]
When NLog loads the config-file, then NLog gives the following error-message:

> LayoutRenderer cannot be found: **'shor'**

When looking at the config-file, then it says:

> fileName="${currentdir}/log/nlog-all-**${shor}**.log"

I'm guessing that it should be:

> fileName="${currentdir}/log/nlog-all-**${shortdate}**.log"

Always a good idea to take the time to read the error messages.

**Comment by ngohungphuc** [comment]
thank you for clearify @snakefoot

**Comment by snakefoot** [comment]
@ngohungphuc Reason is because the `internalLogFile` is not using the NLog-engine to make sure it always works.

The `internalLogFile` is always relative to the current-directory. So in this case then you can just use:

> internalLogFile="/log/internal-nlog.txt"

Alternative solution is to configure the nternalLogFile at runtime (and remove the value from the nlog.config-file):

```c#
NLog.Common.InternalLogger.LogFile = System.IO.Path.Combine(System.IO.Directory.GetCurrentDirectory(), "/log/internal-nlog.txt");
```
