### ISSUE TITLE
Issue with Deploying NLog with Windows Service (VB)

### ISSUE THREAD

**Issue by mrplatypus** [NLog/NLog#3042]
Hi,
I have developed a windows service which uses NLOG to output messages.
The application is developed in Visual Studio 2017 using Visual Basic.
I am using versions:
Product version: 4.5.11
Product Name: NLog v4.5.11
File Version: 4.5.11.8645
All is fine in development, I now need to install to QA.
Before releasing to the QA Team, I want to test that the installation works.

The service installs successfully and runs, however functionality does not work as I expect.
In examining the event viewer, I see some messages:
1)	The windows service gets installed to the program files directory; both Nlog.dll and Nlog.config file are in the same folder;
2)	The service starts;
3)	The service runs with a timer object;
4)	On starting, the event viewer records:
*** START ***
WPOCT DLL::RunProcess Method::[General (Catch-All) Exception Caught: System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\NLog.config'.
File name: 'C:\WINDOWS\system32\NLog.config'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   at NLog.Config.XmlLoggingConfiguration.CreateFileReader(String fileName)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLogger.WPOCT.NLogger.CreateLogFactory()
   at WPOCT.WPOCT.WriteHL7MessageToFile(String HL7Message, Boolean UseNLog, String ErrInfo)
   at WPOCT.WPOCT.RunProcess()

***   END  ***
And:
*** START ***
WPOCT Service::RunProcess::
(General[Catch-All]) Exception encountered: 
System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\NLog.config'.
File name: 'C:\WINDOWS\system32\NLog.config'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   at NLog.Config.XmlLoggingConfiguration.CreateFileReader(String fileName)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLogger.WPOCT.NLogger.CreateLogFactory()
   at WPOCT.WPOCT.WriteHL7MessageToFile(String HL7Message, Boolean UseNLog, String ErrInfo)
   at WPOCT.WPOCT.RunProcess()
   at WPOCT.WPOCT.RunProcess(EventLogger inSvcEventLog, Boolean inWriteMessagesToEventLog)
   at WPOCTService.WPOCTService.RunProcess()
***   END  ***

When I saw the exceptions:

I’ve placed a copy of the NLog.confiig at c:\Windows\System32;
As per the error, I have placed a copy of the NLog.config file in the c:\windows\system32 folder; no joy.
I’ve done some research and found that the filename may not be correct: I’ve read the filename should be: NLog.dll.nlog; so I’ve created a copy both in the windows service folder and at c:\windows\system32 .. Still no joy;
I’ve tried rebooting; no joy;

The config file is the same file I use in dev;
 
Here is my config file content:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Fatal"
      internalLogIncludeTimestamp="true"
      internalLogFile="c:\Temp\WPOCT_Service\OutputFiles\v0.0.0.1\nlog-internal.log"
      internalLogToConsole="false"
      >
  <variable name="logFolder" value="c:\Temp\WPOCT_Service\OutputFiles\v0.0.0.1\v0.0.0.1" />
  <variable name="logExtn" value=".txt" />
  <variable name="logDay" value="${date:format=dd}" />
  <variable name="logDateTime" value="${date:format=yyyy-MMM-dd}" />
  <variable name="sentFileName" value="HL7Messages-${var:logDateTime}${var:logExtn}" />
  <variable name="errorMessagesFileName" value="HL7ErrorMessages-${var:logDateTime}${var:logExtn}" />
  <variable name="sentFileArchiveName" value="HL7MessagesSentArchive" />
  <variable name="errorFileArchiveName" value="HL7MessagesErrorArchive" />
  <targets>
     <target
      name="hl7MessagesProcessedFile"
      xsi:type="File"
      fileName="${var:logFolder}\${var:sentFileName}"
      layout="${message}"
      autoFlush="true"
      encoding="utf-8"
      maxArchiveFiles="30"
      archiveNumbering="Sequence"
      archiveFileName="${var:logFolder}\${var:sentFileArchiveName}.${var:logDateTime}.{#######}.${var:logExtn}"
    />

    <target 
      name="hl7ErrorMessagesFile"
      xsi:type="File"
      fileName="${var:logFolder}\$(var:errorMessagesFileName}"
      layout="${longdate}${newline}${message}" 
      autoFlush="true"       
      encoding="utf-8"
      maxArchiveFiles="30"
      archiveNumbering="Sequence"
      archiveFileName="${var:logFolder}\${var:errorFileArchiveName}.${var:logDateTime}.{#######}.${var:logExtn}"
    />
       

  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="hl7MessagesProcessedFile" />
    <logger name="*" minlevel="Error" writeTo="hl7ErrorMessagesFile" />   
  </rules>
</nlog>

```

- What is the current result?
The service does not output results with NLog.
- What is the expected result?
That the service would process files and output the results using NLog;
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, I have checked there
- Please post full exception details (message, stacktrace, inner exceptions)
Please see content above.
- Are there any workarounds? yes/no
No.
- Is there a version in which it did work? 
Please see content above, I've noted the version there.
- Can you help us by writing an unit test?
I don't feel that a unit test will suffice.
The exception suggests that the dll is not seeing the config file?

Hope someone would help.
Thanks

Dave

**Comment by snakefoot** [comment]
You should never put any NLog.config in `C:\WINDOWS\system32`.

You are doing something special in this method, that doesn't work well:

`NLogger.WPOCT.NLogger.CreateLogFactory()`

Can you show the contents of this method?

**Comment by mrplatypus** [comment]
The only reason why I placed config files in the directory was because of the error in the event viewer;
Rest assured that they will not be left in there.
I fairly convinced its to do with permissions, to read and/or access the config file?
@snakefoot, here you go, the content of the method:
`*** START *** <br>`
`        Private Function CreateLogFactory() As LogFactory<br>`
`<br>`
`            Dim _logFactory As LogFactory = New LogFactory<br>`
`<br>`
`            Try<br>`
`<br>`
`                Dim strConfigFilePath As String = BuildPathToNLogConfig()<br>`
`                _logFactory.Configuration = New XmlLoggingConfiguration(fileName:=strConfigFilePath, ignoreErrors:=False, logFactory:=_logFactory)<br>`
`<br>`
`                If _logFactory.Configuration.AllTargets.Count = 0 Then<br>`
`<br>`
`                    ' an issue has occurred with reading from the configuration file<br>`
`                    Debug.WriteLine("")<br>`
`<br>`
`                End If<br>`
`<br>`
`            Catch ex1 As NLog.NLogConfigurationException<br>`
`<br>`
`                Throw<br>`
`<br>`
`            Catch ex As Exception<br>`
`<br>`
`                Throw<br>`
`<br>`
`            End Try<br>`
`<br>`
`            Return _logFactory<br>`
`<br>`
`        End Function<br>`
`***   END  ***`

**Comment by mrplatypus** [comment]
@snakefoot, okay, the formatting isn't too good on the site, but you should get the gist.

**Comment by mrplatypus** [comment]
@snakefoot 
Thanks for the pointer ..
The use of, "Environment.CurrentDirectory", will default to "C:\Windows\System32"..

I found: 
[https://social.msdn.microsoft.com/Forums/vstudio/en-US/d8eca78c-f645-4897-8259-95e18cd8b47d/how-do-i-get-the-directory-in-which-my-windows-service-is-installed-?forum=csharpgeneral](url)

So by changing the code within, "BuildPathToNLogConfig" to:
`        Private Function BuildPathToNLogConfig() As String`

`            Dim strConfigFilePath As String = System.IO.Path.GetDirectoryName(New System.Uri(System.Reflection.Assembly.GetExecutingAssembly().CodeBase).LocalPath) + "\NLog.config"`
`            Return strConfigFilePath`

`        End Function`

Got over the issue, now returining the windows service deployed folder.

**Comment by mrplatypus** [comment]
@snakefoot : Closing the issue/ticket, thanks.
