### ISSUE TITLE
WebService target with Soap11 protocol does not work with custom action names.

### ISSUE THREAD

**Issue by AlexeyRokhin** [NLog/NLog#3081]
**NLog version**: (e.g. 4.5.11)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 1 / .NET Core 2

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
    <target type="WebService"
            name="loggingService"
            url="http://localhost/logging/loggingservice.svc"
            encoding="UTF-8"
            protocol="Soap11"
            namespace="http://tempuri.org/"
            methodName ="Log"
            preAuthenticate="false" >
      <parameter name="level" layout="1" type="System.Int32"/>
      <parameter name="loggerType" layout="${logger}" type="System.String"/>
      <parameter name="message" layout="${message}" type="System.String"/>
    </target>
  </targets>
  <rules>
    <logger name="*" writeTo="loggingService" minlevel="debug" />
  </rules>
</nlog>

```
The actual action's name is ```http://tempuri.org/ILoggingService/Log```. The target makes action name ```http://tempuri.org/Log``` (namespace + methodName)

- What is the current result? Web service's method is not being invoked.
- What is the expected result? Web service's method is being invoked.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes.
- Please post full exception details (message, stacktrace, inner exceptions)
```
2019-01-14 22:27:55.9415 Error WebServiceTarget(Name=loggingService): Error sending request Exception: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at NLog.Targets.WebServiceTarget.<>c__DisplayClass67_0.<CreateSendContinuation>b__1(IAsyncResult r)
```
- Are there any workarounds? no
- Is there a version in which it did work? No.
- Can you help us by writing an unit test? Yes.

**Comment by 304NotModified** [comment]
methodName  = `ILoggingService/Log` won't work?

**Comment by AlexeyRokhin** [comment]
```methodName = ILoggingService/Log``` gives an exception:
```
2019-01-14 23:26:24.0209 Error Error has been raised. Exception: System.ArgumentException: Invalid name character in 'ILoggingService/Log'. The '/' character, hexadecimal value 0x2F, cannot be included in a name.
   at System.Xml.XmlWellFormedWriter.CheckNCName(String ncname)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at NLog.Targets.WebServiceTarget.HttpPostSoapFormatterBase.WriteContent(MemoryStream ms, Object[] parameterValues)
   at NLog.Targets.WebServiceTarget.HttpPostFormatterBase.PrepareRequest(HttpWebRequest request, Object[] parameterValues)
   at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncContinuation continuation, HttpWebRequest request, Func`2 beginFunc, Func`2 getStreamFunc)
   at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, HttpWebRequest request, AsyncContinuation continuation)
   at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncLogEventInfo logEvent)
   at NLog.Targets.MethodCallTargetBase.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
```

> not sure how NLog otherwise could know the "ILoggingService", that isn't a standard?

Of course, this is a custom wcf logging service. It was developed without any though about NLog existence. The action name of ```Log``` method was not specified in ```OperationContract``` attribute that decorates the method, so WCF generates action name using some conventions and includes the name of the interface where the method is defined.

**Comment by snakefoot** [comment]
Created new PR #3100 as followup.
