### ISSUE TITLE
Unhandled exception when deleting the folder which contains configuration file

### ISSUE THREAD

**Issue by kulcikriu** [NLog/NLog#322]
Hello, I have my Nlog configuration file in special folder. The problem is that when I delete this folder my app crash with such exception:
```
 System.ArgumentException

{"The directory name C:\\dir\\dir is invalid."}

   at System.IO.FileSystemWatcher.set_Path(String value)
   at NLog.Internal.MultiFileWatcher.Watch(String fileName)
   at NLog.Internal.MultiFileWatcher.Watch(IEnumerable`1 fileNames)
   at NLog.LogFactory.ReloadConfigOnTimer(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```
The problem is that the call stack do not include my code, it is pure external (NLog) code. So I do not have any ideas what should I put in try-catch to avoid the crash.

**Comment by 304NotModified** [comment]
This is a bug but with low prio.

**Comment by 304NotModified** [comment]
PR merged
