### ISSUE TITLE
NLog does not send to papertrail with a warning on SendAsync

### ISSUE THREAD

**Issue by slsewall** [NLog/NLog#3313]
NLog version: "4.6.2"

Platform:.Net 4.5

Current NLog config 

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="false" internalLogFile="c:\temp\nlog-internal.log">

  <extensions>
    <add assembly="NLog.Targets.Syslog" />
  </extensions>
  <targets>
    <target name="syslog" type="Syslog">
      <messageCreation>
        <facility>Local7</facility>
          <rfc5424 hostname="${machinename}-Ragnarok" appName="ChatServer-Ragnarok" />

      </messageCreation>
      <messageSend>
        <protocol>TCP</protocol>
        <tcp>
          <server>logs.papertrailapp.com</server>
          <port>REDACTED</port>
          <tls>
            <enabled>true</enabled>
          </tls>
        </tcp>
      </messageSend>
    </target>

    <target name="logfile" xsi:type="File" fileName="file.txt" />
    <target name="logconsole" xsi:type="Console" />

  </targets>

  <rules>
      <logger name="*" minLevel="Trace" appendTo="syslog" />
      <logger name="*" minlevel="Info" writeTo="logconsole" />
      <logger name="*" minlevel="Debug" writeTo="logfile" />
  </rules>
</nlog>

```

I'm getting the following error message on start up though from the internal log:

2019-04-15 13:35:22.3986 Warn SendAsync failed Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NLog.Targets.Syslog.MessageSend.SocketInitializationForWindows.KeepAliveConfigurationIsUpToDate(KeepAliveConfig keepAliveConfig)
   at NLog.Targets.Syslog.MessageSend.SocketInitializationForWindows.ApplyKeepAliveValues(Socket socket, KeepAliveConfig keepAliveConfig)
   at NLog.Targets.Syslog.MessageSend.SocketInitialization.SetKeepAlive(Socket socket, KeepAliveConfig keepAliveConfig)
   at NLog.Targets.Syslog.MessageSend.Tcp.Init()
   at NLog.Targets.Syslog.MessageSend.MessageTransmitter.<PrepareForSendAsync>b__21_0(Task _)
   at NLog.Targets.Syslog.Extensions.TaskExtensions.<>c__DisplayClass0_0`1.<Then>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

But that said this is only happening on our EC2 deployment but not on our local testing.

**Comment by snakefoot** [comment]
@slsewall Nice of you to drop by, but I think you should close this issue and create on for the syslog-target project:

https://github.com/luigiberrettini/NLog.Targets.Syslog

**Comment by slsewall** [comment]
@snakefoot alright, sorry about that!

**Comment by slsewall** [comment]
@snakefoot alright, sorry about that! closing the issue.
