### ISSUE TITLE
System.OutOfMemoryExceptionNLog.Internal.ExceptionHelper.MustBeRethrownImmediately exception

### ISSUE THREAD

**Issue by NikasZalias** [NLog/NLog#3448]
**NLog version**:  4.6.3

**Platform**: .Net 4.6.1

- What is the current result?
`Application crashes`
- What is the expected result?
`Do not crash application`
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
`NO`
- Please post full exception details (message, stacktrace, inner exceptions)
```
System.OutOfMemoryExceptionNLog.Internal.ExceptionHelper.MustBeRethrownImmediately(Exception exception):0
Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at NLog.Internal.ExceptionHelper.MustBeRethrownImmediately(Exception exception)
   at NLog.Common.InternalLogger.Write(Exception ex, LogLevel level, string message, object[] args)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(int id)
```
- Are there any workarounds? yes/no
`NO`
- Is there a version in which it did work? 
`Not sure`
- Can you help us by writing an unit test?
`No`

**Comment by 304NotModified** [comment]
Are you sure this is a NLog issue? We are stopping on a OutOfMemoryException, but most OutOfMemoryExceptions are caused not by NLog (but only logged)

Without NLog, (e.g. remove nlog.config), it there aren't an OutOfMemoryException?

If it's a NLog issue, we need really more info.

**Comment by NikasZalias** [comment]
I don't have more info... I just got a crash report and this is full stacktrace....

**Comment by 304NotModified** [comment]
How do you think we could solve this then?

**Comment by NikasZalias** [comment]
...` Exception of type 'System.OutOfMemoryException' was thrown. at NLog.Internal.ExceptionHelper.MustBeRethrownImmediately(Exception exception) at `... As I see it was thrown by NLog lib.

**Comment by NikasZalias** [comment]
Why stacktrace doesn't give me more detailed info... Don't know...

**Comment by 304NotModified** [comment]
MustBeRethrownImmediately

Rethrows exceptions and doesn't create.

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/blob/7beca26b87ca795b112da9b14fe738e314faf6bc/src/NLog/Internal/ExceptionHelper.cs#L111

**Comment by 304NotModified** [comment]
> Why stacktrace doesn't give me more detailed info... Don't know...

I think there is no memory to record many details

Anyway, out if memory are hard issues. I would recommend to test and isolate the problem.

**Comment by 304NotModified** [comment]
Maybe this is helpful

https://stackoverflow.com/a/3700618/201303
