### ISSUE TITLE
Overriding integer proprety with ${appsetting} configuration results in FormatException

### ISSUE THREAD

**Issue by akiller** [NLog/NLog#3506]
Hi,

When trying to use ${appsetting} to override the SMTPPort of MailTarget it throws an exception due to it not being an integer. I'm assuming NLog attempts to store the "${appsetting}" string against the property when it loads the configuration, and then later parses it to its actual value with the layout renderer. I guess this will effect overriding any property that isn't a string regardless of which target it is.

I took a look through the source to try and figure out how to solve it, then figured it wasn't a simple task!

Thanks

**NLog version**: 4.6.5

**Platform**: .Net 4.7.2

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" throwExceptions="false" internalLogFile="c:\temp\nlog.log"
	internalLogLevel="Error">

  <variable name="VerboseLayout" value="${threadname}|${longdate}|${level:upperCase=true}|${callsite:includSourcePath=true, methodName=true}|${message}"/>
  <variable name="ExceptionVerboseLayoutEmail"
  	value="${threadname}|${VerboseLayout}${newline}${newline}(${stacktrace:topFrames=10})${newline}${newline}${exception:format=ToString}"/>
  
  <targets async="true">
    <target xsi:type="Mail" name="email" html="false" addNewLines="true" subject="Test" from="nlog@example.com" to="nlog@example.com"
      smtpAuthentication="Basic" enableSsl="false" smtpServer="${appsetting:item=SMTPHost}" smtpUsername="" smtpPassword="" smtpPort="${appsetting:item=SMTPPort}"
      layout="${ExceptionVerboseLayoutEmail}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Error" writeTo="email"/>
  </rules>
</nlog>

```

- What is the current result? NLog throws an internal exception when trying to use an ${appsetting} against an integer attribute (e.g., SMTP Port) and the target doesn't get added to NLog.LogManager.Configuration. 
- What is the expected result? The mapped AppSetting configuration is allowed and the specifid port is used
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes
- Please post full exception details (message, stacktrace, inner exceptions)
```
2019-07-09 11:14:37.0557 Error Parsing configuration from C:\SourceControl\Applications\Test.Docker\Portal.Test2.Web\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\SourceControl\Applications\Test.Docker\Portal.Test2.Web\NLog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'SmtpPort' on Mail Target[email] ---> System.Exception: ${appsetting:item=SMTPPort} is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at NLog.Internal.PropertyHelper.TryTypeConverterConversion(Type type, String value, Object& newValue)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.LoggingConfigurationParser.ConfigureObjectFromAttributes(Object targetObject, ILoggingConfigurationElement element, Boolean ignoreType)
   at NLog.Config.LoggingConfigurationParser.ParseTargetElement(Target target, ILoggingConfigurationElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.LoggingConfigurationParser.ParseTargetsElement(ILoggingConfigurationElement targetsElement)
   at NLog.Config.LoggingConfigurationParser.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(ILoggingConfigurationElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```
- Are there any workarounds? I'm guessing I could manually set the port and use LogManager.ReconfigExistingLoggers().
- Is there a version in which it did work? Not that I'm aware of

**Comment by 304NotModified** [comment]
Hi,

smtpport is of type integer and not layout. This means you can't use layout renders for this :(

One option is to change the smtpport with some c# code. 

Another option is to use a `<variable name="myName">` and render it with `${myName}` .  In this case you can't change the value of the variable in code.

**Comment by akiller** [comment]
> 
> 
> Hi,
> 
> smtpport is of type integer and not layout. This means you can't use layout renders for this :(
> 
> One option is to change the smtpport with some c# code.
> 
> Another option is to use a `<variable name="myName">` and render it with `${myName}` . In this case you can't change the value of the variable in code.

Thanks for the reply. Now that you mention it needs to be a layout renderer for it to work I've come across #1234 which I guess this is a duplicate of.

Thanks for the suggestion to use variables, I'll give them a try and see if it works for me.

My use case is so that I can inject/override the port from a random Docker container port. I already have this working for the main SMTP server set in web.config and it would have been great to have used the same setting. I'm using [Configuration Builders](https://github.com/aspnet/MicrosoftConfigurationBuilders) to do app/web.config overriding which may or not be relevant to you.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by snakefoot** [comment]
Created #4435 to resolve this for NLog 5.0
