### ISSUE TITLE
exception renderer fails when used together with ${message}

### ISSUE THREAD

**Issue by goldcode** [NLog/NLog#3508]
exception format renderer works when the layout is 

> ${exception:format=message,data:maxInnerExceptionLevel=10:innerFormat=Message}

but fails when the layout includes a ${message}. failure here means the entire exception details including call stack information is logged.

> ${message} ${exception:format=message,data:maxInnerExceptionLevel=10:innerFormat=Message}

**Version**: NLog v4.6.5

**NLog.Config**
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <targets async="true">
    <target name="foo" 
            xsi:type="File" 
            layout="${exception:format=message,data:maxInnerExceptionLevel=10:innerFormat=Message}"
            fileName="foo.log" />

    <!-- *** with ${message} renderer, see below, exception formatting does not work.
    layout="${message} ${exception:format=message,data:maxInnerExceptionLevel=10:innerFormat=Message}"-->

  </targets>

  <rules>
    <logger name="foo" minlevel="Debug" writeTo="foo"/>
  </rules>

</nlog>
```

**Example Source:**
```
  class Program
    {
        static void Main(string[] args)
        {
            Logger logger = LogManager.GetLogger("foo");
            try
            {             
                fn1();
            }
            catch(Exception e)
            {
                logger.Error(e);
            }            
        }


        static void fn1()
        {
            try
            {
                fn2();
            }
            catch(Exception e)
            {
                var ex = new Exception("Sh*t happens again... fn1()", e);
                ex.Data.Add("data1", "val2");
                throw ex;
            }
            
        }

        static void fn2()
        {
            throw new Exception("Sh*t happens... fn2()");
        }
    }
```

**Comment by 304NotModified** [comment]
> failure here means the entire exception details including call stack information is logged.

Could you please elaborate on that?

I will try to run your example when I'm on my PC.

**Comment by 304NotModified** [comment]
I see the problem.

When only sending one value, the value is marked as "message" and then the whole object is tostringed.

You will get then as result:

```
System.Exception: Sh*t happens again... fn1() ---> System.Exception: Sh*t happens... fn2()
   at NLog.UnitTests.LoggerTests.fn2() in D:\nlog\nlog\tests\NLog.UnitTests\LoggerTests.cs:line 84
   at NLog.UnitTests.LoggerTests.fn1() in D:\nlog\nlog\tests\NLog.UnitTests\LoggerTests.cs:line 71
   --- End of inner exception stack trace ---
   at NLog.UnitTests.LoggerTests.fn1() in D:\nlog\nlog\tests\NLog.UnitTests\LoggerTests.cs:line 77
   at NLog.UnitTests.LoggerTests.Main2(String[] args) in D:\nlog\nlog\tests\NLog.UnitTests\LoggerTests.cs:line 58 Sh*t happens again... fn1() data1: val2
Sh*t happens... fn2()
```

Solution, send always a message, eg.


    logger.Error(e,"my Message");

and then the rendering will be:

```
my Message Sh*t happens again... fn1() data1: val2
Sh*t happens... fn2()
```

This is a know issue and will be fixed in NLog 5. See #1291 and #1034

**Comment by goldcode** [comment]
ok. thanks. i guess i can close it then if it's already been reported.
