### ISSUE TITLE
 Error Error has been raised. Exception: System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by amitsrivastavaa** [NLog/NLog#3536]
Hi, 
I am getting this error on my "nlog-internal.log" file which is **"nlog internalLogFile="d:/logs/MessageExchange/nlog-internal.log"**"

2019-07-29 08:47:39.7089 Error Error has been raised. Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NLog.Internal.PropertiesDictionary.Add(Object key, Object value)
   at NLog.Targets.Gelf.GelfConverter.GetGelfJson(LogEventInfo logEventInfo, String facility)
   at NLog.Targets.Gelf.GelfTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

This is increasing log file size and fulling drive. Please help how to solve this

**Comment by 304NotModified** [comment]
Hi! The gelf target is an external target. The issue seems to be there?

**Comment by 304NotModified** [comment]
What gelf target are you using? Please share your config

**Comment by amitsrivastavaa** [comment]
https://github.com/NLog/NLog/issues/3536


Thanks & Regards,
Amit Kumar Srivastava
Contact# +91 7838368712
Ext : 47000

**Comment by snakefoot** [comment]
@amitsrivastavaa Could you try using [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout)-package together with the network-target (Using NLog ver. 4.6.5 or newer)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog>
  <extensions>
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  <target xsi:type="Network" name="Graylog" address="tcp://xxxxx" lineEnding="Null" layout="${gelf:facility=MyFacility}" />
  <rules>
     <logger name="*" minlevel="Debug" writeTo="Graylog" />
  </rules>
</nlog>
```

Btw. working on a pull-request https://github.com/farzadpanahi/NLog.GelfLayout/pull/13 to improve the GetlfLayout even further (allow one to configure additional fields).

**Comment by snakefoot** [comment]
@amitsrivastavaa [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout) ver. 0.4 have now been released with the ability to add extra fields.
