### ISSUE TITLE
Remoting Issue

### ISSUE THREAD

**Issue by smeegoan** [NLog/NLog#3604]
**NLog version**: NLog 4.6.5

**Platform**: .Net 4.7

Hi,

When using Remoting NLog requires the remoting server to have a reference to NLog or else it will throw an exception.

```
System.Runtime.Serialization.SerializationException: Unable to find assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

Server stack trace: 
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryPar
ser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage r
etMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at RemotingInterface.Foo.GetBar()
   at RemotingClient.Controllers.FooController.GetBar() in C:\\Users\\oso\\Desktop\\lixo\\SimpleSample_Src\\RemotingClient\\Controllers\\FooController.cs:line 23
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

This happens because NLog uses `System.Runtime.Remoting.Messaging.CallContext `instead of `System.Threading.AsyncLocal<INestedContext>` for .NET 4.7 applications (there is no target framework > net45 built).

I created a sample [application ](https://cld.pt/dl/download/c5b40e90-2463-4ffb-8152-242c3e2fb7cb/issue.zip) that shows this issue:

1. Start the server;
2. Start the Client
3. Access http://localhost:5000/Foo

**Comment by snakefoot** [comment]
Strange that NLog affects what is sent together with remoting. Thought it would only transport objects that what wrapped in something that implemented `ILogicalThreadAffinative` Interface :

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.remoting.messaging.ilogicalthreadaffinative

**Comment by snakefoot** [comment]
I guess a workaround is to setup your AspNetCore-application to have IncludeScopes=false until a better version of NLog arrives that can use AsyncLocal on net472:

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-LoggerProvider-Options

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!

**Comment by smeegoan** [comment]
Sorry for the late reply. It was was thanks!

**Comment by ogielee** [comment]
Wow thanks for this! I just wasted couple of hours troubleshooting this and couldn't figure out how NLog is needed for an object that doesn't even reference NLog and why I would need it in the server as, I only meant to use NLog in the client side, which is also a server for a different product.

**Comment by snakefoot** [comment]
@ogielee NLog 5.0 will fix this issue, so using NLog on client-side will cause error on the server-side.
