### ISSUE TITLE
NLog integration in MSTest projects - Question

### ISSUE THREAD

**Issue by Rajkumar28269** [NLog/NLog#3619]
I have an issue integrating NLog in wcf solution. where we have test methods written to reference another project methods which use NLog. I am getting an error saying that test project needs connection string when i do build from Jenkins. However there is no error when i do build from local development machine. 

Error Description: 
```
Test method Test.SomeTest.SomeTest threw exception: 
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
Stack Trace:
    at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString)
   at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString)
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent, String connectionString)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.Log(LogEventInfo logEvent)

**Comment by 304NotModified** [comment]
I would recommend to enable the internal logging for this. https://github.com/nlog/nlog/wiki/Internal-logging#enabling-internal-logging-programmatically

**Comment by Rajkumar28269** [comment]
I have that internal logging as well in NLog.Config File as below.
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogToConsole="false"
      internalLogLevel="Error" internalLogFile="c:\Application.log">
</nlog>

**Comment by 304NotModified** [comment]
If the internal log is empty, you could set it up in code. I guess the NLog.config can't be found as test frameworks move the dll files.

**Comment by Rajkumar28269** [comment]
Do you want me to programmatically do the logging? however my test method has references to other project methods which use NLog that logs to database. The test methods fail when the test methods execution starts after build success.

**Comment by Rajkumar28269** [comment]
Sorry I have couple of questions like 
1.) Do I need to have NLog Nuget Package in MStest project?
2.) I see there are fake assemblies in the mstest project, do I need to remove the existing fake assemblies and add them again?

**Comment by 304NotModified** [comment]
Sorry, missed the questions.



> Sorry I have couple of questions like
> 1.) Do I need to have NLog Nuget Package in MStest project?

Yes

> 2.) I see there are fake assemblies in the mstest project, do I need to remove the existing fake assemblies and add them again?

What fake assemblies?



> Do you want me to programmatically do the logging?

Configure the logging in code is recommend for test projects. See https://github.com/NLog/NLog/wiki/Configure-from-code

**Comment by Rajkumar28269** [comment]
I got this issue fixed now. You can close the question.

Thank you for your assistance.

Regards,
Raj
ESS Agency Pay - Metrics Team
M: (832) 949 2589

**Comment by Rajkumar28269** [comment]
I got this issue fixed now. You can close the question.

Thank you for your assistance.


Regards,
Raj
ESS Agency Pay – Metrics Team
M: (832) 949 2589

**Comment by 304NotModified** [comment]
OK thanks for the feedback!
