### ISSUE TITLE
Programatic database install not working

### ISSUE THREAD

**Issue by mooola** [NLog/NLog#3625]
I'm not having any luck installing a SQLite database programmatically.  I keep getting Exception: System.TypeLoadException: Could not load type 'System.Data.SQLite' from assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

Any help is much appreciated!

**NLog version**: 4.6.7

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant)

 InternalLogger.LogFile = @"c:\test\nlog-internal.log";
            var config = new LoggingConfiguration();
            //LayoutRenderer.Register("username", typeof(UserNameLayoutRenderer));

#if DEBUG
            var consoleTarget = new ColoredConsoleTarget("logconsole");
            consoleTarget.UseDefaultRowHighlightingRules = true;
            consoleTarget.OptimizeBufferReuse = true;

            config.AddTarget(consoleTarget);
            config.AddRuleForAllLevels(consoleTarget);
#endif

            var databaseTarget = new DatabaseTarget("db");
            databaseTarget.KeepConnection = false;  //todo research this one
            databaseTarget.DBProvider = "System.Data.SQLite"; 
            databaseTarget.ConnectionString = @"Data Source=c:\test\Log.sqlite;Version=3;"; //todo put into user data folder
            databaseTarget.CommandType = System.Data.CommandType.Text;
            databaseTarget.CommandText = "INSERT into LogEntries(timestamp, level, callsite, type, message, stacktrace, innerexception, additionalinfo, username) values(@timestamp, @level, @callsite, @type, @message, @stacktrace, @innerexception, @additionalinfo, @username)";

            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@timestamp", "${longdate}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@level", "${level:uppercase=true}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@callsite", "${callsite:filename=true}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@type", "${exception:format=type}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@message", "${exception:format=message}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@stacktrace", "${exception:format=stackTrace}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@innerexception", "${exception:format=:innerFormat=ShortType,Message,Method:MaxInnerExceptionLevel=1:InnerExceptionSeparator=}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@username", "${windows-identity:userName=true:domain=false}"));
            //databaseTarget.Parameters.Add(new DatabaseParameterInfo("@username", "${username}"));
            databaseTarget.Parameters.Add(new DatabaseParameterInfo("@additionalInfo", "${message}"));

            //fileName = "${specialfolder:folder=ApplicationData}/Program/file.txt"

            DatabaseCommandInfo commandInfo = new DatabaseCommandInfo();
            commandInfo.CommandType = System.Data.CommandType.Text;
            commandInfo.Text = "CREATE TABLE LogEntries(logid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, timestamp TEXT, level TEXT, callsite TEXT, type TEXT, message TEXT, stacktrace TEXT, innerexception TEXT, additionalinfo TEXT, username TEXT, platform TEXT, version TEXT)";

            databaseTarget.InstallDdlCommands.Add(commandInfo);
            
            config.AddTarget(databaseTarget);
            config.AddRuleForAllLevels(databaseTarget);

            LogManager.Configuration = config;

            using (var context = new InstallationContext())
            {
                if (databaseTarget.IsInstalled(context) != true)
                {
                    config.Install(context); // internal error logged here
                }
            }

- What is the current result? Exception: System.TypeLoadException: Could not load type 'System.Data.SQLite' from assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

- What is the expected result? database and table created

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
2019-10-13 14:50:38.0971 Error Install of 'Database Target[db]' failed. Exception: System.TypeLoadException: Could not load type 'System.Data.SQLite' from assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at NLog.Targets.DatabaseTarget.SetConnectionType()
   at NLog.Targets.DatabaseTarget.RunInstallCommands(InstallationContext installationContext, IEnumerable`1 commands)
   at NLog.Config.LoggingConfiguration.Install(InstallationContext installationContext)

Internal Log:
2019-10-13 14:50:37.9251 Info Found 52 configuration items
2019-10-13 14:50:38.0831 Info Found 52 configuration items
2019-10-13 14:50:38.0971 Error Install of 'Database Target[db]' failed. Exception: System.TypeLoadException: Could not load type 'System.Data.SQLite' from assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at NLog.Targets.DatabaseTarget.SetConnectionType()
   at NLog.Targets.DatabaseTarget.RunInstallCommands(InstallationContext installationContext, IEnumerable`1 commands)
   at NLog.Config.LoggingConfiguration.Install(InstallationContext installationContext)

**Comment by 304NotModified** [comment]
Have you installed a sqllite package? Which one?

**Comment by mooola** [comment]
Yes, System.Data.SQLite v.1.0.110

**Comment by 304NotModified** [comment]
You could try 

https://github.com/NLog/NLog/wiki/Database-target#microsoftdatasqlite-and-net-core

(So other package and set dbprovider)

**Comment by mooola** [comment]
Bingo!

Changing the dbProvider did the trick!  

from: 
databaseTarget.DBProvider = "System.Data.SQLite"; 

to:
databaseTarget.DBProvider = "System.Data.SQLite.SQLiteConnection, System.Data.SQLite"; 

I really appreciate the quick turn around - especially on a weekend!

**Comment by 304NotModified** [comment]
Cool!
