### ISSUE TITLE
Lock on file when archiving causes severe performance degradation

### ISSUE THREAD

**Issue by timdufrane** [NLog/NLog#3634]
**NLog version**: 4.6.7

**Platform**: .NET 4.5

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Debug" internalLogFile=".\nlog-internal.log" >

  <variable name="brief" value="${longdate} | ${level} | ${callsite} | ${message}"/>
  <variable name="verbose" value="${longdate} | ${machinename} | ${processid} | ${processname} | ${level} | ${callsite} | ${message}"/>

  <targets>
    <target name="file" xsi:type="File"
            layout="${brief}"
            fileName=".\log.log"
            archiveAboveSize="500000"
            archiveFileName=".\log.{#}.log"
            openFileCacheTimeout="10"
            concurrentWrites="false"
            keepFileOpen="true"
            encoding="iso-8859-1" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="file" />
  </rules>
</nlog>
```

- What is the current result?
When performing heavy logging and archiving occurs while file is locked by other process, all threaded program performance is severely degraded.
- What is the expected result?
Little or no loss of program performance when archiver is attempting to archive.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes
- Please post full exception details (message, stacktrace, inner exceptions)
`2019-10-18 12:02:01.3691 Debug FileTarget(Name=file): Do archive file: 'C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.log'
2019-10-18 12:02:01.3691 Info FileTarget(Name=file): Archiving C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\log.log to C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.2.log
2019-10-18 12:02:01.3691 Debug FileTarget(Name=file): Move file from 'C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\log.log' to 'C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.2.log'
2019-10-18 12:02:01.4041 Warn FileTarget(Name=file): Failed to archive file 'C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.log'. Exception: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFileMove(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize, DateTime previousLogEventTimestamp, Boolean initializedNewFile)
2019-10-18 12:02:01.4041 Debug Creating file appender: C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.log
2019-10-18 12:02:01.4041 Debug Watching path 'C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.' filter 'log.log' for changes.
2019-10-18 12:02:01.4041 Debug FileAppender Closing Invalidate - C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.log
2019-10-18 12:02:01.4041 Debug Stopping file watching for path 'C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.' filter 'log.log'
2019-10-18 12:02:01.4041 Info FileTarget(Name=file): Archive mutex not available: C:\Users\xxx\source\repos\NlogTest\NlogTest\bin\Release\.\log.log`
- Are there any workarounds? yes/no
No
- Is there a version in which it did work? 
4.2.3 showed much less of a performance hit because it was not catching exceptions. Regardless, it was enough to be very noticeable.
- Can you help us by writing an unit test?
Not sure of root cause and therefore unable to write a unit test. Currently running some profiling to try and track the cause.

Testing with code for logging:
```c#
static void Main(string[] args)
{
    for (var i = 0; i < 20; i++)
    {
        new Thread(LogStuff).Start(i);
    }

    for (; ; )
    {
        Thread.Sleep(500);
    }
}

static void LogStuff(object param)
{
    var sw = new Stopwatch();
    var log = NLog.LogManager.GetCurrentClassLogger();

    log.Info("Initializing");

    var i = 0;

    sw.Start();
    for (; ; )
    {
        if (i % 25 == 0)
        {
            Console.WriteLine($"{i / 25} {param} {sw.Elapsed}");
            sw.Restart();
        }

        var outLine = $"Hello world {++i} {param}";
        log.Info(outLine);

        Thread.Sleep(5);
    }
}
```
![nlog](https://user-images.githubusercontent.com/1024240/67117861-a1594b80-f1b1-11e9-8093-2df4ee37862e.png)

**Comment by timdufrane** [comment]
Disregard, solving with a buffered async wrapper. Should have RTFMed. Sorry about that.

**Comment by snakefoot** [comment]
Was also my conclusion since NLog ver. 4.2.3 also attempted file-move-operation on every file-write.

When enabling the async-wrapper then it allows the FileTarget to perform batch-writing of multiple logevents in one file-operation. Reducing the number of file-move-operations.
