### ISSUE TITLE
System.InvalidOperationException: Collection was modified 

### ISSUE THREAD

**Issue by andronachev** [NLog/NLog#3804]
Hi,

We started noticing this kind of exception in our .NET Core project: 

```json
{
  "ClassName": "NLog.NLogRuntimeException",
  "Message": "Exception occurred in NLog",
  "Data": {
    "NLog.ExceptionLoggedToInternalLogger": true
  },
  "InnerException": {
    "ClassName": "System.InvalidOperationException",
    "Message": "Collection was modified; enumeration operation may not execute.",
    "Data": {
      "NLog.ExceptionLoggedToInternalLogger": true
    },
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()\r\n   at System.Collections.Generic.List`1.Enumerator.MoveNext()\r\n   at NLog.Targets.ElasticSearch.ElasticSearchTarget.FormPayload(ICollection`1 logEvents)\r\n   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233079,
    "Source": "System.Private.CoreLib",
    "WatsonBuckets": null
  },
  "HelpURL": null,
  "StackTraceString": "   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)\r\n   at NLog.Internal.SingleCallContinuation.Function(Exception exception)\r\n   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)\r\n   at NLog.Targets.ElasticSearch.ElasticSearchTarget.Write(AsyncLogEventInfo logEvent)\r\n   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)\r\n   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)\r\n   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)\r\n   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)\r\n   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)\r\n   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)\r\n   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146233088,
  "Source": "NLog",
  "WatsonBuckets": null
}
```

Which I am not sure if it is a bug in the NLog internal library or something on our side ... but I have seen some other tickets open, related to this exception, in the past (4-5 years ago, and the tickets are closed, so I doubt we have the same issue as those). 

We are using the following packages: 

`<PackageReference Include="NLog" Version="4.6.6" />    
<PackageReference Include="NLog.Targets.ElasticSearch" Version="5.1.0" />
<PackageReference Include="NLog.Web.AspNetCore" Version="4.8.3" />
<PackageReference Include="NLog.Extensions.Logging" Version="1.5.2" />`

In a .NET Core 2.2 project, which is hosted in an Azure Function. 

I'd like to mention one thing; that there is some parallel threading going on in our solution (i.e. I am logging the execution of our function on a parallel thread)... I am not sure if that could cause the issue (because this type of exception is something I've seen in the past where some sort of collection was not thread safe). However I would assume the ILogger framework provided in .NET Core is thread safe

Thoughts ?

Vlad

**Comment by 304NotModified** [comment]
Readable stacktraces:

```
 at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)",
```

Inner:
```

 at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.FormPayload(ICollection`1 logEvents)
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)",
```

If looks like the issue in in  NLog.Targets.ElasticSearch.ElasticSearchTarget. It guess that's this repo: https://github.com/markmcdowell/NLog.Targets.ElasticSearch

**Comment by snakefoot** [comment]
Bug has been found: https://github.com/markmcdowell/NLog.Targets.ElasticSearch/issues/113
