### ISSUE TITLE
NLog creating configuration caching issue

### ISSUE THREAD

**Issue by prkumar112451** [NLog/NLog#3805]
**Problem** - 
A fully function and working encrypting/decrypting of a section in app.config was broken on introducing NLog in our project.

**Steps to reproduce this issue** - 
1. Adding a new section in app.config that needs to be encrypted - 
We had to encrypt few items in appsettings. For this, we separately created a "secureAppSettings" section and used "DataProtectionConfigurationProvider" encryption.

Reference for creating a new section in app.config/web.config:
https://stackoverflow.com/questions/6224732/how-to-encrypt-one-entry-in-web-config

Reference for encrypting the newly created section in app.config:
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings-and-configuration-files?redirectedfrom=MSDN

2. On trying to read this section in our code without NLog. It is working perfectly fine.

3. We decided to introduce NLog and kept NLog configuration section in our app.config

4. It is logging perfectly although while trying to decrypt the encrypted "secureAppSettings" section.. It started throwing below exception:

**Error Message**: 
Unrecognized attribute 'configProtectionProvider'. Note that attribute names are case-sensitive. (C:\Users\prabhat veebrij\source\repos\EncryptDecrypt-Pulks\EncryptDecrypt-Pulks\bin\Debug\EncryptDecrypt-Pulks.exe.Config line 38)

**StackTrace**:
```
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at EncryptDecrypt_Pulks.Program.ReadFromSecureAppSettings() in C:\Users\prabhat veebrij\source\repos\EncryptDecrypt-Pulks\EncryptDecrypt-Pulks\Program.cs:line 44
```

**Workaround** - 
To resolve this issue, we tried to refresh the section after encrypting using RefreshSection

Reference:
https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.refreshsection?view=netframework-4.8

It did not work. A blog mentioned that RefreshSection does not cleanly refreshes the configuration and it is better to use reflection and do this refresh manually.

Reference:
https://andybrennan.wordpress.com/2014/06/05/unrecognized-attribute-configprotectionprovider-after-encrypting-app-config/

On applying this hard refresh, it started working fine.

**Comment by 304NotModified** [comment]
Hi,

Sorry for the late response.

It this really a NLog issue?
