### ISSUE TITLE
Nlog DatabaseTarget stops logging after reseed

### ISSUE THREAD

**Issue by Suresh9sb** [NLog/NLog#3919]
Hi! Thanks for reporting this feature/bug/question! 

we have using Nlog version 4.5.10 for logging the details from web application and windows services. Logging worked fine (logs in to sql db and file) but suddenly stopped logging into the sql db.log table and not seen any errors in eventlogs. (at the same time i see logs in logfile)

If was happening quite few times 2 times before,

Resolution : deleted the log table and created it again it started logging into the sqlserver log table.

we are running job everyday to remove old data logs n days less and reset the seeding. 
DBCC CHECKIDENT (log, RESEED, 0);
 is this causing issue to stop. 

but it does not happened very often only 3 times in 9 months. 

Also please let me know steps to find reason why it got halted or stopped

Note: It looks similar to this issue https://github.com/NLog/NLog/issues/1997 

Thanks

**Comment by 304NotModified** [comment]
Please check the [internal log](https://github.com/NLog/NLog/wiki/Internal-logging). Enable it for Warning at least, and the next time, please post it here :)

**Comment by 304NotModified** [comment]
> Resolution : deleted the log table and created it again it started logging into the sqlserver log table.

Sounds like a timeout?

**Comment by Suresh9sb** [comment]
Hi Team, 

As specified, I have enabled  internal log and got below errors.  with logs I figured out the issue is primary key error and it is occured due to sql job which run everyday for deleting old records and reset the seed as show below 

**Root Cause :- **
we are running job everyday to remove old data logs n days less and reset the seeding.
DBCC CHECKIDENT (log, RESEED, 0);

**Resolution:-** 
Setting back reseed with current seed value in the column value it started inserting records.

**Internal Errors:-**
2020-04-25 00:12:39.3469 Error Error parsing layout aspnet-request will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-request'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
2020-04-25 00:12:39.4230 Error DatabaseTarget(Name=sqldatabaselog): Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): **Violation of PRIMARY KEY constraint 'PK_dbo.Log'. Cannot insert duplicate key in object 'dbo.Log'. The duplicate key value is (417531).**
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
ClientConnectionId:ee275dc7-0156-423b-a5c8-b2e12cd01e34

**Comment by 304NotModified** [comment]
> but I want to reseed inorder to avoid max number (in case int / big int) if you have any other way please do let me know.

Use a guid/uniqueidentifier?

**Comment by Suresh9sb** [comment]
yes we have multiple services each logs lots of data and it is real time tracking we are using nlog to trace out if for issues validations. 

Problem is that if we dont delete log table size increases drastically

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info -
 thanks!
