### ISSUE TITLE
NLog DatabaseTarget Not Displaying Error in InternalLog On 4.7

### ISSUE THREAD

**Issue by taldorblackfire** [NLog/NLog#3936]
**NLog version**: (e.g. 4.7.0)

**Platform**:  .Net 4.5

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">
  <variable name="myvar" value="myvalue"/>
  <targets>
    <target name="ErrorLogging" xsi:type="Database"
            dbUserName="Layout"
            dbProvider="System.Data.SqlClient"
            connectionString="Data Source=TestServer Initial Catalog=TestDB; User Id=********; Password=**********;"
            installConnectionString="Layout"
            commandText="INSERT INTO dbo.ErrorLogging(log_application, log_date, log_level, log_logger, log_message,
                                                               log_machine_name, log_user_name, log_call_site, log_thread, 
                                                               log_exception, log_stacktrace) 
                                                               
                                                               values('Test', @time_stamp, @level, @logger, @message,
                                                                      @machinename, @user_name, @call_site, @threadid, 
                                                                      @log_exception, @stacktrace);">
      <parameter name="@time_stamp" layout="${longdate}"/>
      <parameter name="@level" layout="${level}"/>
      <parameter name="@logger" layout="${logger}"/>
      <parameter name="@message" layout="${message}"/>
      <parameter name="@machinename" layout="${machinename}"/>
      <parameter name="@user_name" layout="${windows-identity:domain=true}"/>
      <parameter name="@call_site" layout="${callsite:filename=true}"/>
      <parameter name="@threadid" layout="${threadid}"/>
      <parameter name="@log_exception" layout="${exception}"/>
      <parameter name="@stacktrace" layout="${stacktrace}"/>
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="ErrorLogging"/>
  </rules>
</nlog>
```
- What is the current result? No error is thrown.
- What is the expected result? An error should have been thrown.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes
- Please post full exception details (message, stacktrace, inner exceptions) 
No errors were thrown. However, when I reverted to version 4.5.8 I received the following: 

```
Error DatabaseTarget(Name=ErrorLogging): Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'system_logging_guid', table 'TestDB.dbo.ErrorLogging'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
ClientConnectionId:6771a95f-1a12-4543-ac56-91e1d844737d
Error Number:515,State:2,Class:16
```
- Are there any workarounds? No
- Is there a version in which it did work? 4.5.8
- Can you help us by writing an unit test? I essentially had an issue with the table design in the database itself. I missed setting default id for a couple of components, which prevented a new record from being inserted. I had to roll back to 4.5.8 to get NLog to throw an error so I could see the issue. Once I discovered the issue I was able to get it fixed immediately.

**Comment by snakefoot** [comment]
Probably a change introduced with adding support for DbType on the Database-Parameters in NLog 4.6:

Database target: support for DbType for parameters (including SqlDbType) - #2899 + #3085 + #3091

Must admit I think it is great that it doesn't throw exceptions, but if the DatabaseTarget fails writing to the database without any errors reported, then it sounds like a bug. Can you verify if insert-row succeeds when providing invalid Guid-value?

**Comment by 304NotModified** [comment]
FYI, There is only 1 catch with internallog (or installationlog): https://github.com/NLog/NLog/blob/ad48c9aee10c49ed2f7d45547d7bb2a408d260b1/src/NLog/Targets/DatabaseTarget.cs#L678-L691

**Comment by 304NotModified** [comment]
> * Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes

So is there error in the internal log?

**Comment by taldorblackfire** [comment]
I did check, no error. It only appeared in the log when I rolled back to 4.5.8 as I stated in my comment.

**Comment by snakefoot** [comment]
@taldorblackfire Can you verify if insert-row succeeds when providing invalid Guid-value?

**Comment by snakefoot** [comment]
@taldorblackfire Can you explain a little more about your setup and the column `system_logging_guid` ? Since the DatabaseTarget-config you have shown here has no column named `system_logging_guid`.

**Comment by taldorblackfire** [comment]
@snakefoot The column is a unique identifier in my table structure that should have been auto-generated with a default value upon row insertion which is why it is not in my NLog configuration. The problem was there was no error recorded when using version 4.7 of NLog indicating that was the problem. I was puzzled as to why I was getting no records entered into the database. I decided that maybe it was the version so I rolled back to 4.5.8 and tried that version and suddenly received that error. I had missed assigning the default value for the system_logging_guid when setting up the table.
No other changes were made other than the versions.

**Comment by snakefoot** [comment]
@taldorblackfire I cannot reproduce your problem. Running NLog 4.7 and this is the output in my internallogger-console:

```
2020-05-01 21:36:53.0961 Trace DatabaseTarget(Name=ErrorLogging): Executing Text: INSERT INTO dbo.Messages(Timestamp, Message, Level)                                                                                                                               values(@time_stamp, @message, @level);
2020-05-01 21:36:53.1041 Trace   DatabaseTarget: Parameter: '@time_stamp' = '05/01/2020 21:36:52' (DateTime)
2020-05-01 21:36:53.1041 Trace   DatabaseTarget: Parameter: '@message' = 'Hello World 0' (String)
2020-05-01 21:36:53.1041 Trace   DatabaseTarget: Parameter: '@level' = 'Info' (String)
2020-05-01 21:36:53.3122 Error DatabaseTarget(Name=ErrorLogging): Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Guid', table 'NLog.dbo.Messages'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.ExecuteDbCommandWithParameters(LogEventInfo logEvent, IDbConnection dbConnection, IDbTransaction dbTransaction)
   at NLog.Targets.DatabaseTarget.WriteLogEventToDatabase(LogEventInfo logEvent, String connectionString)
ClientConnectionId:62e96382-bbf0-4198-b482-3990d56b086e
Error Number:515,State:2,Class:16
```

And this is the **Exception Unhandled** that I'm getting when running with debugger:
```
System.Data.SqlClient.SqlException: 'Cannot insert the value NULL into column 'Guid', table 'NLog.dbo.Messages'; column does not allow nulls. INSERT fails.
The statement has been terminated.'

This exception was originally thrown at this call stack:
	System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
	System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, bool, bool)
	System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, out bool)
	System.Data.SqlClient.SqlCommand.FinishExecuteReader(System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.RunBehavior, string, bool, bool, bool)
	System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, bool, bool, int, out System.Threading.Tasks.Task, bool, bool, System.Data.SqlClient.SqlDataReader, bool)
	System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, bool, string, System.Threading.Tasks.TaskCompletionSource<object>, int, out System.Threading.Tasks.Task, out bool, bool, bool)
	System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(System.Threading.Tasks.TaskCompletionSource<object>, string, bool, int, out bool, bool, bool)
	System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
	NLog.Targets.DatabaseTarget.ExecuteDbCommandWithParameters(NLog.LogEventInfo, System.Data.IDbConnection, System.Data.IDbTransaction)
	NLog.Targets.DatabaseTarget.WriteLogEventToDatabase(NLog.LogEventInfo, string)
    ...
    [Call Stack Truncated]
```

Think you have to provide some more evidence.

**Comment by taldorblackfire** [comment]
Interesting, I just now did a test. It seems that I missed the spot where
