### ISSUE TITLE
Net Core 3.1 Nlog Issue  (using MySQL)

### ISSUE THREAD

**Issue by ronaldo-o-reis** [NLog/NLog#3948]
I am trying to migrate from Net Core 2.2 to Net Core 3.1

After solving a lot of problem I have this one and was unable to find solution until now.

The exception is:

2020-05-05 15:08:52.2508 Warn Type load exception. Exception: System.TypeLoadException: Could not load type 'System.Web.IHttpModule' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
2020-05-05 15:08:53.3247 Error DatabaseTarget(Name=allDb_wrapped): Error when writing to database. Exception: System.IO.FileNotFoundException: Could not load file or assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'. The system cannot find the file specified.
File name: 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.Driver.LoadServerProperties(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString, LogEventInfo logEventInfo)
   at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString, LogEventInfo logEventInfo)
   at NLog.Targets.DatabaseTarget.WriteLogEventToDatabase(LogEventInfo logEvent, String connectionString)

I have added the extendio to nlog-config:

  <extensions>
    <add assembly="NLog.Web" />
    <add assembly="NLog.Web.AspNetCore" />
  </extensions>

Any thoughts?

**Comment by 304NotModified** [comment]
Don't include NLog.Web. That's for ASP.NET non-core only.

So include only NLog.Web.AspNetCore
