### ISSUE TITLE
Extend typed layout so it recognizes string parses

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3994]
Follow up on #3656 

Extend typed layout so it recognizes string parses

Currently this doesn't work:

```c#
[Fact]
public void ComplexTypeTestWithStringConversion()
{
    // Arrange
    var value = "utf8";
    var layout = CreateLayoutRenderedFromProperty<Encoding>();
    var logEventInfo = CreateLogEventInfoWithValue(value);

    // Act
    var result = layout.RenderToValueOrDefault(logEventInfo);

    // Assert
    Assert.Equal("utf8", result.EncodingName);
}
 ```

error:

```        
System.InvalidCastException
Invalid cast from 'System.String' to 'System.Text.Encoding'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at NLog.Common.ValueConverter.Convert(Object propertyValue, Type propertyType, String format, IFormatProvider formatProvider) in D:\nlog\NLog\src\NLog\Common\ValueConverter.cs:line 91
   at NLog.Layouts.Layout`1.TryConvertTo(Object raw, T& value) in D:\nlog\NLog\src\NLog\Layouts\Typed\Layout.cs:line 129
   at NLog.Layouts.Layout`1.TryConvertRawToValue(Object raw, T& value) in D:\nlog\NLog\src\NLog\Layouts\Typed\Layout.cs:line 266
   at NLog.Layouts.Layout`1.TryGetRawValueIntern(LogEventInfo logEvent, T& rawValue) in D:\nlog\NLog\src\NLog\Layouts\Typed\Layout.cs:line 237
   at NLog.Layouts.Layout`1.RenderToValueInternal(LogEventInfo logEvent, StringBuilder reusableBuilder) in D:\nlog\NLog\src\NLog\Layouts\Typed\Layout.cs:line 206
   at NLog.Layouts.Layout`1.NLog.Layouts.IRenderable<T>.RenderToValue(LogEventInfo logEvent) in D:\nlog\NLog\src\NLog\Layouts\Typed\Layout.cs:line 187
   at NLog.Layouts.RenderableExtensions.RenderToValueOrDefault[T](Layout`1 l, LogEventInfo logEvent, T defaultValue) in D:\nlog\NLog\src\NLog\Layouts\Typed\RenderableExtensions.cs:line 60
   at NLog.UnitTests.Layouts.Typed.LayoutTests.ComplexTypeTestWithStringConversion() in D:\nlog\NLog\tests\NLog.UnitTests\Layouts\Typed\LayoutTests.cs:line 170
```

while string to int does work.

The logic for converting string to Encoding (and other stuff) is inside `PropertyHelper`

**Comment by 304NotModified** [comment]
The same counts for lists, but maybe this is tricky?

        [Fact]
        public void ComplexTypeTestWithStringConversion_List()
        {
            // Arrange
            var value = "1,2,3";
            var layout = CreateLayoutRenderedFromProperty<List<int>>();
            var logEventInfo = CreateLogEventInfoWithValue(value);

            // Act
            var result = layout.RenderToValueOrDefault(logEventInfo);

            // Assert
            Assert.Equal(new List<int> { 1, 2, 3 }, result);
        }

**Comment by snakefoot** [comment]
I'm fine with not supporting `Layout<List<int>>` in the first implementation. Lets start with simple values, and see how it evolves from there.
