### ISSUE TITLE
LogEventInfo object null when using custom target

### ISSUE THREAD

**Issue by alefischer13** [NLog/NLog#4008]
**NLog version**: 4.7.2+024896f64b840a743d3fd89e29c2186681e7795f

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
<target name="File" xsi:type="File" fileName="Logs\Event.log">
        <layout xsi:type="JsonLayout">
          <attribute name="time" layout="${longdate}" />
          <attribute name="level" layout="${level:upperCase=true}" />
          <attribute name="exception" layout="${exception:format=toString}" />
          <attribute name="message" layout="${message}" />
        </layout>
      </target>
<target xsi:type="CustomTarget" name="CustomTargetName" providerId="<someGuid>">
        <layout xsi:type="JsonLayout">
          <attribute name="Timestamp" layout="${longdate}" />
          <attribute name="Level" layout="${level:upperCase=true}" />
          <attribute name="Logger" layout="${logger}" />
          <attribute name="CallSite" layout="${callsite}" />
          <attribute name="LineNumber" layout="${callsite-linenumber}" />
          <attribute name="Message" layout="${message}" />
          <attribute name="Exception" layout="${exception:format=toString}" />
          <attribute name="ExceptionData" layout="${exception:format=Data}" />
</target>
  </targets>
  <rules>
      <logger name="*" minlevel="Trace" writeTo="File" />
      <logger name="*" minlevel="Trace" writeTo="CustomTargetName" />
  </rules>
</nlog>

```

- What is the current result?

NLog is writing to the file target correctly, but not to my custom target (writes to ETW internally)

- What is the expected result?

Successfully being able to access LogEventInfo elements in protected override void Write(LogEventInfo logEvent)

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes

- Please post full exception details (message, stacktrace, inner exceptions)

Error CustomTarget Target[CustomTargetName]: Error has been raised. Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Wpa.Libs.EtwLogging.NLogEtwTarget.Write(LogEventInfo logEvent) in C:<path>/CustomTarget.cs:line 27
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

- Are there any workarounds? yes/no

CustomTarget.Write(LogEventInfo logEvent) works if I don't extract values from logEvent.

- Is there a version in which it did work?

No
 
- Can you help us by writing an unit test?

Not familiar with repo

**Comment by 304NotModified** [comment]
Please share the code of CustomTarget, the bug in in there?
