### ISSUE TITLE
Layout Renderer does not work

### ISSUE THREAD

**Issue by NimaFx** [NLog/NLog#4014]
**NLog version**: 4.7.2

**Platform**:  .NET Core 2 

```<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Debug" internalLogFile="D:\nlog-internal.log">
  
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <variable name="LogDir" value="${aspnet-appbasepath}\wwwroot\app_data" />
  
  <targets>
    <target name="file" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
      <target name="logfile" xsi:type="File" encoding="utf-8" layout="${longdate} ${level} ${trace-id} ${message} ${newline} ${exception:format=type,message,method,StackTrace:maxInnerExceptionLevel=10:innerFormat=shortType,message,StackTrace,method}" fileName="${LogDir}\Logs.log" archiveNumbering="Rolling" maxArchiveFiles="150" archiveAboveSize="1048576" archiveFileName="${LogDir}\Logs_{#######}.log" />
    </target>
    <target name="error" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
      <target name="errorLogfile" xsi:type="File" encoding="utf-8" layout="${longdate} ${level} ${trace-id} ${message} ${newline} ${exception:format=type,message,method,StackTrace:maxInnerExceptionLevel=10:innerFormat=shortType,message,StackTrace,method}" fileName="${LogDir}\ErrorLogs.log" archiveNumbering="Rolling" maxArchiveFiles="50" archiveAboveSize="1048576" archiveFileName="${LogDir}\ErrorLogs_{#######}.log" />
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="file" />
    <logger name="*" minlevel="Error" writeTo="error" />
  </rules>
</nlog>
```

```
  LogManager.Setup()
      .SetupExtensions(s =>
              s.RegisterLayoutRenderer("trace-id", (logevent) => "A")
       );

  var logger = LogManager.Setup().GetCurrentClassLogger();
```

**Internal logger:**
2020-06-16 09:56:28.4955 Error Error parsing layout trace-id will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'trace-id'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name, Nullable`1 throwConfigExceptions)

and also It never worked, not in other projects or other versions of nlog!!!

**Comment by snakefoot** [comment]
I'm guessing that you are calling `RegisterLayoutRenderer` after having created the first Logger-object.

NLog is very eager about automatically loading the NLog.config but when you want to register custom extensions, then you need to ensure that it happens as first thing before creating any NLog Logger-objects.

**Comment by snakefoot** [comment]
Have your question been answered?
