### ISSUE TITLE
NLog in powershell script

### ISSUE THREAD

**Issue by maxdanc** [NLog/NLog#4093]
Hi to all, i writed a simple psw script, here code [Nlog_test.txt](https://github.com/NLog/NLog/files/5107732/Nlog_test.txt)

If i run it on psw 5.1 version (legacy) it's all ok ... message are printed on udp, file log, oracle db etc etc, but if i run on core environment (3.0) i have this exception:
"Line |
  22 |  $logger.Error("test")
     |  ~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Error" with "1" argument(s): "Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights,
     | System.IO.FileShare, Int32, System.IO.FileOptions)'."

And here from Nlog internal log:
2020-08-21 09:26:31.2559 Debug Creating file appender: D:\Lavori\SD\logs\TESTNLog.ps1.log
2020-08-21 09:26:31.2810 Debug Failed to create sharable mutex processes Exception: System.MissingMethodException: Method not found: 'Void System.Threading.Mutex..ctor(Boolean, System.String, Boolean ByRef, System.Security.AccessControl.MutexSecurity)'.
   at NLog.Internal.FileAppenders.BaseMutexFileAppender.ForceCreateSharableMutex(String name)
   at NLog.Internal.PlatformDetector.get_RunTimeSupportsSharableMutex()
2020-08-21 09:26:31.3101 Debug Mutex for file archive not supported
2020-08-21 09:26:31.3116 Warn Failed to create file appender: D:\Lavori\SD\logs\TESTNLog.ps1.log Exception: System.MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.
   at NLog.Internal.FileAppenders.WindowsMultiProcessFileAppender.CreateAppendOnlyFile(String fileName)
   at NLog.Internal.FileAppenders.WindowsMultiProcessFileAppender..ctor(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.WindowsMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.CreateAppender(String fileName, Int32 freeSpot)
 
i know that powershell isn't fully supported from nlog but is there a work-around / fix?
Thank's.

**Comment by maxdanc** [comment]
Thank you Snakefoot!! it was exactly as you said! i updated nlog config and script works fine!
