### ISSUE TITLE
ExceptionLayoutRenderer doesn't append AggregateException's own stack trace when using ToString RenderingFormat

### ISSUE THREAD

**Issue by liorss18** [NLog/NLog#4150]
- **NLog version**: 4.7.5

- **Platform**: .NET Core, but by looking on the source code it seems it happens on other platforms as well.

- **Current NLog config** 

```xml
<?xml version="1.0" ?>
<nlog>
<targets>
    <target
       name="consoleError"
       type="ColoredConsole"
       layout="${message} ${exception:format=toString}"/>
</targets>
<rules>
    <logger name="app" MinLevel="Error" appendTo="consoleError" />
</rules>
</nlog>
```

- **Current result:**

```
Task Error. System.InvalidCastException: Inner exception
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.<>c.<NestedFunc>b__2_0() in ExceptionRendererTest.cs:line 55
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)    at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.<>c.<NestedFunc>b__2_0() in ExceptionRendererTest.cs:line 55
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

- **Expected result (look at the repeated lines at the bottom of the stack trace):**
This is the result of doing aggregateException.Tostring() in code.
```
Task Error. System.AggregateException: One or more errors occurred. (Inner exception)
 ---> System.InvalidCastException: Inner exception
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.<>c.<NestedFunc>b__1_0() in ExceptionRendererTest.cs:line 37
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 37
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.NestedFunc(Int32 recursion) in ExceptionRendererTest.cs:line 39
   at DoubleVerify.TP.Service.NetCoreApp.Tests.ExceptionRendererTest.TestAggEx() in ExceptionRendererTest.cs:line 25
```

- **Are there any workarounds?** No, unless writing a custom renderer.
- **Is there a version in which it did work?** Not that I know of.
- **Can you help us by writing a unit test?**
Yes. The following code is the unit test I made that generated the "current result" depicted above.
```c#
[Test]
public void TestAggEx()
{
    try
    {
        int result = NestedFunc(10);
    }
    catch (Exception e)
    {
        LogManager.LoadConfiguration("nlog.config")
            .GetLogger("app")
            .Error(e, "Task Error.");
    }
}

private int NestedFunc(int recursion)
{
    if(recursion-- == 0)
        return Task<int>.Factory.StartNew(() => throw new InvalidCastException("Inner exception"))
            .Result;
    return NestedFunc(recursion);
}
```
- **Suggested fix:**
[In this code line](https://github.com/NLog/NLog/blob/dev/src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs#L325) _currentException_ is the innerException when _aggregateException_ is of type AggregateException. When _renderingFormat_ is "toString" pass _aggregateException_ instead of _currentException_ in the second argument of _ currentRenderFunction._.
Haven't tested this fix suggestion, just looked at the code a bit, so any other suggestion is welcome.

Thanks

**Comment by snakefoot** [comment]
Could you include the full unit-test?

NLog Exception-LayoutRenderer is using Flatten to remove the wrapper: "AggregateException: One or more errors occurred." and also handling nested AggregateExceptions (InnerExceptions contains more AggregateException)

https://codeblog.jonskeet.uk/2010/11/03/propagating-multiple-async-exceptions-or-not/

**Comment by liorss18** [comment]
Yes, edited the pose, see unit test code section.

**Comment by liorss18** [comment]
Yes, edited the pose, see unit test code section.
The "AggregateException: One or more errors occurred" in the expected result is not what I'm referring to so please ignore this line. The missing part from the actual result is the bottom part of the expected result.

**Comment by snakefoot** [comment]
Modified the unit-test to this:

```csharp
        [Fact]
        public void NestedExceptionWithStackTraceAsyncTest()
        {
            var t1 = Task.Run(() => GetNestedExceptionWithStackTraceAsync("Life is hard"));
            var t2 = Task.Run(() => GetNestedExceptionWithStackTraceAsync("No one survives"));
            try
            {
                Task.WaitAll(t1, t2);
            }
            catch (AggregateException ex)
            {
                var layoutRenderer = new ExceptionLayoutRenderer() { Format = "ToString" };
                var logEvent = LogEventInfo.Create(LogLevel.Error, null, null, (object)ex);
                var result = layoutRenderer.Render(logEvent);
            }
        }

        private Exception GetNestedExceptionWithStackTraceAsync(string exceptionMessage)
        {
            Func<int> innerAction = () => throw new ApplicationException(exceptionMessage);
            NestedFunc(2, innerAction);
            return null;
        }

        private int NestedFunc(int recursion, Func<int> innerAction)
        {
            if (recursion-- == 0)
                return System.Threading.Tasks.Task<int>.Factory.StartNew(() => innerAction.Invoke())
                    .Result;
            return NestedFunc(recursion, innerAction);
        }
```

Output when using `Flatten()` because of #1738:

```
System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.ApplicationException: No one survives
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

Output when not using `Flatten()`:

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 918
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 918
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.GetNestedExceptionWithStackTraceAsync(String exceptionMessage) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<NestedExceptionWithStackTraceAsyncTest>b__28_0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 826
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedExceptionWithStackTraceAsyncTest() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 830
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 918
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 918
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.GetNestedExceptionWithStackTraceAsync(String exceptionMessage) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<NestedExceptionWithStackTraceAsyncTest>b__28_0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 826
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
<---

---> (Inner Exception #1) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: No one survives
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 918
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 918
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.GetNestedExceptionWithStackTraceAsync(String exceptionMessage) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<NestedExceptionWithStackTraceAsyncTest>b__28_1() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 827
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: No one survives
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 908
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 916
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
<---
```

I guess you could make a PullRequest with SkipFlatten.

**Comment by snakefoot** [comment]
When using the more simple unit-test:

```c#
        [Fact]
        public void NestedExceptionWithStackTraceAsyncTest()
        {
            var t1 = Task.Run(() => GetNestedExceptionWithStackTraceAsync("Life is hard"));
            try
            {
                t1.Wait();
            }
            catch (AggregateException ex)
            {
                var layoutRenderer = new ExceptionLayoutRenderer() { Format = "ToString" };
                var logEvent = LogEventInfo.Create(LogLevel.Error, null, null, (object)ex);
                var result = layoutRenderer.Render(logEvent);
            }
        }
```

The primary exception:

```
System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

The exception Flatten():

```
System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

The full exception:

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 919
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 919
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.GetNestedExceptionWithStackTraceAsync(String exceptionMessage) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 910
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<NestedExceptionWithStackTraceAsyncTest>b__28_0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 826
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedExceptionWithStackTraceAsyncTest() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 831
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 919
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.NestedFunc(Int32 recursion, Func`1 innerAction) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 919
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.GetNestedExceptionWithStackTraceAsync(String exceptionMessage) in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 910
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<NestedExceptionWithStackTraceAsyncTest>b__28_0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 826
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Life is hard
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass33_0.<GetNestedExceptionWithStackTraceAsync>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 909
   at NLog.UnitTests.LayoutRenderers.ExceptionTests.<>c__DisplayClass34_0.<NestedFunc>b__0() in C:\Users\snakefoot\source\repos\NLog\tests\NLog.UnitTests\LayoutRenderers\ExceptionTests.cs:line 917
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
<---
```

**Comment by snakefoot** [comment]
I guess you could make a PullRequest with SkipFlatten.

**Comment by snakefoot** [comment]
Btw. curious what you expect from `:maxInnerExceptionLevel=100` and `format=tostring`. Should it perform ToString of all nested-exceptions ? Will the outer-exception not automatically call ToString on the inner-exception ? Thus giving duplicate-output ?

**Comment by liorss18** [comment]
Not sure I understand the fix you are proposing by SkipFlatten.
What's wrong by just doing .ToString() on the aggregate exception without iterating on the inner exceptions? If that is the fix we go with, it makes ```maxInnerExceptionLevel``` redundant in case ```format=tostring``` is requested, and should be ignored.

**Comment by liorss18** [comment]
FYI
Edited the main post.
Removed ```,stacktrace:maxInnerExceptionLevel=100``` in the nlog.config as it is irrelevant to reproduce the issue.

**Comment by snakefoot** [comment]
Suggesting that you make a pull request that adds the boolean option SkipFlatten with default value false. So primaryException becomes the input exception without casting to AggregatedException.


Sent from my Sony Xperia


---- liorss18 wrote ----


Not sure I understand the fix you are proposing by SkipFlatten.
What's wrong by just doing .ToString() on the aggregate exception without iterating on the inner exceptions? If that is the fix we go with, it makes maxInnerExceptionLevel redundant in case format=tostring is requested, and should be ignored.

**Comment by snakefoot** [comment]
Created PR #4153

**Comment by snakefoot** [comment]
@liorss18 Can you confirm that #4153 would resolve this issue?

**Comment by snakefoot** [comment]
@liorss18 Excellent. Thank you for the confirmation.

**Comment by snakefoot** [comment]
Merging #4153 has resolved this issue.

**Comment by snakefoot** [comment]
NLog 4.7.6 has beeen released, with the new option `flattenexception`

https://www.nuget.org/packages/NLog/4.7.6/
