### ISSUE TITLE
Can't log message at the AppDomain.CurrentDomain.ProcessExit. and ${aspnet-request-posted-body} is always empty

### ISSUE THREAD

**Issue by 835718973** [NLog/NLog#4540]
**NLog version**: 4.7.10
**Platform**:  .NET Core 3.1
![image](https://user-images.githubusercontent.com/20808204/131326127-bb488a0a-b404-4656-b284-7f59441c7595.png)
![image](https://user-images.githubusercontent.com/20808204/131326167-35e07d9f-faf8-4629-9003-dc6be3b5d8dc.png)

`
            AppDomain.CurrentDomain.ProcessExit += (o, e) =>
            {
                LogManager.GetLogger("Platform").Info("log something"));
            };
`
1.when I close the App,it come into the method,but it did't log anything,what's wrong?
2.the ${aspnet-request-posted-body} property is always empty,even if i do as follows:
`
.UseNLog()
app.Use(async (context, next) =>
            {
                context.Request.EnableBuffering();
                await next();
            });
`
Is it a bug?

**Comment by snakefoot** [comment]
Try loading nlog.config like this on AspNetCore:

```c#
public static void Main(string[] args)
{
    var logger = LogManager.Setup()
       .LoadConfigurationFromAppSettings()
       .LoadConfiguration(builder => builder.LogFactory.AutoShutdown = false)
       .GetCurrentClassLogger();

   try
   {
       // Build WebHost
   }
   finally
   {
       LogManager.Shutdown();
   }
}
```

When building WebHost and calling `AddNLog` or `UseNLog`, then provide the input-parameter: `new NLogAspNetCoreOptions() { ShutdownOnDispose = true }`

**Comment by 835718973** [comment]
Thanks for you help  @snakefoot 
At the begining,i lost `.LoadConfiguration(builder => builder.LogFactory.AutoShutdown = false)`.at now i can log message at the AppDomain.CurrentDomain.ProcessExit event,but the `${aspnet-request-posted-body}` is still empty, the NLog InternalLogger log that `2021-08-31 08:17:44.4559 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.BodyToString(Stream body)
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.Web.LayoutRenderers.AspNetLayoutRendererBase.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)`.
My code is as follows:
`
public class ExceptionMiddleware
    {
        private readonly RequestDelegate _next;

        public ExceptionMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(HttpContext context)
        {
            try
            {
                await _next.Invoke(context);
            }
            catch (Exception ex)
            {

                LogManager.GetLogger("Web").Error(ex, "Web访问错误");
                await HandleExceptionAsync(context, 200, ex.GetBaseException().Message);
            }
        }

        /// <summary>
        /// 异常处理
        /// </summary>
        /// <param name="context"></param>
        /// <param name="statusCode"></param>
        /// <param name="ex"></param>
        private async Task HandleExceptionAsync(HttpContext context, int statusCode, string msg)
        {
            context.Response.StatusCode = statusCode;
            context.Response.ContentType = "application/json;charset=utf-8";
            var response = new Response
            {
                Success = false,
                Message = msg
            };
            var serializeSetting = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(), //序列化时key为驼峰样式
                DateTimeZoneHandling = DateTimeZoneHandling.Local,
                DateFormatString = "yyyy-MM-dd HH:mm:ss",
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                NullValueHandling = NullValueHandling.Include
            };
            await context.Response.WriteAsync(JsonConvert.SerializeObject(response,serializeSetting));
        }
    }
}
`
`
app.UseMiddleware<ExceptionMiddleware>();
.
.other middlewares
.
app.Use(async (context, next) =>
            {
                context.Request.EnableBuffering();
                await next();
            });
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
`

**Comment by snakefoot** [comment]
I'm guessing that you are testing that `LogManager.GetLogger("Web").Error(...)` is producing the wanted output.

I think you need to change it into this:

```csharp
   public class ExceptionMiddleware
   {
        public async Task Invoke(HttpContext httpContext)
        {
            try
            {
                await _next.Invoke(context);
            }
            catch (Exception ex)
                when (ExceptionFilter(ex, httpContext)) // Exception Filter to ensure proper HttpContext
            {
                await HandleExceptionAsync(context, 200, ex.GetBaseException().Message);
            }
        }

        private bool ExceptionFilter(Exception ex, HttpContext httpContext)
        {
             LogManager.GetLogger("Web").Error(ex, "Web访问错误");
             return false;  // Exception should not be filtered
        }
   }
}
```

**Comment by 835718973** [comment]
Unfortunately,I had tried to do this,but the ${aspnet-request-posted-body} is still empty.
`2021-09-01 08:18:16.8134 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.BodyToString(Stream body)
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.Web.LayoutRenderers.AspNetLayoutRendererBase.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
`
`public class ExceptionMiddleware
    {
        private readonly RequestDelegate _next;

        public ExceptionMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(HttpContext context)
        {
            try
            {
                await _next.Invoke(context);
            }
            catch (Exception ex)
            when(ExceptionFilter(ex, context))
            {

                await HandleExceptionAsync(context, 200, ex.GetBaseException().Message);
            }
        }

            private bool ExceptionFilter(Exception ex, HttpContext httpContext)
            {
                LogManager.GetLogger("Web").Error(ex, "Web访问错误");
                return false;  // Exception should not be filtered
            }
            /// <summary>
            /// 异常处理
            /// </summary>
            /// <param name="context"></param>
            /// <param name="statusCode"></param>
            /// <param name="ex"></param>
            private async Task HandleExceptionAsync(HttpContext context, int statusCode, string msg)
        {
            context.Response.StatusCode = statusCode;
            context.Response.ContentType = "application/json;charset=utf-8";
            var response = new Response
            {
                Success = false,
                Message = msg
            };
            var serializeSetting = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(), //序列化时key为驼峰样式
                DateTimeZoneHandling = DateTimeZoneHandling.Local,
                DateFormatString = "yyyy-MM-dd HH:mm:ss",
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                NullValueHandling = NullValueHandling.Include
            };
            await context.Response.WriteAsync(JsonConvert.SerializeObject(response,serializeSetting));
        }
    }`

**Comment by snakefoot** [comment]
Well I have reached my knowledge of ASP.NET Core Middleware, so I have no more ideas. Maybe someone on stackoverfllow knows?

For some reason your logging statement occurs after request has been disposed. Why that I don't know. Maybe reproduce the issue in a debugger, so you can see the entire callstack.

**Comment by snakefoot** [comment]
Closing due to inactivity

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
