### ISSUE TITLE
Custom Layout  aspnet-request-headers And Use itemSeparator

### ISSUE THREAD

**Issue by Shikyoh** [NLog/NLog#4560]
Hi  I want to use aspnet request headers，But I don't know how to configure the itemseparator property and valueseparator property。

Nlog.config like this:
```json
	<target xsi:type="File" name="api-name" fileName="${basedir}/api_${lowercase:${level}}_${shortdate}.log"
					layout="${longdate}|${message}|${aspnet-request-headers:HeaderNames=X-Forwarded-For,aihelp-traceId,Kong-Request-ID:itemSeparator=,:valueSeparator=:}" />
```
but i get :
```txt
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Error when setting property 'Layout' on FileTarget
 ---> NLog.NLogConfigurationException: Error when setting property 'OutputFormat' on AspNetRequestHeadersLayoutRenderer
 ---> NLog.NLogConfigurationException: Invalid enumeration value 'itemSeparator'.
   at NLog.Internal.PropertyHelper.TryGetEnumValue(Type resultType, String value, Object& result, Boolean flagsEnumAllowed)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Layouts.LayoutParser.SetDefaultPropertyValue(ConfigurationItemFactory configurationItemFactory, LayoutRenderer layoutRenderer, String value)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.SetLayoutText(String value, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory, Nullable`1 throwConfigExceptions)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryParseLayoutValue(String stringValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, ConfigurationItemFactory configurationItemFactory, Object& newValue)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.LoggingConfigurationParser.ConfigureObjectFromAttributes(Object targetObject, ILoggingConfigurationElement element, Boolean ignoreType)
   
```
How to set `itemseparator` to `,` and `valueseparator` to  `:`:

**Comment by snakefoot** [comment]
The problem is the missing escape of colon:

> itemSeparator=,:valueSeparator=:}"

Try adding esacpe like this:

> itemSeparator=,:valueSeparator=\:}"

**Comment by Shikyoh** [comment]
thx。
