### ISSUE TITLE
FileLoadException: The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by rgroenewoudt** [NLog/NLog#4608]
I am are running into this exception on production environment (~23 times in 3 months) but I cannot reproduce it.
I suspect that it might be anti-virus software related as we are running Windows Defender (Windows Server 2019) and SentinelOne software. In Windows Defender the C:\logs directory is already excluded.

```
System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NLog.Internal.FileAppenders.BaseFileAppender.WindowsCreateFile(String fileName, Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes, Int32 offset, Int32 count)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, ArraySegment`1 bytes, Boolean initializedNewFile)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, ArraySegment`1 bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.Info(String message, Int32 argument)
```

2 processes, one Windows Service, other IIS application pool are writing to the same logfile.

**NLog version**: 4.7.6
**Platform**: .NET Framework 4.8 on Windows Server 2019
**Current NLog config**
Application 1 Windows Service:
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" autoReload="true" throwExceptions="true">
  <targets>
    <target name="debuglog" type="Console" layout="${longdate}|${level:uppercase=true}|${logger:shortName=true}|${message}|${exception:format=tostring}" />
    <target type="File" name="logfile" fileName="C:\logs\BusinessWindowsService.log" cleanupFileName="false" keepFileOpen="true" openFileCacheTimeout="30" concurrentWrites="true" autoFlush="false" openFileFlushTimeout="5" archiveEvery="Month" archiveDateFormat="yyyyMM" archiveNumbering="Date" enableArchiveFileCompression="true" maxArchiveFiles="12" archiveFileName="C:\logs\archive\BusinessWindowsService-{#}.zip" layout="${longdate}|${level:uppercase=true}|${logger:shortName=true}|${message}|${exception:format=tostring}" />
    <target type="File" name="businesslogfile" fileName="C:\logs\Business.log" cleanupFileName="false" forceMutexConcurrentWrites="true" openFileCacheTimeout="30" concurrentWrites="true" archiveEvery="Month" archiveDateFormat="yyyyMM" archiveNumbering="Date" enableArchiveFileCompression="true" maxArchiveFiles="12" archiveFileName="C:\logs\archive\Business-{#}.zip" layout="${longdate}|${level:uppercase=true}|${logger:shortName=true}|${message}|${exception:format=tostring}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
    <logger name="*" minlevel="Info" writeTo="businesslogfile" />
  </rules>
</nlog>
```

Application 2 IIS application pool:
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" autoReload="true" throwExceptions="true">
  <targets>
    <target name="debuglog" type="Debugger" layout="${longdate}|${level:uppercase=true}|${logger:shortName=true}|${message}|${exception:format=tostring}" />
    <target type="File" name="logfile" fileName="C:\logs\Services.log" cleanupFileName="false" keepFileOpen="true" openFileCacheTimeout="30" concurrentWrites="true" autoFlush="false" openFileFlushTimeout="5" archiveEvery="Month" archiveDateFormat="yyyyMM" archiveNumbering="Date" enableArchiveFileCompression="true" maxArchiveFiles="12" archiveFileName="C:\logs\archive\Services-{#}.zip" layout="${longdate}|${level:uppercase=true}|${logger:shortName=true}|${message}|${exception:format=tostring}" />
    <!-- Both webservice (IIS) and windows service will write to Business.log. Only windows service will archive to prevent conflict -->
    <target type="File" name="businesslogfile" fileName="C:\logs\Business.log" cleanupFileName="false" forceMutexConcurrentWrites="true" openFileCacheTimeout="30" concurrentWrites="true" layout="${longdate}|${level:uppercase=true}|${logger:shortName=true}|${message}|${exception:format=tostring}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
    <logger name="*" minlevel="Info" writeTo="businesslogfile" />
  </rules>
</nlog>
```

Any recommendations on how to debug this problem or prevent it?

Is the openFileCacheTimeout with keeping the file open relevant to this kind of problems?

**Comment by snakefoot** [comment]
Yes seen this problem before that machine-monitoring applications intercepts the file-handle and [blocks the application logging](https://github.com/NLog/NLog/issues/2758#issuecomment-888582204) (Because FileTarget uses KeepFileOpen=false by default so giving up the file-handle after each write).

Therefore it can lead to catastrophic failure if forgetting to specify `keepFileOpen="true"`. But so far me and @304NotModified have only agreed to disagree, on what is the best default.

I recommend that you update your configuration, so both `logfile` + `businesslogfile` has `keepFileOpen="true"`.
