### ISSUE TITLE
System.OutOfMemoryException was thrown

### ISSUE THREAD

**Issue by qwas368** [NLog/NLog#4616]
**NLog version**: (e.g. 4.4.13)
4.7.11

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOs / .NET Core 1 / .NET Core 2 / .NET Core 3
.Net 4.5

**Current NLog config** (xml or C#, if relevant)
```csharp
FilePath = filePath;
var config = new NLog.Config.LoggingConfiguration();

// Targets where to log to: File and Console
var loggerName = "ExecutionContextAsyncLogger";
var logfile = new NLog.Targets.FileTarget(loggerName) 
{ 
	FileName = filePath, 
	KeepFileOpen = true, 
	Encoding = Encoding.UTF8,
	Layout = "${message}"
};

AsyncTargetWrapper wrapper = new()
{
	WrappedTarget = logfile,
	QueueLimit = 10000,
	BatchSize = 5000,
	TimeToSleepBetweenBatches = 100,
	OverflowAction = AsyncTargetWrapperOverflowAction.Discard
};
wrapper.LogEventDropped += (s, e) => GlobalLogEventDropped.Invoke(s, e);

// Rules for mapping loggers to targets            
config.AddRule(NLog.LogLevel.Info, NLog.LogLevel.Fatal, wrapper);
```

- What is the current result?
Our windows form applications crashed sometimes.
We have 400+ windows form application, and they run all day.  It looks good when we changed log package form log4net to Nlog. But we found some application crashed after it run 4 days. Exception message shows out of memory, and we check windows memory usage is 36%.

- What is the expected result?
NLog or my process could handle excpetion and don't let it make process crashed.

- Please post full exception details (message, stacktrace, inner exceptions)
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.SetLength(Int64 value)
   at NLog.Internal.StringBuilderExt.CopyToStream(StringBuilder builder, MemoryStream ms, Encoding encoding, Char[] transformBuffer)
   at NLog.Targets.FileTarget.RenderFormattedMessageToStream(LogEventInfo logEvent, StringBuilder formatBuilder, Char[] transformBuffer, MemoryStream streamTarget)
   at NLog.Targets.FileTarget.WriteToMemoryStream(IList`1 logEvents, Int32 startIndex, MemoryStream ms)
   at NLog.Targets.FileTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.WriteEventsInQueue(Int32 batchSize, String reason)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

- Are there any workarounds? yes/no
no

**Comment by snakefoot** [comment]
NLog 4.7.13 has been released: https://www.nuget.org/packages/NLog/4.7.13

**Comment by qwas368** [comment]
@snakefoot  I have tried the NLog 5.0 Preview 3 and that works fine. No crash as far as we monitor.

**Comment by snakefoot** [comment]
@qwas368 Thank you for the confirmation, that NLog 5.0 resolves the issue. Hopefully we will soon have NLog 5.0 RTM.
