### ISSUE TITLE
NLog + .NET 6.0 + Npgsql 6.0 get error with logged DateTime (timestamptz)

### ISSUE THREAD

**Issue by KarenArzumanyan** [NLog/NLog#4665]
NLog 4.7.12 + .NET 6.0 + Npgsql 6.0 get error with logged DateTime (timestamptz)

After updating the project to .NET 6.0. There was a problem with the logging. Due to changes in the date format, the Npgsql 6.0 component. 

Breaking changes:
https://www.npgsql.org/doc/release-notes/6.0.html
https://www.npgsql.org/doc/types/datetime.html

**NLog version**: 4.7.12

**dbProvider**: Npgsql 6.0

**Platform**: .Net 6.0

**Current NLog config** (xml or C#, if relevant)

```xml
...
    <target name="database" xsi:type="Database"
            dbProvider="Npgsql.NpgsqlConnection, Npgsql"
            connectionString="User ID=user;Password=pass;Host=psqlserver;Port=5432;Database=cloud_logging;Pooling=true;">
...
     <!--
CREATE TABLE log
( 
    Id serial primary key,
    Application character varying(100) NULL,
    Logged timestamptz(6) NOT NULL,
    Level varchar(100) NULL,
    Message varchar(8000) NULL,
    Logger varchar(8000) NULL, 
    Callsite varchar(8000) NULL, 
    Exception varchar(8000) NULL
)
-->
      <commandText>
        insert into log (
        Application, Logged, Level, Message,
        Logger, CallSite, Exception
        ) values (
        @Application, @Logged, @Level, @Message,
        @Logger, @Callsite, @Exception
        );
      </commandText>
...
```

I tried different options and nothing helps.
Try:
```xml
      <parameter name="@logged" layout="${date}" dbType="NpgsqlDbType.TimestampTz" />
```
and:
```xml
      <parameter name="@logged" layout="${date}" dbType="DateTime" />
```
Error:

```
2021-11-15 17:07:12.1611 Error DatabaseTarget(Name=database): Error when writing to database. Exception: System.InvalidCastException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.ExecuteDbCommandWithParameters(LogEventInfo logEvent, IDbConnection dbConnection, IDbTransaction dbTransaction)
   at NLog.Targets.DatabaseTarget.WriteLogEventToDatabase(LogEventInfo logEvent, String connectionString)


```

**Comment by snakefoot** [comment]
Notice this is the repository for the NLog-core-project. So not support forum for specific DbProvider-implementation. Think you will a larger audience at StackOverflow.com.

Found the following Npgsql documentation:

https://www.npgsql.org/doc/release-notes/6.0.html#major-changes-to-timestamp-mapping

But have you tried doing this:

````xml
<parameter name="@logged" layout="${date:universalTime=true}" dbType="NpgsqlDbType.TimestampTz" />
```

Since it complains about:

> Cannot write **DateTime with Kind=Local** to PostgreSQL type 'timestamp with time zone'

**Comment by KarenArzumanyan** [comment]
Thanks **snakefoot**, it helped me.
But I must note that I also had to write down the column names in lowercase letters, otherwise they would not be found.
Before, everything worked without it, 
PS: I apologize if I wrote about the problem in the wrong place.

**Comment by snakefoot** [comment]
Glad you found a solution. Closing issue as resolved.
