### ISSUE TITLE
WCF: Configuration Files not supported in .NET Core / .NET 5+

### ISSUE THREAD

**Issue by MichelZ** [NLog/NLog#4667]
**NLog version**: (e.g. 4.7.12)

**Platform**: .Net 6.0

**Current NLog config** (xml or C#, if relevant)

```
public static LogReceiverWebServiceTarget GetTarget(string url)
        {
            return new LogReceiverWebServiceTarget
            {
                Name = "WCF",
                EndpointAddress = url,
                EndpointConfigurationName = "test",
                IncludeEventProperties = true
            };
        }
```

- What is the current result?
```
2021-11-16 08:39:06.3883 Error LogReceiverService Target[WCF]: Error has been raised. Exception: System.PlatformNotSupportedException: Configuration files are not supported.
   at System.ServiceModel.ClientBase`1..ctor(String endpointConfigurationName, EndpointAddress remoteAddress)
   at NLog.LogReceiverService.WcfLogReceiverClient..ctor(Boolean useOneWay, String endpointConfigurationName, EndpointAddress remoteAddress)
   at NLog.Targets.LogReceiverWebServiceTarget.CreateWcfLogReceiverClient()
   at NLog.Targets.LogReceiverWebServiceTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
```
- What is the expected result? Ability to configure a few basic things for basicHttpBinding, for example the ability to use https URL's (the default basicHttpBinding configuration only allows http URL's)
- Are there any workarounds? no
- Is there a version in which it did work? anything before .net core
- Can you help us by writing an unit test? Sure :)

**Comment by snakefoot** [comment]
Seems you cannot use `EndpointConfigurationName` and `<system.serviceModel>` on NetCore.

Probably because the `app.config` no longer exists on NetCore.

**Comment by snakefoot** [comment]
You are ofcourse wellcome to create pull-request to make it possible to configure the `BasicHttpBinding` on `LogReceiverWebServiceTarget` using NLog-config.

**Comment by snakefoot** [comment]
Closing question as answered. Pull-request with improvements for NLog.Wcf are ofcourse welcome.
