### ISSUE TITLE
Using CompoundLayout for EventLog EntryType-property fails on NLog 5.0

### ISSUE THREAD

**Issue by pockets3407** [NLog/NLog#4957]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: 5.0

**Platform**:   .NET6

**Current NLog config** (xml or C#, if relevant)

```json
{
  "NLog": {
    "autoReload": true,
    "internalLogFile": "c:\\temp\\nlog-internal.log",
    "throwExceptions": false,
    "internalLogLevel": "Off",
    "extensions": [
      { "assembly": "NLog.WindowsEventLog" }
    ],
    "targets": {
      "EventLog": {
        "type": "EventLog",
        "log": "My Product",
        "source": "My Product",
        "layout": "${level} | ${logger} | ${message}${onexception: | ${exception:format=tostring}}",
        "EntryType": {
          "type": "CompoundLayout",
          "layouts": [
            {
              "type": "SimpleLayout",
              "text": "${when:when=contains('${message}','SuccessAudit'):inner=SuccessAudit}"
            },
            {
              "type": "SimpleLayout",
              "text": "${when:when=contains('${message}','FailureAudit'):inner=FailureAudit}"
            },
            {
              "type": "SimpleLayout",
              "text": "${when:when=length('${event-properties:item=EntryType}')>0:inner=${event-properties:item=EntryType}",
              "IsFixedText": false
            }
          ]
        }
      },
      "ColoredConsole": {
        "type": "ColoredConsole"
      },
      "DebugConsole": {
        "type": "Debugger"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Info",
        "writeTo": "EventLog"
      },
      {
        "logger": "*",
        "minLevel": "Info",
        "maxLevel": "Fatal",
        "writeTo": "ColoredConsole"
      },
      {
        "logger": "*",
        "minLevel": "Trace",
        "maxLevel": "Debug",
        "writeTo": "DebugConsole"
      }
    ]
  }
}

```

- What is the current result?
Exception thrown at: LogManager.Configuration = new NLogLoggingConfiguration(config.GetSection("NLog"));
System.ArgumentException: 'Object of type 'NLog.Layouts.CompoundLayout' cannot be converted to type 'NLog.Layouts.Layout`1[System.Diagnostics.EventLogEntryType]'.'

- What is the expected result?
Application to start without error

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes

2022-06-02 13:27:29.3689 Info Message Template Auto Format enabled
2022-06-02 13:27:29.3896 Info Loading assembly: NLog.WindowsEventLog
2022-06-02 13:27:29.3896 Debug ScanAssembly('NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2022-06-02 13:27:29.4447 Debug ScanAssembly('NLog.WindowsEventLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2022-06-02 13:27:29.4626 Debug Setting 'NLog.Targets.ColoredConsoleTarget.name' to 'ColoredConsole'
2022-06-02 13:27:29.4722 Info Adding target ColoredConsoleTarget(Name=ColoredConsole)
2022-06-02 13:27:29.4722 Debug Registered target ColoredConsole: NLog.Targets.ColoredConsoleTarget
2022-06-02 13:27:29.4722 Debug Setting 'NLog.Targets.DebuggerTarget.name' to 'DebugConsole'
2022-06-02 13:27:29.4722 Info Adding target DebuggerTarget(Name=DebugConsole)
2022-06-02 13:27:29.4722 Debug Registered target DebugConsole: NLog.Targets.DebuggerTarget
2022-06-02 13:27:29.4722 Debug Setting 'NLog.Targets.EventLogTarget.name' to 'EventLog'
2022-06-02 13:27:29.4722 Debug Setting 'NLog.Targets.EventLogTarget.layout' to '${level} | ${logger} | ${message}${onexception: | ${exception:format=tostring}}'
2022-06-02 13:27:29.4823 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.4823 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2022-06-02 13:27:29.4823 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.4823 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2022-06-02 13:27:29.4823 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.4823 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2022-06-02 13:27:29.4823 Debug Setting 'NLog.LayoutRenderers.Wrappers.OnExceptionLayoutRendererWrapper.Inner' to ' | ${exception:format=tostring}'
2022-06-02 13:27:29.4956 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.4956 Trace Scanning ExceptionLayoutRenderer 'Layout Renderer: ${exception}'
2022-06-02 13:27:29.4956 Trace  Scanning Property Formats 'System.Collections.Generic.List`1[NLog.Config.ExceptionRenderingFormat]' System.Collections.Generic
2022-06-02 13:27:29.4956 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.4956 Trace Scanning OnExceptionLayoutRendererWrapper 'Layout Renderer: ${onexception}'
2022-06-02 13:27:29.4956 Trace  Scanning Property Inner ' | ${exception:format=tostring}' NLog.Layouts
2022-06-02 13:27:29.4956 Trace  Scanning SimpleLayout ' | ${exception:format=tostring}'
2022-06-02 13:27:29.4956 Trace   Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.4956 Trace   Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2022-06-02 13:27:29.4956 Trace   Scanning ExceptionLayoutRenderer 'Layout Renderer: ${exception}'
2022-06-02 13:27:29.4956 Trace    Scanning Property Formats 'System.Collections.Generic.List`1[NLog.Config.ExceptionRenderingFormat]' System.Collections.Generic
2022-06-02 13:27:29.4956 Debug Setting 'NLog.Targets.EventLogTarget.log' to 'My product'
2022-06-02 13:27:29.4956 Debug Setting 'NLog.Targets.EventLogTarget.source' to 'My product'
2022-06-02 13:27:29.4956 Debug Setting 'NLog.Layouts.SimpleLayout.text' to '${when:when=contains('${message}','SuccessAudit'):inner=SuccessAudit}'
2022-06-02 13:27:29.4956 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.4956 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2022-06-02 13:27:29.5451 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.5451 Trace Scanning WhenLayoutRendererWrapper 'Layout Renderer: ${when}'
2022-06-02 13:27:29.5451 Trace  Scanning Property When 'contains('${message}', 'SuccessAudit')' NLog.Conditions
2022-06-02 13:27:29.5451 Trace  Scanning ConditionMethodExpression 'contains('${message}', 'SuccessAudit')'
2022-06-02 13:27:29.5451 Trace   Scanning Property MethodInfo 'Boolean Contains(System.String, System.String, Boolean)' System.Reflection
2022-06-02 13:27:29.5451 Trace   Scanning Property MethodParameters 'NLog.Conditions.ConditionExpression[]' System.Collections.Generic
2022-06-02 13:27:29.5451 Trace   Scanning ConditionLayoutExpression ''${message}''
2022-06-02 13:27:29.5451 Trace    Scanning Property Layout '${message}' NLog.Layouts
2022-06-02 13:27:29.5451 Trace    Scanning SimpleLayout '${message}'
2022-06-02 13:27:29.5451 Trace     Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.5451 Trace     Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2022-06-02 13:27:29.5451 Trace   Scanning ConditionLiteralExpression ''SuccessAudit''
2022-06-02 13:27:29.5451 Trace    Scanning Property LiteralValue 'SuccessAudit' System
2022-06-02 13:27:29.5451 Trace  Scanning Property Inner 'SuccessAudit' NLog.Layouts
2022-06-02 13:27:29.5451 Trace  Scanning SimpleLayout 'SuccessAudit'
2022-06-02 13:27:29.5451 Trace   Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.5573 Trace   Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2022-06-02 13:27:29.5573 Debug Setting 'NLog.Layouts.SimpleLayout.text' to '${when:when=contains('${message}','FailureAudit'):inner=FailureAudit}'
2022-06-02 13:27:29.5573 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.5573 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2022-06-02 13:27:29.5573 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.5573 Trace Scanning WhenLayoutRendererWrapper 'Layout Renderer: ${when}'
2022-06-02 13:27:29.5573 Trace  Scanning Property When 'contains('${message}', 'FailureAudit')' NLog.Conditions
2022-06-02 13:27:29.5573 Trace  Scanning ConditionMethodExpression 'contains('${message}', 'FailureAudit')'
2022-06-02 13:27:29.5573 Trace   Scanning Property MethodInfo 'Boolean Contains(System.String, System.String, Boolean)' System.Reflection
2022-06-02 13:27:29.5573 Trace   Scanning Property MethodParameters 'NLog.Conditions.ConditionExpression[]' System.Collections.Generic
2022-06-02 13:27:29.5573 Trace   Scanning ConditionLayoutExpression ''${message}''
2022-06-02 13:27:29.5573 Trace    Scanning Property Layout '${message}' NLog.Layouts
2022-06-02 13:27:29.5573 Trace    Scanning SimpleLayout '${message}'
2022-06-02 13:27:29.5573 Trace     Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.5573 Trace     Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2022-06-02 13:27:29.5573 Trace   Scanning ConditionLiteralExpression ''FailureAudit''
2022-06-02 13:27:29.5573 Trace    Scanning Property LiteralValue 'FailureAudit' System
2022-06-02 13:27:29.5573 Trace  Scanning Property Inner 'FailureAudit' NLog.Layouts
2022-06-02 13:27:29.5573 Trace  Scanning SimpleLayout 'FailureAudit'
2022-06-02 13:27:29.5573 Trace   Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.5573 Trace   Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2022-06-02 13:27:29.5573 Debug Setting 'NLog.Layouts.SimpleLayout.text' to '${when:when=length('${event-properties:item=EntryType}')>0:inner=${event-properties:item=EntryType}'
2022-06-02 13:27:29.5573 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.5573 Trace Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-property}'
2022-06-02 13:27:29.5734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.5734 Trace Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-property}'
2022-06-02 13:27:29.5734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2022-06-02 13:27:29.5734 Trace Scanning WhenLayoutRendererWrapper 'Layout Renderer: ${when}'
2022-06-02 13:27:29.5734 Trace  Scanning Property When '(length('${event-properties:item=EntryType}') > 0)' NLog.Conditions
2022-06-02 13:27:29.5734 Trace  Scanning ConditionRelationalExpression '(length('${event-properties:item=EntryType}') > 0)'
2022-06-02 13:27:29.5734 Trace   Scanning Property LeftExpression 'length('${event-properties:item=EntryType}')' NLog.Conditions
2022-06-02 13:27:29.5734 Trace   Scanning ConditionMethodExpression 'length('${event-properties:item=EntryType}')'
2022-06-02 13:27:29.5734 Trace    Scanning Property MethodInfo 'Int32 Length(System.String)' System.Reflection
2022-06-02 13:27:29.5734 Trace    Scanning Property MethodParameters 'NLog.Conditions.ConditionExpression[]' System.Collections.Generic
2022-06-02 13:27:29.5734 Trace    Scanning ConditionLayoutExpression ''${event-properties:item=EntryType}''
2022-06-02 13:27:29.5734 Trace     Scanning Property Layout '${event-properties:item=EntryType}' NLog.Layouts
2022-06-02 13:27:29.5734 Trace     Scanning SimpleLayout '${event-properties:item=EntryType}'
2022-06-02 13:27:29.5734 Trace      Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.5734 Trace      Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-property}'
2022-06-02 13:27:29.5734 Trace   Scanning Property RightExpression '0' NLog.Conditions
2022-06-02 13:27:29.5734 Trace   Scanning ConditionLiteralExpression '0'
2022-06-02 13:27:29.5734 Trace    Scanning Property LiteralValue '0' System
2022-06-02 13:27:29.5734 Trace  Scanning Property Inner '${event-properties:item=EntryType}' NLog.Layouts
2022-06-02 13:27:29.5734 Trace  Scanning SimpleLayout '${event-properties:item=EntryType}'
2022-06-02 13:27:29.5734 Trace   Scanning Property LayoutRenderers 'NLog.LayoutRenderers.LayoutRenderer[]' System.Collections.Generic
2022-06-02 13:27:29.5734 Trace   Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-property}'

- Please post full exception details (message, stacktrace, inner exceptions)
System.ArgumentException
  HResult=0x80070057
  Message=Object of type 'NLog.Layouts.CompoundLayout' cannot be converted to type 'NLog.Layouts.Layout`1[System.Diagnostics.EventLogEntryType]'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at NLog.Config.LoggingConfigurationParser.SetItemOnProperty(Object o, PropertyInfo propInfo, ValidatedConfigurationElement element, Object properyValue)
   at NLog.Config.LoggingConfigurationParser.SetLayoutFromElement(Object o, PropertyInfo propInfo, ValidatedConfigurationElement element)
   at NLog.Config.LoggingConfigurationParser.SetPropertyValuesFromElement(Object o, ValidatedConfigurationElement childElement, ILoggingConfigurationElement parentElement)
   at NLog.Config.LoggingConfigurationParser.ParseTargetElement(Target target, ValidatedConfigurationElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.LoggingConfigurationParser.ParseTargetsElement(ValidatedConfigurationElement targetsElement)
   at NLog.Config.LoggingConfigurationParser.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Extensions.Logging.NLogLoggingConfiguration.LoadConfigurationSection(IConfigurationSection nlogConfig)
   at NLog.Extensions.Logging.NLogLoggingConfiguration..ctor(IConfigurationSection nlogConfig, LogFactory logFactory)
   at NLog.Extensions.Logging.NLogLoggingConfiguration..ctor(IConfigurationSection nlogConfig)
   at MyProject.Program.<Main>d__2.MoveNext() in {PathToMyProject}\Program.cs:line 38

- Are there any workarounds? yes/no
Yes, comment out EntryType section

- Is there a version in which it did work? 
Last version of NLog 4.7.15

- Can you help us by writing an unit test?
Yes, testing against my file.

I see that EventLogTarget's EntryType property type was updated from `Layout` to `Layout<EventLogEntryType>` in NLog 5.0. Is my configuration still supported? How can I update my configuration for NLog 5.0?

**Comment by snakefoot** [comment]
Yes `Layout<EventLogEntryType>` will only support SimpleLayout (And not complex layouts like CompoundLayout)

I think you can do this instead:

```json
{
 "NLog": {
   "variables": {
      "SuccessAudit": "${when:when=contains('${message}','SuccessAudit'):inner=SuccessAudit}",
      "FailureAudit": "${when:when=contains('${message}','FailureAudit'):inner=FailureAudit:whenEmpty=${SuccessAudit}}",
      "EntryTypeProperty": "${event-properties:item=EntryType:whenEmpty=${FailureAudit}}",
   },
   "targets": {
      "EventLog": {
        "type": "EventLog",
        "log": "My Product",
        "source": "My Product",
        "layout": "${level} | ${logger} | ${message}${onexception: | ${exception:format=tostring}}",
        "EntryType": "${EntryTypeProperty}"
      },
      "ColoredConsole": {
        "type": "ColoredConsole"
      },
      "DebugConsole": {
        "type": "Debugger"
      }
   }
}
```

**Comment by pockets3407** [comment]
Yes, that worked. Thanks!

**Comment by snakefoot** [comment]
@pockets3407 Updated the example to ensure the ordering of NLog Variables handles being sorted by the Json-Dictionary-Logic from Microsoft-appsetting-json-file-loader.

**Comment by snakefoot** [comment]
Closing issue as resolved.
