### ISSUE TITLE
The process cannot access the file 

### ISSUE THREAD

**Issue by TanguyIngels** [NLog/NLog#4996]
**NLog version**: 5+

**Platform**: .Net 4.7.3

**Current NLog config** 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  internalLogLevel="Warn"
	  internalLogFile="c:\dev\internallog.log">

  <targets>
    <target xsi:type="File"
            name="file"
            fileName="c:\dev\KasparBuilder.log"
            archiveFileName="c:\dev\KasparBuilder.{#}.log"
            archiveNumbering="Date"
            archiveEvery="Day"
            archiveDateFormat="yyyyMMdd"
            layout="${longdate}|${level:uppercase=true}|${message} ${exception:format=tostring}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="file" />
  </rules>
</nlog>
```

- What is the current result?
```
System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'c:\dev\KasparBuilder.log' because it is being used by another process.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)

  This exception was originally thrown at this call stack:
    System.IO.__Error.WinIOError(int, string)
    System.IO.FileStream.Init(string, System.IO.FileMode, System.IO.FileAccess, int, bool, System.IO.FileShare, int, System.IO.FileOptions, Microsoft.Win32.Win32Native.SECURITY_ATTRIBUTES, string, bool, bool, bool)
    System.IO.FileStream.FileStream(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, int)
    NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(bool, int)
    NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(bool, int)
```

- What is the expected result?  That the log is written to disk.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? yes
```
2022-07-08 15:48:53.9878 Warn FileTarget(Name=file): Failed to create file appender: c:\dev\KasparBuilder.log Exception: System.IO.IOException: The process cannot access the file 'c:\dev\KasparBuilder.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.CountingSingleProcessFileAppender..ctor(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.CountingSingleProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.CreateAppender(String fileName, Int32 freeSpot)
```
- Please post full exception details (message, stacktrace, inner exceptions): See current result
- Are there any workarounds? yes => activate version 4.7+
- Is there a version in which it did work?   4.7+
- Can you help us by writing an unit test?

```c#
        [TestMethod]
        public void TestLog()
        {
            Init.StartInit();
            logger.Error("Could not find project with name");  // warn occurs on this line.
            logger.Error("Could not find project with name");
        }

        public static class Init
        {
            private static NLog.Logger logger = new NLog.LogFactory().GetCurrentClassLogger();

            private static bool AlreadyDone = false;
            public static bool StartInit()
            {
                if (AlreadyDone) return false;

                logger.Info("test");

                AlreadyDone = true;
                return true;
            }
        }
```

**Comment by snakefoot** [comment]
Closing due to inactivity.

**Comment by TanguyIngels** [comment]
Hi,

Just one application, you can perfectly reproduce it with the provided unit test.

Greets,

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Rolf ***@***.***>
Verzonden: woensdag 13 juli 2022 22:39
Aan: ***@***.***>
CC: Tanguy ***@***.***>; ***@***.***>
Onderwerp: Re: [NLog/NLog] The process cannot access the file (Issue #4996)


I'm guessing you have multiple applications that access the log-file c:\dev\KasparBuilder.log.

If this is the case, then you should enable concurrentWrites="true". If some of these applications are not using NLog, then you should also enable keepFileOpen="false".

<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"

      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

          internalLogLevel="Warn"

          internalLogFile="c:\dev\internallog.log">



  <targets>

    <target xsi:type="File"

            name="file"

            fileName="c:\dev\KasparBuilder.log"

            archiveFileName="c:\dev\KasparBuilder.{#}.log"

            keepFileOpen="true"

            concurrentWrites="true"

            archiveNumbering="Date"

            archiveEvery="Day"

            archiveDateFormat="yyyyMMdd"

            layout="${longdate}|${level:uppercase=true}|${message} ${exception:format=tostring}"/>

  </targets>



  <rules>

    <logger name="*" minlevel="Trace" writeTo="file" />

  </rules>

</nlog>

**Comment by snakefoot** [comment]
Created a console application with the above code, and there is no warnings or errors with NLog5. The logfile contains the 3 log-lines. So I cannot reproduce.

Again you are welcome to explicit assign KeepFileOpen=false and ConcurrentWrites=true to handle your special environment.


Sent from my Galaxy



-------- Original message --------
From: TanguyIngels ***@***.***>
Date: 21/07/2022 11:43 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog] The process cannot access the file (Issue #4996)


Hi,

Just one application, you can perfectly reproduce it with the provided unit test.

Greets,

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Rolf ***@***.***>
Verzonden: woensdag 13 juli 2022 22:39
Aan: ***@***.***>
CC: Tanguy ***@***.***>; ***@***.***>
Onderwerp: Re: [NLog/NLog] The process cannot access the file (Issue #4996)


I'm guessing you have multiple applications that access the log-file c:\dev\KasparBuilder.log.

If this is the case, then you should enable concurrentWrites="true". If some of these applications are not using NLog, then you should also enable keepFileOpen="false".

<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

internalLogLevel="Warn"

internalLogFile="c:\dev\internallog.log">



<targets>

<target xsi:type="File"

name="file"

fileName="c:\dev\KasparBuilder.log"

archiveFileName="c:\dev\KasparBuilder.{#}.log"

keepFileOpen="true"

concurrentWrites="true"

archiveNumbering="Date"

archiveEvery="Day"

archiveDateFormat="yyyyMMdd"

layout="${longdate}|${level:uppercase=true}|${message} ${exception:format=tostring}"/>

</targets>



<rules>

<logger name="*" minlevel="Trace" writeTo="file" />

</rules>

</nlog>
