### ISSUE TITLE
System.ArgumentException: 'Parameter 'p_logged' not found in the collection.'

### ISSUE THREAD

**Issue by Clydeston** [NLog/NLog#5103]
**NLog version**: 5.0.5

**Platform**: .NET 4.7 

**Current NLog config** 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <variable name="myvar" value="myvalue"/>

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>
	  <target name="db"
        xsi:type="Database"
	    connectionStringName="DefaultConnection"
        commandType="StoredProcedure"
        commandText="dbo.NLog_AddEntry_p"
        >
		  <parameter name="@logged"         layout="${date}" />
		  <parameter name="@level"          layout="${level}" />
		  <parameter name="@message"        layout="${message}" />
		  <parameter name="@logger"         layout="${logger}" />
		  <parameter name="@properties"     layout="${all-event-properties:separator=|}" />
		  <parameter name="@callsite"       layout="${callsite}" />
		  <parameter name="@exception"      layout="${exception:tostring}" />
	  </target>
    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    -->
  </targets>

  <rules>
    <!-- add your logging rules here -->
	  <logger levels="Error,Warn,Fatal" name="databaseLogger" writeTo="db"/>
    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->
  </rules>
</nlog>


```

I keep getting the error System.ArgumentException for any parameter included in the sql query getting sent to the database. Everytime I remove a parameter it happens to the next param in the queue. Any help or advice appreciated really stuck on this. 

Stack trace 
   at MySql.Data.MySqlClient.MySqlParameterCollection.GetParameterFlexible(String parameterName, Boolean throwOnNotFound)
   at MySql.Data.MySqlClient.StoredProcedure.GetAndFixParameter(String spName, MySqlSchemaRow param, Boolean realAsFloat, MySqlParameter returnParameter)
   at MySql.Data.MySqlClient.StoredProcedure.CheckParameters(String spName)
   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.ExecuteDbCommandWithParameters(LogEventInfo logEvent, IDbConnection dbConnection, IDbTransaction dbTransaction)
   at NLog.Targets.DatabaseTarget.WriteLogEventSuppressTransactionScope(LogEventInfo logEvent, String connectionString)
   at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory logFactory)
   at NLog.Logger.WriteToTargets(LogEventInfo logEvent, TargetWithFilterChain targetsForLevel)
   at NLog.Logger.WriteToTargets(LogLevel level, Exception ex, String message, Object[] args)
   at NLog.Logger.Error(Exception exception, String message)
   at Monotub.Models.Article.GetTotalArticleCount() in C:\Users\Jack\Documents\Coding\C#\Monotub\Monotub\Models\Article.cs:line 47
   at Monotub.Controllers.ArticleController.Articles() in C:\Users\Jack\Documents\Coding\C#\Monotub\Monotub\Controllers\ArticleController.cs:line 22
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()

**Comment by snakefoot** [comment]
This sounds like a [question for StackOverflow](https://github.com/NLog/NLog/issues/new/choose)

But I'm guessing that the stored-procedure `dbo.NLog_AddEntry_p` expects that the input-parameters should start with `p_` (Ex. `p_logged`).

But for some reason then you have decided to remove the `p_` in the NLog-configuration:
```xml
<parameter name="@logged"         layout="${date}" />
```

Maybe take a look at `dbo.NLog_AddEntry_p` and ensure the parameter-names in the NLog-configuration are matching the ones expected by the stored-procedure.

**Comment by Clydeston** [comment]
> This sounds like a [question for StackOverflow](https://github.com/NLog/NLog/issues/new/choose), since you will find very little knowledge about MySql-databases here.
> 
> But I'm guessing that the stored-procedure `dbo.NLog_AddEntry_p` expects that the input-parameters should start with `p_` (Ex. `p_logged`).
> 
> But for some reason then you have decided to remove the `p_` in the NLog-configuration:
> 
> ```
> <parameter name="@logged"         layout="${date}" />
> ```
> 
> Maybe take a look at `dbo.NLog_AddEntry_p` and ensure the parameter-names in the NLog-configuration are matching the ones expected by the stored-procedure.

Thank you for that mate, that's solved my issue. I was so frustrated last night I just couldn't spot it. For any devs reading this the documentation needs updating for that section of code.

**Comment by snakefoot** [comment]
> For any devs reading this the documentation needs updating for that section of code.

If you can point at what part of the documentation that needs to be updated, then please tell. Notice the NLog Wiki-pages are open for editing if you feel something is missing.
