### ISSUE TITLE
Json NLogConfig parsing would fail when custom NLog Target doesn't have any parameters (besides type)

### ISSUE THREAD

**Issue by HaowenZhangBD** [NLog/NLog#5128]
Hi! Thanks for reporting this bug! 

This is Json only, the xml config parsing is fine

**NLog version**: 4.7.7

**Platform**:  .NET6

**Current NLog config**  

```json
{
  "NLog": {
    
    "extensions": [
      { "assembly": "my.NLogTarget" }
    ],
    "targets": {
      "splunk": {
        "type": "AsyncWrapper" ,
        "overflowAction": "Block" ,
        "queueLimit": 10000,
        "fullBatchSizeWriteLimit": 2 ,
        "batchSize": 500,
        "timeToSleepBetweenBatches": 1 ,
        "optimizeBufferReuse": true ,
        "target": {
          "type": "Insights"
        }
      }
    },
    "rules": {
      "doesn't matter": 1
    }
  }
}

```

- What is the current result?
It would throw exceptions
```
Unhandled exception. NLog.NLogConfigurationException: Expected type on target in splunk
   at NLog.Config.LoggingConfigurationElementExtensions.GetRequiredValue(ILoggingConfigurationElement element, String attributeName, String section)
   at NLog.Config.LoggingConfigurationElementExtensions.GetConfigItemTypeAttribute(ILoggingConfigurationElement element, String sectionNameForRequiredValue)
   at NLog.Config.LoggingConfigurationParser.ParseTargetWrapper(Dictionary`2 typeNameToDefaultTargetParameters, String name, ILoggingConfigurationElement childElement, WrapperTargetBase wrapper)
   at NLog.Config.LoggingConfigurationParser.ParseTargetElement(Target target, ILoggingConfigurationElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.LoggingConfigurationParser.ParseTargetsElement(ILoggingConfigurationElement targetsElement)
   at NLog.Config.LoggingConfigurationParser.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
```

- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any workarounds? yes. Add a dummy parameter on my target

This is less an issue as we would expect NLog target to take some parameters. But still this is a bug for my local testing and takes some time to figure out

**Comment by HaowenZhangBD** [comment]
If I change the target to have more parameters, it would be fine
```
        "target": {
          "type": "Insights",
           "someparam": "test"
        }
```

**Comment by snakefoot** [comment]
@HaowenZhangBD It would be a great help if you could make a pull-request to https://github.com/NLog/NLog.Extensions.Logging that reproduces the buggy behavior.
