### ISSUE TITLE
hexadecimal value 0x14, is an invalid character is an invalid character

### ISSUE THREAD

**Issue by twipoc** [NLog/NLog#5214]
Hi
This did not happen with previous versions

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

NLog version 5.1.3

C#  .NET Core 

Current NLog config 4.7.15

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Error" internalLogFile="c:\temp\nlog-internal.log">

 <variable name="GDClogFilePath" value="${basedir}/Logs/IRServices_${shortdate}_${mdc:item=AssemblyClassName}_${mdc:item=Port}.log" />

<targets>
      <target name="GDClogFile" xsi:type="File" 
              layout="${longdate}|${level:uppercase=true}|${callsite}|${message}"
              fileName="${GDClogFilePath}" archiveAboveSize="100000000" archiveEvery="Day" archiveNumbering = "Rolling"  maxArchiveFiles="10" />
	</targets>
 <rules>
    <logger name="GDClogger" minlevel="Trace" writeTo="GDClogFile" />
  </rules>
</nlog>

Send to logger.Trace an ASCII string with a char 0x14 and get an error that did not occur in previous versions

Unhandled error:: '', hexadecimal value 0x14, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at NLog.LayoutRenderers.Log4JXmlEventLayoutRenderer.Append Error hexadecimal value 0x14, is an invalid character.
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
   at NLog.Layouts.Layout.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder target, Boolean cacheLayoutResult)
   at NLog.Targets.NetworkTarget.RenderBytesToWrite(LogEventInfo logEvent)
   at NLog.Targets.NetworkTarget.GetBytesToWrite(LogEventInfo logEvent)
   at NLog.Targets.NetworkTarget.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory logFactory)
   at NLog.Logger.WriteToTargets(LogEventInfo logEvent, TargetWithFilterChain targetsForLevel)

**Comment by snakefoot** [comment]
Bug introduced with #4291, will make a patch with an unit-test.

Thank you for reporting this.

**Comment by snakefoot** [comment]
NLog v5.1.5 has been released - https://www.nuget.org/packages/NLog/5.1.5#release-body-tab

Thank you again for reporting this issue.
