### ISSUE TITLE
Extension prefix for assembly stopped working with NLog v5.2 - Type-alias is unknown

### ISSUE THREAD

**Issue by jonreis** [NLog/NLog#5256]
I'm not sure if this is part of the breaking changes in v5.2.0? This worked in v5.1.5.

NLog version: 5.2.0

Platform: .Net 4.5

[NLog.config.txt](https://github.com/NLog/NLog/files/11747513/NLog.config.txt)

```xml
<nlog>
  <extensions>
    <add assembly="Connexion.Share" prefix="share"/>
  </extensions>
  <targets>
    <target name="AuditFileLogger" xsi:type="File" fileName="Connexion.Audit.txt"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="AuditFileLogger">
      <filters defaultAction="Log">
        <share.AuditEventFilter />
      </filters>
    </logger>
   </rules>
</nlog>
```

- What is the current result?

The following exception:

```
2023-06-14 08:05:23.9958 Error Exception when loading configuration C:\Development\ConnexionV15\Connexion\bin\Debug\NLog.config Exception: NLog.NLogConfigurationException: Failed to create Filter of type: share.AuditEventFilter ---> System.ArgumentException: Filter type-alias is unknown: 'share.AuditEventFilter'
   at NLog.Config.FactoryExtensions.CreateInstance[TBaseType](IFactory`1 factory, String typeAlias)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String typeName, IFactory`1 factory)
   --- End of inner exception stack trace ---
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String typeName, IFactory`1 factory)
   at NLog.Config.LoggingConfigurationParser.ParseLoggingRuleFilters(LoggingRule rule, ValidatedConfigurationElement filtersElement, String filterDefaultAction)
   at NLog.Config.LoggingConfigurationParser.ParseLoggingRuleChildren(ValidatedConfigurationElement loggerElement, LoggingRule rule, String filterDefaultAction)
   at NLog.Config.LoggingConfigurationParser.ParseRuleElement(ValidatedConfigurationElement loggerElement)
   at NLog.Config.LoggingConfigurationParser.ParseRulesElement(ValidatedConfigurationElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(ILoggingConfigurationElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
2023-06-14 08:05:23.9958 Error Failed loading from config file location: C:\Development\ConnexionV15\Connexion\bin\Debug\NLog.config Exception: NLog.NLogConfigurationException: Exception when loading configuration C:\Development\ConnexionV15\Connexion\bin\Debug\NLog.config ---> NLog.NLogConfigurationException: Failed to create Filter of type: share.AuditEventFilter ---> System.ArgumentException: Filter type-alias is unknown: 'share.AuditEventFilter'
   at NLog.Config.FactoryExtensions.CreateInstance[TBaseType](IFactory`1 factory, String typeAlias)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String typeName, IFactory`1 factory)
   --- End of inner exception stack trace ---
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String typeName, IFactory`1 factory)
   at NLog.Config.LoggingConfigurationParser.ParseLoggingRuleFilters(LoggingRule rule, ValidatedConfigurationElement filtersElement, String filterDefaultAction)
   at NLog.Config.LoggingConfigurationParser.ParseLoggingRuleChildren(ValidatedConfigurationElement loggerElement, LoggingRule rule, String filterDefaultAction)
   at NLog.Config.LoggingConfigurationParser.ParseRuleElement(ValidatedConfigurationElement loggerElement)
   at NLog.Config.LoggingConfigurationParser.ParseRulesElement(ValidatedConfigurationElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(ILoggingConfigurationElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.LoggingConfigurationFileLoader.LoadXmlLoggingConfiguration(XmlReader xmlReader, String configFile, LogFactory logFactory)
   at NLog.Config.LoggingConfigurationFileLoader.LoadXmlLoggingConfigurationFile(LogFactory logFactory, String configFile)
   at NLog.Config.LoggingConfigurationFileLoader.TryLoadLoggingConfiguration(LogFactory logFactory, String configFile, LoggingConfiguration& config)
```

It doesn't seem to recognize the alias: "share":

  <extensions>
    <add assembly="Connexion.Share" prefix="share"/>
  </extensions>

**Comment by snakefoot** [comment]
Thank you for reporting this. NLog v5.2 includes a major rewrite of the configuration-item-alias system, but the goal was not any breaking changes.

Can you show how you register the alias `share.AuditEventFilter` ? Or maybe share an unit-test that [reproduces the issue](3268) ?

**Comment by jonreis** [comment]
Hi @snakefoot. Thank you for responding. I have tried both of these methods:

        LayoutRenderer.Register<TruncateLayoutRenderer>("TruncateLayout");
        ConfigurationItemFactory.Default.Filters.RegisterDefinition(nameof(AuditEventFilter), typeof(AuditEventFilter));
        ConfigurationItemFactory.Default.Filters.RegisterDefinition(nameof(UserLogLevelFilter), typeof(UserLogLevelFilter));
        ConfigurationItemFactory.Default.Filters.RegisterDefinition(nameof(UserEventFilter), typeof(UserEventFilter));


and 

         NLog.LogManager.Setup()
          .SetupExtensions(s => s.RegisterLayoutRenderer<TruncateLayoutRenderer>("TruncateLayout"))
          .SetupExtensions(s => s.RegisterType<AuditEventFilter>())
          .SetupExtensions(s => s.RegisterType<UserLogLevelFilter>())
          .SetupExtensions(s => s.RegisterType<UserEventFilter>());

**Comment by snakefoot** [comment]
If you want to keep the "share"-prefix, then you need to register it with and without the prefix:
```c#
     NLog.LogManager.Setup()
      .SetupExtensions(s => {
           s.RegisterLayoutRenderer<TruncateLayoutRenderer>("TruncateLayout");
           s.RegisterLayoutRenderer<TruncateLayoutRenderer>("share.TruncateLayout");
           s.RegisterType<AuditEventFilter>();
           s.RegisterType<AuditEventFilter>("share.AuditEventFilter");
           s.RegisterType<UserLogLevelFilter>();
           s.RegisterType<UserLogLevelFilter>("share.UserLogLevelFilter");
           s.RegisterType<UserEventFilter>();
           s.RegisterType<UserEventFilter>("share.UserEventFilter");
      });
```

**Comment by snakefoot** [comment]
Ahh see now the problem with with your Filter-types, and the generic `RegisterType`

**Comment by snakefoot** [comment]
Created #5257 that will include assembly-prefix when checking if assembly-types are already loaded.

**Comment by jonreis** [comment]
@snakefoot thanks for all your help! 

I thought the purpose of having the prefix associated with the assembly was just an alias for the name of the assembly. For example with:

  <extensions>
    <add assembly="MyNamespace.Assembly1" prefix="share1"/>
    <add assembly="MyNamespace.Assembly2" prefix="share2"/>
  </extensions>


      <filters defaultAction="Log">
        <share1.MyFilter Note = "Do not remove this text"/>
      </filters>

wiykd be equivalent to:

      <filters defaultAction="Log">
        <MyNamespace.Assembly1.MyFilter Note = "Do not remove this text"/>
      </filters>

So I am not sure about hardcoding the prefix since what I am trying to do is specify to nlog from which assembly nlog should grab the type from.

**Comment by snakefoot** [comment]
The assembly-prefix is just a symbol-name, and can be anything. When not depending on assembly-reflection, and making direct registration, then you should know what assembly the type is coming from (and what assembly-symbol to use):
```c#
ConfigurationItemFactory.Default.FilterFactory.RegisterType<MyNamespace.AuditEventFilter>("MyNamespace."+nameof(AuditEventFilter));
ConfigurationItemFactory.Default.FilterFactory.RegisterType<MyNamespace.UserLogLevelFilter>("MyNamespace."+nameof(UserLogLevelFilter));
ConfigurationItemFactory.Default.FilterFactory.RegisterType<MyNamespace.UserEventFilter>("MyNamespace."+nameof(UserEventFilter));
ConfigurationItemFactory.Default.LayoutRendererFactory.RegisterType<MyNamespace.TruncateLayoutRenderer>("MyNamespace."+"TruncateLayout");
```
The assembly-prefix was introduced before my time, and was probably intended for handling type-alias clashes between multiple assemblies. Another possible reason could be to signal that type-alias is not coming from the default NLog-assembly.

**Comment by snakefoot** [comment]
Thank you again for reporting this issue.

Will it be okay, that NLog v5.2.1 is released in 1-2 weeks time ? (Would like to collect as many issues as possible before making the release).

**Comment by jonreis** [comment]
@snakefoot sorry for the late response. The notification for the message went into my spam folder.

I am good with whatever works for you. Thank you very much for all your great work!

**Comment by snakefoot** [comment]
NLog v5.2.1 has now been released - https://www.nuget.org/packages/NLog

Thank you again for taking the time to report this issues.
