### ISSUE TITLE
Network target throws unhandled exception if network is unreachable

### ISSUE THREAD

**Issue by gurkerlbaron** [NLog/NLog#5325]
Hello,

I'm using Nlog version 5.2.2 and the network target for logging

My target configuration:

```
  <target xsi:type="Network" name="SyslogTarget"
                    onOverflow="Split"
                    newLine="false"
                    lineEnding="None"
                    layout="${defaultLayout}"
                    maxMessageSize="1000"
                    encoding="utf-8"
                    connectionCacheSize="5"
                    maxConnections="0"
                    maxQueueSize="0"
                    keepConnection="true"
                    onConnectionOverflow="AllowNewConnnection"
                    address="udp://10.137.8.51:514" />
````

Now on my machine (embedded system) the target ip address is not reachable, because I have NO default gateway and my locale ip address is in a different ip range. There is also no route the configured destination address. 

This leads to an unhandled exception and my software cannot be started (regardles of logging would work or not)

Stack trace:

```
Unhandled exception. NLog.NLogRuntimeException: Exception occurred in NLog
 ---> System.IO.IOException: Error: NetworkUnreachable, Address: udp://10.137.8.51:514
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__0(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.NetworkTarget.<>c__DisplayClass79_0.<WriteBytesToCachedNetworkSender>b__0(Exception ex)
   at NLog.Internal.NetworkSenders.QueuedNetworkSender.SignalSocketFailedForPendingRequests(Exception pendingException)
   at NLog.Internal.NetworkSenders.QueuedNetworkSender.DequeueNextItem()
   at NLog.Internal.NetworkSenders.QueuedNetworkSender.EndRequest(AsyncContinuation asyncContinuation, Exception pendingException)
   at NLog.Internal.NetworkSenders.UdpNetworkSender.SocketOperationCompleted(SocketAsyncEventArgs args)
   at NLog.Internal.NetworkSenders.UdpNetworkSender.BeginSocketRequest(SocketAsyncEventArgs args)
   at NLog.Internal.NetworkSenders.UdpNetworkSender.BeginRequestAsync(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
```

I would expect the exception to be handled and a warning trace to the internal log

**Comment by snakefoot** [comment]
I'm guessing that you are using `throwExceptions="true"` in your NLog-configuration. It is intended for NLog unit-testing, and not for production systems.

**Comment by gurkerlbaron** [comment]
Thanks for the fast response, you are right, I had throwExceptions set to true. In my opinion an exception for UDP sending doesn't make sense, UDP is fire and forget and you will never know if the message arrived.

**Comment by snakefoot** [comment]
I'm not the one to decide if UDP protocol should fail or not. NLog just tries to report the exceptions/errors received from the network-API.
