### ISSUE TITLE
"Unrecognized value" exception on empty arrays and objects

### ISSUE THREAD

**Issue by vzabrodin** [NLog/NLog#5469]
**NLog version**: 5.3.8

**Platform**: .NET 7

**Current NLog config**

```json
{
  "NLog": {
    "throwConfigExceptions": true,
    "variables": {},
    "extensions": [],
    "targets": {},
    "rules": []
  }
}
```

**What is the current result?**

The program throws an exception at startup if sections with empty arrays or objects are specified

```
NLog.NLogConfigurationException
  HResult=0x80131500
  Message=Unrecognized value 'targets'='' for element 'NLog'
  Source=NLog
  StackTrace:
   at NLog.Config.LoggingConfigurationParser.SetNLogElementSettings(ILoggingConfigurationElement nlogConfig)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Extensions.Logging.NLogLoggingConfiguration.LoadConfigurationSection(IConfigurationSection nlogConfig)
   at NLog.Extensions.Logging.SetupBuilderExtensions.LoadConfigurationFromSection(ISetupBuilder setupBuilder, IConfiguration configuration, String configSection)
   at NLog.Web.SetupBuilderExtensions.LoadConfigurationFromAppSettings(ISetupBuilder setupBuilder, String basePath, String environment, String nlogConfigSection, Boolean optional, Boolean reloadOnChange)
   at WebApplication2.Program.Main(String[] args) in E:\WebApplication2\WebApplication2\Program.cs:line 18
```

**What is the expected result?**

The program works if no empty arrays or objects are specified

**Are there any workarounds?**

Removing sections with solves the issue

**Is there a version in which it did work?**

This started happening after I migrated my project from .NET 5 to .NET 7. I also reproduced the problem in .NET 6.

**Comment by snakefoot** [comment]
Yes that sounds like a bug. The parsing og NLog LoggingConfiguration tries to warn you when meeting unexpected values (that will be ignored). I'm guessing an empty JSON-dictionary is probably returned as something that looks like a simple-value, instead of a complex-structure.

Thank you for reporting the issue. If you have the energy, then a pull-request is most wellcome. Curious whether the code-fix should happen in NLog.Extensions.Logging-library, that converts the JSON-dictionary as config-input for the NLog-parser.

**Comment by RodionovDmitry** [comment]
Would that solve the issue? 
https://github.com/NLog/NLog.Extensions.Logging/pull/724

**Comment by snakefoot** [comment]
[NLog.Extensions.Logging v5.3.9](https://www.nuget.org/packages/NLog.Extensions.Logging) has been released, that allows official sections like `targets` and `variables` to be empty.
