### ISSUE TITLE
Config StackTrace

### ISSUE THREAD

**Issue by JinPachi** [NLog/NLog#548]
Hi all.
Please, help me.

message with StackTrace by default is next:
```
2015-02-02 15:09:36.6534|ERROR|Example|System.Exception: Exception of type 'System.Exception' was thrown.
   at ConsoleApplication3.Program.Method2() in c:\Users\viktor.lebedev\Documents\Visual Studio 2012\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 19
   at ConsoleApplication3.Program.Method1() in c:\Users\viktor.lebedev\Documents\Visual Studio 2012\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 14
   at ConsoleApplication3.Program.Main(String[] args) in c:\Users\viktor.lebedev\Documents\Visual Studio 2012\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 28|}
```

Can i make change config Nlog that this message is written by Nlogger in one line?

```
2015-02-02 15:09:36.6534|ERROR|Example|System.Exception: Exception of type 'System.Exception' was thrown.   at ConsoleApplication3.Program.Method2() in c:\Users\viktor.lebedev\Documents\Visual Studio 2012\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 19  at ConsoleApplication3.Program.Method1() in c:\Users\viktor.lebedev\Documents\Visual Studio 2012\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 14 at ConsoleApplication3.Program.Main(String[] args) in c:\Users\viktor.lebedev\Documents\Visual Studio 2012\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 28|}
```

Thanks,
Cheers,
Victor.

**Comment by 304NotModified** [comment]
You can use https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer

**Comment by JinPachi** [comment]
Thank you very much for your response! 
Its all ok.
