### ISSUE TITLE
Empty values ​​{aspnet-user-*} layout renders in DatabaseTarget

### ISSUE THREAD

**Issue by Nelissify** [NLog/NLog#5650]
Hi! 

I am using DatabaseTarget to log messages to the database. When using ${aspnet-user-identity} will pass empty value to the query, and using ${aspnet-user-claim} will pass the name of the claim instead of the value. If I log the same message to a file, everything is fine.
The code below worked correctly in .NET Core 5 with NLog.Web.AspNetCore 4.12.0

**NLog.WebAspNetCore version**: 5.3.14
**NLog.Extension.Logging version**: 5.3.14
**NLog.Database version**: 5.3.4

**Platform**: .NET8

**nlog.config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      autoloadExtensions="true"
      internalLogLevel="trace"
      internalLogFile="c:\temp\nlog-internal.txt">

  <targets>
    <target xsi:type="File" name="application" fileName="${basedir}/logs/nlog-app-${shortdate}.log" layout="${longdate} | ${uppercase:${level}} | ${logger} | CompanyId: ${aspnet-user-claim:CompanyId} | UserId: ${aspnet-user-identity} | ${message} | ${exception:format=tostring,Data}" />
  </targets>

  <rules>
    <logger name="DiamondIS.*" minlevel="Trace" writeTo="application" final="true" FilterDefaultAction="Log">
      <filters>
        <when condition="contains('${exception:format=Type}', 'DiamondIS.UserFriendlyException')" action="Ignore" />
      </filters>
    </logger>
    <logger name="*" minlevel="Error" writeTo="application" final="true" />
  </rules>

</nlog>
```

**Program.cs**

```c#
Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.UseWebRoot("wwwroot");
        webBuilder.UseIISIntegration();
        webBuilder.UseStartup<Startup>();
    })
    .UseContentRoot(Directory.GetCurrentDirectory())
    .ConfigureLogging((hostingContext, logging) =>
    {
        logging.ClearProviders();
        logging.AddConsole();
        logging.AddDebug();
    })
    .UseNLog()
    .Build()
    .Run();
```

**Startup.cs**

```c#
public Startup(IWebHostEnvironment env)
{
    var builder = new ConfigurationBuilder()
	.SetBasePath(env.ContentRootPath)
	.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
	.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true)
        .AddJsonFile($"appsettings.{Environment.MachineName}.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables();

    Configuration = builder.Build();
    HostingEnvironment = env;

    ConfigureLog();
}

private void ConfigureLog()
{
    var dbTarget = new NLog.Targets.DatabaseTarget();
    dbTarget.Name = "db";
    dbTarget.DBProvider = "System.Data.SqlClient";
    dbTarget.ConnectionString = Configuration["ConnectionStrings:DiamondISDatabase"];
    dbTarget.CommandText = @"INSERT INTO dbo.Dis_Log (Created, Level, Message, ExceptionMessage, CompanyId, UserId, Category)
        VALUES (@Created, @Level, @Message, @ExceptionMessage, @CompanyId, @UserId, 0);";
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Created", "${date:universalTime=true}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Level", "${level:format=Ordinal}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Message", "${message}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@ExceptionMessage", "${exception}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@CompanyId", "${aspnet-user-claim:CompanyId}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@UserId", "${aspnet-user-identity}"));

    var dbRule = new NLog.Config.LoggingRule("*", NLog.LogLevel.Trace, dbTarget);
    NLog.LogManager.Configuration.LoggingRules.Insert(0, dbRule);

    NLog.LogManager.ReconfigExistingLoggers();
}
```

**nlog-internal.txt** 
```
2024-10-15 11:22:56.1702 Trace DatabaseTarget(Name=db): Open connection.
2024-10-15 11:22:56.1702 Trace DatabaseTarget(Name=db): Executing Text: INSERT INTO dbo.Dis_Log (Created, Level, Message, ExceptionMessage, CompanyId, UserId, Category)
   VALUES (@Created, @Level, @Message, @ExceptionMessage, @CompanyId, @UserId, 0);
2024-10-15 11:22:56.1702 Trace   DatabaseTarget: Parameter: '@Created' = '2024/10/15 09:22:56.170' (String)
2024-10-15 11:22:56.1702 Trace   DatabaseTarget: Parameter: '@Level' = '2' (String)
2024-10-15 11:22:56.1702 Trace   DatabaseTarget: Parameter: '@Message' = 'Test log message' (String)
2024-10-15 11:22:56.1702 Trace   DatabaseTarget: Parameter: '@ExceptionMessage' = 'System.Exception: Test exception' (String)
2024-10-15 11:22:56.1702 Trace   DatabaseTarget: Parameter: '@CompanyId' = 'CompanyId' (String)
2024-10-15 11:22:56.1702 Trace   DatabaseTarget: Parameter: '@UserId' = '' (String)
2024-10-15 11:22:56.1702 Error DatabaseTarget(Name=db): Error when writing to database. Exception: System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the nvarchar value 'CompanyId' to data type int.
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.ExecuteDbCommandWithParameters(LogEventInfo logEvent, IDbConnection dbConnection, IDbTransaction dbTransaction)
   at NLog.Targets.DatabaseTarget.WriteLogEventSuppressTransactionScope(LogEventInfo logEvent, String connectionString)
ClientConnectionId:e1921859-f67f-42b3-86bd-b73a2f24fe00
Error Number:245,State:1,Class:16
2024-10-15 11:22:56.1702 Trace DatabaseTarget(Name=db): Close connection because of error
```

**nlog-app.log**
```
2024-10-15 11:22:56.1702 | INFO | DiamondIS.Application.ApplicationFacade | CompanyId: 1 | UserId: 3 | Test log message | System.Exception: Test exception
```

If I look at the HttpContext in the place where the message is logged, the Identity including claims is filled in correctly

```
+		[0]	{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: 3}	System.Security.Claims.Claim
+		[1]	{Username: dia}	System.Security.Claims.Claim
+		[2]	{http://schemas.microsoft.com/ws/2008/06/identity/claims/role: SuperAdmin}	System.Security.Claims.Claim
+		[3]	{CompanyId: 1}	System.Security.Claims.Claim
+		[4]	{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/webpage: a169b2f7-af0d-45d5-8c81-5795c8da7990}	System.Security.Claims.Claim
+		[5]	{exp: 1729069941}	System.Security.Claims.Claim
+		[6]	{iss: DiamondIS}	System.Security.Claims.Claim
+		[7]	{aud: DiamondIS}	System.Security.Claims.Claim
```

Can you advise me what I am doing wrong after the upgrade?

Thank you

**Comment by snakefoot** [comment]
I'm guessing the NLog configuration is initialized in the following order:
1) DatabaseTarget is created and initialized with the different database-parameters (before loading NLog extensions like NLog.Web)
2) NLog Configuration is loaded along with automatically loading NLog extensions (Like NLog.Web)
3) NLog DatabaseTarget is added to the NLog configuration.

I think the easy fix is changing the ordering a little inside `ConfigureLog`:
```c#
private void ConfigureLog()
{
    var configuration = NLog.LogManager.Configuration; // First load NLog.config with NLog extension (Like NLog.Web)

    var dbTarget = new NLog.Targets.DatabaseTarget();
    dbTarget.Name = "db";
    dbTarget.DBProvider = "System.Data.SqlClient";
    dbTarget.ConnectionString = Configuration["ConnectionStrings:DiamondISDatabase"];
    dbTarget.CommandText = @"INSERT INTO dbo.Dis_Log (Created, Level, Message, ExceptionMessage, CompanyId, UserId, Category)
        VALUES (@Created, @Level, @Message, @ExceptionMessage, @CompanyId, @UserId, 0);";
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Created", "${date:universalTime=true}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Level", "${level:format=Ordinal}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Message", "${message}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@ExceptionMessage", "${exception}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@CompanyId", "${aspnet-user-claim:CompanyId}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@UserId", "${aspnet-user-identity}"));

    var dbRule = new NLog.Config.LoggingRule("*", NLog.LogLevel.Trace, dbTarget);
    configuration.LoggingRules.Insert(0, dbRule);

    NLog.LogManager.ReconfigExistingLoggers();
}
```
Alternative change to fluent-config-api:
```c#
NLog.LogManager.Setup().LoadConfigurationFromAppSettings().LoadConfiguration(cfg => {
    var dbTarget = new NLog.Targets.DatabaseTarget();
    dbTarget.Name = "db";
    dbTarget.DBProvider = "System.Data.SqlClient";
    dbTarget.ConnectionString = Configuration["ConnectionStrings:DiamondISDatabase"];
    dbTarget.CommandText = @"INSERT INTO dbo.Dis_Log (Created, Level, Message, ExceptionMessage, CompanyId, UserId, Category)
        VALUES (@Created, @Level, @Message, @ExceptionMessage, @CompanyId, @UserId, 0);";
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Created", "${date:universalTime=true}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Level", "${level:format=Ordinal}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@Message", "${message}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@ExceptionMessage", "${exception}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@CompanyId", "${aspnet-user-claim:CompanyId}"));
    dbTarget.Parameters.Add(new NLog.Targets.DatabaseParameterInfo("@UserId", "${aspnet-user-identity}"));

   cfg.ForLogger().TopRule().WriteTo(dbTarget);
});
```

**Comment by Nelissify** [comment]
Addition `var configuration = NLog.LogManager.Configuration;` to the top of the `ConfigureLog()` method solved my problem!

Thanks a lot!
