### ISSUE TITLE
Database target - CommandType property error in XML config file

### ISSUE THREAD

**Issue by e-lima** [NLog/NLog#571]
NLog version: 3.2.0.0  (from NuGet)
Common.Logging: 3.0.0.0 (from NuGet)
Common.Logging.Core: 3.0.0.0 (from NuGet)
Common.Logging.NLog20: 3.0.0.0 (from NuGet)

Using the following target:

    <target xsi:type="Database" name="app_logdb" connectionStringName="APP_LOG" dbProvider="Oracle.DataAccess.Client" commandType="Text"
          commandText="INSERT INTO APP_LOG (TIMESTAMP, LOGGER, LOG_LEVEL, MESSAGE, EXCEPTION) 
                                        VALUES (SYSDATE, :logger, :log_level, :message, :exception)">
      <install-command text="create table APP_LOG (
       TIMESTAMP DATE NOT NULL,
       LOGGER VARCHAR2(32) NOT NULL,
       LOG_LEVEL VARCHAR2(16) NOT NULL,
       MESSAGE VARCHAR2(256) NOT NULL,
       EXCEPTION VARCHAR2(2048)
    );" commandType="Text"></install-command>

      <uninstall-command text="drop table APP_LOG"></uninstall-command>

      <parameter layout="${logger}" name="logger"></parameter>
      <parameter layout="${uppercase:${level}}" name="log_level"></parameter>
      <parameter layout="${message}" name="message"></parameter>
      
      <parameter layout="${stacktrace}" name="exception"></parameter>
    </target>

  
  
I got the following error when trying to log an event:

    NLog.NLogRuntimeException:  Exception occurred in NLog
       at NLog.LoggerImpl.<>c__DisplayClass1.<Write>b__0(Exception ex)
       at NLog.Internal.SingleCallContinuation.Function(Exception exception)
       at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
       at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
       at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
       at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
       at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent)
       at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
       at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 951
       at Common.Logging.NLog.NLogLogger.DebugFormat(String format, Object[] args) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 321
       at myApp.ExecutionWrapper`1.Execute() in C:\TFS\myApp\ExecutionWrapper.cs:line 49
       at SyncInvokeGetCostPrices(Object , Object[] , Object[] )
       at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
       at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)

  
  
The inner exception is:

    System.ArgumentException: Value does not fall within the expected range.
    
       at Oracle.DataAccess.Client.OracleCommand.set_CommandType(CommandType value)
       at NLog.Targets.DatabaseTarget.WriteEventToDatabase(LogEventInfo logEvent)
       at NLog.Targets.DatabaseTarget.Write(LogEventInfo logEvent)
       at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

  
  
Observing the log instance properties, I can get the following:

![error-nlog](https://cloud.githubusercontent.com/assets/893724/6167600/19516ba6-b2a4-11e4-86b0-e79c92f81aa4.png)

The problem is that the `CommandType` has an invalid value: `0`.
Should it be a XmlLoggingConfiguration error?

**Comment by Xharze** [comment]
Do you have exceptions enabled in the config?

**Comment by e-lima** [comment]
What kind of exceptions?
Are you talking about `throwExceptions="true"` attribute in `<nlog>` element?

**Comment by Xharze** [comment]
Yes

**Comment by e-lima** [comment]
Yes ... It is defined as follow:

    <nlog 
      throwExceptions="true" 
      internalLogFile="D:\application\logs\nlog_internal_log.txt" 
      autoReload="true" 
      internalLogLevel="Error">

**Comment by Xharze** [comment]
It that case this is a bug. And yes it should probably be an
XmlConfigurationException.
