### ISSUE TITLE
XSD schema of NLog.Config NuGet package is wrong

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#594]
The XSD schema of the [NLog.Config NuGet package](https://www.nuget.org/packages/NLog.Config/) refers to `http://www.nlog-project.org/schemas/NLog.xsd`

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" >
```

This is wrong because the XSD is locally available and the XSD online is out-dated .

**Comment by ilya-g** [comment]
You can create updated NLog.xsd by building NLog.proj with targets Build and XSD:
`msbuild NLog.proj /t:Build,XSD`

But now the `XSD` build step seems broken. It fails with the message:
````
EXEC : warning : System.NotSupportedException: Unknown API type 'NLog.Targets.LineEndingMode'. [d:\NLog\src\NLog.proj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
     at MakeNLogXSD.XsdFileGenerator.GetXsdType(String apiTypeName, Boolean attribute) in d:\NLog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 321
     at MakeNLogXSD.XsdFileGenerator.GetPropertyElement(XElement propertyElement) in d:\NLog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 272
     at MakeNLogXSD.XsdFileGenerator.GetPropertyElements(XElement type) in d:\NLog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 242
     at MakeNLogXSD.XsdFileGenerator.ProcessApiFile(String apiFile) in d:\NLog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 106
     at MakeNLogXSD.Program.Main(String[] args) in d:\NLog\tools\MakeNLogXSD\Program.cs:line 100
d:\NLog\src\NLog.proj(477,5): warning MSB3073: The command ""d:\NLog\src\..\build\\bin\Tools\MakeNLogXSD.exe" -api NLogMerged.api.xml -out NLog.xsd" exited with code 1.
`````

**Comment by ilya-g** [comment]
I've investigated this a bit deeper and found out that this happened because of the `LineEnding` property, introduced in FileTarget in PR #473.
Seems that the type of this property, namely `LineEndingMode`, is not supported neither in XSD generation, nor in xml configuration reading. The latter is a serious issue.

**Comment by Xharze** [comment]
This have to be fixed before the next release
