### ISSUE TITLE
[MailTarget] NRE if To not initialized

### ISSUE THREAD

**Issue by hayhay27** [NLog/NLog#596]
**NLog version:** 3.0.0

**Internal Log:**

```
2015-02-11 15:23:43.2855 Error Error in lazy writer timer procedure: NLog.NLogRuntimeException: Exception occurred in NLog ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NLog.Targets.MailTarget.GetSmtpSettingsKey(LogEventInfo logEvent)
   at NLog.Targets.MailTarget.<Write>b__0(AsyncLogEventInfo c)
   at NLog.Internal.SortHelpers.BucketSort[TValue,TKey](IEnumerable`1 inputs, KeySelector`2 keySelector)
   at NLog.Targets.MailTarget.Write(AsyncLogEventInfo[] logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEvents)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1.<Write>b__0(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEvents)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)
```

**Current result:** Mail is not send
**Expected result:** Mail must to be sent to Cc and Bcc recipients
**Config:**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogFile="C:\dev\Nlog.log" throwExceptions="true" internalLogLevel="Error">
  <targets async="true">
    <target xsi:type="Mail"
            name="NotificationTarget"
            bcc="<mailBcc>"
            from="<mailFrom>"
            html="false"
            subject="Notification"
            smtpServer="<smtpHost>"
            smtpAuth="<smtpAuth>"
            smtpUserName="<smtpUserName>"
            smtpPassword="<smtpPassword>"
            layout="${message}"
            encoding="utf-8"
          />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="NotificationTarget">    
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment]
Thanks for the report.  I think this is fixed already, we should check that.
