### ISSUE TITLE
WebserviceTarget - HttpGet is broken (Exception thrown)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#701]
The current implementation of `WebServiceTarget` throws an Exception with `HttpGet`. 

```
 Result Message:	System.Net.ProtocolViolationException : Cannot send a content-body with this verb-type.
 Result StackTrace:	
 at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
    at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
    at NLog.Targets.WebServiceTarget.<>c__DisplayClass1.<DoInvoke>b__0(AsyncCallback r) in NLog\src\NLog\Targets\WebServiceTarget.cs:line 151
    at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncContinuation continuation, HttpWebRequest request, Func`2 beginFunc, Func`2 getStreamFunc) in NLog\src\NLog\Targets\WebServiceTarget.cs:line 218
    at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncContinuation continuation) in NLog\src\NLog\Targets\WebServiceTarget.cs:line 154
    at NLog.Targets.MethodCallTargetBase.Write(AsyncLogEventInfo logEvent) in NLog\src\NLog\Targets\MethodCallTargetBase.cs:line 79
    at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent) in NLog\src\NLog\Targets\Target.cs:line 215
    at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException) in NLog\src\NLog\LoggerImpl.cs:line 194
    at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory) in NLog\src\NLog\LoggerImpl.cs:line 97
    at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message) in NLog\src\NLog\Logger.cs:line 480
    at NLog.Logger.Info(String message) in NLog\src\NLog\Logger1.cs:line 636
    at NLog.UnitTests.Targets.WebServiceTargetTests.<>c__DisplayClassc.<TestWebserviceCall_get>b__b() in NLog\tests\NLog.UnitTests\Targets\WebServiceTargetTests.cs:line 326
    at NLog.UnitTests.Targets.WebServiceTargetTests.StartOwinTest(Action tests) in NLog\tests\NLog.UnitTests\Targets\WebServiceTargetTests.cs:line 422
    at NLog.UnitTests.Targets.WebServiceTargetTests.TestWebserviceCall_get() in NLog\tests\NLog.UnitTests\Targets\WebServiceTargetTests.cs:line 323
```

See unit test `WebServiceTargetTests.WebserviceTest_restapi_httpget` (now skipped!)  and #699

**Comment by 304NotModified** [comment]
Note: locally tested with the versions: 3.2.1, 3.0.0 and 2.0.1 - the same results - in this case **un**successful! (same exception) 

(for example the code of [WebserviceTarget of 3.2.1](https://raw.githubusercontent.com/NLog/NLog/v3.2.1/src/NLog/Targets/WebServiceTarget.cs))

**Comment by 304NotModified** [comment]
maybe we should not trying to post something. Anyway, a better error is needed.

**Comment by 304NotModified** [comment]
Current config which goes wrong:

``xml
 <nlog throwExceptions='true'>
                    <targets>
                        <target type='WebService'
                                name='ws'
                                url='{0}{1}'
                                protocol='HttpPost'
                                encoding='UTF-8'
                               >
                            <parameter name='param1' type='System.String' layout='${{message}}'/> 
                            <parameter name='param2' type='System.String' layout='${{level}}'/>
     
                        </target>
                    </targets>
                    <rules>
                      <logger name='*' writeTo='ws'>
                       
                      </logger>
                    </rules>
```

**Comment by MikeFH** [comment]
The first solution (with parameters) looks easier to use and the configuration would be similar to the `HttpPost `protocol. The target would send parameters like that to the endpoint : `http://localhost:1234/logme?param1=message&param2=level.`

The second solution allows to build a wider range of URLs but it feels weird that the endpoint supposed to receive the logs can vary for every log message. It seems to me that the layoutable URL is another feature not related to the `HttpGet` protocol.

**Comment by 304NotModified** [comment]
Thanks for this feedback!



> It seems to me that the layoutable URL is another feature not related to the HttpGet protocol.

Agree, but it's maybe more easy readable and I think there is no problem to allow both. (yes, we need to scan for the `?` in the url)

**Comment by MikeFH** [comment]
Could the [UriBuilder](https://msdn.microsoft.com/en-us/library/system.uribuilder%28v=vs.110%29.aspx) class be used for adding parameters to the query string ? It seems to be included in all the .Net versions supported by NLog. That way it would be easy to add the parameters to the URL even if it already contained a query string from the config.

**Comment by 304NotModified** [comment]
Thanks a good idea!

**Comment by MikeFH** [comment]
If it's OK, I'd like to give a try to make the HttpGet protocol work.

**Comment by 304NotModified** [comment]
That would be great. if you add some unit tests, it has a big change it will be accepted :)
