### ISSUE TITLE
Filter condition to ignore certain exceptions

### ISSUE THREAD

**Issue by CaseyRedisAtWork** [NLog/NLog#728]
I'm trying to create a filter to exclude certain error exceptions from getting sent to our email target.  I've tried various formats for the contains() function but to no avail.  Is this kind of filtering not possible through the config and we'd need to modify the code to log differently?

As an example, here are (what I hope are) relevant snippets of the NLog.config followed by the email body received.  I would have expected this particular log entry (and therefore email) to have been ignored.

Any help would be greatly appreciated.

```
		<target name="error-email" xsi:type="Mail"
		        smtpServer="smtp"
		        smtpUsername="support@xyz.com"
		        smtpPassword="pwd"
		        smtpAuthentication="Basic"
		        from="support@xyz.com"
		        to="support@xyz.com"
		        subject="LOG: ${machinename} Service [${level}]"
		        body="[${level}] ${longdate} ${logger} ${message} ${exception:format=stacktrace}">
		</target>
```

```
<rules>
		<logger name="*" minlevel="Error" writeTo="error-email">
			<filters>
				<when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','You have exceeded the timeout set on your binding')" action="Ignore" />
				<when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','The socket connection was aborted')" action="Ignore" />
				<when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it has been Aborted')" action="Ignore" />
				<when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','Cannot access a disposed object') and contains('${exception:format=stacktrace}','System.ServiceModel.Channels.ServiceChannel')" action="Ignore" />
			</filters>
		</logger>		
	</rules>
```

Email Body Received:
>[Error] 2015-06-05 12:43:55.9625 RGS.RR Exception
Message: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:01:00'.
InnerException: System.IO.IOException: The write operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:01:00'. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.ServiceModel.Channels.SocketConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.SocketConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   at System.ServiceModel.Channels.BufferedConnection.WriteNow(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, BufferManager bufferManager)
   at System.ServiceModel.Channels.BufferedConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   at System.ServiceModel.Channels.TracingConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.NegotiateStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.ServiceModel.Channels.StreamConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
Source: mscorlib
StackTrace: 
Server stack trace: 
   at System.ServiceModel.Channels.StreamConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   at System.ServiceModel.Channels.StreamConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, BufferManager bufferManager)
   at System.ServiceModel.Channels.FramingDuplexSessionChannel.OnSendCore(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.OnSend(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.OutputChannel.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
>
>Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at RGS.RR.MessageNotifications(List`1 rows, String userId)
   at RGS.RR.Run()
TargetSite: Void HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessage)
HelpLink:

**Comment by 304NotModified** [comment]
I would expect also the same :the messages should be ignored. 

The exceptions are strange. Do you have more targets configured?  Can you post the full config? 

Which version of NLog is this?

**Comment by CaseyRedisAtWork** [comment]
Thanks for your reply.

Yes, the exceptions are strange - WCF errors that arguably we should handle better.

There are other targets, but none use filtering (in fact, this is the first time I'm trying to use it).  I put the complete config up on pastebin: http://pastebin.com/ckwsn80U

We're currently using NLog 2.0

**Comment by 304NotModified** [comment]
Config:

```xml
<?xml version="1.0"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true">

	<targets>
		<target xsi:type="Console" name="console"
				layout="[${level}] ${longdate} ${logger} ${message} ${exception:format=stacktrace}" />

		<target name="file" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
			<target xsi:type="File"
			        layout="[${level}]T:${threadid}/${threadname} ${date:format=HH\:mm\:ss.ffff} ${logger} ${message} ${exception:format=stacktrace}"
			        fileName="C:/logs/RS/${shortdate}-Info.log"
			        keepFileOpen="false"
			        encoding="iso-8859-2" />
		</target>

		<target name="file-info" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
			<target xsi:type="File"
			        layout="[${level}]T:${threadid}/${threadname} ${date:format=HH\:mm\:ss.ffff} ${logger} ${message} ${exception:format=stacktrace}"
			        fileName="C:/logs/RS/Info-${shortdate}-Debug.log"
			        keepFileOpen="false"
			        encoding="iso-8859-2" />
		</target>

		<target name="client-usage-file" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
			<target xsi:type="File"
			        layout="${longdate} ${message}"
			        fileName="c:/logs/RS/${shortdate}-ClientUsage.log"
			        keepFileOpen="false"
			        encoding="iso-8859-2" />
		</target>

		<target name="file-error" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Discard">
			<target xsi:type="File"
			        layout="[${level}] ${longdate} ${logger} ${message} ${exception:format=stacktrace}"
			        fileName="c:/logs/RS/${shortdate}-Errors.log"
			        keepFileOpen="false"
			        encoding="iso-8859-2" />
		</target>

        <target name="error-email" xsi:type="Mail"
                smtpServer="smtp"
                smtpUsername="support@xyz.com"
                smtpPassword="pwd"
                smtpAuthentication="Basic"
                from="support@xyz.com"
                to="support@xyz.com"
                subject="LOG: ${machinename} Service [${level}]"
                body="[${level}] ${longdate} ${logger} ${message} ${exception:format=stacktrace}">
        </target>

	</targets>

	<rules>
		<logger name="*" minlevel="Debug" writeTo="file" />
		<logger name="*" minlevel="Info" writeTo="file-info" />
		<logger name="*" minlevel="Error" writeTo="file-error" />
		<logger name="ClientUsage" minlevel="Debug" writeTo="client-usage-file" />
		<logger name="*" minlevel="Error" writeTo="mail-dhs">
			<filters>
                <when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','You have exceeded the timeout set on your binding')" action="Ignore" />
                <when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','The socket connection was aborted')" action="Ignore" />
                <when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it has been Aborted')" action="Ignore" />
                <when condition="contains('${logger}','RGS.RR') and contains('${exception:format=stacktrace}','Cannot access a disposed object') and contains('${exception:format=stacktrace}','System.ServiceModel.Channels.ServiceChannel')" action="Ignore" />
            </filters>
		</logger>
	</rules>

</nlog>
```

**Comment by 304NotModified** [comment]
I'm sorry but don't support NLog 2 anymore. NLog 2.0 is 4 years old.  We almost are ready with the release of 4.0
