### ISSUE TITLE
MainModule does not work

### ISSUE THREAD

**Issue by davidfigueroa** [NLog/NLog#766]
as per https://github.com/nlog/nlog/wiki/ProcessInfo-Layout-Renderer  following renderer in .net 4.5 console application should work ${processinfo:property=MainModule}, but it throws an exception on application start up.

this is my config:
```
	<targets>
		<target xsi:type="File" name="f"
			fileName="/logs/${processinfo:property=MainModule}.log"/>
	</targets>
	<rules>
		<logger name="*" minlevel="Trace" writeTo="f" />
	</rules>
```

Exception is:

{System.TypeInitializationException: The type initializer for 'ConsoleApplication1.NLogTest' threw an exception. ---> NLog.NLogConfigurationException: Invalid enumeration value 'MainModule'.
   at NLog.Internal.PropertyHelper.TryGetEnumValue(Type resultType, String value, Object& result)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object o, String name, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object o, String name, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName)
   at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at ConsoleApplication1.NLogTest..cctor() in c:\Users\davidfig\Documents\Visual Studio 2013\Projects\ConsoleApplication1\ConsoleApplication1\NLogTest.cs:line 10
   --- End of inner exception stack trace ---
   at ConsoleApplication1.NLogTest..ctor()
   at ConsoleApplication1.Program.Main(String[] args) in c:\Users\davidfig\Documents\Visual Studio 2013\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 6
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()}

**Comment by 304NotModified** [comment]
Which. Net and NLog version is this?

**Comment by davidfigueroa** [comment]
.net 4.5 and nlog 4.0.1.

**Comment by 304NotModified** [comment]
I think it's removed since NLog 2.0. 

I have to check why

**Comment by 304NotModified** [comment]
Possible values: https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/ProcessInfoProperty.cs

**Comment by 304NotModified** [comment]
I can find it in the code too bad.

But what do you expected what get logged (example please). 
I see that `Process.MainModule` is of type `ProcessModule`

https://msdn.microsoft.com/en-us/library/system.diagnostics.process.mainmodule(v=vs.110).aspx

there is also `${processname:fullName=Boolean}`. It that the same?

**Comment by davidfigueroa** [comment]
Julian, I was hopping that MainModule wrote the name of the entry point
.net assembly. I am currently using ${processname} in a deployment config
file is that is shared by multiple .net projects (only when deployed). file
name = "${processname}.log" works well as each exe produced has a different
name and thus log files are created with distinct descriptive names.
but, "${processname}.log" does not work for my web applications since them
all produce log file name w3p.exe. i was hopping that MainModule solved
this problem by writing the .net assembly name of the main entry point to
the application which in web apps would created log files named
MyAssemblyName.log.



On Fri, Jun 19, 2015 at 12:44 PM, Julian Verdurmen <notifications@github.com

**Comment by davidfigueroa** [comment]
btw my plan does not
work: System.Diagnostics.Process.GetCurrentProcess().MainModule.ModuleName
returns "w3p.exe" from a web site.

**Comment by 304NotModified** [comment]
Clear story :+1:

Could https://github.com/NLog/NLog/wiki/IIS-site-name-Layout-Renderer be useful?

**Comment by davidfigueroa** [comment]
yes, i tried this. but as of now i have a single config file shared for
console and web apps. i tried log name="${processname} - ${iis-site-name}.log"
so that it works with both console and web apps, but ${iis-site-name}
throws an exception in web apps.

i think that it would be cool to have ${entryassemblyname} that works both
in exe and in web projects
http://stackoverflow.com/questions/4277692/getentryassembly-for-web-applications

**Comment by 304NotModified** [comment]
The latter point,  see https://github.com/NLog/NLog/issues/275

I think it's the easiest way to write your own LayoutRenderer. A good starting point are https://github.com/NLog/NLog.Web/blob/master/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs and https://github.com/NLog/NLog/wiki/How-to-write-a-Target. The latter is about writing a custom target,  but layout renderers are almost the same way.

**Comment by 304NotModified** [comment]
wiki has been updated (in sync with 4.0.1)

**Comment by 304NotModified** [comment]
I will amuse your question has been answered. If not, let me know!
