### ISSUE TITLE
System.InvalidOperationException: Collection was modified in GetCurrentClassLogger

### ISSUE THREAD

**Issue by ha11owed** [NLog/NLog#956]
Using the NLog 4.1.2.0 sometimes throws the following error:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at NLog.LogFactory.GetTargetsByLevelForLogger(String name, IEnumerable`1 rules, TargetWithFilterChain[] targetsByLevel, TargetWithFilterChain[] lastTargetsByLevel, Boolean[] suppressedLevels)
   at NLog.LogFactory.GetConfigurationForLogger(String name, LoggingConfiguration configuration)
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogManager.GetCurrentClassLogger()
```

This seems to happen when I have a very large number of threads that generate logs.

EDIT:
Could this be related to: https://github.com/NLog/NLog/issues/500 ?
The stack traces are very similar.

**Comment by 304NotModified** [comment]
Well #500 is ObjectGraphScanner, and this `GetTargetsByLevelForLogger`. So I think is a another issue. 

We will check this.
