### ISSUE TITLE
Exception is thrown when archiving is enabled

### ISSUE THREAD

**Issue by stepan-p** [NLog/NLog#957]
I have the following NLog.config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogFile="d:\nlogproblems.txt"
      internalLogLevel="Debug"
      throwExceptions="true" >

  <targets>
    <target name="logfile" xsi:type="File" fileName="${basedir}/log.txt" archiveFileName="${basedir}/log.${date}" archiveEvery="Day" archiveNumbering="Date" />
  </targets>

  <rules>
    <logger name="*" writeTo="logfile" />
  </rules>
</nlog>
```

and this simple program:
```C#
class Program
{
    static void Main()
    {
        NLog.LogManager.GetLogger("Test").Info("very important message");
    }
}
```

It crashes with:
```
Unhandled Exception: NLog.NLogRuntimeException: Exception occurred in NLog ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NLog.Targets.FileTarget.FileNameTemplate.ReplacePattern(String replacementValue)
   at NLog.Targets.FileTarget.ReplaceReplaceFileNamePattern(String pattern, String replacementValue)
   at NLog.Targets.FileTarget.DeleteOldDateArchive(String pattern)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1.<Write>b__0(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message)
   at NLog.Logger.Info(String message)
   at Program.Main() in d:\user\Documents\Visual Studio 2013\Projects\NLogTest\Program.cs:line 6
```

Output from internal logging:
```
2015-10-16 11:20:34.0354 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2015-10-16 11:20:34.0354 Debug Setting 'FileTarget.name' to 'logfile'
2015-10-16 11:20:34.0354 Debug Setting 'FileTarget.fileName' to '${basedir}/log.txt'
2015-10-16 11:20:34.0354 Debug Setting 'FileTarget.archiveFileName' to '${basedir}/log.${date}'
2015-10-16 11:20:34.0354 Debug Setting 'FileTarget.archiveEvery' to 'Day'
2015-10-16 11:20:34.0354 Debug Setting 'FileTarget.archiveNumbering' to 'Date'
2015-10-16 11:20:34.0354 Info Adding target File Target[logfile]
2015-10-16 11:20:34.0354 Debug Registering target logfile: NLog.Targets.FileTarget
2015-10-16 11:20:34.0524 Info Configured from an XML element in D:\user\Documents\Visual Studio 2013\Projects\NLogTest\bin\Debug\NLog.config...
2015-10-16 11:20:34.0524 Debug --- NLog configuration dump. ---
2015-10-16 11:20:34.0524 Debug Targets:
2015-10-16 11:20:34.0524 Info File Target[logfile]
2015-10-16 11:20:34.0524 Debug Rules:
2015-10-16 11:20:34.0524 Info logNamePattern: (:All) levels: [ Trace Debug Info Warn Error Fatal ] appendTo: [ logfile ]
2015-10-16 11:20:34.0524 Debug --- End of NLog configuration dump ---
2015-10-16 11:20:34.0524 Info Found 17 configuration items
2015-10-16 11:20:34.0524 Debug Targets for Test by level:
2015-10-16 11:20:34.0664 Debug Trace => logfile
2015-10-16 11:20:34.0664 Debug Debug => logfile
2015-10-16 11:20:34.0664 Debug Info => logfile
2015-10-16 11:20:34.0664 Debug Warn => logfile
2015-10-16 11:20:34.0664 Debug Error => logfile
2015-10-16 11:20:34.0664 Debug Fatal => logfile
```

Disabling archiving or setting `targets async="true"` fixes the problem. NLog version is 4.1.2, there was no such issue in NLog 3.1.

I'm using .NET Framework 4.5.

**Comment by 304NotModified** [comment]
Thanks! Is it possible to create an unit test of this case and PR it? That would boost the fix.
